// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef DATAMODEL_TOOLS_IPHYSICALSYSTEM_H
#define DATAMODEL_TOOLS_IPHYSICALSYSTEM_H
/* Author : desrozis at Thu Jan 12 15:46:17 2012
 * Generated by createNew
 */

#include "ArcRes/Entities/System.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/**
 * \ingroup TwoPhaseFlow
 * \aigenerated
 * \brief Interface for the physical system.
 *
 * Provides access to the ArcRes system representation, which holds
 * all variables, properties, and equations for the two-phase flow
 * physical model.
 */
class IPhysicalSystem
{
public:
  
  /** \aigenerated Virtual destructor */
  virtual ~IPhysicalSystem() {}
  
public:

  /** \aigenerated Initializes the physical system and its variables */
  virtual void init() = 0;
  
  /** \aigenerated Returns the ArcRes system that defines the physics */
  virtual ArcRes::System system() const = 0;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* DATAMODEL_TOOLS_IPHYSICALSYSTEM_H */
