// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef DATAMODEL_ISYSTEMBUILDER_H
#define DATAMODEL_ISYSTEMBUILDER_H
/* Author : desrozis at Thu Jan 12 15:46:17 2012
 * Generated by createNew
 */

//#include "ArcRes/Entities/System.h"
#include "ArcRes/Entities/System.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/


/**
 * \ingroup TwoPhaseFlow
 * \aigenerated
 * \brief Interface for building the physical system.
 *
 * Constructs the ArcRes system by assembling variables, properties,
 * and equations from the data model definition.
 */
class ISystemBuilder
{
public:
  
  /** \aigenerated Virtual destructor */
  virtual ~ISystemBuilder() {}
  
public:
  
  /** \aigenerated Builds and returns the ArcRes system */
  virtual ArcRes::System buildSystem() = 0;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* DATAMODEL_ISYSTEMBUILDER_H */
