// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef VARIABLE_IVARIABLEMANAGER_H
#define VARIABLE_IVARIABLEMANAGER_H
/* Author : dechaiss at Fri Oct 14 16:45:06 2011
 * Generated by createNew
 */

#include "ArcGeoSim/Physics/Law2/Contribution/VariableFolder.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/**
 * \ingroup TwoPhaseFlow
 * \aigenerated
 * \brief Interface for variable management.
 *
 * Manages variable folders at different time states (current, previous,
 * and initial) for the two-phase flow simulation.
 */
class IVariableManager
{
public:
  
  /** \aigenerated Virtual destructor */
  virtual ~IVariableManager() {}
  
public:

  /** \aigenerated Initializes the variable manager */
  virtual void init() = 0;
  
  /** \aigenerated Returns the current-time variable folder */
  virtual Law::VariableCellFolder& domain() = 0;
  
  /** \aigenerated Returns the previous-time (t_{n}) variable folder */
  virtual Law::VariableCellFolder& domainTn() = 0;

  /** \aigenerated Returns the initial-time (t_{0}) variable folder */
  virtual Law::VariableCellFolder& domainT0() = 0;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* VARIABLE_IVARIABLEMANAGER_H */
