ShArc: TwoPhaseFlowSimulationModule Class Reference
TwoPhaseFlowSimulationModule Class Reference
Two-Phase Flow
Public Member Functions
TwoPhaseFlowSimulationModule (const Arcane::ModuleBuildInfo &sbi)
~TwoPhaseFlowSimulationModule ()
void applyConstraintOnSolution (bool &NonPhysicalSolution)
AI comment: Clips saturation to [0,1] and renormalizes to enforce saturation sum constraint.
void build (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds the residual vector and Jacobian matrix for the non-linear system.
void compute ()
AI comment: Solves the non-linear system via Newton method at each time step.
const Law::PropertyVector & equationSystem () const
const Law::VariableCellFolder & folder () const
void init ()
AI comment: Full initialization sequence: system, geometry, groups, variables, laws, Newton.
void initLinearSystemProfile (Arcane::CellGroup cells, Alien::MatrixProfiler &blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size)
AI comment: Initializes matrix profile using two-point or multi-point stencil.
Integer nbEquations () const
void setSolutionVariables (Arcane::SharedArray< Arcane::VariableCellReal * > &solutions)
AI comment: Sets pointers to solution variables for the Newton solver.
Domain const & systemDomain () const
Private Member Functions
void _addTimeVariable (const Gump::ScalarRealProperty &property)
AI comment: Registers a scalar property for time-varying snapshot management.
void _buildAccumulation (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds the accumulation term (mass * saturation * density / delta-t)
void _buildClosure (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds the saturation closure equation (sum of saturations = 1)
void _buildFluxBoundary (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds the boundary flux term using Dirichlet boundary condition values.
void _buildFluxInternal (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds the internal flux term between cells using two-point flux approximation.
void _buildFluxWell (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds the well flux term using well index and bottom-hole pressure.
template<typename Folder >
void _evaluateLaws (Folder &folder, Law::EvaluationMode derivability)
void _initBoundaryVariableMng ()
AI comment: Initializes boundary condition variables and containers for each boundary.
void _initDomainVariableMng ()
AI comment: Registers domain variable containers for all fluid properties and applies IC.
void _initEquationSystem ()
AI comment: Sets up equation/unknown system: pressure for phase 0, saturation for others.
void _initGeometry ()
AI comment: Registers and computes geometric properties (volume, center, face normal)
void _initGroup ()
AI comment: Creates mesh groups via the group creator service.
void _initLaws ()
AI comment: Configures physical laws and evaluates them on domain, boundary, and wells.
void _initNewton ()
AI comment: Initializes the Newton solver with this module as the non-linear system.
void _initPhysicalSystem ()
AI comment: Loads the Gump physical system from the service manager.
void _initRestore ()
AI comment: Initializes Tn containers by copying initial law evaluation results.
void _initTimeVariableMng ()
AI comment: Registers time-varying variables for Newton failure rollback.
void _initTransmissivity ()
AI comment: Computes transmissivity operator using scalar or tensor permeability.
void _initWellVariableMng ()
AI comment: Initializes well condition variables and containers for each well.
void _multiPointsProfiler (Arcane::CellGroup cells, Alien::MatrixProfiler &blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size) const
void _twoPointsProfiler (Arcane::CellGroup cells, Alien::MatrixProfiler &blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size) const
void _updateGeometry ()
AI comment: Forces an update of all geometric properties via the geometry manager.
Law::VariableCellFolder & domain ()
Law::VariableCellFolder & domainT0 ()
Law::VariableCellFolder & domainTn ()
Law::FunctionManager & functionMng ()
ArcRes::System & system ()
const Law::PropertyVector & unknownsManager () const
Private Attributes
ArcNum::INonLinearSystem::Domain m_domain
ArcGeoSim::AppService< IVariableManager > m_folder
Law::FunctionManager m_funcs
Arcane::SharedArray< Gump::ScalarRealProperty > m_properties_to_evaluate
std::shared_ptr< ArcNum::MultiPointsStencil > m_schemeStencil
ArcGeoSim::AppService< ArcGeoSim::ITimeLoopSnapshotManager > m_snapshots
ArcRes::System m_system
ArcNum::TwoPointsTransmissivity m_transmissivities
Law::PropertyVector m_unknown_manager
Detailed Description
AI-Generated Documentation:
Main module for two-phase flow simulation in porous media.
TwoPhaseFlowSimulationModule implements the coupled system of equations for two-phase (water/oil or water/gas) flow, including accumulation, internal flux, and boundary flux computations. It uses the Newton method for solving the non-linear system and supports various physical laws (capillary pressure, relative permeability, fluid density, etc.).
Definition at line 70 of file TwoPhaseFlowSimulationModule.cc.
Constructor & Destructor Documentation
TwoPhaseFlowSimulationModule()
TwoPhaseFlowSimulationModule::TwoPhaseFlowSimulationModule (const Arcane::ModuleBuildInfo & sbi) inline
AI-Generated Documentation: Constructs the module
Definition at line 77 of file TwoPhaseFlowSimulationModule.cc.
~TwoPhaseFlowSimulationModule()
TwoPhaseFlowSimulationModule::~TwoPhaseFlowSimulationModule () inline
AI-Generated Documentation: Destructor
Definition at line 82 of file TwoPhaseFlowSimulationModule.cc.
Member Function Documentation
_addTimeVariable()
void TwoPhaseFlowSimulationModule::_addTimeVariable (const Gump::ScalarRealProperty & property) private
AI comment: Registers a scalar property for time-varying snapshot management.
AI-Generated Documentation: Adds a time-varying variable for snapshot management
Definition at line 330 of file TwoPhaseFlowSimulationModule.cc.
References domain(), domainTn(), and m_snapshots.
Referenced by _initTimeVariableMng().
_buildAccumulation()
void TwoPhaseFlowSimulationModule::_buildAccumulation (ArcNum::Vector & residual, ArcNum::Matrix & jacobian) private
AI comment: Builds the accumulation term (mass * saturation * density / delta-t)
AI-Generated Documentation: Builds the accumulation term (mass matrix)
Definition at line 800 of file TwoPhaseFlowSimulationModule.cc.
References domain(), domainTn(), functionMng(), system(), and unknownsManager().
Referenced by build().
_buildClosure()
void TwoPhaseFlowSimulationModule::_buildClosure (ArcNum::Vector & residual, ArcNum::Matrix & jacobian) private
AI comment: Builds the saturation closure equation (sum of saturations = 1)
AI-Generated Documentation: Builds the closure equations
Definition at line 1075 of file TwoPhaseFlowSimulationModule.cc.
References domain(), functionMng(), system(), and unknownsManager().
Referenced by build().
_buildFluxBoundary()
void TwoPhaseFlowSimulationModule::_buildFluxBoundary (ArcNum::Vector & residual, ArcNum::Matrix & jacobian) private
AI comment: Builds the boundary flux term using Dirichlet boundary condition values.
AI-Generated Documentation: Builds the boundary flux term
Definition at line 928 of file TwoPhaseFlowSimulationModule.cc.
References domain(), ENUMERATE_BOUNDARY, functionMng(), m_transmissivities, system(), and unknownsManager().
Referenced by build().
_buildFluxInternal()
void TwoPhaseFlowSimulationModule::_buildFluxInternal (ArcNum::Vector & residual, ArcNum::Matrix & jacobian) private
AI comment: Builds the internal flux term between cells using two-point flux approximation.
AI-Generated Documentation: Builds the internal flux term
Definition at line 857 of file TwoPhaseFlowSimulationModule.cc.
References domain(), functionMng(), m_transmissivities, system(), and unknownsManager().
Referenced by build().
_buildFluxWell()
void TwoPhaseFlowSimulationModule::_buildFluxWell (ArcNum::Vector & residual, ArcNum::Matrix & jacobian) private
AI comment: Builds the well flux term using well index and bottom-hole pressure.
AI-Generated Documentation: Builds the well flux term
Definition at line 1003 of file TwoPhaseFlowSimulationModule.cc.
References domain(), ENUMERATE_WELL, functionMng(), system(), and unknownsManager().
Referenced by build().
_evaluateLaws()
template<typename Folder > void TwoPhaseFlowSimulationModule::_evaluateLaws (Folder & folder, Law::EvaluationMode derivability) private
AI-Generated Documentation: Evaluates physical laws on a given folder
Definition at line 786 of file TwoPhaseFlowSimulationModule.cc.
References folder(), m_funcs, and m_properties_to_evaluate.
Referenced by _initLaws(), and build().
_initBoundaryVariableMng()
void TwoPhaseFlowSimulationModule::_initBoundaryVariableMng () private
AI comment: Initializes boundary condition variables and containers for each boundary.
AI-Generated Documentation: Initializes boundary variable manager
Definition at line 580 of file TwoPhaseFlowSimulationModule.cc.
References ENUMERATE_BOUNDARY, and system().
Referenced by init().
_initDomainVariableMng()
void TwoPhaseFlowSimulationModule::_initDomainVariableMng () private
AI comment: Registers domain variable containers for all fluid properties and applies IC.
AI-Generated Documentation: Initializes domain variable manager
Definition at line 545 of file TwoPhaseFlowSimulationModule.cc.
References domain(), m_domain, and system().
Referenced by init().
_initEquationSystem()
void TwoPhaseFlowSimulationModule::_initEquationSystem () private
AI comment: Sets up equation/unknown system: pressure for phase 0, saturation for others.
AI-Generated Documentation: Initializes the equation system (unknowns)
Definition at line 755 of file TwoPhaseFlowSimulationModule.cc.
References m_unknown_manager, and system().
Referenced by init().
_initGeometry()
void TwoPhaseFlowSimulationModule::_initGeometry () private
AI comment: Registers and computes geometric properties (volume, center, face normal)
AI-Generated Documentation: Initializes mesh geometry
Definition at line 479 of file TwoPhaseFlowSimulationModule.cc.
References _updateGeometry().
Referenced by init().
_initGroup()
void TwoPhaseFlowSimulationModule::_initGroup () private
AI comment: Creates mesh groups via the group creator service.
AI-Generated Documentation: Initializes mesh groups
Definition at line 530 of file TwoPhaseFlowSimulationModule.cc.
References _updateGeometry(), and init().
Referenced by init().
_initLaws()
void TwoPhaseFlowSimulationModule::_initLaws () private
AI comment: Configures physical laws and evaluates them on domain, boundary, and wells.
AI-Generated Documentation: Configures and initializes physical laws
Definition at line 648 of file TwoPhaseFlowSimulationModule.cc.
References _evaluateLaws(), domain(), ENUMERATE_BOUNDARY, ENUMERATE_WELL, m_funcs, m_properties_to_evaluate, and system().
Referenced by init().
_initNewton()
void TwoPhaseFlowSimulationModule::_initNewton () private
AI comment: Initializes the Newton solver with this module as the non-linear system.
AI-Generated Documentation: Initializes the Newton solver
Definition at line 774 of file TwoPhaseFlowSimulationModule.cc.
Referenced by init().
_initPhysicalSystem()
void TwoPhaseFlowSimulationModule::_initPhysicalSystem () private
AI comment: Loads the Gump physical system from the service manager.
AI-Generated Documentation: Initializes the physical system
Definition at line 341 of file TwoPhaseFlowSimulationModule.cc.
References m_system.
Referenced by init().
_initRestore()
void TwoPhaseFlowSimulationModule::_initRestore () private
AI comment: Initializes Tn containers by copying initial law evaluation results.
AI-Generated Documentation: Initializes the restore/snapshot system
Definition at line 689 of file TwoPhaseFlowSimulationModule.cc.
References domain(), domainTn(), and system().
Referenced by init().
_initTimeVariableMng()
void TwoPhaseFlowSimulationModule::_initTimeVariableMng () private
AI comment: Registers time-varying variables for Newton failure rollback.
AI-Generated Documentation: Initializes time variable manager (restart snapshots)
Definition at line 630 of file TwoPhaseFlowSimulationModule.cc.
References _addTimeVariable(), and system().
Referenced by init().
_initTransmissivity()
void TwoPhaseFlowSimulationModule::_initTransmissivity () private
AI comment: Computes transmissivity operator using scalar or tensor permeability.
AI-Generated Documentation: Initializes transmissivity operators
Definition at line 716 of file TwoPhaseFlowSimulationModule.cc.
References domain(), m_transmissivities, and system().
Referenced by init().
_initWellVariableMng()
void TwoPhaseFlowSimulationModule::_initWellVariableMng () private
AI comment: Initializes well condition variables and containers for each well.
AI-Generated Documentation: Initializes well variable manager
Definition at line 607 of file TwoPhaseFlowSimulationModule.cc.
References domain(), ENUMERATE_WELL, and system().
Referenced by init().
_multiPointsProfiler()
void TwoPhaseFlowSimulationModule::_multiPointsProfiler (Arcane::CellGroup cells, Alien::MatrixProfiler & blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size) const inline private
Definition at line 227 of file TwoPhaseFlowSimulationModule.cc.
References init(), and m_schemeStencil.
Referenced by initLinearSystemProfile().
_twoPointsProfiler()
void TwoPhaseFlowSimulationModule::_twoPointsProfiler (Arcane::CellGroup cells, Alien::MatrixProfiler & blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size) const inline private
Definition at line 200 of file TwoPhaseFlowSimulationModule.cc.
Referenced by initLinearSystemProfile().
_updateGeometry()
void TwoPhaseFlowSimulationModule::_updateGeometry () private
AI comment: Forces an update of all geometric properties via the geometry manager.
AI-Generated Documentation: Updates mesh geometry at each time step
Definition at line 518 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _initGeometry(), and _initGroup().
applyConstraintOnSolution()
void TwoPhaseFlowSimulationModule::applyConstraintOnSolution (bool & NonPhysicalSolution)
AI comment: Clips saturation to [0,1] and renormalizes to enforce saturation sum constraint.
AI-Generated Documentation: Applies constraints on the solution (e.g. clipping)
Definition at line 451 of file TwoPhaseFlowSimulationModule.cc.
References domain(), and system().
build()
void TwoPhaseFlowSimulationModule::build (ArcNum::Vector & residual, ArcNum::Matrix & jacobian)
AI comment: Builds the residual vector and Jacobian matrix for the non-linear system.
AI-Generated Documentation: Builds the residual and Jacobian matrix
Definition at line 431 of file TwoPhaseFlowSimulationModule.cc.
References _buildAccumulation(), _buildClosure(), _buildFluxBoundary(), _buildFluxInternal(), _buildFluxWell(), _evaluateLaws(), and domain().
compute()
void TwoPhaseFlowSimulationModule::compute ()
AI comment: Solves the non-linear system via Newton method at each time step.
AI-Generated Documentation: Executes one computation step
Definition at line 416 of file TwoPhaseFlowSimulationModule.cc.
domain()
Law::VariableCellFolder& TwoPhaseFlowSimulationModule::domain () inline private
AI-Generated Documentation: Returns the domain for contributions
Definition at line 131 of file TwoPhaseFlowSimulationModule.cc.
References m_folder.
Referenced by _addTimeVariable(), _buildAccumulation(), _buildClosure(), _buildFluxBoundary(), _buildFluxInternal(), _buildFluxWell(), _initDomainVariableMng(), _initLaws(), _initRestore(), _initTransmissivity(), _initWellVariableMng(), applyConstraintOnSolution(), and build().
domainT0()
Law::VariableCellFolder& TwoPhaseFlowSimulationModule::domainT0 () inline private
AI-Generated Documentation: Returns the domain at time T0
Definition at line 134 of file TwoPhaseFlowSimulationModule.cc.
References m_folder.
domainTn()
Law::VariableCellFolder& TwoPhaseFlowSimulationModule::domainTn () inline private
AI-Generated Documentation: Returns the domain at time Tn
Definition at line 137 of file TwoPhaseFlowSimulationModule.cc.
References m_folder.
Referenced by _addTimeVariable(), _buildAccumulation(), and _initRestore().
equationSystem()
const Law::PropertyVector& TwoPhaseFlowSimulationModule::equationSystem () const inline
AI-Generated Documentation: Returns the equation system (unknowns manager)
Definition at line 108 of file TwoPhaseFlowSimulationModule.cc.
References m_unknown_manager.
folder()
const Law::VariableCellFolder& TwoPhaseFlowSimulationModule::folder () const inline
AI-Generated Documentation: Returns the variable cell folder
Definition at line 117 of file TwoPhaseFlowSimulationModule.cc.
References m_folder.
Referenced by _evaluateLaws(), and setSolutionVariables().
functionMng()
Law::FunctionManager& TwoPhaseFlowSimulationModule::functionMng () inline private
AI-Generated Documentation: Returns the law function manager
Definition at line 128 of file TwoPhaseFlowSimulationModule.cc.
References m_funcs.
Referenced by _buildAccumulation(), _buildClosure(), _buildFluxBoundary(), _buildFluxInternal(), and _buildFluxWell().
init()
void TwoPhaseFlowSimulationModule::init ()
AI comment: Full initialization sequence: system, geometry, groups, variables, laws, Newton.
AI-Generated Documentation: Initializes the simulation
Definition at line 355 of file TwoPhaseFlowSimulationModule.cc.
References _initBoundaryVariableMng(), _initDomainVariableMng(), _initEquationSystem(), _initGeometry(), _initGroup(), _initLaws(), _initNewton(), _initPhysicalSystem(), _initRestore(), _initTimeVariableMng(), _initTransmissivity(), _initWellVariableMng(), and system().
Referenced by _initGroup(), and _multiPointsProfiler().
initLinearSystemProfile()
void TwoPhaseFlowSimulationModule::initLinearSystemProfile (Arcane::CellGroup cells, Alien::MatrixProfiler & blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size)
AI comment: Initializes matrix profile using two-point or multi-point stencil.
AI-Generated Documentation: Initializes the linear system profile (matrix sparsity)
Definition at line 388 of file TwoPhaseFlowSimulationModule.cc.
References _multiPointsProfiler(), _twoPointsProfiler(), and m_schemeStencil.
nbEquations()
Integer TwoPhaseFlowSimulationModule::nbEquations () const inline
AI-Generated Documentation: Returns the number of equations in the system
Definition at line 93 of file TwoPhaseFlowSimulationModule.cc.
References m_unknown_manager.
setSolutionVariables()
void TwoPhaseFlowSimulationModule::setSolutionVariables (Arcane::SharedArray< Arcane::VariableCellReal * > & solutions)
AI comment: Sets pointers to solution variables for the Newton solver.
AI-Generated Documentation: Sets the solution variable pointers
Definition at line 402 of file TwoPhaseFlowSimulationModule.cc.
References folder(), and m_unknown_manager.
system()
ArcRes::System& TwoPhaseFlowSimulationModule::system () inline private
AI-Generated Documentation: Returns the Gump system
Definition at line 122 of file TwoPhaseFlowSimulationModule.cc.
References m_system.
Referenced by _buildAccumulation(), _buildClosure(), _buildFluxBoundary(), _buildFluxInternal(), _buildFluxWell(), _initBoundaryVariableMng(), _initDomainVariableMng(), _initEquationSystem(), _initLaws(), _initRestore(), _initTimeVariableMng(), _initTransmissivity(), _initWellVariableMng(), applyConstraintOnSolution(), and init().
systemDomain()
Domain const& TwoPhaseFlowSimulationModule::systemDomain () const inline
AI-Generated Documentation: Returns the system domain
Definition at line 96 of file TwoPhaseFlowSimulationModule.cc.
References m_domain.
unknownsManager()
const Law::PropertyVector& TwoPhaseFlowSimulationModule::unknownsManager () const inline private
AI-Generated Documentation: Returns the unknown properties manager
Definition at line 125 of file TwoPhaseFlowSimulationModule.cc.
References m_unknown_manager.
Referenced by _buildAccumulation(), _buildClosure(), _buildFluxBoundary(), _buildFluxInternal(), and _buildFluxWell().
Member Data Documentation
m_domain
ArcNum::INonLinearSystem::Domain TwoPhaseFlowSimulationModule::m_domain private
AI-Generated Documentation: Non-linear system domain
Definition at line 322 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _initDomainVariableMng(), and systemDomain().
m_folder
ArcGeoSim::AppService<IVariableManager> TwoPhaseFlowSimulationModule::m_folder private
Note
Original: acces domain for contributions
AI-Generated Documentation: Domain accessor for contribution assembly
Definition at line 319 of file TwoPhaseFlowSimulationModule.cc.
Referenced by domain(), domainT0(), domainTn(), and folder().
m_funcs
Law::FunctionManager TwoPhaseFlowSimulationModule::m_funcs private
Note
Original: law function manager and evaluator
AI-Generated Documentation: Function manager for physical law evaluation
Definition at line 312 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _evaluateLaws(), _initLaws(), and functionMng().
m_properties_to_evaluate
Arcane::SharedArray<Gump::ScalarRealProperty> TwoPhaseFlowSimulationModule::m_properties_to_evaluate private
AI-Generated Documentation: Properties to evaluate in law functions
Definition at line 315 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _evaluateLaws(), and _initLaws().
m_schemeStencil
std::shared_ptr<ArcNum::MultiPointsStencil> TwoPhaseFlowSimulationModule::m_schemeStencil private
AI-Generated Documentation: Multi-point stencil for flux computation (optional)
Definition at line 296 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _multiPointsProfiler(), and initLinearSystemProfile().
m_snapshots
ArcGeoSim::AppService<ArcGeoSim::ITimeLoopSnapshotManager> TwoPhaseFlowSimulationModule::m_snapshots private
Note
Original: evolutive variable management restart newton
AI-Generated Documentation: Snapshot manager for restart on Newton failure
Definition at line 308 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _addTimeVariable().
m_system
ArcRes::System TwoPhaseFlowSimulationModule::m_system private
Note
Original: system instance based on gump
AI-Generated Documentation: Gump-based system instance
Definition at line 304 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _initPhysicalSystem(), and system().
m_transmissivities
ArcNum::TwoPointsTransmissivity TwoPhaseFlowSimulationModule::m_transmissivities private
AI-Generated Documentation: Two-point transmissivity operator
Definition at line 293 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _buildFluxBoundary(), _buildFluxInternal(), and _initTransmissivity().
m_unknown_manager
Law::PropertyVector TwoPhaseFlowSimulationModule::m_unknown_manager private
Note
Original: unknowns as Law::PropertyVector!
AI-Generated Documentation: Manager for unknown properties
Definition at line 300 of file TwoPhaseFlowSimulationModule.cc.
Referenced by _initEquationSystem(), equationSystem(), nbEquations(), setSolutionVariables(), and unknownsManager().
The documentation for this class was generated from the following file:
src/TwoPhaseFlowSimulation/TwoPhaseFlowSimulationModule.cc