ShArc: ArcaneFemFunctions::BoundaryConditions Class Reference
ArcaneFemFunctions::BoundaryConditions Class Reference
Provides methods for applying boundary conditions in 2D/3D FEM.
#include <ArcaneFemFunctions.h>
Static Public Member Functions
static void applyDirichletToLhsAndRhs (BC::IDirichletBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, DoFLinearSystem &m_linear_system, VariableDoFReal &rhs_values)
Applies Dirichlet boundary conditions to RHS and LHS.
static void applyDirichletToRhs (BC::IDirichletBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, VariableDoFReal &rhs_values)
Applies Dirichlet boundary conditions to RHS.
static void applyPointDirichletToLhsAndRhs (BC::IDirichletPointCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, DoFLinearSystem &m_linear_system, VariableDoFReal &rhs_values)
Applies Point Dirichlet boundary conditions to RHS and LHS.
static void applyPointDirichletToRhs (BC::IDirichletPointCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, VariableDoFReal &rhs_values)
Applies Point Dirichlet boundary conditions to RHS.
Detailed Description
Provides methods for applying boundary conditions in 2D/3D FEM.
This class includes static methods for applying:
Dirichlet boundary condition
Point Dirichlet condition
Definition at line 1232 of file ArcaneFemFunctions.h.
Member Function Documentation
applyDirichletToLhsAndRhs()
static void ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs (BC::IDirichletBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, DoFLinearSystem & m_linear_system, VariableDoFReal & rhs_values) inline static
Applies Dirichlet boundary conditions to RHS and LHS.
Updates the LHS matrix and RHS vector to enforce Dirichlet conditions.
For LHS matrix 𝐀, the diagonal term for the Dirichlet DOF is set to 𝑃.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
Parameters
bs Boundary condition values.
node_dof DOF connectivity view.
node_coord Node coordinates.
m_linear_system Linear system for LHS.
rhs_values RHS values to update.
Definition at line 1252 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty(), ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowColumnElimination(), ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowElimination(), BC::IDirichletBoundaryCondition::getEnforceDirichletMethod(), BC::IDirichletBoundaryCondition::getPenalty(), BC::IDirichletBoundaryCondition::getSurface(), and BC::IDirichletBoundaryCondition::getValue().
Referenced by FemModuleElasticity::_applyDirichlet(), and FemModulePoisson::_assembleLinearOperatorCpu().
applyDirichletToRhs()
static void ArcaneFemFunctions::BoundaryConditions::applyDirichletToRhs (BC::IDirichletBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, VariableDoFReal & rhs_values) inline static
Applies Dirichlet boundary conditions to RHS.
Updates the RHS vector to enforce Dirichlet conditions.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
Parameters
bs Boundary condition values.
node_dof DOF connectivity view.
node_coord Node coordinates.
rhs_values RHS values to update.
Definition at line 1331 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupRhsOnly(), BC::IDirichletBoundaryCondition::getEnforceDirichletMethod(), BC::IDirichletBoundaryCondition::getPenalty(), BC::IDirichletBoundaryCondition::getSurface(), and BC::IDirichletBoundaryCondition::getValue().
applyPointDirichletToLhsAndRhs()
static void ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs (BC::IDirichletPointCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, DoFLinearSystem & m_linear_system, VariableDoFReal & rhs_values) inline static
Applies Point Dirichlet boundary conditions to RHS and LHS.
Updates the LHS matrix and RHS vector to enforce the Dirichlet.
For LHS matrix 𝐀, the diagonal term for the Dirichlet DOF is set to 𝑃.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
Parameters
bs Boundary condition values.
node_dof DOF connectivity view.
node_coord Node coordinates.
m_linear_system Linear system for LHS.
rhs_values RHS values to update.
Definition at line 1293 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty(), ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowColumnElimination(), ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowElimination(), BC::IDirichletPointCondition::getEnforceDirichletMethod(), BC::IDirichletPointCondition::getNode(), BC::IDirichletPointCondition::getPenalty(), and BC::IDirichletPointCondition::getValue().
Referenced by FemModuleElasticity::_applyDirichlet(), and FemModulePoisson::_assembleLinearOperatorCpu().
applyPointDirichletToRhs()
static void ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToRhs (BC::IDirichletPointCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, VariableDoFReal & rhs_values) inline static
Applies Point Dirichlet boundary conditions to RHS.
Updates the RHS vector to enforce the Dirichlet.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
Parameters
bs Boundary condition values.
node_dof DOF connectivity view.
node_coord Node coordinates.
rhs_values RHS values to update.
Definition at line 1371 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupRhsOnly(), BC::IDirichletPointCondition::getEnforceDirichletMethod(), BC::IDirichletPointCondition::getNode(), BC::IDirichletPointCondition::getPenalty(), and BC::IDirichletPointCondition::getValue().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/ArcaneFemFunctions.h