ShArc: Arcane::FemUtils::CsrDoFLinearSystemImpl Class Reference
Arcane::FemUtils::CsrDoFLinearSystemImpl Class Reference
#include <CsrDoFLinearSystemImpl.h>
Public Member Functions
CsrDoFLinearSystemImpl (IItemFamily *dof_family, const String &solver_name)
void _applyForcedValuesToLhs ()
void _applyRowColumnEliminationOnMatrix ()
void _applyRowEliminationOnMatrix ()
void _applyRowOrRowColumnEliminationOnRHS ()
void _fillRowColumnEliminationInfos ()
void applyMatrixTransformation () override
void applyRHSTransformation () override
void clearValues () override
void eliminateRow (DoFLocalId row, Real value) override
void eliminateRowColumn (DoFLocalId row, Real value) override
CSRFormatView & getCSRValues () override
bool hasSetCSRValues () const override
Int32 indexValue (DoFLocalId row_lid, DoFLocalId column_lid)
void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) override
void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) override
void setCSRValues (const CSRFormatView &csr_view) override
Public Member Functions inherited from Arcane::FemUtils::DoFLinearSystemImplBase
DoFLinearSystemImplBase (IItemFamily *dof_family, const String &solver_name)
void clearValues () override
IItemFamily * dofFamily () const
VariableDoFByte & getEliminationInfo () final
VariableDoFReal & getEliminationValue () final
VariableDoFBool & getForcedInfo () final
VariableDoFReal & getForcedValue () final
bool isMatrixSparsityConstant () const final
bool isMatrixValuesConstant () const final
VariableDoFReal & rhsVariable () final
Runner runner () const override
void setConstantMatrixSparsity (const bool val) final
void setConstantMatrixValues (const bool val) final
void setRunner (const Runner &r) override
VariableDoFReal & solutionVariable () final
Public Member Functions inherited from Arcane::FemUtils::IDoFLinearSystemImpl
virtual ~IDoFLinearSystemImpl ()=default
virtual void setSolverCommandLineArguments (const CommandLineArguments &args)=0
virtual void solve ()=0
Protected Member Functions
void _applyRowOrRowColumnEliminationOnMatrix ()
Protected Member Functions inherited from Arcane::FemUtils::DoFLinearSystemImplBase
void _applyRowColumnEliminationToRHS (bool is_verbose)
OrderedRowColumnMap & _rowColumnEliminationMap ()
Private Attributes
CSRFormatView m_csr_view
bool m_has_row_column_elimination = false
Detailed Description
Definition at line 36 of file CsrDoFLinearSystemImpl.h.
Constructor & Destructor Documentation
CsrDoFLinearSystemImpl()
Arcane::FemUtils::CsrDoFLinearSystemImpl::CsrDoFLinearSystemImpl (IItemFamily * dof_family, const String & solver_name)
Definition at line 39 of file CsrDoFLinearSystemImpl.cc.
Member Function Documentation
_applyForcedValuesToLhs()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyForcedValuesToLhs ()
Definition at line 50 of file CsrDoFLinearSystemImpl.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::DoFLinearSystemImplBase::getForcedInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getForcedValue(), m_csr_view, and Arcane::FemUtils::DoFLinearSystemImplBase::runner().
Referenced by applyMatrixTransformation().
_applyRowColumnEliminationOnMatrix()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowColumnEliminationOnMatrix ()
Definition at line 88 of file CsrDoFLinearSystemImpl.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::ELIMINATE_ROW, Arcane::FemUtils::ELIMINATE_ROW_COLUMN, Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue(), m_csr_view, Arcane::FemUtils::DoFLinearSystemImplBase::rhsVariable(), and Arcane::FemUtils::DoFLinearSystemImplBase::runner().
Referenced by _applyRowOrRowColumnEliminationOnMatrix().
_applyRowEliminationOnMatrix()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowEliminationOnMatrix ()
Definition at line 126 of file CsrDoFLinearSystemImpl.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::ELIMINATE_ROW, Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue(), m_csr_view, Arcane::FemUtils::DoFLinearSystemImplBase::rhsVariable(), and Arcane::FemUtils::DoFLinearSystemImplBase::runner().
Referenced by _applyRowOrRowColumnEliminationOnMatrix().
_applyRowOrRowColumnEliminationOnMatrix()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnMatrix () protected
Definition at line 77 of file CsrDoFLinearSystemImpl.cc.
References _applyRowColumnEliminationOnMatrix(), _applyRowEliminationOnMatrix(), and m_has_row_column_elimination.
Referenced by applyMatrixTransformation().
_applyRowOrRowColumnEliminationOnRHS()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnRHS ()
Definition at line 157 of file CsrDoFLinearSystemImpl.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::ELIMINATE_ROW, Arcane::FemUtils::ELIMINATE_ROW_COLUMN, Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue(), Arcane::FemUtils::DoFLinearSystemImplBase::rhsVariable(), and Arcane::FemUtils::DoFLinearSystemImplBase::runner().
Referenced by applyRHSTransformation().
_fillRowColumnEliminationInfos()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::_fillRowColumnEliminationInfos ()
Definition at line 187 of file CsrDoFLinearSystemImpl.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::_rowColumnEliminationMap(), Arcane::FemUtils::OrderedRowColumnMap::clear(), Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::ELIMINATE_ROW_COLUMN, Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue(), m_csr_view, and m_has_row_column_elimination.
Referenced by applyMatrixTransformation().
applyMatrixTransformation()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::applyMatrixTransformation () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 235 of file CsrDoFLinearSystemImpl.cc.
References _applyForcedValuesToLhs(), _applyRowOrRowColumnEliminationOnMatrix(), and _fillRowColumnEliminationInfos().
applyRHSTransformation()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::applyRHSTransformation () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 247 of file CsrDoFLinearSystemImpl.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::_applyRowColumnEliminationToRHS(), and _applyRowOrRowColumnEliminationOnRHS().
clearValues()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::clearValues () inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 80 of file CsrDoFLinearSystemImpl.h.
References Arcane::FemUtils::DoFLinearSystemImplBase::clearValues(), and m_csr_view.
eliminateRow()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::eliminateRow (DoFLocalId row, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 67 of file CsrDoFLinearSystemImpl.h.
eliminateRowColumn()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::eliminateRowColumn (DoFLocalId row, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 72 of file CsrDoFLinearSystemImpl.h.
getCSRValues()
CSRFormatView& Arcane::FemUtils::CsrDoFLinearSystemImpl::getCSRValues () inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 87 of file CsrDoFLinearSystemImpl.h.
References m_csr_view.
hasSetCSRValues()
bool Arcane::FemUtils::CsrDoFLinearSystemImpl::hasSetCSRValues () const inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 94 of file CsrDoFLinearSystemImpl.h.
indexValue()
Int32 Arcane::FemUtils::CsrDoFLinearSystemImpl::indexValue (DoFLocalId row_lid, DoFLocalId column_lid) inline
Definition at line 45 of file CsrDoFLinearSystemImpl.h.
References Arcane::FemUtils::CsrFormatMatrixView::columns(), m_csr_view, Arcane::FemUtils::CsrFormatMatrixView::nbColumn(), Arcane::FemUtils::CsrFormatMatrixView::nbRow(), Arcane::FemUtils::CsrFormatMatrixView::row(), and Arcane::FemUtils::CsrFormatMatrixView::rows().
Referenced by matrixAddValue(), and matrixSetValue().
matrixAddValue()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 57 of file CsrDoFLinearSystemImpl.h.
References indexValue(), m_csr_view, and Arcane::FemUtils::CsrFormatMatrixView::values().
matrixSetValue()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 62 of file CsrDoFLinearSystemImpl.h.
References indexValue(), m_csr_view, and Arcane::FemUtils::CsrFormatMatrixView::values().
setCSRValues()
void Arcane::FemUtils::CsrDoFLinearSystemImpl::setCSRValues (const CSRFormatView & csr_view) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 89 of file CsrDoFLinearSystemImpl.h.
References m_csr_view.
Member Data Documentation
m_csr_view
CSRFormatView Arcane::FemUtils::CsrDoFLinearSystemImpl::m_csr_view private
Definition at line 98 of file CsrDoFLinearSystemImpl.h.
Referenced by _applyForcedValuesToLhs(), _applyRowColumnEliminationOnMatrix(), _applyRowEliminationOnMatrix(), _fillRowColumnEliminationInfos(), clearValues(), getCSRValues(), indexValue(), matrixAddValue(), matrixSetValue(), and setCSRValues().
m_has_row_column_elimination
bool Arcane::FemUtils::CsrDoFLinearSystemImpl::m_has_row_column_elimination = false private
Definition at line 99 of file CsrDoFLinearSystemImpl.h.
Referenced by _applyRowOrRowColumnEliminationOnMatrix(), and _fillRowColumnEliminationInfos().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/internal/CsrDoFLinearSystemImpl.h
src/CAWF/FEMUtils/CsrDoFLinearSystemImpl.cc