ShArc: Arcane::FemUtils::IDoFLinearSystemImpl Class Reference
Arcane::FemUtils::IDoFLinearSystemImpl Class Reference abstract
#include <IDoFLinearSystemImpl.h>
Public Member Functions
virtual ~IDoFLinearSystemImpl ()=default
virtual void applyMatrixTransformation ()=0
virtual void applyRHSTransformation ()=0
virtual void clearValues ()=0
virtual void eliminateRow (DoFLocalId row, Real value)=0
virtual void eliminateRowColumn (DoFLocalId row, Real value)=0
virtual CSRFormatView & getCSRValues ()=0
virtual VariableDoFByte & getEliminationInfo ()=0
virtual VariableDoFReal & getEliminationValue ()=0
virtual VariableDoFBool & getForcedInfo ()=0
virtual VariableDoFReal & getForcedValue ()=0
virtual bool hasSetCSRValues () const =0
virtual bool isMatrixSparsityConstant () const =0
virtual bool isMatrixValuesConstant () const =0
virtual void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value)=0
virtual void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value)=0
virtual VariableDoFReal & rhsVariable ()=0
virtual Runner runner () const =0
virtual void setConstantMatrixSparsity (bool val)=0
virtual void setConstantMatrixValues (bool val)=0
virtual void setCSRValues (const CSRFormatView &csr_view)=0
virtual void setRunner (const Runner &r)=0
virtual void setSolverCommandLineArguments (const CommandLineArguments &args)=0
virtual VariableDoFReal & solutionVariable ()=0
virtual void solve ()=0
Detailed Description
Definition at line 37 of file IDoFLinearSystemImpl.h.
Constructor & Destructor Documentation
~IDoFLinearSystemImpl()
virtual Arcane::FemUtils::IDoFLinearSystemImpl::~IDoFLinearSystemImpl () virtual default
Member Function Documentation
applyMatrixTransformation()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::applyMatrixTransformation () pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::applyMatrixTransformation().
applyRHSTransformation()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::applyRHSTransformation () pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::applyRHSTransformation().
clearValues()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::clearValues () pure virtual
Implemented in Arcane::FemUtils::DoFLinearSystemImplBase, Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::clearValues().
eliminateRow()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::eliminateRow (DoFLocalId row, Real value) pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::_eliminateRow().
eliminateRowColumn()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::eliminateRowColumn (DoFLocalId row, Real value) pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::_eliminateRowColumn().
getCSRValues()
virtual CSRFormatView& Arcane::FemUtils::IDoFLinearSystemImpl::getCSRValues () pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::getCSRValues().
getEliminationInfo()
virtual VariableDoFByte& Arcane::FemUtils::IDoFLinearSystemImpl::getEliminationInfo () pure virtual
Implemented in Arcane::FemUtils::SequentialDoFLinearSystemImpl, and Arcane::FemUtils::DoFLinearSystemImplBase.
Referenced by Arcane::FemUtils::DoFLinearSystem::_getEliminationInfo().
getEliminationValue()
virtual VariableDoFReal& Arcane::FemUtils::IDoFLinearSystemImpl::getEliminationValue () pure virtual
Implemented in Arcane::FemUtils::SequentialDoFLinearSystemImpl, and Arcane::FemUtils::DoFLinearSystemImplBase.
Referenced by Arcane::FemUtils::DoFLinearSystem::_getEliminationValue().
getForcedInfo()
virtual VariableDoFBool& Arcane::FemUtils::IDoFLinearSystemImpl::getForcedInfo () pure virtual
Implemented in Arcane::FemUtils::SequentialDoFLinearSystemImpl, and Arcane::FemUtils::DoFLinearSystemImplBase.
Referenced by Arcane::FemUtils::DoFLinearSystem::getForcedInfo().
getForcedValue()
virtual VariableDoFReal& Arcane::FemUtils::IDoFLinearSystemImpl::getForcedValue () pure virtual
Implemented in Arcane::FemUtils::SequentialDoFLinearSystemImpl, and Arcane::FemUtils::DoFLinearSystemImplBase.
Referenced by Arcane::FemUtils::DoFLinearSystem::getForcedValue().
hasSetCSRValues()
virtual bool Arcane::FemUtils::IDoFLinearSystemImpl::hasSetCSRValues () const pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::hasSetCSRValues().
isMatrixSparsityConstant()
virtual bool Arcane::FemUtils::IDoFLinearSystemImpl::isMatrixSparsityConstant () const pure virtual
Implemented in Arcane::FemUtils::SequentialDoFLinearSystemImpl, and Arcane::FemUtils::DoFLinearSystemImplBase.
Referenced by Arcane::FemUtils::DoFLinearSystem::isMatrixSparsityConstant().
isMatrixValuesConstant()
virtual bool Arcane::FemUtils::IDoFLinearSystemImpl::isMatrixValuesConstant () const pure virtual
Implemented in Arcane::FemUtils::SequentialDoFLinearSystemImpl, and Arcane::FemUtils::DoFLinearSystemImplBase.
Referenced by Arcane::FemUtils::DoFLinearSystem::isMatrixValuesConstant().
matrixAddValue()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
matrixSetValue()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::matrixSetValue().
rhsVariable()
virtual VariableDoFReal& Arcane::FemUtils::IDoFLinearSystemImpl::rhsVariable () pure virtual
Implemented in Arcane::FemUtils::SequentialDoFLinearSystemImpl, and Arcane::FemUtils::DoFLinearSystemImplBase.
Referenced by Arcane::FemUtils::DoFLinearSystem::rhsVariable().
runner()
virtual Runner Arcane::FemUtils::IDoFLinearSystemImpl::runner () const pure virtual
Implemented in Arcane::FemUtils::DoFLinearSystemImplBase, and Arcane::FemUtils::SequentialDoFLinearSystemImpl.
setConstantMatrixSparsity()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::setConstantMatrixSparsity (bool val) pure virtual
Implemented in Arcane::FemUtils::DoFLinearSystemImplBase, and Arcane::FemUtils::SequentialDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::setConstantMatrixSparsity().
setConstantMatrixValues()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::setConstantMatrixValues (bool val) pure virtual
Implemented in Arcane::FemUtils::DoFLinearSystemImplBase, and Arcane::FemUtils::SequentialDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::setConstantMatrixValues().
setCSRValues()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::setCSRValues (const CSRFormatView & csr_view) pure virtual
Implemented in Arcane::FemUtils::CsrDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::setCSRValues().
setRunner()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::setRunner (const Runner & r) pure virtual
Implemented in Arcane::FemUtils::DoFLinearSystemImplBase, and Arcane::FemUtils::SequentialDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::initialize().
setSolverCommandLineArguments()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::setSolverCommandLineArguments (const CommandLineArguments & args) pure virtual
Implemented in Arcane::FemUtils::PETScDoFLinearSystemImpl, Arcane::FemUtils::HypreDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, Arcane::FemUtils::AlephDoFLinearSystemImpl, and Arcane::FemUtils::SequentialDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::setSolverCommandLineArguments().
solutionVariable()
virtual VariableDoFReal& Arcane::FemUtils::IDoFLinearSystemImpl::solutionVariable () pure virtual
Implemented in Arcane::FemUtils::SequentialDoFLinearSystemImpl, and Arcane::FemUtils::DoFLinearSystemImplBase.
Referenced by Arcane::FemUtils::DoFLinearSystem::solutionVariable().
solve()
virtual void Arcane::FemUtils::IDoFLinearSystemImpl::solve () pure virtual
Implemented in Arcane::FemUtils::PETScDoFLinearSystemImpl, Arcane::FemUtils::HypreDoFLinearSystemImpl, Arcane::FemUtils::SequentialDoFLinearSystemImpl, Arcane::FemUtils::AlienDoFLinearSystemImpl, and Arcane::FemUtils::AlephDoFLinearSystemImpl.
Referenced by Arcane::FemUtils::DoFLinearSystem::solve().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/internal/IDoFLinearSystemImpl.h