ShArc: Arcane::FemUtils::BSRMatrix Class Reference
Arcane::FemUtils::BSRMatrix Class Reference
A class representing a Block Sparse Row (BSR) matrix.
#include <BSRFormat.h>
Public Member Functions
BSRMatrix (ITraceMng *tm, const eMemoryRessource &mem_ressource, const RunQueue &queue)
AI generated: Constructor.
void addValue (DoFLocalId row, DoFLocalId col, Real value)
AI generated: Adds a value at a given (row, col) DoF pair.
void dump (const String &filename)
AI generated: Dumps the matrix to a file.
Int32 findValueIndex (DoFLocalId row, DoFLocalId col) const
AI generated: Finds the value index for a given (row, col) DoF pair.
Real getValue (DoFLocalId row, DoFLocalId col) const
AI generated: Gets the value at a given (row, col) DoF pair.
void initialize (Int32 nb_non_zero_value, Int32 nb_col, Int32 nb_row, Int8 nb_block, bool order_values_per_block)
AI generated: Initializes matrix dimensions and storage order.
Int8 nbBlock ()
AI generated: Returns the number of blocks.
Int32 nbColumn ()
AI generated: Returns the number of columns.
Int32 nbNonZero ()
AI generated: Returns the number of non-zero values.
Int32 nbRow ()
AI generated: Returns the number of rows.
bool orderValuePerBlock ()
AI generated: Returns whether values are ordered per block.
void setValue (DoFLocalId row, DoFLocalId col, Real value)
AI generated: Sets the value at a given (row, col) DoF pair.
void toCsr (CsrFormat *csr_matrix)
AI generated: Converts the BSR matrix to CSR format.
void toLinearSystem (DoFLinearSystem &linear_system)
AI generated: Converts to a DoF linear system.
Private Member Functions
NumArray< Int32, MDDim1 > & _columns ()
NumArray< Int32, MDDim1 > & _nbNonZeroPerRows ()
NumArray< Int32, MDDim1 > & _rowsIndex ()
NumArray< Real, MDDim1 > & _values ()
Private Attributes
NumArray< Int32, MDDim1 > m_columns
Int8 m_nb_block = 1
Int32 m_nb_col = 0
NumArray< Int32, MDDim1 > m_nb_non_zero_per_rows
Int32 m_nb_non_zero_value = 0
Int32 m_nb_row = 0
bool m_order_values_per_block = true
RunQueue m_queue
NumArray< Int32, MDDim1 > m_rows_index
NumArray< Real, MDDim1 > m_values
Friends
class BSRFormat
Detailed Description
A class representing a Block Sparse Row (BSR) matrix.
The BSRMatrix class stores sparse matrices in the Block Sparse Row (BSR) format, suitable for block-structured computations.
The BSR format groups non-zero elements into fixed-size blocks, enabling efficient storage and computation for multi-DoFs meshes. Below is an example for a 6x6 matrix with a block size of 2x2 (2 DoFs per node).
Original Matrix (6x6, Block Size = 2x2):
[ 1  2  0  0  0  0 ]
[ 3  4  0  0  0  0 ]
[ 0  0  5  6  7  8 ]
[ 0  0  9 10 11 12 ]
[ 0  0  0  0 13 14 ]
[ 0  0  0  0 15 16 ]
BSR Representation:
  - Values:
     if "Ordered per block":
       [ 1, 2, 3, 4, 5, 6, 9, 10, 7, 8, 11, 12, 13, 14, 15, 16 ]
     if "Ordered per row" (same as CSR):
       [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
  - Columns:   [ 0, 1, 2, 2 ]  // Column indices of each block
  - Row Index: [ 0, 1, 3 ]     // Starting indices of blocks per row
Note
The class supports flexible memory management for computations on different hardware backends (e.g., CPU, GPU). Having the value array stored in per row (which the way CSR format stores matrices) allow us to pass it directly to HYPRE (which support CSR but not BSR), whithout the need for a translation step on it.
Definition at line 76 of file BSRFormat.h.
Constructor & Destructor Documentation
BSRMatrix()
Arcane::FemUtils::BSRMatrix::BSRMatrix (ITraceMng * tm, const eMemoryRessource & mem_ressource, const RunQueue & queue)
AI generated: Constructor.
Definition at line 37 of file BSRFormat.cc.
Member Function Documentation
_columns()
NumArray<Int32, MDDim1>& Arcane::FemUtils::BSRMatrix::_columns () inline private
Definition at line 131 of file BSRFormat.h.
References m_columns.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree(), Arcane::FemUtils::BSRFormat::computeColumns(), and Arcane::FemUtils::BSRFormat::computeColumnsAtomicFree().
_nbNonZeroPerRows()
NumArray<Int32, MDDim1>& Arcane::FemUtils::BSRMatrix::_nbNonZeroPerRows () inline private
Definition at line 133 of file BSRFormat.h.
References m_nb_non_zero_per_rows.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree(), and Arcane::FemUtils::BSRFormat::computeNzPerRowArray().
_rowsIndex()
NumArray<Int32, MDDim1>& Arcane::FemUtils::BSRMatrix::_rowsIndex () inline private
Definition at line 132 of file BSRFormat.h.
References m_rows_index.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree(), Arcane::FemUtils::BSRFormat::computeColumns(), Arcane::FemUtils::BSRFormat::computeColumnsAtomicFree(), Arcane::FemUtils::BSRFormat::computeNzPerRowArray(), Arcane::FemUtils::BSRFormat::computeRowIndex(), and Arcane::FemUtils::BSRFormat::computeRowIndexAtomicFree().
_values()
NumArray<Real, MDDim1>& Arcane::FemUtils::BSRMatrix::_values () inline private
Definition at line 130 of file BSRFormat.h.
References m_values.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree(), and Arcane::FemUtils::BSRFormat::resetMatrixValues().
addValue()
void Arcane::FemUtils::BSRMatrix::addValue (DoFLocalId row, DoFLocalId col, Real value) inline
AI generated: Adds a value at a given (row, col) DoF pair.
Definition at line 105 of file BSRFormat.h.
References findValueIndex(), and m_values.
dump()
void Arcane::FemUtils::BSRMatrix::dump (const String & filename)
AI generated: Dumps the matrix to a file.
Definition at line 202 of file BSRFormat.cc.
References m_columns, m_rows_index, m_values, nbNonZero(), and nbRow().
Referenced by Arcane::FemUtils::BSRFormat::dumpMatrix().
findValueIndex()
Int32 Arcane::FemUtils::BSRMatrix::findValueIndex (DoFLocalId row, DoFLocalId col) const
AI generated: Finds the value index for a given (row, col) DoF pair.
Definition at line 79 of file BSRFormat.cc.
References m_columns, m_nb_block, m_nb_col, m_nb_non_zero_per_rows, m_nb_row, m_order_values_per_block, and m_rows_index.
Referenced by addValue(), getValue(), and setValue().
getValue()
Real Arcane::FemUtils::BSRMatrix::getValue (DoFLocalId row, DoFLocalId col) const inline
AI generated: Gets the value at a given (row, col) DoF pair.
Definition at line 93 of file BSRFormat.h.
References findValueIndex(), and m_values.
Referenced by toLinearSystem().
initialize()
void Arcane::FemUtils::BSRMatrix::initialize (Int32 nb_non_zero_value, Int32 nb_col, Int32 nb_row, Int8 nb_block, bool order_values_per_block)
AI generated: Initializes matrix dimensions and storage order.
Definition at line 48 of file BSRFormat.cc.
References m_columns, m_nb_block, m_nb_col, m_nb_non_zero_per_rows, m_nb_non_zero_value, m_nb_row, m_order_values_per_block, m_queue, m_rows_index, and m_values.
Referenced by Arcane::FemUtils::BSRFormat::initialize().
nbBlock()
Int8 Arcane::FemUtils::BSRMatrix::nbBlock () inline
AI generated: Returns the number of blocks.
Definition at line 126 of file BSRFormat.h.
References m_nb_block.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow(), and Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree().
nbColumn()
Int32 Arcane::FemUtils::BSRMatrix::nbColumn () inline
AI generated: Returns the number of columns.
Definition at line 122 of file BSRFormat.h.
References m_nb_col.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree(), and Arcane::FemUtils::BSRFormat::computeNzPerRowArray().
nbNonZero()
Int32 Arcane::FemUtils::BSRMatrix::nbNonZero () inline
AI generated: Returns the number of non-zero values.
Definition at line 120 of file BSRFormat.h.
References m_nb_non_zero_value.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree(), and dump().
nbRow()
Int32 Arcane::FemUtils::BSRMatrix::nbRow () inline
AI generated: Returns the number of rows.
Definition at line 124 of file BSRFormat.h.
References m_nb_row.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree(), Arcane::FemUtils::BSRFormat::computeNzPerRowArray(), and dump().
orderValuePerBlock()
bool Arcane::FemUtils::BSRMatrix::orderValuePerBlock () inline
AI generated: Returns whether values are ordered per block.
Definition at line 118 of file BSRFormat.h.
References m_order_values_per_block.
Referenced by Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), and Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree().
setValue()
void Arcane::FemUtils::BSRMatrix::setValue (DoFLocalId row, DoFLocalId col, Real value) inline
AI generated: Sets the value at a given (row, col) DoF pair.
Definition at line 99 of file BSRFormat.h.
References findValueIndex(), and m_values.
toCsr()
void Arcane::FemUtils::BSRMatrix::toCsr (CsrFormat * csr_matrix)
AI generated: Converts the BSR matrix to CSR format.
Definition at line 110 of file BSRFormat.cc.
References Arcane::FemUtils::CsrFormat::initialize(), m_columns, Arcane::FemUtils::CsrFormat::m_matrix_column, Arcane::FemUtils::CsrFormat::m_matrix_row, Arcane::FemUtils::CsrFormat::m_matrix_rows_nb_column, Arcane::FemUtils::CsrFormat::m_matrix_value, m_nb_block, m_nb_col, m_nb_non_zero_per_rows, m_nb_non_zero_value, m_queue, m_rows_index, and m_values.
Referenced by Arcane::FemUtils::BSRFormat::toLinearSystem().
toLinearSystem()
void Arcane::FemUtils::BSRMatrix::toLinearSystem (DoFLinearSystem & linear_system)
AI generated: Converts to a DoF linear system.
Definition at line 177 of file BSRFormat.cc.
References getValue(), m_columns, m_nb_block, m_nb_col, m_nb_row, m_rows_index, and Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
Referenced by Arcane::FemUtils::BSRFormat::toLinearSystem().
Friends And Related Function Documentation
BSRFormat
friend class BSRFormat friend
Definition at line 79 of file BSRFormat.h.
Member Data Documentation
m_columns
NumArray<Int32, MDDim1> Arcane::FemUtils::BSRMatrix::m_columns private
Definition at line 145 of file BSRFormat.h.
Referenced by _columns(), dump(), findValueIndex(), initialize(), toCsr(), and toLinearSystem().
m_nb_block
Int8 Arcane::FemUtils::BSRMatrix::m_nb_block = 1 private
Definition at line 142 of file BSRFormat.h.
Referenced by findValueIndex(), initialize(), nbBlock(), toCsr(), and toLinearSystem().
m_nb_col
Int32 Arcane::FemUtils::BSRMatrix::m_nb_col = 0 private
Definition at line 140 of file BSRFormat.h.
Referenced by findValueIndex(), initialize(), nbColumn(), toCsr(), and toLinearSystem().
m_nb_non_zero_per_rows
NumArray<Int32, MDDim1> Arcane::FemUtils::BSRMatrix::m_nb_non_zero_per_rows private
Definition at line 147 of file BSRFormat.h.
Referenced by _nbNonZeroPerRows(), findValueIndex(), initialize(), and toCsr().
m_nb_non_zero_value
Int32 Arcane::FemUtils::BSRMatrix::m_nb_non_zero_value = 0 private
Definition at line 139 of file BSRFormat.h.
Referenced by initialize(), nbNonZero(), and toCsr().
m_nb_row
Int32 Arcane::FemUtils::BSRMatrix::m_nb_row = 0 private
Definition at line 141 of file BSRFormat.h.
Referenced by findValueIndex(), initialize(), nbRow(), and toLinearSystem().
m_order_values_per_block
bool Arcane::FemUtils::BSRMatrix::m_order_values_per_block = true private
Definition at line 137 of file BSRFormat.h.
Referenced by findValueIndex(), initialize(), and orderValuePerBlock().
m_queue
RunQueue Arcane::FemUtils::BSRMatrix::m_queue private
Definition at line 149 of file BSRFormat.h.
Referenced by initialize(), and toCsr().
m_rows_index
NumArray<Int32, MDDim1> Arcane::FemUtils::BSRMatrix::m_rows_index private
Definition at line 146 of file BSRFormat.h.
Referenced by _rowsIndex(), dump(), findValueIndex(), initialize(), toCsr(), and toLinearSystem().
m_values
NumArray<Real, MDDim1> Arcane::FemUtils::BSRMatrix::m_values private
Definition at line 144 of file BSRFormat.h.
Referenced by _values(), addValue(), dump(), getValue(), initialize(), setValue(), and toCsr().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/BSRFormat.h
src/CAWF/FEMUtils/BSRFormat.cc