ShArc: FemModulePoisson Class Reference
FemModulePoisson Class Reference
CAWF
Finite Element module for the Poisson (scalar elliptic) equation.
#include <FemPoissonModule.h>
Public Member Functions
FemModulePoisson (const ModuleBuildInfo &mbi)
void _assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
void _assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step.
void compute () override
Performs the main computation for the FemModulePoisson.
void startInit () override
Initializes the FemModulePoisson at the start of the simulation.
VersionInfo versionInfo () const override
Private Member Functions
template<int N>
void _assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
AI comment: Assembles the bilinear form using element matrix computation callback.
void _assembleLinearOperator ()
Assembles the FEM linear operator for the current simulation step.
void _assembleLinearOperatorCpu ()
FEM linear operator for the current simulation step.
RealMatrix< 8, 8 > _computeElementMatrixHexa8 (Cell cell)
AI comment: Computes the 8-node hexahedron element matrix.
RealMatrix< 4, 4 > _computeElementMatrixQuad4 (Cell cell)
AI comment: Computes the 4-node quadrilateral element matrix.
RealMatrix< 4, 4 > _computeElementMatrixTetra4 (Cell cell)
AI comment: Computes the 4-node tetrahedron element matrix.
RealMatrix< 3, 3 > _computeElementMatrixTria3 (Cell cell)
AI comment: Computes the 3-node triangle element matrix.
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _getMaterialParameters ()
Retrieves and sets the material parameters for the simulation.
void _solve ()
Solves the linear system.
void _updateVariables ()
Update the FEM variables.
void _validateResults ()
Validates and prints the results of the FEM computation.
Private Attributes
Real f
bool m_assemble_linear_system = true
BSRFormat m_bsr_format
bool m_cross_validation = false
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
bool m_hex_quad_mesh = false
DoFLinearSystem m_linear_system
String m_matrix_format = "DOK"
String m_petsc_flags
bool m_solve_linear_system = true
Detailed Description
Finite Element module for the Poisson (scalar elliptic) equation.
AI-Generated Documentation:
Solves a steady-state diffusion problem using the Finite Element Method. Supports multiple element types (Tria3, Tetra4, Quad4, Hexa8) with CPU and GPU assembly backends.
Definition at line 66 of file FemPoissonModule.h.
Constructor & Destructor Documentation
FemModulePoisson()
FemModulePoisson::FemModulePoisson (const ModuleBuildInfo & mbi) inline explicit
AI-Generated Documentation: Constructs the Poisson FEM module
Definition at line 72 of file FemPoissonModule.h.
Member Function Documentation
_assembleBilinear()
template<int N> void FemModulePoisson::_assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
AI comment: Assembles the bilinear form using element matrix computation callback.
Assembles the bilinear operator matrix for the FEM linear system.
The method performs the following steps:
For each cell, retrieves the cell-specific constant lambda.
Computes element matrix using provided compute_element_matrix function.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 364 of file FemPoissonModule.cc.
References m_dofs_on_nodes, m_linear_system, Arcane::FemUtils::DoFLinearSystem::matrixAddValue(), and Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView().
_assembleBilinearOperator()
void FemModulePoisson::_assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
AI-Generated Documentation: Assembles the bilinear operator (stiffness matrix)
Definition at line 298 of file FemPoissonModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), _computeElementMatrixTetra4Gpu(), _computeElementMatrixTria3(), _computeElementMatrixTria3Gpu(), _computeElementVectorTetra4Gpu(), _computeElementVectorTria3Gpu(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), m_bsr_format, m_hex_quad_mesh, m_linear_system, m_matrix_format, ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::BSRFormat::toLinearSystem().
Referenced by _doStationarySolve().
_assembleLinearOperator()
void FemModulePoisson::_assembleLinearOperator () private
Assembles the FEM linear operator for the current simulation step.
AI-Generated Documentation: Assembles the full linear operator (stiffness + BCs)
This method constructs the right-hand side (RHS) vector by calling then appropriate assembly function based on the execution context:
CPU-exclusive execution: Calls _assembleLinearOperatorCpu().
CPU or GPU execution: Calls _assembleLinearOperatorGpu().
Definition at line 160 of file FemPoissonModule.cc.
References _assembleLinearOperatorCpu(), and _assembleLinearOperatorGpu().
Referenced by _doStationarySolve().
_assembleLinearOperatorCpu()
void FemModulePoisson::_assembleLinearOperatorCpu () private
FEM linear operator for the current simulation step.
AI-Generated Documentation: Assembles the linear operator on CPU
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 239 of file FemPoissonModule.cc.
References ArcaneFemFunctions::BoundaryConditions3D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyConstantSourceToRhsHexa8(), ArcaneFemFunctions::BoundaryConditions2D::applyConstantSourceToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhsHexa8(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), BC::IArcaneFemBC::dirichletBoundaryConditions(), BC::IArcaneFemBC::dirichletPointConditions(), f, m_dofs_on_nodes, m_hex_quad_mesh, m_linear_system, BC::IArcaneFemBC::neumannBoundaryConditions(), Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperator().
_assembleLinearOperatorGpu()
void FemModulePoisson::_assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step.
AI-Generated Documentation: Assembles the linear operator on GPU
GPU compatible. Currently working with HypreDoFLinearSystem.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 184 of file FemPoissonModule.cc.
References BC::IArcaneFemBC::dirichletBoundaryConditions(), BC::IArcaneFemBC::dirichletPointConditions(), f, Arcane::FemUtils::DoFLinearSystem::getForcedInfo(), m_dofs_on_nodes, m_linear_system, BC::IArcaneFemBC::neumannBoundaryConditions(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperator().
_computeElementMatrixHexa8()
RealMatrix< 8, 8 > FemModulePoisson::_computeElementMatrixHexa8 (Cell cell) private
AI comment: Computes the 8-node hexahedron element matrix.
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Define Gauss points (2x2x2) and weights.
Loop over Gauss points to compute the gradients in physical space (𝑥,𝑦,𝑧) and the determinant of the Jacobian via computeGradientsAndJacobianHexa8.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 86 of file ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), and M_SQRT1_3.
Referenced by _assembleBilinearOperator().
_computeElementMatrixQuad4()
RealMatrix< 4, 4 > FemModulePoisson::_computeElementMatrixQuad4 (Cell cell) private
AI comment: Computes the 4-node quadrilateral element matrix.
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 33 of file ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), and M_SQRT1_3.
Referenced by _assembleBilinearOperator().
_computeElementMatrixTetra4()
RealMatrix< 4, 4 > FemModulePoisson::_computeElementMatrixTetra4 (Cell cell) private
AI comment: Computes the 4-node tetrahedron element matrix.
Computes the element matrix for a tetrahedral element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 79 of file ElementMatrix.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTria3()
RealMatrix< 3, 3 > FemModulePoisson::_computeElementMatrixTria3 (Cell cell) private
AI comment: Computes the 3-node triangle element matrix.
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 28 of file ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator().
_doStationarySolve()
void FemModulePoisson::_doStationarySolve () private
Performs a stationary solve for the FEM system.
AI-Generated Documentation: Performs a stationary (direct) solve
This method follows a sequence of steps to solve FEM system:
_getMaterialParameters() Retrieves material parameters via
_assembleBilinearOperator() Assembles the FEM matrix A
_assembleLinearOperator() Assembles the FEM RHS vector b
_solve() Solves for solution vector u = A^-1*b
_updateVariables() Updates FEM variables u = x
_validateResults() Regression test
Definition at line 110 of file FemPoissonModule.cc.
References _assembleBilinearOperator(), _assembleLinearOperator(), _getMaterialParameters(), _solve(), _updateVariables(), _validateResults(), m_assemble_linear_system, m_cross_validation, and m_solve_linear_system.
Referenced by compute().
_getMaterialParameters()
void FemModulePoisson::_getMaterialParameters () private
Retrieves and sets the material parameters for the simulation.
AI-Generated Documentation: Retrieves material parameters from the case file
Definition at line 136 of file FemPoissonModule.cc.
References f, and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_solve()
void FemModulePoisson::_solve () private
Solves the linear system.
AI-Generated Documentation: Solves the assembled linear system
Definition at line 394 of file FemPoissonModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), m_linear_system, and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateVariables()
void FemModulePoisson::_updateVariables () private
Update the FEM variables.
AI-Generated Documentation: Updates time-dependent variables
This method performs the following actions:
Fetches values of solution from solved linear system to FEM variables, i.e., it copies RHS DOF to u.
Performs synchronize of FEM variables across subdomains.
Definition at line 417 of file FemPoissonModule.cc.
References m_dofs_on_nodes, m_linear_system, Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModulePoisson::_validateResults () private
Validates and prints the results of the FEM computation.
AI-Generated Documentation: Validates results against reference values
This method performs the following actions:
If number of nodes < 200, prints the computed values for each node.
Retrieves the filename for the result file from options.
If a filename is provided, checks the computed results against result file.
Note
The result comparison uses a tolerance of 1.0e-4.
Definition at line 451 of file FemPoissonModule.cc.
References Arcane::FemUtils::checkNodeResultFile(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
compute()
void FemModulePoisson::compute () override
Performs the main computation for the FemModulePoisson.
AI-Generated Documentation: Computes the solution at each iteration
This method:
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Executes the stationary solve.
Definition at line 57 of file FemPoissonModule.cc.
References _doStationarySolve(), Arcane::FemUtils::BSRFormat::computeSparsity(), Arcane::FemUtils::FemDoFsOnNodes::dofFamily(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), Arcane::FemUtils::BSRFormat::initialize(), Arcane::FemUtils::DoFLinearSystem::initialize(), m_bsr_format, m_dofs_on_nodes, m_linear_system, m_matrix_format, m_petsc_flags, ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory(), and Arcane::FemUtils::DoFLinearSystem::setSolverCommandLineArguments().
startInit()
void FemModulePoisson::startInit () override
Initializes the FemModulePoisson at the start of the simulation.
AI-Generated Documentation: Method called at the beginning of the simulation
This method initializes degrees of freedom (DoFs) on nodes.
Definition at line 26 of file FemPoissonModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::dofFamily(), Arcane::FemUtils::FemDoFsOnNodes::initialize(), m_assemble_linear_system, m_cross_validation, m_dof_family, m_dofs_on_nodes, m_hex_quad_mesh, m_matrix_format, m_petsc_flags, m_solve_linear_system, and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModulePoisson::versionInfo () const inline override
AI-Generated Documentation: Returns the module version
Definition at line 87 of file FemPoissonModule.h.
Member Data Documentation
f
Real FemModulePoisson::f private
AI-Generated Documentation: Source term value
Definition at line 106 of file FemPoissonModule.h.
Referenced by _assembleLinearOperatorCpu(), _assembleLinearOperatorGpu(), and _getMaterialParameters().
m_assemble_linear_system
bool FemModulePoisson::m_assemble_linear_system = true private
AI-Generated Documentation: Whether to assemble the linear system
Definition at line 114 of file FemPoissonModule.h.
Referenced by _doStationarySolve(), and startInit().
m_bsr_format
BSRFormat FemModulePoisson::m_bsr_format private
AI-Generated Documentation: Block sparse row matrix format for assembly
Definition at line 97 of file FemPoissonModule.h.
Referenced by _assembleBilinearOperator(), and compute().
m_cross_validation
bool FemModulePoisson::m_cross_validation = false private
AI-Generated Documentation: Whether to perform cross-validation
Definition at line 118 of file FemPoissonModule.h.
Referenced by _doStationarySolve(), and startInit().
m_dof_family
IItemFamily* FemModulePoisson::m_dof_family = nullptr private
AI-Generated Documentation: Degree-of-freedom item family
Definition at line 101 of file FemPoissonModule.h.
Referenced by startInit().
m_dofs_on_nodes
FemDoFsOnNodes FemModulePoisson::m_dofs_on_nodes private
AI-Generated Documentation: DoF mapping on mesh nodes
Definition at line 103 of file FemPoissonModule.h.
Referenced by _assembleBilinear(), _assembleLinearOperatorCpu(), _assembleLinearOperatorGpu(), _updateVariables(), compute(), and startInit().
m_hex_quad_mesh
bool FemModulePoisson::m_hex_quad_mesh = false private
AI-Generated Documentation: Whether the mesh uses hex/quad elements
Definition at line 120 of file FemPoissonModule.h.
Referenced by _assembleBilinearOperator(), _assembleLinearOperatorCpu(), and startInit().
m_linear_system
DoFLinearSystem FemModulePoisson::m_linear_system private
AI-Generated Documentation: Linear system (matrix + RHS + solution)
Definition at line 99 of file FemPoissonModule.h.
Referenced by _assembleBilinear(), _assembleBilinearOperator(), _assembleLinearOperatorCpu(), _assembleLinearOperatorGpu(), _solve(), _updateVariables(), and compute().
m_matrix_format
String FemModulePoisson::m_matrix_format = "DOK" private
AI-Generated Documentation: Matrix format type
Definition at line 111 of file FemPoissonModule.h.
Referenced by _assembleBilinearOperator(), compute(), and startInit().
m_petsc_flags
String FemModulePoisson::m_petsc_flags private
AI-Generated Documentation: PETSc solver flags
Definition at line 109 of file FemPoissonModule.h.
Referenced by compute(), and startInit().
m_solve_linear_system
bool FemModulePoisson::m_solve_linear_system = true private
AI-Generated Documentation: Whether to solve the linear system
Definition at line 116 of file FemPoissonModule.h.
Referenced by _doStationarySolve(), and startInit().
The documentation for this class was generated from the following files:
src/CAWF/Poisson/FemPoissonModule.h
src/CAWF/Poisson/ElementMatrix.h
src/CAWF/Poisson/ElementMatrixHexQuad.h
src/CAWF/Poisson/FemPoissonModule.cc