ShArc: Arcane::FemUtils::RealVector< N > Class Template Reference
Arcane::FemUtils::RealVector< N > Class Template Reference
Vector of size N.
#include <FemUtils.h>
Public Member Functions
ARCCORE_HOST_DEVICE RealVector ()=default
ARCCORE_HOST_DEVICE RealVector (std::initializer_list< Arcane::Real > init_list)
ARCCORE_HOST_DEVICE void add (const RealVector< N > &b)
Add b to this vector.
ARCCORE_HOST_DEVICE void addInPlace (Arcane::Real v)
Add v to all the components.
void dump (std::ostream &o) const
Dump values.
ARCCORE_HOST_DEVICE void multInPlace (Arcane::Real v)
Multiply all the components by v.
ARCCORE_HOST_DEVICE Arcane::Real & operator() (Arcane::Int32 i)
Add operator()
ARCCORE_HOST_DEVICE Arcane::Real operator() (Arcane::Int32 i) const
Add operator()
ARCCORE_HOST_DEVICE RealVector< N > operator* (Real scalar) const
Scalar multiplication: RealVector * scalar.
ARCCORE_HOST_DEVICE RealVector< N > operator+ (const RealVector< N > &other) const
Define the addition operator.
RealVector< N > operator- () const
Define the unary negation operator.
RealVector< N > operator- (const RealVector< N > &other) const
Define the subtraction operator.
ARCCORE_HOST_DEVICE RealVector< N > operator/ (Real scalar) const
Scalar division: RealVector / scalar.
ARCCORE_HOST_DEVICE Arcane::Real & operator[] (Arcane::Int32 i)
Add operator[].
ARCCORE_HOST_DEVICE Arcane::Real operator[] (Arcane::Int32 i) const
Add operator[].
ARCCORE_HOST_DEVICE void setEqualTo (const RealVector< N > &b)
Set this vector equal to b.
ARCCORE_HOST_DEVICE void sub (const RealVector< N > &b)
Substract b to this vector.
Static Public Member Functions
static constexpr Arcane::Int32 totalNbElement ()
Protected Attributes
std::array< Arcane::Real, totalNbElement()> m_values = {}
Private Types
using ThatClass = RealVector< N >
Friends
ARCCORE_HOST_DEVICE friend Real dot (const RealVector< N > &u, const RealVector< N > &v)
Friend function for dot product of RealVector.
ARCCORE_HOST_DEVICE friend RealVector< N > operator* (Real scalar, const RealVector< N > &vector)
Friend function for scalar multiplication: scalar * RealVector.
Detailed Description
template<int N>
class Arcane::FemUtils::RealVector< N >
Vector of size N.
Definition at line 363 of file FemUtils.h.
Member Typedef Documentation
ThatClass
template<int N> using Arcane::FemUtils::RealVector< N >::ThatClass = RealVector<N> private
Definition at line 365 of file FemUtils.h.
Constructor & Destructor Documentation
RealVector() [1/2]
template<int N> ARCCORE_HOST_DEVICE Arcane::FemUtils::RealVector< N >::RealVector () default
RealVector() [2/2]
template<int N> ARCCORE_HOST_DEVICE Arcane::FemUtils::RealVector< N >::RealVector (std::initializer_list< Arcane::Real > init_list) inline
Definition at line 373 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values.
Member Function Documentation
add()
template<int N> ARCCORE_HOST_DEVICE void Arcane::FemUtils::RealVector< N >::add (const RealVector< N > & b) inline
Add b to this vector.
Definition at line 477 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values, and Arcane::FemUtils::RealVector< N >::totalNbElement().
addInPlace()
template<int N> ARCCORE_HOST_DEVICE void Arcane::FemUtils::RealVector< N >::addInPlace (Arcane::Real v) inline
Add v to all the components.
Definition at line 421 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values, and Arcane::FemUtils::RealVector< N >::totalNbElement().
Referenced by Arcane::FemUtils::Tensor2::addInPlace().
dump()
template<int N> void Arcane::FemUtils::RealVector< N >::dump (std::ostream & o) const inline
Dump values.
Definition at line 428 of file FemUtils.h.
Referenced by Arcane::FemUtils::Tensor2::dump().
multInPlace()
template<int N> ARCCORE_HOST_DEVICE void Arcane::FemUtils::RealVector< N >::multInPlace (Arcane::Real v) inline
Multiply all the components by v.
Definition at line 414 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values, and Arcane::FemUtils::RealVector< N >::totalNbElement().
Referenced by Arcane::FemUtils::Tensor2::multInPlace().
operator()() [1/2]
template<int N> ARCCORE_HOST_DEVICE Arcane::Real& Arcane::FemUtils::RealVector< N >::operator() (Arcane::Int32 i) inline
Add operator()
Definition at line 384 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values.
operator()() [2/2]
template<int N> ARCCORE_HOST_DEVICE Arcane::Real Arcane::FemUtils::RealVector< N >::operator() (Arcane::Int32 i) const inline
Add operator()
Definition at line 391 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values.
operator*()
template<int N> ARCCORE_HOST_DEVICE RealVector<N> Arcane::FemUtils::RealVector< N >::operator* (Real scalar) const inline
Scalar multiplication: RealVector * scalar.
Definition at line 493 of file FemUtils.h.
operator+()
template<int N> ARCCORE_HOST_DEVICE RealVector<N> Arcane::FemUtils::RealVector< N >::operator+ (const RealVector< N > & other) const inline
Define the addition operator.
Definition at line 439 of file FemUtils.h.
operator-() [1/2]
template<int N> RealVector<N> Arcane::FemUtils::RealVector< N >::operator- () const inline
Define the unary negation operator.
Definition at line 459 of file FemUtils.h.
operator-() [2/2]
template<int N> RealVector<N> Arcane::FemUtils::RealVector< N >::operator- (const RealVector< N > & other) const inline
Define the subtraction operator.
Definition at line 449 of file FemUtils.h.
operator/()
template<int N> ARCCORE_HOST_DEVICE RealVector<N> Arcane::FemUtils::RealVector< N >::operator/ (Real scalar) const inline
Scalar division: RealVector / scalar.
Definition at line 503 of file FemUtils.h.
operator[]() [1/2]
template<int N> ARCCORE_HOST_DEVICE Arcane::Real& Arcane::FemUtils::RealVector< N >::operator[] (Arcane::Int32 i) inline
Add operator[].
Definition at line 398 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values.
operator[]() [2/2]
template<int N> ARCCORE_HOST_DEVICE Arcane::Real Arcane::FemUtils::RealVector< N >::operator[] (Arcane::Int32 i) const inline
Add operator[].
Definition at line 405 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values.
setEqualTo()
template<int N> ARCCORE_HOST_DEVICE void Arcane::FemUtils::RealVector< N >::setEqualTo (const RealVector< N > & b) inline
Set this vector equal to b.
Definition at line 469 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values, and Arcane::FemUtils::RealVector< N >::totalNbElement().
sub()
template<int N> ARCCORE_HOST_DEVICE void Arcane::FemUtils::RealVector< N >::sub (const RealVector< N > & b) inline
Substract b to this vector.
Definition at line 485 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::m_values, and Arcane::FemUtils::RealVector< N >::totalNbElement().
totalNbElement()
template<int N> static constexpr Arcane::Int32 Arcane::FemUtils::RealVector< N >::totalNbElement () inline static constexpr
Definition at line 369 of file FemUtils.h.
Referenced by Arcane::FemUtils::RealVector< N >::add(), Arcane::FemUtils::RealVector< N >::addInPlace(), Arcane::FemUtils::RealVector< N >::multInPlace(), Arcane::FemUtils::RealVector< N >::setEqualTo(), and Arcane::FemUtils::RealVector< N >::sub().
Friends And Related Function Documentation
dot
template<int N> ARCCORE_HOST_DEVICE friend Real dot (const RealVector< N > & u, const RealVector< N > & v) friend
Friend function for dot product of RealVector.
Definition at line 523 of file FemUtils.h.
operator*
template<int N> ARCCORE_HOST_DEVICE friend RealVector<N> operator* (Real scalar, const RealVector< N > & vector) friend
Friend function for scalar multiplication: scalar * RealVector.
Definition at line 513 of file FemUtils.h.
Member Data Documentation
m_values
template<int N> std::array<Arcane::Real, totalNbElement()> Arcane::FemUtils::RealVector< N >::m_values = {} protected
Definition at line 535 of file FemUtils.h.
Referenced by Arcane::FemUtils::RealVector< N >::RealVector(), Arcane::FemUtils::RealVector< N >::add(), Arcane::FemUtils::RealVector< N >::addInPlace(), Arcane::FemUtils::RealVector< N >::multInPlace(), Arcane::FemUtils::RealVector< N >::operator()(), Arcane::FemUtils::RealVector< N >::operator[](), Arcane::FemUtils::RealVector< N >::setEqualTo(), and Arcane::FemUtils::RealVector< N >::sub().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/FemUtils.h