ShArc: Arcane::FemUtils::AlienDoFLinearSystemImpl Class Reference
Arcane::FemUtils::AlienDoFLinearSystemImpl Class Reference
AI generated: Implementation of DoFLinearSystem using Alien linear algebra.
#include <AlienDoFLinearSystem.h>
Public Member Functions
AlienDoFLinearSystemImpl (IItemFamily *dof_family, const String &solver_name)
~AlienDoFLinearSystemImpl () override
void applyMatrixTransformation () override
void applyRHSTransformation () override
AlienBSRFormat * bsr (ITraceMng *trace_mng, RunQueue &queue, FemDoFsOnNodes &dofs_on_nodes)
void clearValues () override
void eliminateRow (DoFLocalId row, Real value) override
void eliminateRowColumn (DoFLocalId row, Real value) override
void endSystemAssembly ()
CSRFormatView & getCSRValues () override
bool hasSetCSRValues () const override
Int32 indexValue (DoFLocalId row_lid, DoFLocalId column_lid)
void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) override
void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) override
void setCSRValues (const CSRFormatView &csr_view) override
void setSolver (Alien::ILinearSolver *s)
void setSolverCommandLineArguments (const CommandLineArguments &args) override
void solve () override
void startSystemAssembly ()
Public Member Functions inherited from Arcane::FemUtils::DoFLinearSystemImplBase
DoFLinearSystemImplBase (IItemFamily *dof_family, const String &solver_name)
void clearValues () override
IItemFamily * dofFamily () const
VariableDoFByte & getEliminationInfo () final
VariableDoFReal & getEliminationValue () final
VariableDoFBool & getForcedInfo () final
VariableDoFReal & getForcedValue () final
bool isMatrixSparsityConstant () const final
bool isMatrixValuesConstant () const final
VariableDoFReal & rhsVariable () final
Runner runner () const override
void setConstantMatrixSparsity (const bool val) final
void setConstantMatrixValues (const bool val) final
void setRunner (const Runner &r) override
VariableDoFReal & solutionVariable () final
Public Member Functions inherited from Arcane::FemUtils::IDoFLinearSystemImpl
virtual ~IDoFLinearSystemImpl ()=default
Public Attributes
CaseOptionsAlienDoFLinearSystemFactory * options = nullptr
Private Member Functions
void _applyForcedValuesToLhsCpu ()
void _getSolutionCpu (Alien::Vector &vectorX)
void _printMatrixCpu (Alien::Matrix &matrix)
void _setVectorsCpu (Alien::Vector &vectorX, Alien::Vector &vectorB)
Private Attributes
std::unique_ptr< AlienBSRFormat > m_alien_bsr_format
ConstArrayView< Arccore::Integer > m_allUIndex
Alien::ProfiledMatrixBuilder * m_builder = nullptr
Alien::ILinearSolver * m_solver_backend = nullptr
bool m_use_accelerator = false
Additional Inherited Members
Protected Member Functions inherited from Arcane::FemUtils::DoFLinearSystemImplBase
void _applyRowColumnEliminationToRHS (bool is_verbose)
OrderedRowColumnMap & _rowColumnEliminationMap ()
Detailed Description
AI generated: Implementation of DoFLinearSystem using Alien linear algebra.
Definition at line 92 of file AlienDoFLinearSystem.h.
Constructor & Destructor Documentation
AlienDoFLinearSystemImpl()
Arcane::FemUtils::AlienDoFLinearSystemImpl::AlienDoFLinearSystemImpl (IItemFamily * dof_family, const String & solver_name)
Definition at line 77 of file AlienDoFLinearSystem.cc.
~AlienDoFLinearSystemImpl()
Arcane::FemUtils::AlienDoFLinearSystemImpl::~AlienDoFLinearSystemImpl () override
Definition at line 85 of file AlienDoFLinearSystem.cc.
Member Function Documentation
_applyForcedValuesToLhsCpu()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::_applyForcedValuesToLhsCpu () private
Definition at line 286 of file AlienDoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::DoFLinearSystemImplBase::getForcedInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getForcedValue(), m_alien_bsr_format, m_allUIndex, Arcane::FemUtils::DoFLinearSystemImplBase::rhsVariable(), and Arcane::FemUtils::DoFLinearSystemImplBase::solutionVariable().
Referenced by applyMatrixTransformation().
_getSolutionCpu()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::_getSolutionCpu (Alien::Vector & vectorX) private
Definition at line 120 of file AlienDoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), m_allUIndex, and Arcane::FemUtils::DoFLinearSystemImplBase::solutionVariable().
Referenced by solve().
_printMatrixCpu()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::_printMatrixCpu (Alien::Matrix & matrix) private
Definition at line 134 of file AlienDoFLinearSystem.cc.
Referenced by solve().
_setVectorsCpu()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::_setVectorsCpu (Alien::Vector & vectorX, Alien::Vector & vectorB) private
Definition at line 90 of file AlienDoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), m_allUIndex, Arcane::FemUtils::DoFLinearSystemImplBase::rhsVariable(), and Arcane::FemUtils::DoFLinearSystemImplBase::solutionVariable().
Referenced by solve().
applyMatrixTransformation()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::applyMatrixTransformation () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 310 of file AlienDoFLinearSystem.cc.
References _applyForcedValuesToLhsCpu(), and m_use_accelerator.
applyRHSTransformation()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::applyRHSTransformation () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 327 of file AlienDoFLinearSystem.cc.
bsr()
AlienBSRFormat* Arcane::FemUtils::AlienDoFLinearSystemImpl::bsr (ITraceMng * trace_mng, RunQueue & queue, FemDoFsOnNodes & dofs_on_nodes) inline
Definition at line 103 of file AlienDoFLinearSystem.h.
Referenced by Arcane::FemUtils::DoFLinearSystem::alienBsr().
clearValues()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::clearValues () inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 164 of file AlienDoFLinearSystem.h.
References Arcane::FemUtils::DoFLinearSystemImplBase::clearValues().
eliminateRow()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::eliminateRow (DoFLocalId row, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 151 of file AlienDoFLinearSystem.h.
eliminateRowColumn()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::eliminateRowColumn (DoFLocalId row, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 156 of file AlienDoFLinearSystem.h.
endSystemAssembly()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::endSystemAssembly () inline
Definition at line 179 of file AlienDoFLinearSystem.h.
Referenced by Arcane::FemUtils::DoFLinearSystem::endSystemAssembly().
getCSRValues()
CSRFormatView& Arcane::FemUtils::AlienDoFLinearSystemImpl::getCSRValues () inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 137 of file AlienDoFLinearSystem.h.
hasSetCSRValues()
bool Arcane::FemUtils::AlienDoFLinearSystemImpl::hasSetCSRValues () const inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 149 of file AlienDoFLinearSystem.h.
indexValue()
Int32 Arcane::FemUtils::AlienDoFLinearSystemImpl::indexValue (DoFLocalId row_lid, DoFLocalId column_lid) inline
Definition at line 110 of file AlienDoFLinearSystem.h.
matrixAddValue()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 124 of file AlienDoFLinearSystem.h.
matrixSetValue()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 130 of file AlienDoFLinearSystem.h.
setCSRValues()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::setCSRValues (const CSRFormatView & csr_view) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 143 of file AlienDoFLinearSystem.h.
setSolver()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::setSolver (Alien::ILinearSolver * s) inline
Definition at line 205 of file AlienDoFLinearSystem.h.
setSolverCommandLineArguments()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::setSolverCommandLineArguments (const CommandLineArguments & args) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 194 of file AlienDoFLinearSystem.h.
solve()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::solve () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 155 of file AlienDoFLinearSystem.cc.
References _getSolutionCpu(), _printMatrixCpu(), _setVectorsCpu(), Arcane::FemUtils::a1, Arcane::FemUtils::a2, Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), m_alien_bsr_format, m_solver_backend, m_use_accelerator, options, and Arcane::FemUtils::DoFLinearSystemImplBase::runner().
startSystemAssembly()
void Arcane::FemUtils::AlienDoFLinearSystemImpl::startSystemAssembly () inline
Definition at line 173 of file AlienDoFLinearSystem.h.
Referenced by Arcane::FemUtils::DoFLinearSystem::startSystemAssembly().
Member Data Documentation
m_alien_bsr_format
std::unique_ptr<AlienBSRFormat> Arcane::FemUtils::AlienDoFLinearSystemImpl::m_alien_bsr_format private
Definition at line 223 of file AlienDoFLinearSystem.h.
Referenced by _applyForcedValuesToLhsCpu(), and solve().
m_allUIndex
ConstArrayView<Arccore::Integer> Arcane::FemUtils::AlienDoFLinearSystemImpl::m_allUIndex private
Definition at line 224 of file AlienDoFLinearSystem.h.
Referenced by _applyForcedValuesToLhsCpu(), _getSolutionCpu(), and _setVectorsCpu().
m_builder
Alien::ProfiledMatrixBuilder* Arcane::FemUtils::AlienDoFLinearSystemImpl::m_builder = nullptr private
Definition at line 222 of file AlienDoFLinearSystem.h.
m_solver_backend
Alien::ILinearSolver* Arcane::FemUtils::AlienDoFLinearSystemImpl::m_solver_backend = nullptr private
Definition at line 221 of file AlienDoFLinearSystem.h.
Referenced by solve().
m_use_accelerator
bool Arcane::FemUtils::AlienDoFLinearSystemImpl::m_use_accelerator = false private
Definition at line 220 of file AlienDoFLinearSystem.h.
Referenced by applyMatrixTransformation(), and solve().
options
CaseOptionsAlienDoFLinearSystemFactory* Arcane::FemUtils::AlienDoFLinearSystemImpl::options = nullptr
Definition at line 207 of file AlienDoFLinearSystem.h.
Referenced by solve().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/AlienDoFLinearSystem.h
src/CAWF/FEMUtils/AlienDoFLinearSystem.cc