ShArc: Arcane::FemUtils::OrderedRowColumnMap Class Reference
Arcane::FemUtils::OrderedRowColumnMap Class Reference
Ordered map to keep a set a values indexed by (row,column).
#include <OrderedRowColumnMap.h>
Classes
struct RowColumn
Index in a RowColumnMap.
Public Types
using const_iterator = typename MapType::const_iterator
using iterator = typename MapType::iterator
Public Member Functions
void addValue (RowColumn rc, Real value)
iterator begin ()
const_iterator begin () const
void clear ()
bool contains (RowColumn rc) const
iterator end ()
const_iterator end () const
iterator find (RowColumn rc)
const_iterator find (RowColumn rc) const
Real & operator[] (RowColumn rc)
Int32 size () const
Private Types
using MapType = std::map< RowColumn, Real >
Private Attributes
MapType m_values_map
Detailed Description
Ordered map to keep a set a values indexed by (row,column).
Definition at line 34 of file OrderedRowColumnMap.h.
Member Typedef Documentation
const_iterator
using Arcane::FemUtils::OrderedRowColumnMap::const_iterator = typename MapType::const_iterator
Definition at line 64 of file OrderedRowColumnMap.h.
iterator
using Arcane::FemUtils::OrderedRowColumnMap::iterator = typename MapType::iterator
Definition at line 63 of file OrderedRowColumnMap.h.
MapType
using Arcane::FemUtils::OrderedRowColumnMap::MapType = std::map<RowColumn, Real> private
Definition at line 59 of file OrderedRowColumnMap.h.
Member Function Documentation
addValue()
void Arcane::FemUtils::OrderedRowColumnMap::addValue (RowColumn rc, Real value) inline
Definition at line 68 of file OrderedRowColumnMap.h.
References m_values_map.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::matrixAddValue().
begin() [1/2]
iterator Arcane::FemUtils::OrderedRowColumnMap::begin () inline
Definition at line 83 of file OrderedRowColumnMap.h.
References m_values_map.
begin() [2/2]
const_iterator Arcane::FemUtils::OrderedRowColumnMap::begin () const inline
Definition at line 85 of file OrderedRowColumnMap.h.
References m_values_map.
clear()
void Arcane::FemUtils::OrderedRowColumnMap::clear () inline
Definition at line 82 of file OrderedRowColumnMap.h.
References m_values_map.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), and Arcane::FemUtils::AlephDoFLinearSystemImpl::clearValues().
contains()
bool Arcane::FemUtils::OrderedRowColumnMap::contains (RowColumn rc) const inline
Definition at line 89 of file OrderedRowColumnMap.h.
References end(), and find().
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix().
end() [1/2]
iterator Arcane::FemUtils::OrderedRowColumnMap::end () inline
Definition at line 84 of file OrderedRowColumnMap.h.
References m_values_map.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix(), and contains().
end() [2/2]
const_iterator Arcane::FemUtils::OrderedRowColumnMap::end () const inline
Definition at line 86 of file OrderedRowColumnMap.h.
References m_values_map.
find() [1/2]
iterator Arcane::FemUtils::OrderedRowColumnMap::find (RowColumn rc) inline
Definition at line 87 of file OrderedRowColumnMap.h.
References m_values_map.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix(), and contains().
find() [2/2]
const_iterator Arcane::FemUtils::OrderedRowColumnMap::find (RowColumn rc) const inline
Definition at line 88 of file OrderedRowColumnMap.h.
References m_values_map.
operator[]()
Real& Arcane::FemUtils::OrderedRowColumnMap::operator[] (RowColumn rc) inline
Definition at line 77 of file OrderedRowColumnMap.h.
References m_values_map.
size()
Int32 Arcane::FemUtils::OrderedRowColumnMap::size () const inline
Definition at line 90 of file OrderedRowColumnMap.h.
References m_values_map.
Member Data Documentation
m_values_map
MapType Arcane::FemUtils::OrderedRowColumnMap::m_values_map private
Definition at line 94 of file OrderedRowColumnMap.h.
Referenced by addValue(), begin(), clear(), end(), find(), operator[](), and size().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/internal/OrderedRowColumnMap.h