ShArc: DirichletManagerService Class Reference
DirichletManagerService Class Reference
Public Member Functions
DirichletManagerService (const Arcane::ServiceBuildInfo &sbi)
~DirichletManagerService ()
IBoundaryManager::BoundaryEnumerator boundaryEnumerator () const
bool exists () const
void init (ArcRes::System &system)
AI comment: Initializes boundary folders, adds variables for all condition types.
void update (ArcRes::System &system)
AI comment: Re-evaluates all boundary conditions (e.g.
Private Member Functions
void _checkSizeMulti ()
AI comment: Validates that property/value count matches for each multi-limit condition.
void _compute (ArcRes::System &system)
AI comment: Evaluates boundary conditions: space-time, single, and multi-limit conditions.
void _fatalIfNotInitialized () const
AI comment: Asserts that the service has been initialized.
Private Attributes
Arcane::UniqueArray< Law::PartialVariableFaceFolder * > m_boundaries
Arcane::UniqueArray< Arcane::String > m_boundary_names
bool m_initialized
Detailed Description
Definition at line 41 of file DirichletManagerService.cc.
Constructor & Destructor Documentation
DirichletManagerService()
DirichletManagerService::DirichletManagerService (const Arcane::ServiceBuildInfo & sbi) inline
Definition at line 46 of file DirichletManagerService.cc.
~DirichletManagerService()
DirichletManagerService::~DirichletManagerService () inline
Definition at line 50 of file DirichletManagerService.cc.
References m_boundaries.
Member Function Documentation
_checkSizeMulti()
void DirichletManagerService::_checkSizeMulti () private
AI comment: Validates that property/value count matches for each multi-limit condition.
Definition at line 90 of file DirichletManagerService.cc.
Referenced by init().
_compute()
void DirichletManagerService::_compute (ArcRes::System & system) private
AI comment: Evaluates boundary conditions: space-time, single, and multi-limit conditions.
Definition at line 211 of file DirichletManagerService.cc.
References m_boundaries.
Referenced by init(), and update().
_fatalIfNotInitialized()
void DirichletManagerService::_fatalIfNotInitialized () const private
AI comment: Asserts that the service has been initialized.
Definition at line 120 of file DirichletManagerService.cc.
References m_initialized.
Referenced by update().
boundaryEnumerator()
IBoundaryManager::BoundaryEnumerator DirichletManagerService::boundaryEnumerator () const inline
Definition at line 64 of file DirichletManagerService.cc.
References m_boundaries, and m_boundary_names.
exists()
bool DirichletManagerService::exists () const inline
Definition at line 62 of file DirichletManagerService.cc.
init()
void DirichletManagerService::init (ArcRes::System & system)
AI comment: Initializes boundary folders, adds variables for all condition types.
Definition at line 131 of file DirichletManagerService.cc.
References _checkSizeMulti(), _compute(), m_boundaries, m_boundary_names, and m_initialized.
update()
void DirichletManagerService::update (ArcRes::System & system)
AI comment: Re-evaluates all boundary conditions (e.g.
after mesh change or time step)
Definition at line 297 of file DirichletManagerService.cc.
References _compute(), and _fatalIfNotInitialized().
Member Data Documentation
m_boundaries
Arcane::UniqueArray<Law::PartialVariableFaceFolder*> DirichletManagerService::m_boundaries private
Definition at line 81 of file DirichletManagerService.cc.
Referenced by ~DirichletManagerService(), _compute(), boundaryEnumerator(), and init().
m_boundary_names
Arcane::UniqueArray<Arcane::String> DirichletManagerService::m_boundary_names private
Definition at line 82 of file DirichletManagerService.cc.
Referenced by boundaryEnumerator(), and init().
m_initialized
bool DirichletManagerService::m_initialized private
Definition at line 79 of file DirichletManagerService.cc.
Referenced by _fatalIfNotInitialized(), and init().
The documentation for this class was generated from the following file:
src/TwoPhaseFlowSimulation/BoundaryCondition/Dirichlet/DirichletManagerService.cc