ShArc: Arcane::FemUtils::Gpu::BoundaryConditions Class Reference
Arcane::FemUtils::Gpu::BoundaryConditions Class Reference
AI generated: Applies FEM boundary conditions (Dirichlet, point Dirichlet) on LHS and RHS.
#include <ArcaneFemFunctionsGpu.h>
Static Public Member Functions
static void applyDirichletToLhsAndRhs (BC::IDirichletBoundaryCondition *bs, const FemDoFsOnNodes &dofs_on_nodes, DoFLinearSystem &linear_system, IMesh *mesh, Accelerator::RunQueue *queue)
AI generated: Applies Dirichlet boundary conditions to both RHS and LHS.
static void applyDirichletToRhs (BC::IDirichletBoundaryCondition *bs, const FemDoFsOnNodes &dofs_on_nodes, DoFLinearSystem &linear_system, IMesh *mesh, Accelerator::RunQueue *queue)
Applies Dirichlet boundary conditions to RHS.
static void applyPointDirichletToLhsAndRhs (BC::IDirichletPointCondition *bs, const FemDoFsOnNodes &dofs_on_nodes, DoFLinearSystem &linear_system, IMesh *mesh, RunQueue *queue)
Applies Point Dirichlet boundary conditions to RHS and LHS.
static void applyPointDirichletToRhs (BC::IDirichletPointCondition *bs, const FemDoFsOnNodes &dofs_on_nodes, DoFLinearSystem &linear_system, IMesh *mesh, Accelerator::RunQueue *queue)
Applies Point Dirichlet boundary conditions to RHS.
Detailed Description
AI generated: Applies FEM boundary conditions (Dirichlet, point Dirichlet) on LHS and RHS.
Definition at line 714 of file ArcaneFemFunctionsGpu.h.
Member Function Documentation
applyDirichletToLhsAndRhs()
static void Arcane::FemUtils::Gpu::BoundaryConditions::applyDirichletToLhsAndRhs (BC::IDirichletBoundaryCondition * bs, const FemDoFsOnNodes & dofs_on_nodes, DoFLinearSystem & linear_system, IMesh * mesh, Accelerator::RunQueue * queue) static
AI generated: Applies Dirichlet boundary conditions to both RHS and LHS.
applyDirichletToRhs()
static void Arcane::FemUtils::Gpu::BoundaryConditions::applyDirichletToRhs (BC::IDirichletBoundaryCondition * bs, const FemDoFsOnNodes & dofs_on_nodes, DoFLinearSystem & linear_system, IMesh * mesh, Accelerator::RunQueue * queue) static
Applies Dirichlet boundary conditions to RHS.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
applyPointDirichletToLhsAndRhs()
void Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs (BC::IDirichletPointCondition * bs, const FemDoFsOnNodes & dofs_on_nodes, DoFLinearSystem & linear_system, IMesh * mesh, RunQueue * queue) static
Applies Point Dirichlet boundary conditions to RHS and LHS.
For LHS matrix 𝐀, the diagonal term for the Dirichlet DOF is set to 𝑃.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
Definition at line 157 of file ArcaneFemFunctionsGpu.cc.
References Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty(), Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowOrRowColumnElimination(), Arcane::FemUtils::ELIMINATE_ROW, Arcane::FemUtils::ELIMINATE_ROW_COLUMN, BC::IDirichletPointCondition::getEnforceDirichletMethod(), BC::IDirichletPointCondition::getNode(), BC::IDirichletPointCondition::getPenalty(), and BC::IDirichletPointCondition::getValue().
applyPointDirichletToRhs()
static void Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToRhs (BC::IDirichletPointCondition * bs, const FemDoFsOnNodes & dofs_on_nodes, DoFLinearSystem & linear_system, IMesh * mesh, Accelerator::RunQueue * queue) static
Applies Point Dirichlet boundary conditions to RHS.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/ArcaneFemFunctionsGpu.h
src/CAWF/FEMUtils/ArcaneFemFunctionsGpu.cc