ShArc: Arcane::FemUtils::DoFLinearSystemImplBase Class Reference
Arcane::FemUtils::DoFLinearSystemImplBase Class Reference
#include <DoFLinearSystemImplBase.h>
Public Member Functions
DoFLinearSystemImplBase (IItemFamily *dof_family, const String &solver_name)
void clearValues () override
IItemFamily * dofFamily () const
VariableDoFByte & getEliminationInfo () final
VariableDoFReal & getEliminationValue () final
VariableDoFBool & getForcedInfo () final
VariableDoFReal & getForcedValue () final
bool isMatrixSparsityConstant () const final
bool isMatrixValuesConstant () const final
VariableDoFReal & rhsVariable () final
Runner runner () const override
void setConstantMatrixSparsity (const bool val) final
void setConstantMatrixValues (const bool val) final
void setRunner (const Runner &r) override
VariableDoFReal & solutionVariable () final
Public Member Functions inherited from Arcane::FemUtils::IDoFLinearSystemImpl
virtual ~IDoFLinearSystemImpl ()=default
virtual void applyMatrixTransformation ()=0
virtual void applyRHSTransformation ()=0
virtual void eliminateRow (DoFLocalId row, Real value)=0
virtual void eliminateRowColumn (DoFLocalId row, Real value)=0
virtual CSRFormatView & getCSRValues ()=0
virtual bool hasSetCSRValues () const =0
virtual void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value)=0
virtual void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value)=0
virtual void setCSRValues (const CSRFormatView &csr_view)=0
virtual void setSolverCommandLineArguments (const CommandLineArguments &args)=0
virtual void solve ()=0
Protected Member Functions
void _applyRowColumnEliminationToRHS (bool is_verbose)
OrderedRowColumnMap & _rowColumnEliminationMap ()
Private Attributes
bool m_constant_matrix_sparsity = false
Indicates if the matrix changes sparsity between solve() calls.
bool m_constant_matrix_values = false
Indicates if the matrix changes values between solve() calls.
VariableDoFByte m_dof_elimination_info
VariableDoFReal m_dof_elimination_value
IItemFamily * m_dof_family = nullptr
VariableDoFBool m_dof_forced_info
VariableDoFReal m_dof_forced_value
VariableDoFReal m_rhs_variable
OrderedRowColumnMap m_row_column_elimination_map
List of (row,column) which contribute to RowColumn elimination.
Runner m_runner
VariableDoFReal m_solution_variable
Detailed Description
Definition at line 38 of file DoFLinearSystemImplBase.h.
Constructor & Destructor Documentation
DoFLinearSystemImplBase()
Arcane::FemUtils::DoFLinearSystemImplBase::DoFLinearSystemImplBase (IItemFamily * dof_family, const String & solver_name)
Definition at line 26 of file DoFLinearSystemImplBase.cc.
Member Function Documentation
_applyRowColumnEliminationToRHS()
void Arcane::FemUtils::DoFLinearSystemImplBase::_applyRowColumnEliminationToRHS (bool is_verbose) protected
Definition at line 55 of file DoFLinearSystemImplBase.cc.
References Arcane::FemUtils::ELIMINATE_ROW_COLUMN, getEliminationInfo(), getEliminationValue(), m_dof_family, m_row_column_elimination_map, and rhsVariable().
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyRHSTransformation(), and Arcane::FemUtils::CsrDoFLinearSystemImpl::applyRHSTransformation().
_rowColumnEliminationMap()
OrderedRowColumnMap& Arcane::FemUtils::DoFLinearSystemImplBase::_rowColumnEliminationMap () inline protected
Definition at line 71 of file DoFLinearSystemImplBase.h.
References m_row_column_elimination_map.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), and Arcane::FemUtils::CsrDoFLinearSystemImpl::_fillRowColumnEliminationInfos().
clearValues()
void Arcane::FemUtils::DoFLinearSystemImplBase::clearValues () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 44 of file DoFLinearSystemImplBase.cc.
References Arcane::FemUtils::ELIMINATE_NONE, m_dof_elimination_info, m_dof_elimination_value, and m_dof_forced_info.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::build(), Arcane::FemUtils::AlephDoFLinearSystemImpl::clearValues(), Arcane::FemUtils::AlienDoFLinearSystemImpl::clearValues(), and Arcane::FemUtils::CsrDoFLinearSystemImpl::clearValues().
dofFamily()
IItemFamily* Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily () const inline
Definition at line 62 of file DoFLinearSystemImplBase.h.
References m_dof_family.
Referenced by Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyForcedValuesToLhs(), Arcane::FemUtils::AlienDoFLinearSystemImpl::_applyForcedValuesToLhsCpu(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyRHSTransformation(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowColumnEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnRHS(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_computeMatrixInfo(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRHSVector(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::AlienDoFLinearSystemImpl::_getSolutionCpu(), Arcane::FemUtils::AlienDoFLinearSystemImpl::_setVectorsCpu(), Arcane::FemUtils::AlephDoFLinearSystemImpl::solve(), and Arcane::FemUtils::AlienDoFLinearSystemImpl::solve().
getEliminationInfo()
VariableDoFByte& Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo () inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 56 of file DoFLinearSystemImplBase.h.
References m_dof_elimination_info.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyRHSTransformation(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowColumnEliminationOnMatrix(), _applyRowColumnEliminationToRHS(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnRHS(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::AlephDoFLinearSystemImpl::eliminateRow(), and Arcane::FemUtils::AlephDoFLinearSystemImpl::eliminateRowColumn().
getEliminationValue()
VariableDoFReal& Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue () inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 57 of file DoFLinearSystemImplBase.h.
References m_dof_elimination_value.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyRHSTransformation(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowColumnEliminationOnMatrix(), _applyRowColumnEliminationToRHS(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnRHS(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::AlephDoFLinearSystemImpl::eliminateRow(), and Arcane::FemUtils::AlephDoFLinearSystemImpl::eliminateRowColumn().
getForcedInfo()
VariableDoFBool& Arcane::FemUtils::DoFLinearSystemImplBase::getForcedInfo () inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 54 of file DoFLinearSystemImplBase.h.
References m_dof_forced_info.
Referenced by Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyForcedValuesToLhs(), and Arcane::FemUtils::AlienDoFLinearSystemImpl::_applyForcedValuesToLhsCpu().
getForcedValue()
VariableDoFReal& Arcane::FemUtils::DoFLinearSystemImplBase::getForcedValue () inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 55 of file DoFLinearSystemImplBase.h.
References m_dof_forced_value.
Referenced by Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyForcedValuesToLhs(), and Arcane::FemUtils::AlienDoFLinearSystemImpl::_applyForcedValuesToLhsCpu().
isMatrixSparsityConstant()
bool Arcane::FemUtils::DoFLinearSystemImplBase::isMatrixSparsityConstant () const inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 66 of file DoFLinearSystemImplBase.h.
References m_constant_matrix_sparsity.
isMatrixValuesConstant()
bool Arcane::FemUtils::DoFLinearSystemImplBase::isMatrixValuesConstant () const inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 67 of file DoFLinearSystemImplBase.h.
References m_constant_matrix_values.
rhsVariable()
VariableDoFReal& Arcane::FemUtils::DoFLinearSystemImplBase::rhsVariable () inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 52 of file DoFLinearSystemImplBase.h.
References m_rhs_variable.
Referenced by Arcane::FemUtils::AlienDoFLinearSystemImpl::_applyForcedValuesToLhsCpu(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyRHSTransformation(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowColumnEliminationOnMatrix(), _applyRowColumnEliminationToRHS(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnRHS(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRHSVector(), and Arcane::FemUtils::AlienDoFLinearSystemImpl::_setVectorsCpu().
runner()
Runner Arcane::FemUtils::DoFLinearSystemImplBase::runner () const inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 60 of file DoFLinearSystemImplBase.h.
References m_runner.
Referenced by Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyForcedValuesToLhs(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowColumnEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnRHS(), and Arcane::FemUtils::AlienDoFLinearSystemImpl::solve().
setConstantMatrixSparsity()
void Arcane::FemUtils::DoFLinearSystemImplBase::setConstantMatrixSparsity (const bool val) inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 64 of file DoFLinearSystemImplBase.h.
References m_constant_matrix_sparsity.
setConstantMatrixValues()
void Arcane::FemUtils::DoFLinearSystemImplBase::setConstantMatrixValues (const bool val) inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 65 of file DoFLinearSystemImplBase.h.
References m_constant_matrix_values.
setRunner()
void Arcane::FemUtils::DoFLinearSystemImplBase::setRunner (const Runner & r) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 59 of file DoFLinearSystemImplBase.h.
References m_runner.
solutionVariable()
VariableDoFReal& Arcane::FemUtils::DoFLinearSystemImplBase::solutionVariable () inline final virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 50 of file DoFLinearSystemImplBase.h.
References m_solution_variable.
Referenced by Arcane::FemUtils::AlienDoFLinearSystemImpl::_applyForcedValuesToLhsCpu(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_computeMatrixInfo(), Arcane::FemUtils::AlienDoFLinearSystemImpl::_getSolutionCpu(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_setMatrixValue(), Arcane::FemUtils::AlienDoFLinearSystemImpl::_setVectorsCpu(), and Arcane::FemUtils::AlephDoFLinearSystemImpl::solve().
Member Data Documentation
m_constant_matrix_sparsity
bool Arcane::FemUtils::DoFLinearSystemImplBase::m_constant_matrix_sparsity = false private
Indicates if the matrix changes sparsity between solve() calls.
Definition at line 87 of file DoFLinearSystemImplBase.h.
Referenced by isMatrixSparsityConstant(), and setConstantMatrixSparsity().
m_constant_matrix_values
bool Arcane::FemUtils::DoFLinearSystemImplBase::m_constant_matrix_values = false private
Indicates if the matrix changes values between solve() calls.
Definition at line 90 of file DoFLinearSystemImplBase.h.
Referenced by isMatrixValuesConstant(), and setConstantMatrixValues().
m_dof_elimination_info
VariableDoFByte Arcane::FemUtils::DoFLinearSystemImplBase::m_dof_elimination_info private
Definition at line 83 of file DoFLinearSystemImplBase.h.
Referenced by clearValues(), and getEliminationInfo().
m_dof_elimination_value
VariableDoFReal Arcane::FemUtils::DoFLinearSystemImplBase::m_dof_elimination_value private
Definition at line 84 of file DoFLinearSystemImplBase.h.
Referenced by clearValues(), and getEliminationValue().
m_dof_family
IItemFamily* Arcane::FemUtils::DoFLinearSystemImplBase::m_dof_family = nullptr private
Definition at line 76 of file DoFLinearSystemImplBase.h.
Referenced by _applyRowColumnEliminationToRHS(), and dofFamily().
m_dof_forced_info
VariableDoFBool Arcane::FemUtils::DoFLinearSystemImplBase::m_dof_forced_info private
Definition at line 81 of file DoFLinearSystemImplBase.h.
Referenced by clearValues(), and getForcedInfo().
m_dof_forced_value
VariableDoFReal Arcane::FemUtils::DoFLinearSystemImplBase::m_dof_forced_value private
Definition at line 82 of file DoFLinearSystemImplBase.h.
Referenced by getForcedValue().
m_rhs_variable
VariableDoFReal Arcane::FemUtils::DoFLinearSystemImplBase::m_rhs_variable private
Definition at line 79 of file DoFLinearSystemImplBase.h.
Referenced by rhsVariable().
m_row_column_elimination_map
OrderedRowColumnMap Arcane::FemUtils::DoFLinearSystemImplBase::m_row_column_elimination_map private
List of (row,column) which contribute to RowColumn elimination.
Definition at line 93 of file DoFLinearSystemImplBase.h.
Referenced by _applyRowColumnEliminationToRHS(), and _rowColumnEliminationMap().
m_runner
Runner Arcane::FemUtils::DoFLinearSystemImplBase::m_runner private
Definition at line 77 of file DoFLinearSystemImplBase.h.
Referenced by runner(), and setRunner().
m_solution_variable
VariableDoFReal Arcane::FemUtils::DoFLinearSystemImplBase::m_solution_variable private
Definition at line 80 of file DoFLinearSystemImplBase.h.
Referenced by solutionVariable().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/internal/DoFLinearSystemImplBase.h
src/CAWF/FEMUtils/DoFLinearSystemImplBase.cc