ShArc: ThermoChemicalConvectionModule Class Reference
ThermoChemicalConvectionModule Class Reference
Two-Phase Flow
Public Member Functions
ThermoChemicalConvectionModule (const Arcane::ModuleBuildInfo &sbi)
~ThermoChemicalConvectionModule ()
void build (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds residual and Jacobian for pressure, concentration, and temperature equations.
void compute ()
AI comment: Solves the non-linear thermo-chemical convection system via Newton.
const Law::PropertyVector & equationSystem () const
const Law::VariableCellFolder & folder () const
void init ()
AI comment: Full initialization: system, geometry, groups, variables, laws, Newton.
void initLinearSystemProfile (Arcane::CellGroup cells, Alien::MatrixProfiler &blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size)
AI comment: Initializes matrix profile using two-point or multi-point stencil.
Integer nbEquations () const
void setSolutionVariables (Arcane::SharedArray< Arcane::VariableCellReal * > &solutions)
AI comment: Sets pointers to solution variables for the Newton solver.
Domain const & systemDomain () const
Private Member Functions
void _addTimeVariable (const Gump::ScalarRealProperty &property)
AI comment: Registers a scalar property for time-varying snapshot management.
void _buildAccumulation (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds accumulation terms for mass, concentration, and energy equations.
void _buildFluxBoundary (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds boundary flux terms for all three equations using Dirichlet BC values.
void _buildFluxInternal (ArcNum::Vector &residual, ArcNum::Matrix &jacobian)
AI comment: Builds internal flux terms for pressure, concentration, and temperature (advection + diffusion)
template<typename Folder >
void _evaluateLaws (Folder &folder, Law::EvaluationMode derivability)
AI comment: Evaluates all registered physical laws on the given folder.
void _initBoundaryVariableMng ()
AI comment: Initializes boundary condition variables for fluid and solid properties.
void _initDomainVariableMng ()
AI comment: Registers domain variables for fluid and solid properties, applies IC.
void _initEquationSystem ()
AI comment: Sets up three equations: pressure, concentration, and temperature.
void _initGeometry ()
AI comment: Registers and computes geometric properties (volume, center, face normal)
void _initGroup ()
AI comment: Creates mesh groups via the group creator service.
void _initLaws ()
AI comment: Configures physical laws and evaluates them on domain and boundaries.
void _initNewton ()
AI comment: Initializes the Newton solver with this module as the non-linear system.
void _initPhysicalSystem ()
AI comment: Loads the Gump physical system from the service manager.
void _initRestore ()
AI comment: Initializes Tn containers by copying initial law evaluation results.
void _initTimeVariableMng ()
AI comment: Registers time-varying variables (P, C, T, density) for Newton rollback.
void _initTransmissivity ()
AI comment: Computes transmissivity operator using permeability tensor.
void _multiPointsProfiler (Arcane::CellGroup cells, Alien::MatrixProfiler &blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size) const
void _twoPointsProfiler (Arcane::CellGroup cells, Alien::MatrixProfiler &blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size) const
Law::VariableCellFolder & domain ()
Law::VariableCellFolder & domainT0 ()
Law::VariableCellFolder & domainTn ()
Law::FunctionManager & functionMng ()
ArcRes::System & system ()
const Law::PropertyVector & unknownsManager () const
Private Attributes
ArcNum::INonLinearSystem::Domain m_domain
ArcGeoSim::AppService< IVariableManager > m_folder
Law::FunctionManager m_funcs
Arcane::SharedArray< Gump::ScalarRealProperty > m_properties_to_evaluate
std::shared_ptr< ArcNum::MultiPointsStencil > m_schemeStencil
ArcGeoSim::AppService< ArcGeoSim::ITimeLoopSnapshotManager > m_snapshots
ArcRes::System m_system
ArcNum::TwoPointsTransmissivity m_transmissivities
Law::PropertyVector m_unknown_manager
Detailed Description
AI-Generated Documentation:
Thermo-chemical convection simulation module.
ThermoChemicalConvectionModule solves coupled heat and mass transfer with chemical convection in porous media. It handles the non-linear system of equations for pressure, concentration, and temperature, including accumulation, internal flux, and boundary flux terms.
Definition at line 65 of file ThermoChemicalConvectionModule.cc.
Constructor & Destructor Documentation
ThermoChemicalConvectionModule()
ThermoChemicalConvectionModule::ThermoChemicalConvectionModule (const Arcane::ModuleBuildInfo & sbi) inline
AI-Generated Documentation: Constructs the module
Definition at line 72 of file ThermoChemicalConvectionModule.cc.
~ThermoChemicalConvectionModule()
ThermoChemicalConvectionModule::~ThermoChemicalConvectionModule () inline
AI-Generated Documentation: Destructor
Definition at line 77 of file ThermoChemicalConvectionModule.cc.
Member Function Documentation
_addTimeVariable()
void ThermoChemicalConvectionModule::_addTimeVariable (const Gump::ScalarRealProperty & property) private
AI comment: Registers a scalar property for time-varying snapshot management.
AI-Generated Documentation: Adds a time-varying variable for snapshot management
Definition at line 310 of file ThermoChemicalConvectionModule.cc.
References domain(), domainTn(), and m_snapshots.
Referenced by _initTimeVariableMng().
_buildAccumulation()
void ThermoChemicalConvectionModule::_buildAccumulation (ArcNum::Vector & residual, ArcNum::Matrix & jacobian) private
AI comment: Builds accumulation terms for mass, concentration, and energy equations.
AI-Generated Documentation: Builds the accumulation term
Definition at line 711 of file ThermoChemicalConvectionModule.cc.
References domain(), domainTn(), functionMng(), system(), and unknownsManager().
Referenced by build().
_buildFluxBoundary()
void ThermoChemicalConvectionModule::_buildFluxBoundary (ArcNum::Vector & residual, ArcNum::Matrix & jacobian) private
AI comment: Builds boundary flux terms for all three equations using Dirichlet BC values.
AI-Generated Documentation: Builds the boundary flux term
Definition at line 899 of file ThermoChemicalConvectionModule.cc.
References domain(), ENUMERATE_BOUNDARY, functionMng(), m_transmissivities, system(), and unknownsManager().
Referenced by build().
_buildFluxInternal()
void ThermoChemicalConvectionModule::_buildFluxInternal (ArcNum::Vector & residual, ArcNum::Matrix & jacobian) private
AI comment: Builds internal flux terms for pressure, concentration, and temperature (advection + diffusion)
AI-Generated Documentation: Builds the internal flux term
Definition at line 786 of file ThermoChemicalConvectionModule.cc.
References domain(), functionMng(), m_transmissivities, system(), and unknownsManager().
Referenced by build().
_evaluateLaws()
template<typename Folder > void ThermoChemicalConvectionModule::_evaluateLaws (Folder & folder, Law::EvaluationMode derivability) private
AI comment: Evaluates all registered physical laws on the given folder.
AI-Generated Documentation: Evaluates physical laws on a given folder
Definition at line 697 of file ThermoChemicalConvectionModule.cc.
References folder(), m_funcs, and m_properties_to_evaluate.
Referenced by _initLaws(), and build().
_initBoundaryVariableMng()
void ThermoChemicalConvectionModule::_initBoundaryVariableMng () private
AI comment: Initializes boundary condition variables for fluid and solid properties.
AI-Generated Documentation: Initializes boundary variable manager
Definition at line 525 of file ThermoChemicalConvectionModule.cc.
References ENUMERATE_BOUNDARY, and system().
Referenced by init().
_initDomainVariableMng()
void ThermoChemicalConvectionModule::_initDomainVariableMng () private
AI comment: Registers domain variables for fluid and solid properties, applies IC.
AI-Generated Documentation: Initializes domain variable manager
Definition at line 478 of file ThermoChemicalConvectionModule.cc.
References domain(), m_domain, and system().
Referenced by init().
_initEquationSystem()
void ThermoChemicalConvectionModule::_initEquationSystem () private
AI comment: Sets up three equations: pressure, concentration, and temperature.
AI-Generated Documentation: Initializes the equation system (unknowns)
Definition at line 669 of file ThermoChemicalConvectionModule.cc.
References m_unknown_manager, and system().
Referenced by init().
_initGeometry()
void ThermoChemicalConvectionModule::_initGeometry () private
AI comment: Registers and computes geometric properties (volume, center, face normal)
AI-Generated Documentation: Initializes mesh geometry
Definition at line 426 of file ThermoChemicalConvectionModule.cc.
Referenced by init().
_initGroup()
void ThermoChemicalConvectionModule::_initGroup () private
AI comment: Creates mesh groups via the group creator service.
AI-Generated Documentation: Initializes mesh groups
Definition at line 466 of file ThermoChemicalConvectionModule.cc.
References init().
Referenced by init().
_initLaws()
void ThermoChemicalConvectionModule::_initLaws () private
AI comment: Configures physical laws and evaluates them on domain and boundaries.
AI-Generated Documentation: Configures and initializes physical laws
Definition at line 581 of file ThermoChemicalConvectionModule.cc.
References _evaluateLaws(), domain(), ENUMERATE_BOUNDARY, m_funcs, m_properties_to_evaluate, and system().
Referenced by init().
_initNewton()
void ThermoChemicalConvectionModule::_initNewton () private
AI comment: Initializes the Newton solver with this module as the non-linear system.
AI-Generated Documentation: Initializes the Newton solver
Definition at line 684 of file ThermoChemicalConvectionModule.cc.
Referenced by init().
_initPhysicalSystem()
void ThermoChemicalConvectionModule::_initPhysicalSystem () private
AI comment: Loads the Gump physical system from the service manager.
AI-Generated Documentation: Initializes the physical system
Definition at line 321 of file ThermoChemicalConvectionModule.cc.
References m_system.
Referenced by init().
_initRestore()
void ThermoChemicalConvectionModule::_initRestore () private
AI comment: Initializes Tn containers by copying initial law evaluation results.
AI-Generated Documentation: Initializes the restore/snapshot system
Definition at line 624 of file ThermoChemicalConvectionModule.cc.
References domain(), domainTn(), and system().
Referenced by init().
_initTimeVariableMng()
void ThermoChemicalConvectionModule::_initTimeVariableMng () private
AI comment: Registers time-varying variables (P, C, T, density) for Newton rollback.
AI-Generated Documentation: Initializes time variable manager (restart snapshots)
Definition at line 560 of file ThermoChemicalConvectionModule.cc.
References _addTimeVariable(), and system().
Referenced by init().
_initTransmissivity()
void ThermoChemicalConvectionModule::_initTransmissivity () private
AI comment: Computes transmissivity operator using permeability tensor.
AI-Generated Documentation: Initializes transmissivity operators
Definition at line 651 of file ThermoChemicalConvectionModule.cc.
References domain(), m_transmissivities, and system().
Referenced by init().
_multiPointsProfiler()
void ThermoChemicalConvectionModule::_multiPointsProfiler (Arcane::CellGroup cells, Alien::MatrixProfiler & blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size) const inline private
Definition at line 207 of file ThermoChemicalConvectionModule.cc.
References init(), and m_schemeStencil.
Referenced by initLinearSystemProfile().
_twoPointsProfiler()
void ThermoChemicalConvectionModule::_twoPointsProfiler (Arcane::CellGroup cells, Alien::MatrixProfiler & blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size) const inline private
Definition at line 180 of file ThermoChemicalConvectionModule.cc.
Referenced by initLinearSystemProfile().
build()
void ThermoChemicalConvectionModule::build (ArcNum::Vector & residual, ArcNum::Matrix & jacobian)
AI comment: Builds residual and Jacobian for pressure, concentration, and temperature equations.
AI-Generated Documentation: Builds the residual and Jacobian matrix
Definition at line 410 of file ThermoChemicalConvectionModule.cc.
References _buildAccumulation(), _buildFluxBoundary(), _buildFluxInternal(), _evaluateLaws(), and domain().
compute()
void ThermoChemicalConvectionModule::compute ()
AI comment: Solves the non-linear thermo-chemical convection system via Newton.
AI-Generated Documentation: Executes one computation step
Definition at line 395 of file ThermoChemicalConvectionModule.cc.
domain()
Law::VariableCellFolder& ThermoChemicalConvectionModule::domain () inline private
AI-Generated Documentation: Returns the domain for contributions
Definition at line 123 of file ThermoChemicalConvectionModule.cc.
References m_folder.
Referenced by _addTimeVariable(), _buildAccumulation(), _buildFluxBoundary(), _buildFluxInternal(), _initDomainVariableMng(), _initLaws(), _initRestore(), _initTransmissivity(), and build().
domainT0()
Law::VariableCellFolder& ThermoChemicalConvectionModule::domainT0 () inline private
AI-Generated Documentation: Returns the domain at time T0
Definition at line 126 of file ThermoChemicalConvectionModule.cc.
References m_folder.
domainTn()
Law::VariableCellFolder& ThermoChemicalConvectionModule::domainTn () inline private
AI-Generated Documentation: Returns the domain at time Tn
Definition at line 129 of file ThermoChemicalConvectionModule.cc.
References m_folder.
Referenced by _addTimeVariable(), _buildAccumulation(), and _initRestore().
equationSystem()
const Law::PropertyVector& ThermoChemicalConvectionModule::equationSystem () const inline
AI-Generated Documentation: Returns the equation system (unknowns manager)
Definition at line 103 of file ThermoChemicalConvectionModule.cc.
References m_unknown_manager.
folder()
const Law::VariableCellFolder& ThermoChemicalConvectionModule::folder () const inline
AI-Generated Documentation: Returns the variable cell folder
Definition at line 109 of file ThermoChemicalConvectionModule.cc.
References m_folder.
Referenced by _evaluateLaws(), and setSolutionVariables().
functionMng()
Law::FunctionManager& ThermoChemicalConvectionModule::functionMng () inline private
AI-Generated Documentation: Returns the law function manager
Definition at line 120 of file ThermoChemicalConvectionModule.cc.
References m_funcs.
Referenced by _buildAccumulation(), _buildFluxBoundary(), and _buildFluxInternal().
init()
void ThermoChemicalConvectionModule::init ()
AI comment: Full initialization: system, geometry, groups, variables, laws, Newton.
AI-Generated Documentation: Initializes the simulation
Definition at line 335 of file ThermoChemicalConvectionModule.cc.
References _initBoundaryVariableMng(), _initDomainVariableMng(), _initEquationSystem(), _initGeometry(), _initGroup(), _initLaws(), _initNewton(), _initPhysicalSystem(), _initRestore(), _initTimeVariableMng(), _initTransmissivity(), and system().
Referenced by _initGroup(), and _multiPointsProfiler().
initLinearSystemProfile()
void ThermoChemicalConvectionModule::initLinearSystemProfile (Arcane::CellGroup cells, Alien::MatrixProfiler & blockProfiler, Arcane::ConstArray2View< Arcane::Integer > indexes, Arcane::Integer block_size)
AI comment: Initializes matrix profile using two-point or multi-point stencil.
AI-Generated Documentation: Initializes the linear system profile
Definition at line 366 of file ThermoChemicalConvectionModule.cc.
References _multiPointsProfiler(), _twoPointsProfiler(), and m_schemeStencil.
nbEquations()
Integer ThermoChemicalConvectionModule::nbEquations () const inline
AI-Generated Documentation: Returns the number of equations in the system
Definition at line 88 of file ThermoChemicalConvectionModule.cc.
References m_unknown_manager.
setSolutionVariables()
void ThermoChemicalConvectionModule::setSolutionVariables (Arcane::SharedArray< Arcane::VariableCellReal * > & solutions)
AI comment: Sets pointers to solution variables for the Newton solver.
AI-Generated Documentation: Sets the solution variable pointers
Definition at line 381 of file ThermoChemicalConvectionModule.cc.
References folder(), and m_unknown_manager.
system()
ArcRes::System& ThermoChemicalConvectionModule::system () inline private
AI-Generated Documentation: Returns the Gump system
Definition at line 114 of file ThermoChemicalConvectionModule.cc.
References m_system.
Referenced by _buildAccumulation(), _buildFluxBoundary(), _buildFluxInternal(), _initBoundaryVariableMng(), _initDomainVariableMng(), _initEquationSystem(), _initLaws(), _initRestore(), _initTimeVariableMng(), _initTransmissivity(), and init().
systemDomain()
Domain const& ThermoChemicalConvectionModule::systemDomain () const inline
AI-Generated Documentation: Returns the system domain
Definition at line 91 of file ThermoChemicalConvectionModule.cc.
References m_domain.
unknownsManager()
const Law::PropertyVector& ThermoChemicalConvectionModule::unknownsManager () const inline private
AI-Generated Documentation: Returns the unknown properties manager
Definition at line 117 of file ThermoChemicalConvectionModule.cc.
References m_unknown_manager.
Referenced by _buildAccumulation(), _buildFluxBoundary(), and _buildFluxInternal().
Member Data Documentation
m_domain
ArcNum::INonLinearSystem::Domain ThermoChemicalConvectionModule::m_domain private
AI-Generated Documentation: Non-linear system domain
Definition at line 302 of file ThermoChemicalConvectionModule.cc.
Referenced by _initDomainVariableMng(), and systemDomain().
m_folder
ArcGeoSim::AppService<IVariableManager> ThermoChemicalConvectionModule::m_folder private
Note
Original: acces domain for contributions
AI-Generated Documentation: Domain accessor for contribution assembly
Definition at line 299 of file ThermoChemicalConvectionModule.cc.
Referenced by domain(), domainT0(), domainTn(), and folder().
m_funcs
Law::FunctionManager ThermoChemicalConvectionModule::m_funcs private
Note
Original: law function manager and evaluator
AI-Generated Documentation: Function manager for physical law evaluation
Definition at line 292 of file ThermoChemicalConvectionModule.cc.
Referenced by _evaluateLaws(), _initLaws(), and functionMng().
m_properties_to_evaluate
Arcane::SharedArray<Gump::ScalarRealProperty> ThermoChemicalConvectionModule::m_properties_to_evaluate private
AI-Generated Documentation: Properties to evaluate in law functions
Definition at line 295 of file ThermoChemicalConvectionModule.cc.
Referenced by _evaluateLaws(), and _initLaws().
m_schemeStencil
std::shared_ptr<ArcNum::MultiPointsStencil> ThermoChemicalConvectionModule::m_schemeStencil private
AI-Generated Documentation: Multi-point stencil for flux computation (optional)
Definition at line 276 of file ThermoChemicalConvectionModule.cc.
Referenced by _multiPointsProfiler(), and initLinearSystemProfile().
m_snapshots
ArcGeoSim::AppService<ArcGeoSim::ITimeLoopSnapshotManager> ThermoChemicalConvectionModule::m_snapshots private
Note
Original: evolutive variable management restart newton
AI-Generated Documentation: Snapshot manager for restart on failure
Definition at line 288 of file ThermoChemicalConvectionModule.cc.
Referenced by _addTimeVariable().
m_system
ArcRes::System ThermoChemicalConvectionModule::m_system private
Note
Original: system instance based on gump
AI-Generated Documentation: Gump-based system instance
Definition at line 284 of file ThermoChemicalConvectionModule.cc.
Referenced by _initPhysicalSystem(), and system().
m_transmissivities
ArcNum::TwoPointsTransmissivity ThermoChemicalConvectionModule::m_transmissivities private
AI-Generated Documentation: Two-point transmissivity operator
Definition at line 273 of file ThermoChemicalConvectionModule.cc.
Referenced by _buildFluxBoundary(), _buildFluxInternal(), and _initTransmissivity().
m_unknown_manager
Law::PropertyVector ThermoChemicalConvectionModule::m_unknown_manager private
Note
Original: unknowns as Law::PropertyVector!
AI-Generated Documentation: Manager for unknown properties
Definition at line 280 of file ThermoChemicalConvectionModule.cc.
Referenced by _initEquationSystem(), equationSystem(), nbEquations(), setSolutionVariables(), and unknownsManager().
The documentation for this class was generated from the following file:
src/TwoPhaseFlowSimulation/ThermoChemicalConvectionModule.cc