ShArc: Arcane::FemUtils::AlienBSRMatrix Class Reference
Arcane::FemUtils::AlienBSRMatrix Class Reference
A class representing a Block Sparse Row (BSR) matrix.
#include <AlienBSRFormat.h>
Public Member Functions
AlienBSRMatrix (ITraceMng *tm, const eMemoryRessource &mem_ressource, const RunQueue &queue)
AI generated: Constructor initializing the BSR matrix with memory resource and queue.
void addValue (DoFLocalId row, DoFLocalId col, Real value)
AI generated: Adds a value at the specified (row, col) position.
void dump (const String &filename)
AI generated: Dumps the matrix contents to a file.
Int32 findValueIndex (DoFLocalId row, DoFLocalId col) const
AI generated: Finds the linear index of a value given its (row, col) coordinates.
Real getValue (DoFLocalId row, DoFLocalId col) const
AI generated: Gets the value at the specified (row, col) position.
void initialize (Int32 nb_non_zero_value, Int32 nb_col, Int32 nb_row, Int8 nb_block, bool order_values_per_block)
AI generated: Initializes the matrix with dimensions and block parameters.
Int8 nbBlock ()
AI generated: Returns the block size.
Int32 nbColumn ()
AI generated: Returns the number of columns.
Int32 nbNonZero ()
AI generated: Returns the number of non-zero values.
Int32 nbRow ()
AI generated: Returns the number of rows.
bool orderValuePerBlock ()
AI generated: Returns true if values are ordered per block (vs per row).
void setValue (DoFLocalId row, DoFLocalId col, Real value)
AI generated: Sets the value at the specified (row, col) position.
void toCsr (CsrFormat *csr_matrix)
AI generated: Converts the BSR matrix to CSR format.
void toLinearSystem (DoFLinearSystem &linear_system)
AI generated: Converts the matrix to a linear system for solving.
Private Member Functions
NumArray< Int32, MDDim1 > & _columns ()
NumArray< Int32, MDDim1 > & _nbNonZeroPerRows ()
NumArray< Int32, MDDim1 > & _rowsIndex ()
NumArray< Real, MDDim1 > & _values ()
Private Attributes
NumArray< Int32, MDDim1 > m_columns
Int8 m_nb_block = 1
Int32 m_nb_col = 0
NumArray< Int32, MDDim1 > m_nb_non_zero_per_rows
Int32 m_nb_non_zero_value = 0
Int32 m_nb_row = 0
bool m_order_values_per_block = true
RunQueue m_queue
NumArray< Int32, MDDim1 > m_rows_index
NumArray< Real, MDDim1 > m_values
Friends
class AlienBSRFormat
Detailed Description
A class representing a Block Sparse Row (BSR) matrix.
The AlienBSRMatrix class stores sparse matrices in the Block Sparse Row (BSR) format, suitable for block-structured computations.
The BSR format groups non-zero elements into fixed-size blocks, enabling efficient storage and computation for multi-DoFs meshes. Below is an example for a 6x6 matrix with a block size of 2x2 (2 DoFs per node).
Original Matrix (6x6, Block Size = 2x2):
[ 1  2  0  0  0  0 ]
[ 3  4  0  0  0  0 ]
[ 0  0  5  6  7  8 ]
[ 0  0  9 10 11 12 ]
[ 0  0  0  0 13 14 ]
[ 0  0  0  0 15 16 ]
BSR Representation:
  - Values:
     if "Ordered per block":
       [ 1, 2, 3, 4, 5, 6, 9, 10, 7, 8, 11, 12, 13, 14, 15, 16 ]
     if "Ordered per row" (same as CSR):
       [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
  - Columns:   [ 0, 1, 2, 2 ]  // Column indices of each block
  - Row Index: [ 0, 1, 3 ]     // Starting indices of blocks per row
Note
The class supports flexible memory management for computations on different hardware backends (e.g., CPU, GPU). Having the value array stored in per row (which the way CSR format stores matrices) allow us to pass it directly to HYPRE (which support CSR but not BSR), whithout the need for a translation step on it.
Definition at line 75 of file AlienBSRFormat.h.
Constructor & Destructor Documentation
AlienBSRMatrix()
Arcane::FemUtils::AlienBSRMatrix::AlienBSRMatrix (ITraceMng * tm, const eMemoryRessource & mem_ressource, const RunQueue & queue)
AI generated: Constructor initializing the BSR matrix with memory resource and queue.
Definition at line 57 of file AlienBSRFormat.cc.
Member Function Documentation
_columns()
NumArray<Int32, MDDim1>& Arcane::FemUtils::AlienBSRMatrix::_columns () inline private
Definition at line 133 of file AlienBSRFormat.h.
References m_columns.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree(), Arcane::FemUtils::AlienBSRFormat::computeColumns(), and Arcane::FemUtils::AlienBSRFormat::computeColumnsAtomicFree().
_nbNonZeroPerRows()
NumArray<Int32, MDDim1>& Arcane::FemUtils::AlienBSRMatrix::_nbNonZeroPerRows () inline private
Definition at line 135 of file AlienBSRFormat.h.
References m_nb_non_zero_per_rows.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree(), and Arcane::FemUtils::AlienBSRFormat::computeNzPerRowArray().
_rowsIndex()
NumArray<Int32, MDDim1>& Arcane::FemUtils::AlienBSRMatrix::_rowsIndex () inline private
Definition at line 134 of file AlienBSRFormat.h.
References m_rows_index.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree(), Arcane::FemUtils::AlienBSRFormat::computeColumns(), Arcane::FemUtils::AlienBSRFormat::computeColumnsAtomicFree(), Arcane::FemUtils::AlienBSRFormat::computeNzPerRowArray(), Arcane::FemUtils::AlienBSRFormat::computeRowIndex(), and Arcane::FemUtils::AlienBSRFormat::computeRowIndexAtomicFree().
_values()
NumArray<Real, MDDim1>& Arcane::FemUtils::AlienBSRMatrix::_values () inline private
Definition at line 132 of file AlienBSRFormat.h.
References m_values.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree(), and Arcane::FemUtils::AlienBSRFormat::resetMatrixValues().
addValue()
void Arcane::FemUtils::AlienBSRMatrix::addValue (DoFLocalId row, DoFLocalId col, Real value) inline
AI generated: Adds a value at the specified (row, col) position.
Definition at line 106 of file AlienBSRFormat.h.
References findValueIndex(), and m_values.
dump()
void Arcane::FemUtils::AlienBSRMatrix::dump (const String & filename)
AI generated: Dumps the matrix contents to a file.
Definition at line 225 of file AlienBSRFormat.cc.
References m_columns, m_rows_index, m_values, nbNonZero(), and nbRow().
Referenced by Arcane::FemUtils::AlienBSRFormat::dumpMatrix().
findValueIndex()
Int32 Arcane::FemUtils::AlienBSRMatrix::findValueIndex (DoFLocalId row, DoFLocalId col) const
AI generated: Finds the linear index of a value given its (row, col) coordinates.
Definition at line 102 of file AlienBSRFormat.cc.
References m_columns, m_nb_block, m_nb_col, m_nb_non_zero_per_rows, m_nb_row, m_order_values_per_block, and m_rows_index.
Referenced by addValue(), getValue(), and setValue().
getValue()
Real Arcane::FemUtils::AlienBSRMatrix::getValue (DoFLocalId row, DoFLocalId col) const inline
AI generated: Gets the value at the specified (row, col) position.
Definition at line 94 of file AlienBSRFormat.h.
References findValueIndex(), and m_values.
Referenced by toLinearSystem().
initialize()
void Arcane::FemUtils::AlienBSRMatrix::initialize (Int32 nb_non_zero_value, Int32 nb_col, Int32 nb_row, Int8 nb_block, bool order_values_per_block)
AI generated: Initializes the matrix with dimensions and block parameters.
Definition at line 71 of file AlienBSRFormat.cc.
References m_columns, m_nb_block, m_nb_col, m_nb_non_zero_per_rows, m_nb_non_zero_value, m_nb_row, m_order_values_per_block, m_queue, m_rows_index, and m_values.
nbBlock()
Int8 Arcane::FemUtils::AlienBSRMatrix::nbBlock () inline
AI generated: Returns the block size.
Definition at line 128 of file AlienBSRFormat.h.
References m_nb_block.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), and Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree().
nbColumn()
Int32 Arcane::FemUtils::AlienBSRMatrix::nbColumn () inline
AI generated: Returns the number of columns.
Definition at line 124 of file AlienBSRFormat.h.
References m_nb_col.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree(), and Arcane::FemUtils::AlienBSRFormat::computeNzPerRowArray().
nbNonZero()
Int32 Arcane::FemUtils::AlienBSRMatrix::nbNonZero () inline
AI generated: Returns the number of non-zero values.
Definition at line 122 of file AlienBSRFormat.h.
References m_nb_non_zero_value.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree(), and dump().
nbRow()
Int32 Arcane::FemUtils::AlienBSRMatrix::nbRow () inline
AI generated: Returns the number of rows.
Definition at line 126 of file AlienBSRFormat.h.
References m_nb_row.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlockAtomicFree(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree(), Arcane::FemUtils::AlienBSRFormat::computeNzPerRowArray(), and dump().
orderValuePerBlock()
bool Arcane::FemUtils::AlienBSRMatrix::orderValuePerBlock () inline
AI generated: Returns true if values are ordered per block (vs per row).
Definition at line 120 of file AlienBSRFormat.h.
References m_order_values_per_block.
Referenced by Arcane::FemUtils::AlienBSRFormat::assembleBilinearAtomic(), and Arcane::FemUtils::AlienBSRFormat::assembleBilinearAtomicFree().
setValue()
void Arcane::FemUtils::AlienBSRMatrix::setValue (DoFLocalId row, DoFLocalId col, Real value) inline
AI generated: Sets the value at the specified (row, col) position.
Definition at line 100 of file AlienBSRFormat.h.
References findValueIndex(), and m_values.
toCsr()
void Arcane::FemUtils::AlienBSRMatrix::toCsr (CsrFormat * csr_matrix)
AI generated: Converts the BSR matrix to CSR format.
Definition at line 133 of file AlienBSRFormat.cc.
References Arcane::FemUtils::CsrFormat::initialize(), m_columns, Arcane::FemUtils::CsrFormat::m_matrix_column, Arcane::FemUtils::CsrFormat::m_matrix_row, Arcane::FemUtils::CsrFormat::m_matrix_rows_nb_column, Arcane::FemUtils::CsrFormat::m_matrix_value, m_nb_block, m_nb_col, m_nb_non_zero_per_rows, m_nb_non_zero_value, m_queue, m_rows_index, and m_values.
toLinearSystem()
void Arcane::FemUtils::AlienBSRMatrix::toLinearSystem (DoFLinearSystem & linear_system)
AI generated: Converts the matrix to a linear system for solving.
Definition at line 200 of file AlienBSRFormat.cc.
References getValue(), m_columns, m_nb_block, m_nb_col, m_nb_row, m_rows_index, and Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
Friends And Related Function Documentation
AlienBSRFormat
friend class AlienBSRFormat friend
Definition at line 78 of file AlienBSRFormat.h.
Member Data Documentation
m_columns
NumArray<Int32, MDDim1> Arcane::FemUtils::AlienBSRMatrix::m_columns private
Definition at line 147 of file AlienBSRFormat.h.
Referenced by _columns(), dump(), findValueIndex(), initialize(), toCsr(), and toLinearSystem().
m_nb_block
Int8 Arcane::FemUtils::AlienBSRMatrix::m_nb_block = 1 private
Definition at line 144 of file AlienBSRFormat.h.
Referenced by findValueIndex(), initialize(), nbBlock(), toCsr(), and toLinearSystem().
m_nb_col
Int32 Arcane::FemUtils::AlienBSRMatrix::m_nb_col = 0 private
Definition at line 142 of file AlienBSRFormat.h.
Referenced by findValueIndex(), initialize(), nbColumn(), toCsr(), and toLinearSystem().
m_nb_non_zero_per_rows
NumArray<Int32, MDDim1> Arcane::FemUtils::AlienBSRMatrix::m_nb_non_zero_per_rows private
Definition at line 149 of file AlienBSRFormat.h.
Referenced by _nbNonZeroPerRows(), findValueIndex(), initialize(), and toCsr().
m_nb_non_zero_value
Int32 Arcane::FemUtils::AlienBSRMatrix::m_nb_non_zero_value = 0 private
Definition at line 141 of file AlienBSRFormat.h.
Referenced by initialize(), nbNonZero(), and toCsr().
m_nb_row
Int32 Arcane::FemUtils::AlienBSRMatrix::m_nb_row = 0 private
Definition at line 143 of file AlienBSRFormat.h.
Referenced by findValueIndex(), initialize(), nbRow(), and toLinearSystem().
m_order_values_per_block
bool Arcane::FemUtils::AlienBSRMatrix::m_order_values_per_block = true private
Definition at line 139 of file AlienBSRFormat.h.
Referenced by findValueIndex(), initialize(), and orderValuePerBlock().
m_queue
RunQueue Arcane::FemUtils::AlienBSRMatrix::m_queue private
Definition at line 151 of file AlienBSRFormat.h.
Referenced by initialize(), and toCsr().
m_rows_index
NumArray<Int32, MDDim1> Arcane::FemUtils::AlienBSRMatrix::m_rows_index private
Definition at line 148 of file AlienBSRFormat.h.
Referenced by _rowsIndex(), dump(), findValueIndex(), initialize(), toCsr(), and toLinearSystem().
m_values
NumArray<Real, MDDim1> Arcane::FemUtils::AlienBSRMatrix::m_values private
Definition at line 146 of file AlienBSRFormat.h.
Referenced by _values(), addValue(), dump(), getValue(), initialize(), setValue(), and toCsr().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/AlienBSRFormat.h
src/CAWF/FEMUtils/AlienBSRFormat.cc