ShArc: Arcane::FemUtils::Gpu::BoundaryConditionsHelpers Class Reference
Arcane::FemUtils::Gpu::BoundaryConditionsHelpers Class Reference
AI generated: Helper class implementing generic GPU boundary condition operations (Dirichlet, source terms)
#include <ArcaneFemFunctionsGpu.h>
Static Public Member Functions
template<class Function >
static void applyConstantSourceToRhsBase (Function computeSpatialIntegral, Real qdot, RunQueue *queue, VariableDoFReal &rhs_variable_na, IMesh *mesh, const FemDoFsOnNodes &dofs_on_nodes, const VariableNodeReal3 &node_coord)
AI generated: Applies a constant source term to the RHS using a spatial integral functor.
static void applyDirichletToNodeGroupRhsOnly (Int32 dof_index, Real value, RunQueue *queue, IMesh *mesh, DoFLinearSystem &linear_system, const FemDoFsOnNodes &dofs_on_nodes, const NodeGroup &node_group)
AI generated: Applies Dirichlet BCs by setting the RHS value directly (no matrix modification)
static void applyDirichletToNodeGroupViaPenalty (Int32 dof_index, Real value, Real penalty, RunQueue *queue, IMesh *mesh, DoFLinearSystem &linear_system, const FemDoFsOnNodes &dofs_on_nodes, const NodeGroup &node_group)
AI generated: Applies Dirichlet BCs using the penalty method (adds penalty to diagonal and RHS)
static void applyDirichletToNodeGroupViaRowOrRowColumnElimination (Byte elimination_type, Int32 dof_index, Real value, RunQueue *queue, DoFLinearSystem &linear_system, const FemDoFsOnNodes &dofs_on_nodes, const NodeGroup &node_group)
AI generated: Applies Dirichlet BCs via row or row-column elimination (modifies matrix and RHS)
Detailed Description
AI generated: Helper class implementing generic GPU boundary condition operations (Dirichlet, source terms)
Definition at line 651 of file ArcaneFemFunctionsGpu.h.
Member Function Documentation
applyConstantSourceToRhsBase()
template<class Function > static void Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyConstantSourceToRhsBase (Function computeSpatialIntegral, Real qdot, RunQueue * queue, VariableDoFReal & rhs_variable_na, IMesh * mesh, const FemDoFsOnNodes & dofs_on_nodes, const VariableNodeReal3 & node_coord) inline static
AI generated: Applies a constant source term to the RHS using a spatial integral functor.
Definition at line 657 of file ArcaneFemFunctionsGpu.h.
References Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView().
applyDirichletToNodeGroupRhsOnly()
void Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupRhsOnly (Int32 dof_index, Real value, RunQueue * queue, IMesh * mesh, DoFLinearSystem & linear_system, const FemDoFsOnNodes & dofs_on_nodes, const NodeGroup & node_group) static
AI generated: Applies Dirichlet BCs by setting the RHS value directly (no matrix modification)
Definition at line 26 of file ArcaneFemFunctionsGpu.cc.
References Arcane::FemUtils::DoFLinearSystem::getForcedInfo(), Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
applyDirichletToNodeGroupViaPenalty()
void Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty (Int32 dof_index, Real value, Real penalty, RunQueue * queue, IMesh * mesh, DoFLinearSystem & linear_system, const FemDoFsOnNodes & dofs_on_nodes, const NodeGroup & node_group) static
AI generated: Applies Dirichlet BCs using the penalty method (adds penalty to diagonal and RHS)
Definition at line 54 of file ArcaneFemFunctionsGpu.cc.
References Arcane::FemUtils::DoFLinearSystem::getForcedInfo(), Arcane::FemUtils::DoFLinearSystem::getForcedValue(), Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs().
applyDirichletToNodeGroupViaRowOrRowColumnElimination()
void Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowOrRowColumnElimination (Byte elimination_type, Int32 dof_index, Real value, RunQueue * queue, DoFLinearSystem & linear_system, const FemDoFsOnNodes & dofs_on_nodes, const NodeGroup & node_group) static
AI generated: Applies Dirichlet BCs via row or row-column elimination (modifies matrix and RHS)
Definition at line 83 of file ArcaneFemFunctionsGpu.cc.
References Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::getEliminationInfo(), Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::getEliminationValue(), Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView(), and Arcane::FemUtils::DoFLinearSystem::rowEliminationHelper().
Referenced by Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/ArcaneFemFunctionsGpu.h
src/CAWF/FEMUtils/ArcaneFemFunctionsGpu.cc