ShArc: ArcaneFemFunctions::CellFEMDispatcher Class Reference
ArcaneFemFunctions::CellFEMDispatcher Class Reference
Provides methods based on the Dispatcher mechanism available in Arcane, allowing to compute FEM methods without declaring the FE entity type (coming from PASSMO).
#include <ArcaneFemFunctions.h>
Public Member Functions
CellFEMDispatcher ()
Initialize the CellFEMDispatcher class (coming from PASSMO)
RealUniqueArray getGaussData (ItemWithNodes item, Integer nint, Integer ngauss)
Provides at once, all Gauss data of a given input finite element (vector containing weights, ref.
Real3 getShapeFuncDeriv (Int16, Integer, Real3)
Computes the value of the nodal shape function derivatives at a given Gauss point, along 1, 2 and/or 3 directions depending on space dimension (for a given node within in a given element) This method is generic (coming from PASSMO)
Real getShapeFuncVal (Int16, Integer, Real3)
Computes the value of the nodal shape function at a given Gauss point (for a given node within in a given element) This method is generic (coming from PASSMO)
Private Attributes
std::function< Real(Integer inod, Real3 coord)> m_shapefunc [NB_BASIC_ITEM_TYPE]
std::function< Real3(Integer inod, Real3 coord)> m_shapefuncderiv [NB_BASIC_ITEM_TYPE]
Detailed Description
Provides methods based on the Dispatcher mechanism available in Arcane, allowing to compute FEM methods without declaring the FE entity type (coming from PASSMO).
Definition at line 2943 of file ArcaneFemFunctions.h.
Constructor & Destructor Documentation
CellFEMDispatcher()
ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher ()
Initialize the CellFEMDispatcher class (coming from PASSMO)
Definition at line 17 of file ArcaneFemFunctions.cc.
References ArcaneFemFunctions::FemShapeMethods::hexa20ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::hexa20ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::hexa8ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::hexa8ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::line2ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::line2ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::line3ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::line3ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::penta6ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::penta6ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::pyramid5ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::pyramid5ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::quad4ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::quad4ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::quad8ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::quad8ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::tetra10ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::tetra10ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::tetra4ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::tetra4ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::tri3ShapeFuncDeriv(), ArcaneFemFunctions::FemShapeMethods::tri3ShapeFuncVal(), ArcaneFemFunctions::FemShapeMethods::tri6ShapeFuncDeriv(), and ArcaneFemFunctions::FemShapeMethods::tri6ShapeFuncVal().
Member Function Documentation
getGaussData()
RealUniqueArray ArcaneFemFunctions::CellFEMDispatcher::getGaussData (ItemWithNodes item, Integer nint, Integer ngauss)
Provides at once, all Gauss data of a given input finite element (vector containing weights, ref.
coordinates, nodal shape values & derivatives) This method is generic (coming from PASSMO)
Definition at line 69 of file ArcaneFemFunctions.cc.
References ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition(), ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight(), and ArcaneFemFunctions::FemGaussQuadrature::getNbGaussPointsfromOrder().
getShapeFuncDeriv()
Real3 ArcaneFemFunctions::CellFEMDispatcher::getShapeFuncDeriv (Int16 item_type, Integer inod, Real3 ref_coord)
Computes the value of the nodal shape function derivatives at a given Gauss point, along 1, 2 and/or 3 directions depending on space dimension (for a given node within in a given element) This method is generic (coming from PASSMO)
Definition at line 127 of file ArcaneFemFunctions.cc.
getShapeFuncVal()
Real ArcaneFemFunctions::CellFEMDispatcher::getShapeFuncVal (Int16 item_type, Integer inod, Real3 coord)
Computes the value of the nodal shape function at a given Gauss point (for a given node within in a given element) This method is generic (coming from PASSMO)
Definition at line 110 of file ArcaneFemFunctions.cc.
Member Data Documentation
m_shapefunc
std::function<Real(Integer inod, Real3 coord)> ArcaneFemFunctions::CellFEMDispatcher::m_shapefunc[NB_BASIC_ITEM_TYPE] private
Definition at line 2957 of file ArcaneFemFunctions.h.
m_shapefuncderiv
std::function<Real3(Integer inod, Real3 coord)> ArcaneFemFunctions::CellFEMDispatcher::m_shapefuncderiv[NB_BASIC_ITEM_TYPE] private
Definition at line 2958 of file ArcaneFemFunctions.h.
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/ArcaneFemFunctions.h
src/CAWF/FEMUtils/ArcaneFemFunctions.cc