ShArc: FluidDensityLaw Class Reference
FluidDensityLaw Class Reference
Two-Phase Flow
Fluid density law with linear expansion.
#include <FluidDensityLaw.h>
Public Member Functions
FluidDensityLaw ()
void eval (const Real T, const Real C, Real &rho, Real &drho_dt, Real &drho_dc) const
AI comment: Evaluates fluid density rho = rho0 * (1 - betat*(T-T0) + betac*(C-C0))
void setParameters (const Real rho0, const Real betat, const Real betac, const Real t0, const Real c0)
AI comment: Sets fluid density law parameters: reference density, thermal/salinity expansion.
Private Member Functions
void initParameters ()
AI comment: Initializes fluid density parameters to default values.
Private Attributes
Real m_betac
Real m_betat
Real m_c0
Real m_rho0
Real m_t0
Detailed Description
Fluid density law with linear expansion.
AI-Generated Documentation:
Computes fluid density as a function of temperature and concentration using the linear expansion model: \(\rho(T,C) = \rho_0 [1 - \beta_T (T - T_0) - \beta_C (C - C_0)]\).
Definition at line 27 of file FluidDensityLaw.h.
Constructor & Destructor Documentation
FluidDensityLaw()
FluidDensityLaw::FluidDensityLaw () inline
AI-Generated Documentation: Constructs the law with default parameters
Definition at line 32 of file FluidDensityLaw.h.
References initParameters().
Member Function Documentation
eval()
void FluidDensityLaw::eval (const Real T, const Real C, Real & rho, Real & drho_dt, Real & drho_dc) const
AI comment: Evaluates fluid density rho = rho0 * (1 - betat*(T-T0) + betac*(C-C0))
AI-Generated Documentation: Evaluates density and its partial derivatives
Parameters
T Temperature
C Concentration
rho Density
drho_dt Partial derivative wrt temperature
drho_dc Partial derivative wrt concentration
Definition at line 23 of file FluidDensityLaw.cc.
References m_betac, m_betat, m_c0, m_rho0, and m_t0.
Referenced by FluidDensityLawConfigService::configure().
initParameters()
void FluidDensityLaw::initParameters () private
AI comment: Initializes fluid density parameters to default values.
AI-Generated Documentation: Initializes parameters to default values
Definition at line 70 of file FluidDensityLaw.cc.
References setParameters().
Referenced by FluidDensityLaw().
setParameters()
void FluidDensityLaw::setParameters (const Real rho0, const Real betat, const Real betac, const Real t0, const Real c0)
AI comment: Sets fluid density law parameters: reference density, thermal/salinity expansion.
AI-Generated Documentation: Sets the law parameters
Parameters
rho0 Reference density
betat Thermal expansion coefficient
betac Concentration expansion coefficient
t0 Reference temperature
c0 Reference concentration
Definition at line 55 of file FluidDensityLaw.cc.
References m_betac, m_betat, m_c0, m_rho0, and m_t0.
Referenced by FluidDensityLawConfigService::configure(), and initParameters().
Member Data Documentation
m_betac
Real FluidDensityLaw::m_betac private
AI-Generated Documentation: Concentration expansion coefficient
Definition at line 65 of file FluidDensityLaw.h.
Referenced by eval(), and setParameters().
m_betat
Real FluidDensityLaw::m_betat private
AI-Generated Documentation: Thermal expansion coefficient
Definition at line 63 of file FluidDensityLaw.h.
Referenced by eval(), and setParameters().
m_c0
Real FluidDensityLaw::m_c0 private
AI-Generated Documentation: Reference concentration
Definition at line 69 of file FluidDensityLaw.h.
Referenced by eval(), and setParameters().
m_rho0
Real FluidDensityLaw::m_rho0 private
AI-Generated Documentation: Reference density
Definition at line 61 of file FluidDensityLaw.h.
Referenced by eval(), and setParameters().
m_t0
Real FluidDensityLaw::m_t0 private
AI-Generated Documentation: Reference temperature
Definition at line 67 of file FluidDensityLaw.h.
Referenced by eval(), and setParameters().
The documentation for this class was generated from the following files:
src/TwoPhaseFlowSimulation/PhysicalLaws/FluidDensityLaw/FluidDensityLaw.h
src/TwoPhaseFlowSimulation/PhysicalLaws/FluidDensityLaw/FluidDensityLaw.cc