ShArc: ArcaneFemFunctions::BoundaryConditionsHelpers Class Reference
ArcaneFemFunctions::BoundaryConditionsHelpers Class Reference
Provides methods to help build boundary conditions in 2D/3D.
#include <ArcaneFemFunctions.h>
Static Public Member Functions
static void applyDirichletToNodeGroupRhsOnly (const Int32 dof_index, Real value, const IndexedNodeDoFConnectivityView &node_dof, VariableDoFReal &rhs_values, NodeGroup &node_group)
static void applyDirichletToNodeGroupViaPenalty (const Int32 dof_index, Real value, Real penalty, const IndexedNodeDoFConnectivityView &node_dof, DoFLinearSystem &linear_system, VariableDoFReal &rhs_values, NodeGroup &node_group)
static void applyDirichletToNodeGroupViaRowColumnElimination (const Int32 dof_index, Real value, const IndexedNodeDoFConnectivityView &node_dof, DoFLinearSystem &linear_system, VariableDoFReal &rhs_values, NodeGroup &node_group)
static void applyDirichletToNodeGroupViaRowElimination (const Int32 dof_index, Real value, const IndexedNodeDoFConnectivityView &node_dof, DoFLinearSystem &linear_system, VariableDoFReal &rhs_values, NodeGroup &node_group)
Detailed Description
Provides methods to help build boundary conditions in 2D/3D.
Definition at line 1165 of file ArcaneFemFunctions.h.
Member Function Documentation
applyDirichletToNodeGroupRhsOnly()
static void ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupRhsOnly (const Int32 dof_index, Real value, const IndexedNodeDoFConnectivityView & node_dof, VariableDoFReal & rhs_values, NodeGroup & node_group) inline static
Definition at line 1169 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::BoundaryConditions::applyDirichletToRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToRhs().
applyDirichletToNodeGroupViaPenalty()
static void ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty (const Int32 dof_index, Real value, Real penalty, const IndexedNodeDoFConnectivityView & node_dof, DoFLinearSystem & linear_system, VariableDoFReal & rhs_values, NodeGroup & node_group) inline static
Definition at line 1179 of file ArcaneFemFunctions.h.
References Arcane::FemUtils::DoFLinearSystem::matrixSetValue().
Referenced by ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs().
applyDirichletToNodeGroupViaRowColumnElimination()
static void ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowColumnElimination (const Int32 dof_index, Real value, const IndexedNodeDoFConnectivityView & node_dof, DoFLinearSystem & linear_system, VariableDoFReal & rhs_values, NodeGroup & node_group) inline static
Definition at line 1206 of file ArcaneFemFunctions.h.
References Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::addElimination(), and Arcane::FemUtils::DoFLinearSystem::rowColumnEliminationHelper().
Referenced by ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs().
applyDirichletToNodeGroupViaRowElimination()
static void ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowElimination (const Int32 dof_index, Real value, const IndexedNodeDoFConnectivityView & node_dof, DoFLinearSystem & linear_system, VariableDoFReal & rhs_values, NodeGroup & node_group) inline static
Definition at line 1191 of file ArcaneFemFunctions.h.
References Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::addElimination(), and Arcane::FemUtils::DoFLinearSystem::rowEliminationHelper().
Referenced by ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/ArcaneFemFunctions.h