ShArc: FemModuleElasticity Class Reference
FemModuleElasticity Class Reference
CAWF
A module for finite element method.
#include <FemModule.h>
Public Member Functions
FemModuleElasticity (const ModuleBuildInfo &mbi)
void _assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
void _assembleDirichletsGpu ()
Applies dirichlet to LHS matrix and RHS vector of the linear system on Gpu.
void _computePostPro ()
AI comment: Post-processing: extracts displacement components and computes divergence.
void _computePrePro ()
AI comment: Pre-processing: computes body force from pressure gradient on hexahedral meshes.
template<typename ProfilerT >
void _defineMatrixProfile (ProfilerT &profiler, ConstArrayView< Integer > allUIndex)
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _updateTopBoundary (CellGroup const &new_event)
AI comment: Updates the top boundary face group from new event cells.
void computeDivU () override
Performs the main computation for the FemModuleElasticity.
void init () override
Initializes the FemModuleElasticity at the start of the simulation.
void reloadOldState ()
AI comment: Reloads the previously saved state after a failed coupling iteration.
void saveOldState ()
AI comment: Saves the current state for potential rollback in coupled simulations.
void startInit () override
AI comment: Initializes solver parameters, material properties, body force, and node pressure.
void test () override
AI comment: Main time loop, handles coupled (preCICE) and standalone computation modes.
VersionInfo versionInfo () const override
Private Member Functions
void _applyBodyForce (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies body force to the RHS vector of the linear system.
void _applyDirichlet (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies dirichlet to LHS matrix and RHS vector of the linear system.
void _applyTraction (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies traction to the RHS vector of the linear system.
template<int N>
void _assembleBilinearOperatorCpu (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the FEM bilinear operator on CPU.
template<class FunctionT >
void _assembleBilinearOperatorGpu (const FunctionT &compute_element_matrix)
void _assembleLinearOperator ()
Assemble the FEM linear operator.
Real _computeElementDiv (Cell cell)
Real3 _computeElementGradientHexa8 (Cell cell)
RealMatrix< 24, 24 > _computeElementMatrixHexa8 (Cell cell)
AI comment: Computes the hexahedron element matrix using 2×2×2 Gauss quadrature.
RealMatrix< 8, 8 > _computeElementMatrixQuad4 (Cell cell)
AI comment: Computes the quadrilateral element matrix using 2×2 Gauss quadrature.
RealMatrix< 12, 12 > _computeElementMatrixTetra4 (Cell cell)
AI comment: Computes the tetrahedron element matrix, called from CPU assembly path.
RealMatrix< 6, 6 > _computeElementMatrixTria3 (Cell cell)
AI comment: Computes the triangle element matrix, called from CPU assembly path.
void _getMaterialParameters (CellGroup const &cells)
Retrieves and sets the material parameters for the simulation.
void _initAlienBsr ()
AI comment: Initializes the Alien BSR (Block Sparse Row) matrix format.
void _initBsr ()
Initializes BSR matrix.
void _solve ()
Solves the linear system.
void _updateVariables ()
Update the FEM variables.
void _validateResults ()
AI comment: Validates computed results against a reference solution file.
Private Attributes
Real E
UniqueArray< Int64 > m_activated_layers_uids
AlienBSRFormat * m_alien_bsr_format = nullptr
Arcane::FemUtils::AlienDoFLinearSystemImpl * m_alien_linear_system = nullptr
bool m_applyBodyForce = false
bool m_assemble_linear_system = true
BSRFormat m_bsr_format
ArcGeoSim::ICAWFMng * m_cawf_mng = nullptr
bool m_cross_validation = false
UniqueArray< Integer > m_dof_dof_connection_index
UniqueArray< Integer > m_dof_dof_connection_offset
Int8 m_dof_per_node
FemDoFsOnNodes m_dofs_on_nodes
Real m_dt = 0.
ShArc::IDynamicMeshMng * m_dynamic_mesh_mng = nullptr
Integer m_event_index = 0
Real m_event_period = 0.
Real3 m_F
IGeometryMng * m_geometry_mng = nullptr
NoOptimizationGeometryPolicy m_geometry_policy
Real m_gravity = 9.8
bool m_hex_quad_mesh = false
int m_iter = 0
Real m_layer_event_period = 0.
Real m_layer_event_time = 0.
UniqueArray< Arcane::CellGroup > m_layers
Alien::ILinearSolver * m_linear_solver = nullptr
DoFLinearSystem m_linear_system
String m_matrix_format = "DOK"
Integer m_max_iter = 0
Integer m_new_layer_id = 0
Real m_next_event_time = 0.
Real m_next_layer_event_time = 0.
IParallelMng * m_parallel_mng = nullptr
String m_petsc_flags
bool m_precice_mesh_is_updated = false
bool m_solve_linear_system = true
Real m_time = 0.
Real m_top_z = 0.
Real nu
Real3 t
Detailed Description
A module for finite element method.
This class handles the initialization and computation for finite element method (FEM) simulations, providing methods to set up and solve linear systems, assemble FEM operators, and perform result checks.
Definition at line 80 of file FemModule.h.
Constructor & Destructor Documentation
FemModuleElasticity()
FemModuleElasticity::FemModuleElasticity (const ModuleBuildInfo & mbi) inline explicit
AI-Generated Documentation: Constructs the elasticity module
Definition at line 87 of file FemModule.h.
Member Function Documentation
_applyBodyForce()
void FemModuleElasticity::_applyBodyForce (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies body force to the RHS vector of the linear system.
AI-Generated Documentation: Applies body force contribution to the RHS
This function computes the contribution of body forces to the RHS vector of the linear system. It iterates over all cells in the mesh, calculates the appropriate force contributions based on the element type and mesh dimension, and updates the RHS vector accordingly.
body force ∫∫∫ (𝐟.𝐯) with 𝐟 = (𝑓𝑥, 𝑓𝑦, 𝑓𝑧) = (f[0], f[1], f[2])
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding degrees of freedom (DoFs).
Definition at line 31 of file BodyForce.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), ArcaneFemFunctions::FeOperation3D::computeShapeFunctionsHexa8(), ArcaneFemFunctions::FeOperation2D::computeShapeFunctionsQuad4(), ArcaneFemFunctions::MeshOperation::computeVolumeTetra4(), m_applyBodyForce, m_hex_quad_mesh, and M_SQRT1_3.
Referenced by _assembleLinearOperator().
_applyDirichlet()
void FemModuleElasticity::_applyDirichlet (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies dirichlet to LHS matrix and RHS vector of the linear system.
AI-Generated Documentation: Applies Dirichlet BCs to the linear system
This function applies Dirichlet boundary conditions to both the LHS matrix and RHS vector of the linear system.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 26 of file Dirichlet.h.
References _assembleDirichletsGpu(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), BC::IArcaneFemBC::dirichletBoundaryConditions(), BC::IArcaneFemBC::dirichletPointConditions(), m_linear_system, and m_matrix_format.
Referenced by _assembleLinearOperator().
_applyTraction()
void FemModuleElasticity::_applyTraction (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies traction to the RHS vector of the linear system.
AI-Generated Documentation: Applies traction contribution to the RHS
This function computes the contribution of traction to the RHS vector of the linear system. It iterates over all cells in the mesh, calculates the appropriate force contributions based on the element type and mesh dimension, and updates the RHS vector accordingly.
traction term ∫∫ (𝐭.𝐯) with 𝐭 = (𝑡𝑥, 𝑡𝑦, 𝑡𝑧) = (t[0], t[1], t[2])
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding degrees of freedom (DoFs).
Definition at line 31 of file Traction.h.
References ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsHexa8(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsTetra4(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsTria3(), m_hex_quad_mesh, and BC::IArcaneFemBC::tractionBoundaryConditions().
Referenced by _assembleLinearOperator().
_assembleBilinearOperator()
void FemModuleElasticity::_assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
AI-Generated Documentation: Assembles the bilinear operator (stiffness matrix)
Definition at line 792 of file FemModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), _computeElementMatrixTria3(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), computeElementMatrixTetra4Gpu(), computeElementMatrixTria3Gpu(), computeElementVectorTetra4Gpu(), computeElementVectorTria3Gpu(), Arcane::FemUtils::BSRFormat::computeSparsity(), m_bsr_format, m_hex_quad_mesh, m_linear_system, m_matrix_format, ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::BSRFormat::toLinearSystem().
Referenced by _doStationarySolve().
_assembleBilinearOperatorCpu()
template<int N> void FemModuleElasticity::_assembleBilinearOperatorCpu (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the FEM bilinear operator on CPU.
AI-Generated Documentation: Assembles the bilinear operator on CPU for a given element type
This method assembles the FEM stiffness matrix by iterating over each cell, computing the element stiffness matrix using the provided function, and populating the global stiffness matrix accordingly.
Template Parameters
N Total DOF size (nodes_per_element × dimensions).
Parameters
compute_element_matrix function computing cell's element stiffness matrix.
Definition at line 899 of file FemModule.cc.
References m_dofs_on_nodes, m_linear_system, Arcane::FemUtils::DoFLinearSystem::matrixAddValue(), and Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView().
_assembleBilinearOperatorGpu()
template<class FunctionT > void FemModuleElasticity::_assembleBilinearOperatorGpu (const FunctionT & compute_element_matrix) private
AI-Generated Documentation: Assembles the bilinear operator on GPU for a given element type
Definition at line 80 of file FemModuleSYCL.cc.
References Arcane::FemUtils::AlienBSRFormat::getAllUIndex(), Arcane::FemUtils::AlienBSRFormat::getMatrixA(), m_alien_bsr_format, m_dofs_on_nodes, and Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView().
_assembleDirichletsGpu()
void FemModuleElasticity::_assembleDirichletsGpu ()
Applies dirichlet to LHS matrix and RHS vector of the linear system on Gpu.
AI-Generated Documentation: Assembles Dirichlet boundary conditions on GPU
This function applies Dirichlet boundary conditions to both the LHS matrix and RHS vector of the linear system using GPU acceleration.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 62 of file Dirichlet.h.
References BC::IArcaneFemBC::dirichletBoundaryConditions(), BC::IArcaneFemBC::dirichletPointConditions(), m_dofs_on_nodes, and m_linear_system.
Referenced by _applyDirichlet().
_assembleLinearOperator()
void FemModuleElasticity::_assembleLinearOperator () private
Assemble the FEM linear operator.
AI-Generated Documentation: Assembles the linear operator (stiffness + BCs)
This method follows a sequence of steps to assemble RHS of FEM linear system:
assembles the bodyforce contribution (source term) ∫∫∫ (𝐟.𝐯) on Ω
assembles the traction contribution (Neumann term) ∫∫ (𝐭.𝐯) on ∂Ω
apply Dirichlet contributions to LHS and RHS
Definition at line 767 of file FemModule.cc.
References _applyBodyForce(), _applyDirichlet(), _applyTraction(), m_dofs_on_nodes, m_linear_system, Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _doStationarySolve().
_computeElementDiv()
Real FemModuleElasticity::_computeElementDiv (Cell cell) private
AI-Generated Documentation: Computes the divergence of displacement for a cell
_computeElementGradientHexa8()
Real3 FemModuleElasticity::_computeElementGradientHexa8 (Cell cell) private
AI-Generated Documentation: Computes the gradient of displacement for a Hexa8 element
_computeElementMatrixHexa8()
RealMatrix< 24, 24 > FemModuleElasticity::_computeElementMatrixHexa8 (Cell cell) private
AI comment: Computes the hexahedron element matrix using 2×2×2 Gauss quadrature.
AI-Generated Documentation: Computes the 24x24 element matrix for a 3D Hexa8 element
Definition at line 234 of file ElementMatrixHexQuad.h.
References computeElementMatrixHexa8Base(), ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), and M_SQRT1_3.
Referenced by _assembleBilinearOperator().
_computeElementMatrixQuad4()
RealMatrix< 8, 8 > FemModuleElasticity::_computeElementMatrixQuad4 (Cell cell) private
AI comment: Computes the quadrilateral element matrix using 2×2 Gauss quadrature.
AI-Generated Documentation: Computes the 8x8 element matrix for a 2D Quad4 element
Definition at line 74 of file ElementMatrixHexQuad.h.
References computeElementMatrixQuad4Base(), ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), and M_SQRT1_3.
Referenced by _assembleBilinearOperator().
_computeElementMatrixTetra4()
RealMatrix< 12, 12 > FemModuleElasticity::_computeElementMatrixTetra4 (Cell cell) private
AI comment: Computes the tetrahedron element matrix, called from CPU assembly path.
AI-Generated Documentation: Computes the 12x12 element matrix for a 3D Tetra4 element
Definition at line 202 of file ElementMatrix.h.
References computeElementMatrixTetra4Base(), ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTria3()
RealMatrix< 6, 6 > FemModuleElasticity::_computeElementMatrixTria3 (Cell cell) private
AI comment: Computes the triangle element matrix, called from CPU assembly path.
AI-Generated Documentation: Computes the 6x6 element matrix for a 2D Tria3 element
Definition at line 82 of file ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), computeElementMatrixTria3Base(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator().
_computePostPro()
void FemModuleElasticity::_computePostPro ()
AI comment: Post-processing: extracts displacement components and computes divergence.
AI-Generated Documentation: Post-processing computations after solve
Definition at line 646 of file FemModule.cc.
References ArcaneFemFunctions::FeOperation3D::computeGradientHexa8(), and m_hex_quad_mesh.
Referenced by computeDivU().
_computePrePro()
void FemModuleElasticity::_computePrePro ()
AI comment: Pre-processing: computes body force from pressure gradient on hexahedral meshes.
AI-Generated Documentation: Pre-processing computations before assembly
Definition at line 614 of file FemModule.cc.
References ArcaneFemFunctions::FeOperation3D::computeGradientHexa8(), m_geometry_mng, and m_hex_quad_mesh.
Referenced by computeDivU().
_defineMatrixProfile()
template<typename ProfilerT > void FemModuleElasticity::_defineMatrixProfile (ProfilerT & profiler, ConstArrayView< Integer > allUIndex)
AI-Generated Documentation: Defines the matrix sparsity pattern from element connectivities
Definition at line 276 of file FemModule.h.
References Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView().
Referenced by _doStationarySolve().
_doStationarySolve()
void FemModuleElasticity::_doStationarySolve ()
Performs a stationary solve for the FEM system.
AI-Generated Documentation: Performs a stationary (non-transient) solve
This method follows a sequence of steps to solve FEM system:
_getMaterialParameters() Retrieves material parameters via
_assembleBilinearOperator() Assembles the FEM matrix 𝐀
_assembleLinearOperator() Assembles the FEM RHS vector 𝐛
_solve() Solves for solution vector 𝐮 = 𝐀⁻¹𝐛
_updateVariables() Updates FEM variables 𝐮 = 𝐱
_validateResults() Regression test
Definition at line 686 of file FemModule.cc.
References _assembleBilinearOperator(), _assembleLinearOperator(), _defineMatrixProfile(), _solve(), _updateVariables(), _validateResults(), Arcane::FemUtils::AlienBSRFormat::computeProfile(), Arcane::FemUtils::DoFLinearSystem::endSystemAssembly(), m_alien_bsr_format, m_assemble_linear_system, m_cross_validation, m_linear_system, m_matrix_format, m_solve_linear_system, and Arcane::FemUtils::DoFLinearSystem::startSystemAssembly().
Referenced by computeDivU().
_getMaterialParameters()
void FemModuleElasticity::_getMaterialParameters (CellGroup const & cells) private
Retrieves and sets the material parameters for the simulation.
AI-Generated Documentation: Retrieves material parameters (lambda, mu) for a cell group
Definition at line 728 of file FemModule.cc.
References E, nu, and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by startInit(), and test().
_initAlienBsr()
void FemModuleElasticity::_initAlienBsr () private
AI comment: Initializes the Alien BSR (Block Sparse Row) matrix format.
AI-Generated Documentation: Initializes the Alien BSR matrix format
Definition at line 597 of file FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::alienBsr(), Arcane::FemUtils::AlienBSRFormat::initialize(), m_alien_bsr_format, m_dof_per_node, m_dofs_on_nodes, m_linear_system, and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by computeDivU().
_initBsr()
void FemModuleElasticity::_initBsr () private
Initializes BSR matrix.
AI-Generated Documentation: Initializes the BSR matrix format
Definition at line 577 of file FemModule.cc.
References Arcane::FemUtils::BSRFormat::initialize(), m_bsr_format, m_dof_per_node, m_matrix_format, and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by computeDivU().
_solve()
void FemModuleElasticity::_solve () private
Solves the linear system.
AI-Generated Documentation: Solves the assembled linear system
Definition at line 940 of file FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), m_linear_system, and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateTopBoundary()
void FemModuleElasticity::_updateTopBoundary (CellGroup const & new_event)
AI comment: Updates the top boundary face group from new event cells.
AI-Generated Documentation: Updates the top boundary cell group for sedimentation
Definition at line 216 of file FemModule.cc.
References m_event_index, m_geometry_mng, and m_top_z.
Referenced by test().
_updateVariables()
void FemModuleElasticity::_updateVariables () private
Update the FEM variables.
AI-Generated Documentation: Updates time-dependent variables for next step
This method performs the following actions:
Fetches values of solution from solved linear system to FEM variables, i.e., it copies RHS DOF to u.
Performs synchronize of FEM variables across subdomains.
Definition at line 995 of file FemModule.cc.
References m_dofs_on_nodes, m_linear_system, Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModuleElasticity::_validateResults () private
AI comment: Validates computed results against a reference solution file.
AI-Generated Documentation: Validates results against reference values
Definition at line 956 of file FemModule.cc.
References Arcane::FemUtils::checkNodeResultFile(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
computeDivU()
void FemModuleElasticity::computeDivU () override
Performs the main computation for the FemModuleElasticity.
AI-Generated Documentation: Computes the divergence of displacement at each iteration
This method:
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Sets PETSc flags if user has provided them.
Executes the stationary solve.
Definition at line 281 of file FemModule.cc.
References _computePostPro(), _computePrePro(), _doStationarySolve(), _initAlienBsr(), _initBsr(), Arcane::FemUtils::DoFLinearSystem::clearValues(), Arcane::FemUtils::FemDoFsOnNodes::dofFamily(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), Arcane::FemUtils::FemDoFsOnNodes::initialize(), Arcane::FemUtils::DoFLinearSystem::initialize(), m_dof_per_node, m_dofs_on_nodes, m_linear_system, m_matrix_format, m_petsc_flags, ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory(), and Arcane::FemUtils::DoFLinearSystem::setSolverCommandLineArguments().
Referenced by test().
init()
void FemModuleElasticity::init () override
Initializes the FemModuleElasticity at the start of the simulation.
AI-Generated Documentation: Initializes the module
This method initializes degrees of freedom (DoFs) on nodes.
Definition at line 34 of file FemModule.cc.
References ShArc::IDynamicMeshMng::init(), m_cawf_mng, m_dt, m_dynamic_mesh_mng, m_event_index, m_event_period, m_geometry_mng, m_geometry_policy, m_max_iter, m_new_layer_id, m_next_event_time, m_parallel_mng, m_time, m_top_z, and startInit().
reloadOldState()
void FemModuleElasticity::reloadOldState ()
AI comment: Reloads the previously saved state after a failed coupling iteration.
AI-Generated Documentation: Reloads the old state for time stepping
Definition at line 562 of file FemModule.cc.
saveOldState()
void FemModuleElasticity::saveOldState ()
AI comment: Saves the current state for potential rollback in coupled simulations.
AI-Generated Documentation: Saves the old state for time stepping
Definition at line 552 of file FemModule.cc.
startInit()
void FemModuleElasticity::startInit () override
AI comment: Initializes solver parameters, material properties, body force, and node pressure.
AI-Generated Documentation: Method called at the beginning of the simulation
Definition at line 175 of file FemModule.cc.
References _getMaterialParameters(), m_applyBodyForce, m_assemble_linear_system, m_cross_validation, m_dof_per_node, m_F, m_geometry_mng, m_hex_quad_mesh, m_matrix_format, m_petsc_flags, m_solve_linear_system, and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by init().
test()
void FemModuleElasticity::test () override
AI comment: Main time loop, handles coupled (preCICE) and standalone computation modes.
AI-Generated Documentation: Executes the test case at each iteration
Definition at line 333 of file FemModule.cc.
References _getMaterialParameters(), _updateTopBoundary(), computeDivU(), m_applyBodyForce, m_cawf_mng, m_dt, m_dynamic_mesh_mng, m_event_index, m_event_period, m_F, m_geometry_mng, m_geometry_policy, m_iter, m_max_iter, m_new_layer_id, m_next_event_time, m_time, m_top_z, and ShArc::IDynamicMeshMng::updateNewEvent().
versionInfo()
VersionInfo FemModuleElasticity::versionInfo () const inline override
AI-Generated Documentation: Returns the module version
Definition at line 110 of file FemModule.h.
Member Data Documentation
E
Real FemModuleElasticity::E private
AI-Generated Documentation: Young's modulus
Definition at line 158 of file FemModule.h.
Referenced by _getMaterialParameters().
m_activated_layers_uids
UniqueArray<Int64> FemModuleElasticity::m_activated_layers_uids private
AI-Generated Documentation: UIDs of activated layers
Definition at line 216 of file FemModule.h.
m_alien_bsr_format
AlienBSRFormat* FemModuleElasticity::m_alien_bsr_format = nullptr private
AI-Generated Documentation: Alien BSR format (optional, for external solvers)
Definition at line 146 of file FemModule.h.
Referenced by _assembleBilinearOperatorGpu(), _doStationarySolve(), and _initAlienBsr().
m_alien_linear_system
Arcane::FemUtils::AlienDoFLinearSystemImpl* FemModuleElasticity::m_alien_linear_system = nullptr private
AI-Generated Documentation: Alien linear system implementation (optional)
Definition at line 148 of file FemModule.h.
m_applyBodyForce
bool FemModuleElasticity::m_applyBodyForce = false private
AI-Generated Documentation: Whether to apply body forces
Definition at line 165 of file FemModule.h.
Referenced by _applyBodyForce(), startInit(), and test().
m_assemble_linear_system
bool FemModuleElasticity::m_assemble_linear_system = true private
AI-Generated Documentation: Whether to assemble the linear system
Definition at line 176 of file FemModule.h.
Referenced by _doStationarySolve(), and startInit().
m_bsr_format
BSRFormat FemModuleElasticity::m_bsr_format private
AI-Generated Documentation: Block sparse row matrix format for FEM assembly
Definition at line 144 of file FemModule.h.
Referenced by _assembleBilinearOperator(), and _initBsr().
m_cawf_mng
ArcGeoSim::ICAWFMng* FemModuleElasticity::m_cawf_mng = nullptr private
AI-Generated Documentation: CAWF manager
Definition at line 223 of file FemModule.h.
Referenced by init(), and test().
m_cross_validation
bool FemModuleElasticity::m_cross_validation = false private
AI-Generated Documentation: Whether to perform cross-validation
Definition at line 180 of file FemModule.h.
Referenced by _doStationarySolve(), and startInit().
m_dof_dof_connection_index
UniqueArray<Integer> FemModuleElasticity::m_dof_dof_connection_index private
AI-Generated Documentation: DoF-to-DoF connection index array
Definition at line 151 of file FemModule.h.
m_dof_dof_connection_offset
UniqueArray<Integer> FemModuleElasticity::m_dof_dof_connection_offset private
AI-Generated Documentation: DoF-to-DoF connection offset array
Definition at line 153 of file FemModule.h.
m_dof_per_node
Int8 FemModuleElasticity::m_dof_per_node private
AI-Generated Documentation: Number of DoFs per node (2 for 2D, 3 for 3D)
Definition at line 168 of file FemModule.h.
Referenced by _initAlienBsr(), _initBsr(), computeDivU(), and startInit().
m_dofs_on_nodes
FemDoFsOnNodes FemModuleElasticity::m_dofs_on_nodes private
AI-Generated Documentation: Degree-of-freedom mapping on mesh nodes
Definition at line 142 of file FemModule.h.
Referenced by _assembleBilinearOperatorCpu(), _assembleBilinearOperatorGpu(), _assembleDirichletsGpu(), _assembleLinearOperator(), _initAlienBsr(), _updateVariables(), and computeDivU().
m_dt
Real FemModuleElasticity::m_dt = 0. private
AI-Generated Documentation: Current time step size
Definition at line 185 of file FemModule.h.
Referenced by init(), and test().
m_dynamic_mesh_mng
ShArc::IDynamicMeshMng* FemModuleElasticity::m_dynamic_mesh_mng = nullptr private
AI-Generated Documentation: Dynamic mesh manager for sedimentation
Definition at line 221 of file FemModule.h.
Referenced by init(), and test().
m_event_index
Integer FemModuleElasticity::m_event_index = 0 private
AI-Generated Documentation: Current event index
Definition at line 201 of file FemModule.h.
Referenced by _updateTopBoundary(), init(), and test().
m_event_period
Real FemModuleElasticity::m_event_period = 0. private
AI-Generated Documentation: Period between sedimentation events
Definition at line 197 of file FemModule.h.
Referenced by init(), and test().
m_F
Real3 FemModuleElasticity::m_F private
AI-Generated Documentation: Global body force vector
Definition at line 156 of file FemModule.h.
Referenced by startInit(), and test().
m_geometry_mng
IGeometryMng* FemModuleElasticity::m_geometry_mng = nullptr private
AI-Generated Documentation: Geometry manager
Definition at line 225 of file FemModule.h.
Referenced by _computePrePro(), _updateTopBoundary(), init(), startInit(), and test().
m_geometry_policy
NoOptimizationGeometryPolicy FemModuleElasticity::m_geometry_policy private
AI-Generated Documentation: Geometry policy
Definition at line 227 of file FemModule.h.
Referenced by init(), and test().
m_gravity
Real FemModuleElasticity::m_gravity = 9.8 private
AI-Generated Documentation: Gravitational acceleration
Definition at line 193 of file FemModule.h.
m_hex_quad_mesh
bool FemModuleElasticity::m_hex_quad_mesh = false private
AI-Generated Documentation: Whether the mesh uses hex/quad elements
Definition at line 182 of file FemModule.h.
Referenced by _applyBodyForce(), _applyTraction(), _assembleBilinearOperator(), _computePostPro(), _computePrePro(), and startInit().
m_iter
int FemModuleElasticity::m_iter = 0 private
AI-Generated Documentation: Current iteration number
Definition at line 189 of file FemModule.h.
Referenced by test().
m_layer_event_period
Real FemModuleElasticity::m_layer_event_period = 0. private
AI-Generated Documentation: Period for new layer events
Definition at line 210 of file FemModule.h.
m_layer_event_time
Real FemModuleElasticity::m_layer_event_time = 0. private
AI-Generated Documentation: Time of current layer event
Definition at line 212 of file FemModule.h.
m_layers
UniqueArray<Arcane::CellGroup> FemModuleElasticity::m_layers private
AI-Generated Documentation: Array of sediment layer cell groups
Definition at line 208 of file FemModule.h.
m_linear_solver
Alien::ILinearSolver* FemModuleElasticity::m_linear_solver = nullptr private
AI-Generated Documentation: Linear solver for the FEM system
Definition at line 229 of file FemModule.h.
m_linear_system
DoFLinearSystem FemModuleElasticity::m_linear_system private
AI-Generated Documentation: Linear system (matrix + RHS + solution)
Definition at line 140 of file FemModule.h.
Referenced by _applyDirichlet(), _assembleBilinearOperator(), _assembleBilinearOperatorCpu(), _assembleDirichletsGpu(), _assembleLinearOperator(), _doStationarySolve(), _initAlienBsr(), _solve(), _updateVariables(), and computeDivU().
m_matrix_format
String FemModuleElasticity::m_matrix_format = "DOK" private
AI-Generated Documentation: Matrix format type ("DOK", "BSR", "Alien-BSR-Acc")
Definition at line 173 of file FemModule.h.
Referenced by _applyDirichlet(), _assembleBilinearOperator(), _doStationarySolve(), _initBsr(), computeDivU(), and startInit().
m_max_iter
Integer FemModuleElasticity::m_max_iter = 0 private
AI-Generated Documentation: Maximum number of iterations
Definition at line 191 of file FemModule.h.
Referenced by init(), and test().
m_new_layer_id
Integer FemModuleElasticity::m_new_layer_id = 0 private
AI-Generated Documentation: ID for new sediment layers
Definition at line 203 of file FemModule.h.
Referenced by init(), and test().
m_next_event_time
Real FemModuleElasticity::m_next_event_time = 0. private
AI-Generated Documentation: Time of next sedimentation event
Definition at line 199 of file FemModule.h.
Referenced by init(), and test().
m_next_layer_event_time
Real FemModuleElasticity::m_next_layer_event_time = 0. private
AI-Generated Documentation: Time of next layer event
Definition at line 214 of file FemModule.h.
m_parallel_mng
IParallelMng* FemModuleElasticity::m_parallel_mng = nullptr private
AI-Generated Documentation: Parallel communication manager
Definition at line 219 of file FemModule.h.
Referenced by init().
m_petsc_flags
String FemModuleElasticity::m_petsc_flags private
AI-Generated Documentation: PETSc solver flags string
Definition at line 171 of file FemModule.h.
Referenced by computeDivU(), and startInit().
m_precice_mesh_is_updated
bool FemModuleElasticity::m_precice_mesh_is_updated = false private
AI-Generated Documentation: Whether the precice mesh has been updated
Definition at line 205 of file FemModule.h.
m_solve_linear_system
bool FemModuleElasticity::m_solve_linear_system = true private
AI-Generated Documentation: Whether to solve the linear system
Definition at line 178 of file FemModule.h.
Referenced by _doStationarySolve(), and startInit().
m_time
Real FemModuleElasticity::m_time = 0. private
AI-Generated Documentation: Current simulation time
Definition at line 187 of file FemModule.h.
Referenced by init(), and test().
m_top_z
Real FemModuleElasticity::m_top_z = 0. private
AI-Generated Documentation: Top boundary z-coordinate
Definition at line 195 of file FemModule.h.
Referenced by _updateTopBoundary(), init(), and test().
nu
Real FemModuleElasticity::nu private
AI-Generated Documentation: Poisson's ratio
Definition at line 160 of file FemModule.h.
Referenced by _getMaterialParameters().
t
Real3 FemModuleElasticity::t private
AI-Generated Documentation: Traction vector
Definition at line 163 of file FemModule.h.
The documentation for this class was generated from the following files:
src/CAWF/Elasticity/FemModule.h
src/CAWF/Elasticity/BodyForce.h
src/CAWF/Elasticity/Dirichlet.h
src/CAWF/Elasticity/ElementMatrix.h
src/CAWF/Elasticity/ElementMatrixHexQuad.h
src/CAWF/Elasticity/FemModule.cc
src/CAWF/Elasticity/FemModuleSYCL.cc
src/CAWF/Elasticity/Traction.h