ShArc: ArcaneFemFunctions::BoundaryConditions2D Class Reference
ArcaneFemFunctions::BoundaryConditions2D Class Reference
Provides methods for applying boundary conditions in 3D FEM problems.
#include <ArcaneFemFunctions.h>
Static Public Member Functions
static void applyConstantSourceToRhs (Real qdot, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies a constant source term to the RHS vector.
static void applyConstantSourceToRhsQuad4 (Real qdot, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
static void applyManufacturedDirichletToLhsAndRhs (IBinaryMathFunctor< Real, Real3, Real > *manufactured_dirichlet, Real, const FaceGroup &group, BC::IManufacturedSolution *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, DoFLinearSystem &m_linear_system, VariableDoFReal &rhs_values)
Applies Manufactured Dirichlet boundary conditions to RHS and LHS.
static void applyManufacturedSourceToRhs (IBinaryMathFunctor< Real, Real3, Real > *manufactured_source, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies a manufactured source term to the RHS vector.
static void applyNeumannToRhs (BC::INeumannBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies Neumann conditions to the right-hand side (RHS) values.
static void applyNeumannToRhsQuad4 (BC::INeumannBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
static void applyTractionTableToRhsQuad4 (BC::ITractionBoundaryCondition *bs, const Real t, Int32 boundary_condition_index, const UniqueArray< CaseTableInfo > &traction_case_table_list, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
static void applyTractionTableToRhsTria3 (BC::ITractionBoundaryCondition *bs, const Real t, Int32 boundary_condition_index, const UniqueArray< Arcane::FemUtils::CaseTableInfo > &traction_case_table_list, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies trasient traction conditions to the right-hand side (RHS) values.
static void applyTractionToRhsQuad4 (BC::ITractionBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
static void applyTractionToRhsTria3 (BC::ITractionBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies traction conditions to the right-hand side (RHS) values.
static void integrateNodalFieldToRhsQuad4 (VariableNodeReal &field, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies a nodal field to the RHS vector.
static void integrateNodalFieldToRhsTria3 (VariableNodeReal &field, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies a nodal field to the RHS vector.
Detailed Description
Provides methods for applying boundary conditions in 3D FEM problems.
This class includes static methods for applying Neumann boundary conditions to the right-hand side (RHS) of finite element method equations in 3D.
Definition at line 2281 of file ArcaneFemFunctions.h.
Member Function Documentation
applyConstantSourceToRhs()
static void ArcaneFemFunctions::BoundaryConditions2D::applyConstantSourceToRhs (Real qdot, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies a constant source term to the RHS vector.
This method adds a constant source term qdot to the RHS vector for each node in the mesh. The contribution to each node is weighted by the area of the cell and evenly distributed among the number of nodes of the cell.
Parameters
qdot The constant source term.
mesh The mesh containing all cells.
node_dof DOF connectivity view.
node_coord The coordinates of the nodes.
rhs_values The RHS values to update.
Definition at line 2301 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3().
Referenced by FemModulePoisson::_assembleLinearOperatorCpu().
applyConstantSourceToRhsQuad4()
static void ArcaneFemFunctions::BoundaryConditions2D::applyConstantSourceToRhsQuad4 (Real qdot, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Definition at line 2313 of file ArcaneFemFunctions.h.
References M_SQRT1_3.
Referenced by FemModulePoisson::_assembleLinearOperatorCpu().
applyManufacturedDirichletToLhsAndRhs()
static void ArcaneFemFunctions::BoundaryConditions2D::applyManufacturedDirichletToLhsAndRhs (IBinaryMathFunctor< Real, Real3, Real > * manufactured_dirichlet, Real , const FaceGroup & group, BC::IManufacturedSolution * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, DoFLinearSystem & m_linear_system, VariableDoFReal & rhs_values) inline static
Applies Manufactured Dirichlet boundary conditions to RHS and LHS.
Updates the LHS matrix and RHS vector to enforce the Dirichlet.
For LHS matrix 𝐀, the diagonal term for the Dirichlet DOF is set to 𝑃.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
Parameters
manufactured_dirichlet External function for Dirichlet.
group Group of all external faces.
bs Boundary condition values.
node_dof DOF connectivity view.
node_coord Node coordinates.
m_linear_system Linear system for LHS.
rhs_values RHS values to update.
Definition at line 2921 of file ArcaneFemFunctions.h.
References BC::IManufacturedSolution::getPenalty(), and Arcane::FemUtils::DoFLinearSystem::matrixSetValue().
applyManufacturedSourceToRhs()
static void ArcaneFemFunctions::BoundaryConditions2D::applyManufacturedSourceToRhs (IBinaryMathFunctor< Real, Real3, Real > * manufactured_source, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies a manufactured source term to the RHS vector.
This method adds a manufactured source term to the RHS vector for each node in the mesh. The contribution to each node is weighted by the area of the cell and evenly distributed among the nodes of the cell.
Parameters
qdot The constant source term.
mesh The mesh containing all cells.
node_dof DOF connectivity view.
node_coord The coordinates of the nodes.
rhs_values The RHS values to update.
Definition at line 2532 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), and ArcaneFemFunctions::MeshOperation::computeBaryCenterTria3().
applyNeumannToRhs()
static void ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs (BC::INeumannBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies Neumann conditions to the right-hand side (RHS) values.
This method updates the RHS values of the finite element method equations based on the provided Neumann boundary condition. The boundary condition can specify a value or its components along the x and y directions.
Parameters
bs The Neumann boundary condition values.
node_dof Connectivity view for degrees of freedom at nodes.
node_coord Coordinates of the nodes in the mesh.
rhs_values The right-hand side values to be updated.
Definition at line 2561 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeLengthEdge2(), ArcaneFemFunctions::MeshOperation::computeNormalEdge2(), BC::INeumannBoundaryCondition::getSurface(), and BC::INeumannBoundaryCondition::getValue().
Referenced by FemModulePoisson::_assembleLinearOperatorCpu().
applyNeumannToRhsQuad4()
static void ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhsQuad4 (BC::INeumannBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Definition at line 2608 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeLengthEdge2(), ArcaneFemFunctions::MeshOperation::computeNormalEdge2(), BC::INeumannBoundaryCondition::getSurface(), BC::INeumannBoundaryCondition::getValue(), and M_SQRT1_3.
Referenced by FemModulePoisson::_assembleLinearOperatorCpu().
applyTractionTableToRhsQuad4()
static void ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsQuad4 (BC::ITractionBoundaryCondition * bs, const Real t, Int32 boundary_condition_index, const UniqueArray< CaseTableInfo > & traction_case_table_list, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Definition at line 2836 of file ArcaneFemFunctions.h.
References Arcane::FemUtils::CaseTableInfo::case_table, ArcaneFemFunctions::MeshOperation::computeLengthEdge2(), ArcaneFemFunctions::MeshOperation::computeNormalEdge2(), Arcane::FemUtils::CaseTableInfo::file_name, BC::ITractionBoundaryCondition::getSurface(), BC::ITractionBoundaryCondition::getTractionInputFile(), and M_SQRT1_3.
applyTractionTableToRhsTria3()
static void ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsTria3 (BC::ITractionBoundaryCondition * bs, const Real t, Int32 boundary_condition_index, const UniqueArray< Arcane::FemUtils::CaseTableInfo > & traction_case_table_list, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies trasient traction conditions to the right-hand side (RHS) values.
Parameters
bs The traction boundary condition values.
t Time at which traction is applied.
boundary_condition_index Boundary condition index iterator.
traction_case_table_list Traction case table list.
node_dof Connectivity view for dof at nodes.
node_coord Coordinates of the nodes in the mesh.
rhs_values The right-hand side values to be updated.
Definition at line 2796 of file ArcaneFemFunctions.h.
References Arcane::FemUtils::CaseTableInfo::case_table, ArcaneFemFunctions::MeshOperation::computeLengthEdge2(), Arcane::FemUtils::CaseTableInfo::file_name, BC::ITractionBoundaryCondition::getSurface(), and BC::ITractionBoundaryCondition::getTractionInputFile().
applyTractionToRhsQuad4()
static void ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsQuad4 (BC::ITractionBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Definition at line 2722 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeLengthEdge2(), ArcaneFemFunctions::MeshOperation::computeNormalEdge2(), BC::ITractionBoundaryCondition::getSurface(), BC::ITractionBoundaryCondition::getValue(), and M_SQRT1_3.
Referenced by FemModuleElasticity::_applyTraction().
applyTractionToRhsTria3()
static void ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsTria3 (BC::ITractionBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies traction conditions to the right-hand side (RHS) values.
Parameters
bs The traction boundary condition values.
node_dof Connectivity view for degrees of freedom at nodes.
node_coord Coordinates of the nodes in the mesh.
rhs_values The right-hand side values to be updated.
Definition at line 2689 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeLengthEdge2(), BC::ITractionBoundaryCondition::getSurface(), and BC::ITractionBoundaryCondition::getValue().
Referenced by FemModuleElasticity::_applyTraction().
integrateNodalFieldToRhsQuad4()
static void ArcaneFemFunctions::BoundaryConditions2D::integrateNodalFieldToRhsQuad4 (VariableNodeReal & field, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies a nodal field to the RHS vector.
Parameters
field The field term defined on nodes.
mesh The mesh containing all cells.
node_dof DOF connectivity view.
node_coord The coordinates of the nodes.
rhs_values The RHS values to update.
Definition at line 2451 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), and M_SQRT1_3.
integrateNodalFieldToRhsTria3()
static void ArcaneFemFunctions::BoundaryConditions2D::integrateNodalFieldToRhsTria3 (VariableNodeReal & field, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies a nodal field to the RHS vector.
Parameters
field The field term defined on nodes.
mesh The mesh containing all cells.
node_dof DOF connectivity view.
node_coord The coordinates of the nodes.
rhs_values The RHS values to update.
Definition at line 2400 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/ArcaneFemFunctions.h