ShArc: ExpressionService Class Reference
ExpressionService Class Reference
Public Member Functions
ExpressionService (const Arcane::ServiceBuildInfo &sbi)
~ExpressionService ()
void init (ArcRes::System &system, Law::VariableCellFolder &domain)
AI comment: Initializes and evaluates expression-based initial conditions.
void revaluate (ArcRes::System &system, Law::VariableCellFolder &domain)
AI comment: Re-evaluates expression-based conditions (e.g.
Private Member Functions
void _evaluate (ArcRes::System &system, Law::VariableCellFolder &domain)
AI comment: Evaluates the expression-based condition function on all domain cells.
Private Attributes
Gump::ScalarRealProperty m_property
Detailed Description
Definition at line 26 of file ExpressionService.cc.
Constructor & Destructor Documentation
ExpressionService()
ExpressionService::ExpressionService (const Arcane::ServiceBuildInfo & sbi) inline
Definition at line 31 of file ExpressionService.cc.
~ExpressionService()
ExpressionService::~ExpressionService () inline
Definition at line 34 of file ExpressionService.cc.
Member Function Documentation
_evaluate()
void ExpressionService::_evaluate (ArcRes::System & system, Law::VariableCellFolder & domain) private
AI comment: Evaluates the expression-based condition function on all domain cells.
Definition at line 76 of file ExpressionService.cc.
References init(), and m_property.
Referenced by init(), and revaluate().
init()
void ExpressionService::init (ArcRes::System & system, Law::VariableCellFolder & domain)
AI comment: Initializes and evaluates expression-based initial conditions.
Definition at line 56 of file ExpressionService.cc.
References _evaluate().
Referenced by _evaluate().
revaluate()
void ExpressionService::revaluate (ArcRes::System & system, Law::VariableCellFolder & domain)
AI comment: Re-evaluates expression-based conditions (e.g.
after mesh change)
Definition at line 66 of file ExpressionService.cc.
References _evaluate().
Member Data Documentation
m_property
Gump::ScalarRealProperty ExpressionService::m_property private
Definition at line 48 of file ExpressionService.cc.
Referenced by _evaluate().
The documentation for this class was generated from the following file:
src/TwoPhaseFlowSimulation/InitialCondition/Expression/ExpressionService.cc