ShArc: PhysicalModelModule Class Reference
PhysicalModelModule Class Reference
Public Member Functions
PhysicalModelModule (const Arcane::ModuleBuildInfo &mbi)
~PhysicalModelModule ()
void build ()
AI comment: Registers this module as IPhysicalSystem and IVariableManager services.
Law::VariableCellFolder & domain ()
Retourne le gestionnaire des variables.
Law::VariableCellFolder & domainT0 ()
Law::VariableCellFolder & domainTn ()
void exit ()
AI comment: Destroys the Gump physical system model.
void init ()
AI comment: Builds the Gump system and creates domain variable folders.
ArcRes::System system () const
Retourne le systeme physique (retour const impossible.
Arcane::VersionInfo versionInfo () const
Retourne le numero de version du module.
Private Member Functions
void _fatalIfNotInitialized () const
AI comment: Asserts that the physical model has been initialized.
Private Member Functions inherited from IPhysicalSystem
virtual ~IPhysicalSystem ()
Private Member Functions inherited from IVariableManager
virtual ~IVariableManager ()
Private Attributes
Law::VariableCellFolder m_domain
Manager des conteneurs de lois.
Law::VariableCellFolder m_domain_t0
Law::VariableCellFolder m_domain_tn
bool m_initialized
ArcRes::System m_system
Systeme.
Detailed Description
Definition at line 27 of file PhysicalModelModule.cc.
Constructor & Destructor Documentation
PhysicalModelModule()
PhysicalModelModule::PhysicalModelModule (const Arcane::ModuleBuildInfo & mbi) inline
Definition at line 34 of file PhysicalModelModule.cc.
~PhysicalModelModule()
PhysicalModelModule::~PhysicalModelModule () inline
Definition at line 41 of file PhysicalModelModule.cc.
Member Function Documentation
_fatalIfNotInitialized()
void PhysicalModelModule::_fatalIfNotInitialized () const private
AI comment: Asserts that the physical model has been initialized.
Definition at line 87 of file PhysicalModelModule.cc.
References m_initialized.
Referenced by exit(), and system().
build()
void PhysicalModelModule::build ()
AI comment: Registers this module as IPhysicalSystem and IVariableManager services.
Definition at line 98 of file PhysicalModelModule.cc.
domain()
Law::VariableCellFolder& PhysicalModelModule::domain () inline virtual
Retourne le gestionnaire des variables.
Implements IVariableManager.
Definition at line 60 of file PhysicalModelModule.cc.
References m_domain.
domainT0()
Law::VariableCellFolder& PhysicalModelModule::domainT0 () inline virtual
AI-Generated Documentation: Returns the initial-time (t_{0}) variable folder
Implements IVariableManager.
Definition at line 62 of file PhysicalModelModule.cc.
References m_domain_t0.
domainTn()
Law::VariableCellFolder& PhysicalModelModule::domainTn () inline virtual
AI-Generated Documentation: Returns the previous-time (t_{n}) variable folder
Implements IVariableManager.
Definition at line 61 of file PhysicalModelModule.cc.
References m_domain_tn.
exit()
void PhysicalModelModule::exit ()
AI comment: Destroys the Gump physical system model.
Definition at line 145 of file PhysicalModelModule.cc.
References _fatalIfNotInitialized(), and m_system.
init()
void PhysicalModelModule::init () virtual
AI comment: Builds the Gump system and creates domain variable folders.
Implements IPhysicalSystem.
Definition at line 109 of file PhysicalModelModule.cc.
References m_domain, m_domain_t0, m_domain_tn, m_initialized, m_system, and system().
system()
ArcRes::System PhysicalModelModule::system () const virtual
Retourne le systeme physique (retour const impossible.
AI comment: Returns the Gump physical system, asserting it has been initialized.
Implements IPhysicalSystem.
Definition at line 133 of file PhysicalModelModule.cc.
References _fatalIfNotInitialized(), and m_system.
Referenced by init().
versionInfo()
Arcane::VersionInfo PhysicalModelModule::versionInfo () const inline
Retourne le numero de version du module.
Definition at line 53 of file PhysicalModelModule.cc.
Member Data Documentation
m_domain
Law::VariableCellFolder PhysicalModelModule::m_domain private
Manager des conteneurs de lois.
Definition at line 76 of file PhysicalModelModule.cc.
Referenced by domain(), and init().
m_domain_t0
Law::VariableCellFolder PhysicalModelModule::m_domain_t0 private
Definition at line 78 of file PhysicalModelModule.cc.
Referenced by domainT0(), and init().
m_domain_tn
Law::VariableCellFolder PhysicalModelModule::m_domain_tn private
Definition at line 77 of file PhysicalModelModule.cc.
Referenced by domainTn(), and init().
m_initialized
bool PhysicalModelModule::m_initialized private
Definition at line 70 of file PhysicalModelModule.cc.
Referenced by _fatalIfNotInitialized(), and init().
m_system
ArcRes::System PhysicalModelModule::m_system private
Systeme.
Definition at line 73 of file PhysicalModelModule.cc.
Referenced by exit(), init(), and system().
The documentation for this class was generated from the following file:
src/TwoPhaseFlowSimulation/PhysicalSystem/PhysicalModelModule.cc