ShArc: Arcane::FemUtils::Tensor2 Class Reference
Arcane::FemUtils::Tensor2 Class Reference
#include <FemUtils.h>
Public Member Functions
ARCCORE_HOST_DEVICE Tensor2 ()=default
ARCCORE_HOST_DEVICE Tensor2 (const Real3 &a, const Real3 &b)
ARCCORE_HOST_DEVICE Tensor2 (const Real3x3 &mat)
ARCCORE_HOST_DEVICE Tensor2 (const RealVector< 6 > &vec)
ARCCORE_HOST_DEVICE Tensor2 (std::initializer_list< Real > init_list)
ARCCORE_HOST_DEVICE ~Tensor2 ()=default
ARCCORE_HOST_DEVICE void add (const Real3x3 &b)
Substract b to this Tensor2.
ARCCORE_HOST_DEVICE void add (const RealVector< 6 > &b)
Add b to this Tensor2.
ARCCORE_HOST_DEVICE void add (const Tensor2 &b)
Add b to this Tensor2.
ARCCORE_HOST_DEVICE void addInPlace (Real v)
Add v to all the components.
void dump (std::ostream &o) const
Dump values.
ARCCORE_HOST_DEVICE void fromReal3x3ToTensor2 (const Real3x3 &mat)
Function to convert Real3x3 matrix (symmetric) to Tensor.
ARCCORE_HOST_DEVICE Real3 get_diagonal () const
ARCCORE_HOST_DEVICE Real3 get_outdiagonal () const
ARCCORE_HOST_DEVICE RealVector< 6 > getVec () const
ARCCORE_HOST_DEVICE void multInPlace (Real v)
Multiply all the components by v.
ARCCORE_HOST_DEVICE Real norm () const
ARCCORE_HOST_DEVICE operator Real3x3 () const
Convert this Tensor to Real3x3 matrix.
ARCCORE_HOST_DEVICE Real & operator() (Int32 i)
ARCCORE_HOST_DEVICE Real operator() (Int32 i) const
ARCCORE_HOST_DEVICE Real & operator() (Int32 i, Int32 j)
ARCCORE_HOST_DEVICE Real operator() (Int32 i, Int32 j) const
ARCCORE_HOST_DEVICE Tensor2 operator* (Real scalar) const
Scalar multiplication: Tensor * scalar.
ARCCORE_HOST_DEVICE Tensor2 & operator*= (Real scalar)
Define the *= operator.
ARCCORE_HOST_DEVICE Tensor2 operator+ (const Tensor2 &other) const
Define the addition operator.
ARCCORE_HOST_DEVICE Tensor2 & operator+= (const Tensor2 &vec)
Define the += operator.
ARCCORE_HOST_DEVICE Tensor2 operator- () const
Define the unary negation operator.
ARCCORE_HOST_DEVICE Tensor2 operator- (const Tensor2 &other) const
Define the subtraction operator.
ARCCORE_HOST_DEVICE Tensor2 & operator-= (const Tensor2 &vec)
Define the -= operator.
ARCCORE_HOST_DEVICE Tensor2 operator/ (Real scalar) const
Scalar division: Tensor / scalar.
ARCCORE_HOST_DEVICE Tensor2 & operator/= (Real scalar)
Define the *= operator.
ARCCORE_HOST_DEVICE Tensor2 & operator= (const Real3x3 &mat)
Define the = operator.
ARCCORE_HOST_DEVICE Tensor2 & operator= (const Tensor2 &vec)
Define the = operator.
ARCCORE_HOST_DEVICE bool operator== (const Tensor2 &vec)
Define the == operator.
ARCCORE_HOST_DEVICE void set_diagonal (const Real3 &d)
ARCCORE_HOST_DEVICE void set_outdiagonal (const Real3 &s)
ARCCORE_HOST_DEVICE void setEqualTo (const Tensor2 &b)
Set this Tensor2 equal to b.
ARCCORE_HOST_DEVICE void setVec (const Real3 &d, const Real3 &s)
ARCCORE_HOST_DEVICE void sub (const Real3x3 &b)
Substract b to this Tensor2.
ARCCORE_HOST_DEVICE void sub (const RealVector< 6 > &b)
Substract b to this Tensor2.
ARCCORE_HOST_DEVICE void sub (const Tensor2 &b)
Substract b to this Tensor2.
ARCCORE_HOST_DEVICE Real trace () const
Static Public Member Functions
static Arcane::Int32 get_index (Arcane::Int32 i, Arcane::Int32 j)
static Tensor2 identity ()
Return Identity Tensor2.
static constexpr Int32 totalNbElement ()
static Tensor2 zero ()
Return zero Tensor2.
Private Attributes
RealVector< 6 > m_vec
Friends
ARCCORE_HOST_DEVICE friend Real3x3 fromTensor2Real3x3 (const Tensor2 &vector)
Friend function to convert Tensor to Real3x3 matrix.
ARCCORE_HOST_DEVICE friend Tensor2 operator* (Real scalar, const Tensor2 &vector)
Friend function for scalar multiplication: scalar * Tensor.
Detailed Description
Definition at line 643 of file FemUtils.h.
Constructor & Destructor Documentation
Tensor2() [1/5]
ARCCORE_HOST_DEVICE Arcane::FemUtils::Tensor2::Tensor2 () default
Tensor2() [2/5]
ARCCORE_HOST_DEVICE Arcane::FemUtils::Tensor2::Tensor2 (std::initializer_list< Real > init_list) inline
Definition at line 653 of file FemUtils.h.
Tensor2() [3/5]
ARCCORE_HOST_DEVICE Arcane::FemUtils::Tensor2::Tensor2 (const Real3 & a, const Real3 & b) inline
Definition at line 656 of file FemUtils.h.
References m_vec.
Tensor2() [4/5]
ARCCORE_HOST_DEVICE Arcane::FemUtils::Tensor2::Tensor2 (const RealVector< 6 > & vec) inline explicit
Definition at line 659 of file FemUtils.h.
References m_vec.
Tensor2() [5/5]
ARCCORE_HOST_DEVICE Arcane::FemUtils::Tensor2::Tensor2 (const Real3x3 & mat) inline explicit
Definition at line 663 of file FemUtils.h.
References m_vec, and Arcane::FemUtils::real3x3IsSym().
~Tensor2()
ARCCORE_HOST_DEVICE Arcane::FemUtils::Tensor2::~Tensor2 () default
Member Function Documentation
add() [1/3]
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::add (const Real3x3 & b) inline
Substract b to this Tensor2.
Definition at line 807 of file FemUtils.h.
References add().
add() [2/3]
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::add (const RealVector< 6 > & b) inline
Add b to this Tensor2.
Definition at line 813 of file FemUtils.h.
References m_vec.
add() [3/3]
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::add (const Tensor2 & b) inline
Add b to this Tensor2.
Definition at line 802 of file FemUtils.h.
References m_vec.
Referenced by add().
addInPlace()
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::addInPlace (Real v) inline
Add v to all the components.
Definition at line 719 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::addInPlace(), and m_vec.
dump()
void Arcane::FemUtils::Tensor2::dump (std::ostream & o) const inline
Dump values.
Definition at line 722 of file FemUtils.h.
References Arcane::FemUtils::RealVector< N >::dump(), and m_vec.
fromReal3x3ToTensor2()
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::fromReal3x3ToTensor2 (const Real3x3 & mat) inline
Function to convert Real3x3 matrix (symmetric) to Tensor.
Definition at line 901 of file FemUtils.h.
get_diagonal()
ARCCORE_HOST_DEVICE Real3 Arcane::FemUtils::Tensor2::get_diagonal () const inline
Definition at line 877 of file FemUtils.h.
References m_vec.
get_index()
static Arcane::Int32 Arcane::FemUtils::Tensor2::get_index (Arcane::Int32 i, Arcane::Int32 j) inline static
Definition at line 865 of file FemUtils.h.
Referenced by operator()().
get_outdiagonal()
ARCCORE_HOST_DEVICE Real3 Arcane::FemUtils::Tensor2::get_outdiagonal () const inline
Definition at line 885 of file FemUtils.h.
References m_vec.
getVec()
ARCCORE_HOST_DEVICE RealVector<6> Arcane::FemUtils::Tensor2::getVec () const inline
Definition at line 678 of file FemUtils.h.
References m_vec.
identity()
static Tensor2 Arcane::FemUtils::Tensor2::identity () inline static
Return Identity Tensor2.
Definition at line 710 of file FemUtils.h.
multInPlace()
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::multInPlace (Real v) inline
Multiply all the components by v.
Definition at line 716 of file FemUtils.h.
References m_vec, and Arcane::FemUtils::RealVector< N >::multInPlace().
norm()
ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Tensor2::norm () const inline
Definition at line 896 of file FemUtils.h.
References m_vec.
operator Real3x3()
ARCCORE_HOST_DEVICE Arcane::FemUtils::Tensor2::operator Real3x3 () const inline explicit
Convert this Tensor to Real3x3 matrix.
Definition at line 697 of file FemUtils.h.
operator()() [1/4]
ARCCORE_HOST_DEVICE Real& Arcane::FemUtils::Tensor2::operator() (Int32 i) inline
Definition at line 674 of file FemUtils.h.
References m_vec.
operator()() [2/4]
ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Tensor2::operator() (Int32 i) const inline
Definition at line 680 of file FemUtils.h.
References m_vec.
operator()() [3/4]
ARCCORE_HOST_DEVICE Real& Arcane::FemUtils::Tensor2::operator() (Int32 i, Int32 j) inline
Definition at line 684 of file FemUtils.h.
References get_index(), and m_vec.
operator()() [4/4]
ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Tensor2::operator() (Int32 i, Int32 j) const inline
Definition at line 690 of file FemUtils.h.
References get_index(), and m_vec.
operator*()
ARCCORE_HOST_DEVICE Tensor2 Arcane::FemUtils::Tensor2::operator* (Real scalar) const inline
Scalar multiplication: Tensor * scalar.
Definition at line 836 of file FemUtils.h.
References m_vec.
Referenced by operator*=().
operator*=()
ARCCORE_HOST_DEVICE Tensor2& Arcane::FemUtils::Tensor2::operator*= (Real scalar) inline
Define the *= operator.
Definition at line 845 of file FemUtils.h.
References operator*().
operator+()
ARCCORE_HOST_DEVICE Tensor2 Arcane::FemUtils::Tensor2::operator+ (const Tensor2 & other) const inline
Define the addition operator.
Definition at line 750 of file FemUtils.h.
References m_vec.
Referenced by operator+=().
operator+=()
ARCCORE_HOST_DEVICE Tensor2& Arcane::FemUtils::Tensor2::operator+= (const Tensor2 & vec) inline
Define the += operator.
Definition at line 759 of file FemUtils.h.
References operator+().
operator-() [1/2]
ARCCORE_HOST_DEVICE Tensor2 Arcane::FemUtils::Tensor2::operator- () const inline
Define the unary negation operator.
Definition at line 780 of file FemUtils.h.
References m_vec.
Referenced by operator-=().
operator-() [2/2]
ARCCORE_HOST_DEVICE Tensor2 Arcane::FemUtils::Tensor2::operator- (const Tensor2 & other) const inline
Define the subtraction operator.
Definition at line 765 of file FemUtils.h.
References m_vec.
operator-=()
ARCCORE_HOST_DEVICE Tensor2& Arcane::FemUtils::Tensor2::operator-= (const Tensor2 & vec) inline
Define the -= operator.
Definition at line 774 of file FemUtils.h.
References operator-().
operator/()
ARCCORE_HOST_DEVICE Tensor2 Arcane::FemUtils::Tensor2::operator/ (Real scalar) const inline
Scalar division: Tensor / scalar.
Definition at line 851 of file FemUtils.h.
References m_vec.
Referenced by operator/=().
operator/=()
ARCCORE_HOST_DEVICE Tensor2& Arcane::FemUtils::Tensor2::operator/= (Real scalar) inline
Define the *= operator.
Definition at line 860 of file FemUtils.h.
References operator/().
operator=() [1/2]
ARCCORE_HOST_DEVICE Tensor2& Arcane::FemUtils::Tensor2::operator= (const Real3x3 & mat) inline
Define the = operator.
Definition at line 741 of file FemUtils.h.
References m_vec, and Arcane::FemUtils::real3x3IsSym().
operator=() [2/2]
ARCCORE_HOST_DEVICE Tensor2& Arcane::FemUtils::Tensor2::operator= (const Tensor2 & vec) inline
Define the = operator.
Definition at line 735 of file FemUtils.h.
References m_vec.
operator==()
ARCCORE_HOST_DEVICE bool Arcane::FemUtils::Tensor2::operator== (const Tensor2 & vec) inline
Define the == operator.
Definition at line 725 of file FemUtils.h.
References m_vec.
set_diagonal()
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::set_diagonal (const Real3 & d) inline
Definition at line 881 of file FemUtils.h.
References m_vec.
set_outdiagonal()
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::set_outdiagonal (const Real3 & s) inline
Definition at line 888 of file FemUtils.h.
References m_vec.
setEqualTo()
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::setEqualTo (const Tensor2 & b) inline
Set this Tensor2 equal to b.
Definition at line 789 of file FemUtils.h.
References m_vec.
setVec()
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::setVec (const Real3 & d, const Real3 & s) inline
Definition at line 794 of file FemUtils.h.
References m_vec.
sub() [1/3]
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::sub (const Real3x3 & b) inline
Substract b to this Tensor2.
Definition at line 824 of file FemUtils.h.
References sub().
sub() [2/3]
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::sub (const RealVector< 6 > & b) inline
Substract b to this Tensor2.
Definition at line 830 of file FemUtils.h.
References m_vec.
sub() [3/3]
ARCCORE_HOST_DEVICE void Arcane::FemUtils::Tensor2::sub (const Tensor2 & b) inline
Substract b to this Tensor2.
Definition at line 819 of file FemUtils.h.
References m_vec.
Referenced by sub().
totalNbElement()
static constexpr Int32 Arcane::FemUtils::Tensor2::totalNbElement () inline static constexpr
Definition at line 649 of file FemUtils.h.
trace()
ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Tensor2::trace () const inline
Definition at line 892 of file FemUtils.h.
References m_vec.
zero()
static Tensor2 Arcane::FemUtils::Tensor2::zero () inline static
Return zero Tensor2.
Definition at line 712 of file FemUtils.h.
Friends And Related Function Documentation
fromTensor2Real3x3
ARCCORE_HOST_DEVICE friend Real3x3 fromTensor2Real3x3 (const Tensor2 & vector) friend
Friend function to convert Tensor to Real3x3 matrix.
Definition at line 918 of file FemUtils.h.
operator*
ARCCORE_HOST_DEVICE friend Tensor2 operator* (Real scalar, const Tensor2 & vector) friend
Friend function for scalar multiplication: scalar * Tensor.
Definition at line 909 of file FemUtils.h.
Member Data Documentation
m_vec
RealVector<6> Arcane::FemUtils::Tensor2::m_vec private
Definition at line 645 of file FemUtils.h.
Referenced by Tensor2(), add(), addInPlace(), dump(), get_diagonal(), get_outdiagonal(), getVec(), multInPlace(), norm(), operator()(), operator*(), operator+(), operator-(), operator/(), operator=(), operator==(), set_diagonal(), set_outdiagonal(), setEqualTo(), setVec(), sub(), and trace().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/FemUtils.h