ShArc: CapillaryPressureLaw Class Reference
CapillaryPressureLaw Class Reference
Two-Phase Flow
Brooks-Corey capillary pressure law.
#include <FluidDensityLaw.h>
Public Member Functions
CapillaryPressureLaw ()
void eval (const Real S, Real &Pc, Real &dPc_dS) const
AI comment: Evaluates capillary pressure Pc = Pe * Se^(-1/lambda)
void setParameters (const Real Pe, const Real Sr_ref, const Real Sr, const Real lambda)
AI comment: Sets capillary pressure law parameters: entry pressure, residual saturations, exponent.
Private Member Functions
Real computeSe (const Real S, Real &dSe_dS) const
AI comment: Computes effective saturation Se from saturation S and residual saturations.
void initParameters ()
AI comment: Initializes capillary pressure parameters to default values.
Private Attributes
Real m_lambda
Real m_Pe
Real m_Sr
Real m_Sr_ref
Detailed Description
Brooks-Corey capillary pressure law.
AI-Generated Documentation:
Computes capillary pressure \(P_c(S)\) as a function of wetting-phase saturation, using the Brooks-Corey model with entry pressure, residual saturations, and pore-size distribution index. Parameters: entry pressure \(P_e\), reference residual \(S_{r,ref}\), residual saturation \(S_r\), and pore-size index \(\lambda\).
Definition at line 29 of file FluidDensityLaw.h.
Constructor & Destructor Documentation
CapillaryPressureLaw()
CapillaryPressureLaw::CapillaryPressureLaw () inline
AI-Generated Documentation: Constructs the law with default parameters
Definition at line 34 of file FluidDensityLaw.h.
References initParameters().
Member Function Documentation
computeSe()
Real CapillaryPressureLaw::computeSe (const Real S, Real & dSe_dS) const private
AI comment: Computes effective saturation Se from saturation S and residual saturations.
AI-Generated Documentation: Computes effective saturation
\(S_e = (S - S_r) / (1 - S_r - S_{r,ref})\)
and its derivative
Definition at line 45 of file CapillaryPressureLaw.cc.
References m_Sr, and m_Sr_ref.
Referenced by eval().
eval()
void CapillaryPressureLaw::eval (const Real S, Real & Pc, Real & dPc_dS) const
AI comment: Evaluates capillary pressure Pc = Pe * Se^(-1/lambda)
AI-Generated Documentation: Evaluates capillary pressure and its derivative
Parameters
S Wetting-phase saturation
Pc Capillary pressure
dPc_dS Derivative of Pc with respect to S
Definition at line 23 of file CapillaryPressureLaw.cc.
References computeSe(), m_lambda, and m_Pe.
Referenced by CapillaryPressureLawConfigService::configure().
initParameters()
void CapillaryPressureLaw::initParameters () private
AI comment: Initializes capillary pressure parameters to default values.
AI-Generated Documentation: Initializes parameters to default values
Definition at line 71 of file CapillaryPressureLaw.cc.
References setParameters().
Referenced by CapillaryPressureLaw().
setParameters()
void CapillaryPressureLaw::setParameters (const Real Pe, const Real Sr_ref, const Real Sr, const Real lambda)
AI comment: Sets capillary pressure law parameters: entry pressure, residual saturations, exponent.
AI-Generated Documentation: Sets the law parameters
Parameters
Pe Entry pressure
Sr_ref Reference residual saturation
Sr Residual saturation
lambda Pore-size distribution index
Definition at line 58 of file CapillaryPressureLaw.cc.
References m_lambda, m_Pe, m_Sr, and m_Sr_ref.
Referenced by CapillaryPressureLawConfigService::configure(), and initParameters().
Member Data Documentation
m_lambda
Real CapillaryPressureLaw::m_lambda private
AI-Generated Documentation: Pore-size distribution index
Definition at line 71 of file FluidDensityLaw.h.
Referenced by eval(), and setParameters().
m_Pe
Real CapillaryPressureLaw::m_Pe private
AI-Generated Documentation: Entry pressure
Definition at line 65 of file FluidDensityLaw.h.
Referenced by eval(), and setParameters().
m_Sr
Real CapillaryPressureLaw::m_Sr private
AI-Generated Documentation: Residual saturation
Definition at line 69 of file FluidDensityLaw.h.
Referenced by computeSe(), and setParameters().
m_Sr_ref
Real CapillaryPressureLaw::m_Sr_ref private
AI-Generated Documentation: Reference residual saturation
Definition at line 67 of file FluidDensityLaw.h.
Referenced by computeSe(), and setParameters().
The documentation for this class was generated from the following files:
src/TwoPhaseFlowSimulation/PhysicalLaws/CapillaryPressureLaw/FluidDensityLaw.h
src/TwoPhaseFlowSimulation/PhysicalLaws/CapillaryPressureLaw/CapillaryPressureLaw.cc