ShArc: WellIndexComputer Class Reference
WellIndexComputer Class Reference
Two-Phase Flow
Computes Peaceman well indices for well-cell connections.
#include <WellIndexComputer.h>
Public Member Functions
WellIndexComputer (IMesh *mesh)
void compute (ArcRes::System &system, Law::VariableCellFolder &domain, Arcane::PartialVariableCellReal well_index, Arcane::Real radius, Arcane::Real skin) const
Private Member Functions
Arcane::Real3 _computeCellThickness (const Arcane::Cell &cell) const
Arcane::Real _computeWellIndex (const Arcane::Real3 &cell_dims, const Arcane::Real3 &cell_perm, const Arcane::Real &well_radius, const Arcane::Real &well_skin) const
Private Attributes
const Arcane::VariableNodeReal3 & m_node_coordinates
Arcane::Real m_pi
Detailed Description
Computes Peaceman well indices for well-cell connections.
AI-Generated Documentation:
Implements the Peaceman (1983) well index formula for 3D anisotropic permeability fields. The well index relates the wellbore pressure to the cell-averaged pressure for inflow/outflow calculations.
Formula: \(WI = \frac{2\pi \sqrt{k_x k_y} \Delta z}{\ln(r_e / r_w) + s}\) where \(r_e\) is the Peaceman equivalent radius, \(r_w\) the wellbore radius, and \(s\) the skin factor.
Definition at line 40 of file WellIndexComputer.h.
Constructor & Destructor Documentation
WellIndexComputer()
WellIndexComputer::WellIndexComputer (IMesh * mesh)
AI-Generated Documentation: Constructs the computer with mesh node coordinates
Definition at line 8 of file WellIndexComputer.cc.
Member Function Documentation
_computeCellThickness()
Arcane::Real3 WellIndexComputer::_computeCellThickness (const Arcane::Cell & cell) const inline private
Definition at line 180 of file WellIndexComputer.h.
References m_node_coordinates.
Referenced by compute().
_computeWellIndex()
Arcane::Real WellIndexComputer::_computeWellIndex (const Arcane::Real3 & cell_dims, const Arcane::Real3 & cell_perm, const Arcane::Real & well_radius, const Arcane::Real & well_skin) const inline private
AI-Generated Documentation: Computes the Peaceman well index for a single cell
Definition at line 89 of file WellIndexComputer.h.
References m_pi.
Referenced by compute().
compute()
void WellIndexComputer::compute (ArcRes::System & system, Law::VariableCellFolder & domain, Arcane::PartialVariableCellReal well_index, Arcane::Real radius, Arcane::Real skin) const
AI-Generated Documentation: Computes well indices for all wells in the system
Parameters
system The ArcRes system
domain Cell variable folder
well_index Output well index variable
radius Wellbore radius
skin Skin factor
Definition at line 16 of file WellIndexComputer.cc.
References _computeCellThickness(), and _computeWellIndex().
Referenced by WellManagerService::init().
Member Data Documentation
m_node_coordinates
const Arcane::VariableNodeReal3& WellIndexComputer::m_node_coordinates private
AI-Generated Documentation: Mesh node coordinates
Definition at line 82 of file WellIndexComputer.h.
Referenced by _computeCellThickness().
m_pi
Arcane::Real WellIndexComputer::m_pi private
AI-Generated Documentation: Pi constant
Definition at line 79 of file WellIndexComputer.h.
Referenced by _computeWellIndex().
The documentation for this class was generated from the following files:
src/TwoPhaseFlowSimulation/WellCondition/Well/WellIndexComputer.h
src/TwoPhaseFlowSimulation/WellCondition/Well/WellIndexComputer.cc