ShArc: ConstantService Class Reference
ConstantService Class Reference
Public Member Functions
ConstantService (const Arcane::ServiceBuildInfo &sbi)
~ConstantService ()
void init (ArcRes::System &system, Law::VariableCellFolder &domain)
AI comment: Initializes and evaluates constant-value conditions on the domain.
void revaluate (ArcRes::System &system, Law::VariableCellFolder &domain)
AI comment: Re-evaluates constant conditions (e.g.
Private Member Functions
void _evaluate (ArcRes::System &system, Law::VariableCellFolder &domain)
AI comment: Parses and evaluates constant value expressions for the selected property.
void _fatalIfNotInitialized () const
AI comment: Asserts that the constant initial condition service has been initialized.
Private Attributes
bool m_initialized
Gump::ScalarRealProperty m_property
Detailed Description
Definition at line 38 of file ConstantService.cc.
Constructor & Destructor Documentation
ConstantService()
ConstantService::ConstantService (const Arcane::ServiceBuildInfo & sbi) inline
Definition at line 43 of file ConstantService.cc.
~ConstantService()
ConstantService::~ConstantService () inline
Definition at line 47 of file ConstantService.cc.
Member Function Documentation
_evaluate()
void ConstantService::_evaluate (ArcRes::System & system, Law::VariableCellFolder & domain) private
AI comment: Parses and evaluates constant value expressions for the selected property.
Definition at line 108 of file ConstantService.cc.
References m_property.
Referenced by init(), and revaluate().
_fatalIfNotInitialized()
void ConstantService::_fatalIfNotInitialized () const private
AI comment: Asserts that the constant initial condition service has been initialized.
Definition at line 73 of file ConstantService.cc.
References m_initialized.
init()
void ConstantService::init (ArcRes::System & system, Law::VariableCellFolder & domain)
AI comment: Initializes and evaluates constant-value conditions on the domain.
Definition at line 84 of file ConstantService.cc.
References _evaluate(), and m_initialized.
revaluate()
void ConstantService::revaluate (ArcRes::System & system, Law::VariableCellFolder & domain)
AI comment: Re-evaluates constant conditions (e.g.
after mesh change)
Definition at line 98 of file ConstantService.cc.
References _evaluate().
Member Data Documentation
m_initialized
bool ConstantService::m_initialized private
Definition at line 63 of file ConstantService.cc.
Referenced by _fatalIfNotInitialized(), and init().
m_property
Gump::ScalarRealProperty ConstantService::m_property private
Definition at line 65 of file ConstantService.cc.
Referenced by _evaluate().
The documentation for this class was generated from the following file:
src/TwoPhaseFlowSimulation/InitialCondition/Constant/ConstantService.cc