ShArc: Arcane::FemUtils::DoFLinearSystemRowEliminationHelper Class Reference
Arcane::FemUtils::DoFLinearSystemRowEliminationHelper Class Reference
Helper class to handle Row elimination.
#include <DoFLinearSystem.h>
Public Member Functions
~DoFLinearSystemRowEliminationHelper ()
void addElimination (DoFLocalId row, Real value)
AI generated: Mark a row for elimination (sets row to identity and RHS to value)
VariableDoFByte & getEliminationInfo ()
AI generated: Returns the variable tracking elimination info for each DoF.
VariableDoFReal & getEliminationValue ()
AI generated: Returns the variable tracking elimination values for each DoF.
Private Member Functions
DoFLinearSystemRowEliminationHelper (DoFLinearSystem *dof_ls)
Private Attributes
friend DoFLinearSystem
DoFLinearSystem * m_dof_linear_system = nullptr
Detailed Description
Helper class to handle Row elimination.
Instances of this class are temporary and are created via a call to DoFLinearSystem::rowEliminationHelper().
There is two ways to use this class.
use the method addElimination() and specify the row and the value
get the variables handling elimination info (getEliminationInfo()) and elimination value (getEliminationValue()) and set the corresponding row with ELIMINATION_ROW and the value of the elimination.
Only the method 2 is available on accelerator. AI generated: Helper class for row elimination in a linear system
Definition at line 48 of file DoFLinearSystem.h.
Constructor & Destructor Documentation
DoFLinearSystemRowEliminationHelper()
Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::DoFLinearSystemRowEliminationHelper (DoFLinearSystem * dof_ls) explicit private
Definition at line 699 of file DoFLinearSystem.cc.
~DoFLinearSystemRowEliminationHelper()
Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::~DoFLinearSystemRowEliminationHelper ()
Definition at line 708 of file DoFLinearSystem.cc.
Member Function Documentation
addElimination()
void Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::addElimination (DoFLocalId row, Real value)
AI generated: Mark a row for elimination (sets row to identity and RHS to value)
Definition at line 715 of file DoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystem::_eliminateRow(), and m_dof_linear_system.
Referenced by ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowElimination().
getEliminationInfo()
VariableDoFByte & Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::getEliminationInfo ()
AI generated: Returns the variable tracking elimination info for each DoF.
Definition at line 724 of file DoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystem::_getEliminationInfo(), and m_dof_linear_system.
Referenced by Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowOrRowColumnElimination().
getEliminationValue()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::getEliminationValue ()
AI generated: Returns the variable tracking elimination values for each DoF.
Definition at line 733 of file DoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystem::_getEliminationValue(), and m_dof_linear_system.
Referenced by Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowOrRowColumnElimination().
Member Data Documentation
DoFLinearSystem
friend Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::DoFLinearSystem private
Definition at line 50 of file DoFLinearSystem.h.
m_dof_linear_system
DoFLinearSystem* Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::m_dof_linear_system = nullptr private
Definition at line 72 of file DoFLinearSystem.h.
Referenced by addElimination(), getEliminationInfo(), and getEliminationValue().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/DoFLinearSystem.h
src/CAWF/FEMUtils/DoFLinearSystem.cc