ShArc: Arcane::FemUtils::DoFLinearSystem Class Reference
Arcane::FemUtils::DoFLinearSystem Class Reference
Linear system Matrix A + Vector x + Vector b for Ax=b.
#include <DoFLinearSystem.h>
Public Member Functions
DoFLinearSystem ()
DoFLinearSystem (const DoFLinearSystem &)=delete
DoFLinearSystem (DoFLinearSystem &&)=delete
~DoFLinearSystem ()
AlienBSRFormat * alienBsr (ITraceMng *trace_mng, RunQueue &queue, FemDoFsOnNodes &dofs_on_nodes)
void applyLinearSystemTransformationAndSolve ()
Apply the underlying transformation and Solve the current linear system.
void applyMatrixTransformation ()
Apply Matrix Transformation.
void applyRHSTransformation ()
Apply RHS Transformation.
void clearValues ()
Clear values.
void endSystemAssembly ()
CSRFormatView & getCSRValues ()
VariableDoFBool & getForcedInfo ()
VariableDoFReal & getForcedValue ()
bool hasSetCSRValues () const
Indique si l'implémentation supporte d'utiliser setCSRValue()
void initialize (ISubDomain *sd, IItemFamily *dof_family, const String &solver_name)
void initialize (ISubDomain *sd, Runner *runner, IItemFamily *dof_family, const String &solver_name)
Initialize the instance with a specific runner.
bool isInitialized () const
Indicate if method initialize() has been called.
bool isMatrixSparsityConstant ()
Getter de l'attribut m_constant_matrix_sparsity.
bool isMatrixValuesConstant ()
Getter de l'attribut m_constant_matrix_values.
IDoFLinearSystemFactory * linearSystemFactory () const
void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value)
Add the value value to the (row,column) element of the matrix.
void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value)
Set the value value to the (row,column) element of the matrix.
DoFLinearSystem & operator= (const DoFLinearSystem &)=delete
DoFLinearSystem & operator= (DoFLinearSystem &&)=delete
void reset ()
Reset the current instance.
VariableDoFReal & rhsVariable ()
Variable containing the right hand side vector.
DoFLinearSystemRowColumnEliminationHelper rowColumnEliminationHelper ()
DoFLinearSystemRowEliminationHelper rowEliminationHelper ()
void setConstantMatrixSparsity (bool val)
Setter de l'attribut m_constant_matrix_sparsity.
void setConstantMatrixValues (bool val)
Setter de l'attribut m_constant_matrix_values.
void setCSRValues (const CSRFormatView &csr_view)
Positionne directement les valeurs de la matrice.
void setLinearSystemFactory (IDoFLinearSystemFactory *factory)
Set the factory used to create the underlying linear system solver.
void setSolverCommandLineArguments (const CommandLineArguments &args)
VariableDoFReal & solutionVariable ()
Variable containing the solution vector.
void solve ()
Solve the current linear system.
void startSystemAssembly ()
Private Member Functions
void _checkInit () const
void _eliminateRow (DoFLocalId row, Real value)
void _eliminateRowColumn (DoFLocalId row, Real value)
VariableDoFByte & _getEliminationInfo ()
VariableDoFReal & _getEliminationValue ()
Private Attributes
friend DoFLinearSystemRowColumnEliminationHelper
friend DoFLinearSystemRowEliminationHelper
IDoFLinearSystemFactory * m_default_linear_system_factory = nullptr
IItemFamily * m_item_family = nullptr
IDoFLinearSystemFactory * m_linear_system_factory = nullptr
IDoFLinearSystemImpl * m_p = nullptr
Detailed Description
Linear system Matrix A + Vector x + Vector b for Ax=b.
Before using an instance of this class you need to call method initialize(). If you want to reuse the same instance for several solving you need to call reset() to destroy the underlying linear system and then you need to call initialize() again.
The solve() method solves the current linear system. After this variable returned by the method solutionVariable() will be filled with the values of the solution vector.
Definition at line 154 of file DoFLinearSystem.h.
Constructor & Destructor Documentation
DoFLinearSystem() [1/3]
Arcane::FemUtils::DoFLinearSystem::DoFLinearSystem ()
Definition at line 341 of file DoFLinearSystem.cc.
~DoFLinearSystem()
Arcane::FemUtils::DoFLinearSystem::~DoFLinearSystem ()
Definition at line 349 of file DoFLinearSystem.cc.
References m_default_linear_system_factory, and m_p.
DoFLinearSystem() [2/3]
Arcane::FemUtils::DoFLinearSystem::DoFLinearSystem (const DoFLinearSystem &) delete
DoFLinearSystem() [3/3]
Arcane::FemUtils::DoFLinearSystem::DoFLinearSystem (DoFLinearSystem &&) delete
Member Function Documentation
_checkInit()
void Arcane::FemUtils::DoFLinearSystem::_checkInit () const private
Definition at line 359 of file DoFLinearSystem.cc.
References m_p.
Referenced by _getEliminationInfo(), _getEliminationValue(), alienBsr(), applyMatrixTransformation(), applyRHSTransformation(), clearValues(), endSystemAssembly(), getCSRValues(), getForcedInfo(), getForcedValue(), hasSetCSRValues(), isMatrixSparsityConstant(), isMatrixValuesConstant(), matrixAddValue(), matrixSetValue(), rhsVariable(), rowColumnEliminationHelper(), rowEliminationHelper(), setConstantMatrixSparsity(), setConstantMatrixValues(), setCSRValues(), setSolverCommandLineArguments(), solutionVariable(), solve(), and startSystemAssembly().
_eliminateRow()
void Arcane::FemUtils::DoFLinearSystem::_eliminateRow (DoFLocalId row, Real value) private
Definition at line 450 of file DoFLinearSystem.cc.
References Arcane::FemUtils::IDoFLinearSystemImpl::eliminateRow(), and m_p.
Referenced by Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::addElimination().
_eliminateRowColumn()
void Arcane::FemUtils::DoFLinearSystem::_eliminateRowColumn (DoFLocalId row, Real value) private
Definition at line 459 of file DoFLinearSystem.cc.
References Arcane::FemUtils::IDoFLinearSystemImpl::eliminateRowColumn(), and m_p.
Referenced by Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::addElimination().
_getEliminationInfo()
VariableDoFByte & Arcane::FemUtils::DoFLinearSystem::_getEliminationInfo () private
Definition at line 596 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::getEliminationInfo(), and m_p.
Referenced by Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::getEliminationInfo(), and Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::getEliminationInfo().
_getEliminationValue()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystem::_getEliminationValue () private
Definition at line 606 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::getEliminationValue(), and m_p.
Referenced by Arcane::FemUtils::DoFLinearSystemRowEliminationHelper::getEliminationValue(), and Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::getEliminationValue().
alienBsr()
AlienBSRFormat * Arcane::FemUtils::DoFLinearSystem::alienBsr (ITraceMng * trace_mng, RunQueue & queue, FemDoFsOnNodes & dofs_on_nodes)
Definition at line 417 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::AlienDoFLinearSystemImpl::bsr(), and m_p.
Referenced by FemModuleElasticity::_initAlienBsr().
applyLinearSystemTransformationAndSolve()
void Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve ()
Apply the underlying transformation and Solve the current linear system.
This is equivalent to calling the following methods in order:
applyMatrixTransformation()
applyRHSTransformation()
solve()
Definition at line 518 of file DoFLinearSystem.cc.
References applyMatrixTransformation(), applyRHSTransformation(), and solve().
Referenced by FemModuleElasticity::_solve(), and FemModulePoisson::_solve().
applyMatrixTransformation()
void Arcane::FemUtils::DoFLinearSystem::applyMatrixTransformation ()
Apply Matrix Transformation.
Apply operation like Row or RowColumn elimination on the matrix. This has to be done one and only time before calling solve(). If the values of the matrix are cleared, this method has to be called again.
Definition at line 498 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::applyMatrixTransformation(), and m_p.
Referenced by applyLinearSystemTransformationAndSolve().
applyRHSTransformation()
void Arcane::FemUtils::DoFLinearSystem::applyRHSTransformation ()
Apply RHS Transformation.
Apply operation like Row or RowColumn elimination on the RHS. This method has to be called at least one time calling solve(). You may call this method several time if you have manually changed the values of the RHS.
Definition at line 508 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::applyRHSTransformation(), and m_p.
Referenced by applyLinearSystemTransformationAndSolve().
clearValues()
void Arcane::FemUtils::DoFLinearSystem::clearValues ()
Clear values.
After this call, the matrix and the RHS vector will have their values cleared.
Definition at line 637 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::clearValues(), and m_p.
Referenced by FemModuleElasticity::computeDivU().
endSystemAssembly()
void Arcane::FemUtils::DoFLinearSystem::endSystemAssembly ()
Definition at line 409 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::AlienDoFLinearSystemImpl::endSystemAssembly(), and m_p.
Referenced by FemModuleElasticity::_doStationarySolve().
getCSRValues()
CSRFormatView & Arcane::FemUtils::DoFLinearSystem::getCSRValues ()
Definition at line 569 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::getCSRValues(), and m_p.
getForcedInfo()
VariableDoFBool & Arcane::FemUtils::DoFLinearSystem::getForcedInfo ()
Definition at line 587 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::getForcedInfo(), and m_p.
Referenced by FemModulePoisson::_assembleLinearOperatorGpu(), Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupRhsOnly(), and Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty().
getForcedValue()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystem::getForcedValue ()
Definition at line 578 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::getForcedValue(), and m_p.
Referenced by Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty().
hasSetCSRValues()
bool Arcane::FemUtils::DoFLinearSystem::hasSetCSRValues () const
Indique si l'implémentation supporte d'utiliser setCSRValue()
Definition at line 616 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::hasSetCSRValues(), and m_p.
Referenced by Arcane::FemUtils::BSRFormat::toLinearSystem(), and Arcane::FemUtils::CsrFormat::translateToLinearSystem().
initialize() [1/2]
void Arcane::FemUtils::DoFLinearSystem::initialize (ISubDomain * sd, IItemFamily * dof_family, const String & solver_name)
Definition at line 392 of file DoFLinearSystem.cc.
Referenced by FemModulePoisson::compute(), and FemModuleElasticity::computeDivU().
initialize() [2/2]
void Arcane::FemUtils::DoFLinearSystem::initialize (ISubDomain * sd, Runner * runner, IItemFamily * dof_family, const String & solver_name)
Initialize the instance with a specific runner.
runner may be null.
Definition at line 369 of file DoFLinearSystem.cc.
References Arcane::FemUtils::IDoFLinearSystemFactory::createInstance(), m_default_linear_system_factory, m_item_family, m_linear_system_factory, m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::setRunner().
isInitialized()
bool Arcane::FemUtils::DoFLinearSystem::isInitialized () const
Indicate if method initialize() has been called.
Definition at line 647 of file DoFLinearSystem.cc.
References m_p.
isMatrixSparsityConstant()
bool Arcane::FemUtils::DoFLinearSystem::isMatrixSparsityConstant ()
Getter de l'attribut m_constant_matrix_sparsity.
Indique si la matrice du système linéaire change de sparsité (disposition des nnz) entre les appels à la fonction solve(). Cela permet des optimisations en termes d'allocations de mémoire, par exemple en allouant la matrice une seule fois avant les solving plutôt qu'à chaque appel de solve(). L'attribut est par défaut initialisé à false.
Definition at line 676 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::isMatrixSparsityConstant(), and m_p.
isMatrixValuesConstant()
bool Arcane::FemUtils::DoFLinearSystem::isMatrixValuesConstant ()
Getter de l'attribut m_constant_matrix_values.
Indique si la matrice du système linéaire change de valeurs entre les appels à la fonction solve(). Cela permet certaines optimisations en termes de copie de valeurs. L'attribut est par défaut initialisé à false.
Definition at line 686 of file DoFLinearSystem.cc.
References _checkInit(), Arcane::FemUtils::IDoFLinearSystemImpl::isMatrixValuesConstant(), and m_p.
linearSystemFactory()
IDoFLinearSystemFactory* Arcane::FemUtils::DoFLinearSystem::linearSystemFactory () const inline
Definition at line 390 of file DoFLinearSystem.h.
References m_linear_system_factory.
matrixAddValue()
void Arcane::FemUtils::DoFLinearSystem::matrixAddValue (DoFLocalId row, DoFLocalId column, Real value)
Add the value value to the (row,column) element of the matrix.
Definition at line 430 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::matrixAddValue().
Referenced by FemModulePoisson::_assembleBilinear(), FemModuleElasticity::_assembleBilinearOperatorCpu(), Arcane::FemUtils::AlienBSRMatrix::toLinearSystem(), Arcane::FemUtils::BSRMatrix::toLinearSystem(), Arcane::FemUtils::CooFormat::translateToLinearSystem(), and Arcane::FemUtils::CsrFormat::translateToLinearSystem().
matrixSetValue()
void Arcane::FemUtils::DoFLinearSystem::matrixSetValue (DoFLocalId row, DoFLocalId column, Real value)
Set the value value to the (row,column) element of the matrix.
The value is only changed when solve() is called. Any call to matrixAddValue(row,column) done before or after the call to matrixSetValue(row,column) are discarded.
Definition at line 440 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::matrixSetValue().
Referenced by ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty(), ArcaneFemFunctions::BoundaryConditions3D::applyManufacturedDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions2D::applyManufacturedDirichletToLhsAndRhs().
operator=() [1/2]
DoFLinearSystem& Arcane::FemUtils::DoFLinearSystem::operator= (const DoFLinearSystem &) delete
operator=() [2/2]
DoFLinearSystem& Arcane::FemUtils::DoFLinearSystem::operator= (DoFLinearSystem &&) delete
reset()
void Arcane::FemUtils::DoFLinearSystem::reset ()
Reset the current instance.
You have to call initialize() again to re-use the same instance.
Definition at line 626 of file DoFLinearSystem.cc.
References m_item_family, and m_p.
Referenced by FemModulePoisson::compute(), and FemModuleElasticity::computeDivU().
rhsVariable()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystem::rhsVariable ()
Variable containing the right hand side vector.
The values of this variable will be used during the solve() call to fill the right hand side vector.
Definition at line 539 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::rhsVariable().
Referenced by FemModuleElasticity::_assembleLinearOperator(), FemModulePoisson::_assembleLinearOperatorCpu(), FemModulePoisson::_assembleLinearOperatorGpu(), Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupRhsOnly(), and Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty().
rowColumnEliminationHelper()
DoFLinearSystemRowColumnEliminationHelper Arcane::FemUtils::DoFLinearSystem::rowColumnEliminationHelper ()
Definition at line 478 of file DoFLinearSystem.cc.
References _checkInit(), and DoFLinearSystemRowColumnEliminationHelper.
Referenced by ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowColumnElimination().
rowEliminationHelper()
DoFLinearSystemRowEliminationHelper Arcane::FemUtils::DoFLinearSystem::rowEliminationHelper ()
Definition at line 468 of file DoFLinearSystem.cc.
References _checkInit(), and DoFLinearSystemRowEliminationHelper.
Referenced by ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowElimination(), and Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowOrRowColumnElimination().
setConstantMatrixSparsity()
void Arcane::FemUtils::DoFLinearSystem::setConstantMatrixSparsity (bool val)
Setter de l'attribut m_constant_matrix_sparsity.
Indique si la matrice du système linéaire change de sparsité (disposition des nnz) entre les appels à la fonction solve(). Cela permet des optimisations en termes d'allocations de mémoire, par exemple en allouant la matrice une seule fois avant les solving plutôt qu'à chaque appel de solve(). L'attribut est par défaut initialisé à false.
Definition at line 656 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::setConstantMatrixSparsity().
setConstantMatrixValues()
void Arcane::FemUtils::DoFLinearSystem::setConstantMatrixValues (bool val)
Setter de l'attribut m_constant_matrix_values.
Indique si la matrice du système linéaire change de valeurs entre les appels à la fonction solve(). Cela permet certaines optimisations en termes de copie de valeurs. L'attribut est par défaut initialisé à false.
Definition at line 666 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::setConstantMatrixValues().
setCSRValues()
void Arcane::FemUtils::DoFLinearSystem::setCSRValues (const CSRFormatView & csr_view)
Positionne directement les valeurs de la matrice.
Positionne les valeurs de la matrice en considérant le format comme étant au format CSR. Les vues doivent rester valides jusqu'à la résolution du système linéaire (appel à solve()).
Definition at line 559 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::setCSRValues().
Referenced by Arcane::FemUtils::BSRFormat::toLinearSystem(), and Arcane::FemUtils::CsrFormat::translateToLinearSystem().
setLinearSystemFactory()
void Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory (IDoFLinearSystemFactory * factory) inline
Set the factory used to create the underlying linear system solver.
Definition at line 298 of file DoFLinearSystem.h.
References m_linear_system_factory.
Referenced by FemModulePoisson::compute(), and FemModuleElasticity::computeDivU().
setSolverCommandLineArguments()
void Arcane::FemUtils::DoFLinearSystem::setSolverCommandLineArguments (const CommandLineArguments & args)
Definition at line 549 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::setSolverCommandLineArguments().
Referenced by FemModulePoisson::compute(), and FemModuleElasticity::computeDivU().
solutionVariable()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystem::solutionVariable ()
Variable containing the solution vector.
The values of this variable are only relevant after a call to solve().
Definition at line 529 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::solutionVariable().
Referenced by FemModuleElasticity::_updateVariables(), and FemModulePoisson::_updateVariables().
solve()
void Arcane::FemUtils::DoFLinearSystem::solve ()
Solve the current linear system.
You have to call applyMatrixTransformation() and applyRHSTransformation() before calling this method().
Definition at line 488 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::IDoFLinearSystemImpl::solve().
Referenced by applyLinearSystemTransformationAndSolve().
startSystemAssembly()
void Arcane::FemUtils::DoFLinearSystem::startSystemAssembly ()
Definition at line 400 of file DoFLinearSystem.cc.
References _checkInit(), m_p, and Arcane::FemUtils::AlienDoFLinearSystemImpl::startSystemAssembly().
Referenced by FemModuleElasticity::_doStationarySolve().
Member Data Documentation
DoFLinearSystemRowColumnEliminationHelper
friend Arcane::FemUtils::DoFLinearSystem::DoFLinearSystemRowColumnEliminationHelper private
Definition at line 157 of file DoFLinearSystem.h.
Referenced by rowColumnEliminationHelper().
DoFLinearSystemRowEliminationHelper
friend Arcane::FemUtils::DoFLinearSystem::DoFLinearSystemRowEliminationHelper private
Definition at line 156 of file DoFLinearSystem.h.
Referenced by rowEliminationHelper().
m_default_linear_system_factory
IDoFLinearSystemFactory* Arcane::FemUtils::DoFLinearSystem::m_default_linear_system_factory = nullptr private
Definition at line 400 of file DoFLinearSystem.h.
Referenced by ~DoFLinearSystem(), and initialize().
m_item_family
IItemFamily* Arcane::FemUtils::DoFLinearSystem::m_item_family = nullptr private
Definition at line 398 of file DoFLinearSystem.h.
Referenced by initialize(), and reset().
m_linear_system_factory
IDoFLinearSystemFactory* Arcane::FemUtils::DoFLinearSystem::m_linear_system_factory = nullptr private
Definition at line 399 of file DoFLinearSystem.h.
Referenced by initialize(), linearSystemFactory(), and setLinearSystemFactory().
m_p
IDoFLinearSystemImpl* Arcane::FemUtils::DoFLinearSystem::m_p = nullptr private
Definition at line 397 of file DoFLinearSystem.h.
Referenced by ~DoFLinearSystem(), _checkInit(), _eliminateRow(), _eliminateRowColumn(), _getEliminationInfo(), _getEliminationValue(), alienBsr(), applyMatrixTransformation(), applyRHSTransformation(), clearValues(), endSystemAssembly(), getCSRValues(), getForcedInfo(), getForcedValue(), hasSetCSRValues(), initialize(), isInitialized(), isMatrixSparsityConstant(), isMatrixValuesConstant(), matrixAddValue(), matrixSetValue(), reset(), rhsVariable(), setConstantMatrixSparsity(), setConstantMatrixValues(), setCSRValues(), setSolverCommandLineArguments(), solutionVariable(), solve(), and startSystemAssembly().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/DoFLinearSystem.h
src/CAWF/FEMUtils/DoFLinearSystem.cc