ShArc: ArcaneFemFunctions::BoundaryConditions3D Class Reference
ArcaneFemFunctions::BoundaryConditions3D Class Reference
Provides methods for applying boundary conditions in 3D FEM problems.
#include <ArcaneFemFunctions.h>
Static Public Member Functions
static void applyConstantSourceToRhs (Real qdot, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies a constant source term to the RHS vector.
static void applyConstantSourceToRhsHexa8 (Real qdot, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
static void applyManufacturedDirichletToLhsAndRhs (IBinaryMathFunctor< Real, Real3, Real > *manufactured_dirichlet, Real, const FaceGroup &group, BC::IManufacturedSolution *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, DoFLinearSystem &m_linear_system, VariableDoFReal &rhs_values)
Applies Manufactured Dirichlet boundary conditions to RHS and LHS.
static void applyManufacturedSourceToRhs (IBinaryMathFunctor< Real, Real3, Real > *manufactured_source, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies a manufactured source term to the RHS vector.
static void applyNeumannToRhs (BC::INeumannBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies Neumann conditions to the right-hand side (RHS) values.
static void applyNeumannToRhsHexa8 (BC::INeumannBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
static void applyTractionTableToRhsHexa8 (BC::ITractionBoundaryCondition *bs, const Real t, Int32 boundary_condition_index, const ConstArrayView< CaseTableInfo > &traction_case_table_list, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
static void applyTractionTableToRhsTetra4 (BC::ITractionBoundaryCondition *bs, const Real t, Int32 boundary_condition_index, const UniqueArray< Arcane::FemUtils::CaseTableInfo > &traction_case_table_list, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies trasient traction conditions to the right-hand side (RHS) values.
static void applyTractionToRhsHexa8 (BC::ITractionBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
static void applyTractionToRhsTetra4 (BC::ITractionBoundaryCondition *bs, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies traction conditions to the right-hand side (RHS) values.
static void integrateNodalFieldToRhsHexa8 (VariableNodeReal &field, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies a nodal field to the RHS vector.
static void integrateNodalFieldToRhsTetra4 (VariableNodeReal &field, IMesh *mesh, const IndexedNodeDoFConnectivityView &node_dof, const VariableNodeReal3 &node_coord, VariableDoFReal &rhs_values)
Applies a nodal field as a source term to the RHS vector.
Detailed Description
Provides methods for applying boundary conditions in 3D FEM problems.
This class includes static methods for applying Neumann boundary conditions to the right-hand side (RHS) of finite element method equations in 3D.
Definition at line 1405 of file ArcaneFemFunctions.h.
Member Function Documentation
applyConstantSourceToRhs()
static void ArcaneFemFunctions::BoundaryConditions3D::applyConstantSourceToRhs (Real qdot, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies a constant source term to the RHS vector.
This method adds a constant source term qdot to the RHS vector for each node in the mesh. The contribution to each node is weighted by the area of the cell and evenly distributed among the number of nodes of the cell.
Parameters
qdot The constant source term.
mesh The mesh containing all cells.
node_dof DOF connectivity view.
node_coord The coordinates of the nodes.
rhs_values The RHS values to update.
Definition at line 1425 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by FemModulePoisson::_assembleLinearOperatorCpu().
applyConstantSourceToRhsHexa8()
static void ArcaneFemFunctions::BoundaryConditions3D::applyConstantSourceToRhsHexa8 (Real qdot, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Definition at line 1437 of file ArcaneFemFunctions.h.
References M_SQRT1_3.
Referenced by FemModulePoisson::_assembleLinearOperatorCpu().
applyManufacturedDirichletToLhsAndRhs()
static void ArcaneFemFunctions::BoundaryConditions3D::applyManufacturedDirichletToLhsAndRhs (IBinaryMathFunctor< Real, Real3, Real > * manufactured_dirichlet, Real , const FaceGroup & group, BC::IManufacturedSolution * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, DoFLinearSystem & m_linear_system, VariableDoFReal & rhs_values) inline static
Applies Manufactured Dirichlet boundary conditions to RHS and LHS.
Updates the LHS matrix and RHS vector to enforce the Dirichlet.
For LHS matrix 𝐀, the diagonal term for the Dirichlet DOF is set to 𝑃.
For RHS vector 𝐛, the Dirichlet DOF term is scaled by 𝑃.
Parameters
manufactured_dirichlet External function for Dirichlet.
group Group of all external faces.
bs Boundary condition values.
node_dof DOF connectivity view.
node_coord Node coordinates.
m_linear_system Linear system for LHS.
rhs_values RHS values to update.
Definition at line 2258 of file ArcaneFemFunctions.h.
References BC::IManufacturedSolution::getPenalty(), and Arcane::FemUtils::DoFLinearSystem::matrixSetValue().
applyManufacturedSourceToRhs()
static void ArcaneFemFunctions::BoundaryConditions3D::applyManufacturedSourceToRhs (IBinaryMathFunctor< Real, Real3, Real > * manufactured_source, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies a manufactured source term to the RHS vector.
This method adds a manufactured source term to the RHS vector for each node in the mesh. The contribution to each node is weighted by the area of the cell and evenly distributed among the nodes of the cell.
Parameters
qdot The constant source term.
mesh The mesh containing all cells.
node_dof DOF connectivity view.
node_coord The coordinates of the nodes.
rhs_values The RHS values to update.
Definition at line 1708 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeBaryCenterTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
applyNeumannToRhs()
static void ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs (BC::INeumannBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies Neumann conditions to the right-hand side (RHS) values.
This method updates the RHS values of the finite element method equations based on the provided Neumann boundary condition. The boundary condition can specify a value or its components along the x and y directions.
Parameters
bs The Neumann boundary condition values.
node_dof Connectivity view for degrees of freedom at nodes.
node_coord Coordinates of the nodes in the mesh.
rhs_values The right-hand side values to be updated.
Definition at line 1737 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::MeshOperation::computeNormalTriangle(), BC::INeumannBoundaryCondition::getSurface(), and BC::INeumannBoundaryCondition::getValue().
Referenced by FemModulePoisson::_assembleLinearOperatorCpu().
applyNeumannToRhsHexa8()
static void ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhsHexa8 (BC::INeumannBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Definition at line 1787 of file ArcaneFemFunctions.h.
References BC::INeumannBoundaryCondition::getSurface(), BC::INeumannBoundaryCondition::getValue(), and M_SQRT1_3.
Referenced by FemModulePoisson::_assembleLinearOperatorCpu().
applyTractionTableToRhsHexa8()
static void ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsHexa8 (BC::ITractionBoundaryCondition * bs, const Real t, Int32 boundary_condition_index, const ConstArrayView< CaseTableInfo > & traction_case_table_list, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Definition at line 2126 of file ArcaneFemFunctions.h.
References Arcane::FemUtils::CaseTableInfo::case_table, Arcane::FemUtils::CaseTableInfo::file_name, BC::ITractionBoundaryCondition::getSurface(), BC::ITractionBoundaryCondition::getTractionInputFile(), and M_SQRT1_3.
applyTractionTableToRhsTetra4()
static void ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsTetra4 (BC::ITractionBoundaryCondition * bs, const Real t, Int32 boundary_condition_index, const UniqueArray< Arcane::FemUtils::CaseTableInfo > & traction_case_table_list, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies trasient traction conditions to the right-hand side (RHS) values.
Parameters
bs The traction boundary condition values.
t Time at which traction is applied.
boundary_condition_index Boundary condition index iterator.
traction_case_table_list Traction case table list.
node_dof Connectivity view for dof at nodes.
node_coord Coordinates of the nodes in the mesh.
rhs_values The right-hand side values to be updated.
Definition at line 2085 of file ArcaneFemFunctions.h.
References Arcane::FemUtils::CaseTableInfo::case_table, ArcaneFemFunctions::MeshOperation::computeAreaTria3(), Arcane::FemUtils::CaseTableInfo::file_name, BC::ITractionBoundaryCondition::getSurface(), and BC::ITractionBoundaryCondition::getTractionInputFile().
applyTractionToRhsHexa8()
static void ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsHexa8 (BC::ITractionBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Definition at line 1964 of file ArcaneFemFunctions.h.
References BC::ITractionBoundaryCondition::getSurface(), BC::ITractionBoundaryCondition::getValue(), and M_SQRT1_3.
Referenced by FemModuleElasticity::_applyTraction().
applyTractionToRhsTetra4()
static void ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsTetra4 (BC::ITractionBoundaryCondition * bs, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies traction conditions to the right-hand side (RHS) values.
This method updates the RHS values of the finite element method equations based on the provided traction boundary condition. The boundary condition can specify a value or its components along the x and y directions.
Parameters
bs The traction boundary condition values.
node_dof Connectivity view for degrees of freedom at nodes.
node_coord Coordinates of the nodes in the mesh.
rhs_values The right-hand side values to be updated.
Definition at line 1930 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), BC::ITractionBoundaryCondition::getSurface(), and BC::ITractionBoundaryCondition::getValue().
Referenced by FemModuleElasticity::_applyTraction().
integrateNodalFieldToRhsHexa8()
static void ArcaneFemFunctions::BoundaryConditions3D::integrateNodalFieldToRhsHexa8 (VariableNodeReal & field, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies a nodal field to the RHS vector.
Parameters
field The field term defined on nodes.
mesh The mesh containing all cells.
node_dof DOF connectivity view.
node_coord The coordinates of the nodes.
rhs_values The RHS values to update.
Definition at line 1607 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), and M_SQRT1_3.
integrateNodalFieldToRhsTetra4()
static void ArcaneFemFunctions::BoundaryConditions3D::integrateNodalFieldToRhsTetra4 (VariableNodeReal & field, IMesh * mesh, const IndexedNodeDoFConnectivityView & node_dof, const VariableNodeReal3 & node_coord, VariableDoFReal & rhs_values) inline static
Applies a nodal field as a source term to the RHS vector.
Parameters
field The field values at cell nodes.
mesh The mesh containing all cells.
node_dof DOF connectivity view.
node_coord The coordinates of the nodes.
rhs_values The RHS values to update.
Definition at line 1555 of file ArcaneFemFunctions.h.
References ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/ArcaneFemFunctions.h