ShArc: Arcane::FemUtils::AlephDoFLinearSystemImpl Class Reference
Arcane::FemUtils::AlephDoFLinearSystemImpl Class Reference
Public Member Functions
AlephDoFLinearSystemImpl (ISubDomain *sd, IItemFamily *dof_family, const String &solver_name)
~AlephDoFLinearSystemImpl () override
void applyMatrixTransformation () override
void applyRHSTransformation () override
void build ()
void clearValues () override
void eliminateRow (DoFLocalId row, Real value) override
void eliminateRowColumn (DoFLocalId row, Real value) override
CSRFormatView & getCSRValues () override
bool hasSetCSRValues () const override
void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) override
void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) override
AlephParams * params () const
void setCSRValues (const CSRFormatView &csr_view) override
void setSolverBackend (eSolverBackend v)
void setSolverCommandLineArguments (const CommandLineArguments &args) override
void solve () override
Public Member Functions inherited from Arcane::FemUtils::DoFLinearSystemImplBase
DoFLinearSystemImplBase (IItemFamily *dof_family, const String &solver_name)
void clearValues () override
IItemFamily * dofFamily () const
VariableDoFByte & getEliminationInfo () final
VariableDoFReal & getEliminationValue () final
VariableDoFBool & getForcedInfo () final
VariableDoFReal & getForcedValue () final
bool isMatrixSparsityConstant () const final
bool isMatrixValuesConstant () const final
VariableDoFReal & rhsVariable () final
Runner runner () const override
void setConstantMatrixSparsity (const bool val) final
void setConstantMatrixValues (const bool val) final
void setRunner (const Runner &r) override
VariableDoFReal & solutionVariable () final
Public Member Functions inherited from Arcane::FemUtils::IDoFLinearSystemImpl
virtual ~IDoFLinearSystemImpl ()=default
Private Types
using RowColumn = RowColumnMap::RowColumn
using RowColumnMap = OrderedRowColumnMap
Map to store values by Row/Column.
Private Member Functions
void _applyMatrixTransformationAndFillAlephMatrix ()
void _applyRHSTransformation ()
void _computeMatrixInfo ()
AlephParams * _createAlephParam () const
void _createRHSAndSolutionVector ()
void _fillRHSVector ()
void _fillRowColumnEliminationInfos ()
void _setMatrixValue (DoF row, DoF column, Real value)
Private Attributes
AlephKernel * m_aleph_kernel = nullptr
AlephMatrix * m_aleph_matrix = nullptr
AlephParams * m_aleph_params = nullptr
AlephVector * m_aleph_rhs_vector = nullptr
AlephVector * m_aleph_solution_vector = nullptr
bool m_do_print_filling = true
True to print matrix values during filling.
VariableDoFInt32 m_dof_matrix_indexes
RowColumnMap m_forced_set_values_map
List of (i,j) whose value is fixed. This will override added values in m_values_map.
bool m_need_destroy_matrix_and_vector = true
True is we need to manually destroy the matrix/vector.
eSolverBackend m_solver_backend = eSolverBackend::Hypre
ISubDomain * m_sub_domain = nullptr
RowColumnMap m_values_map
List of (i,j) values added to the matrix.
UniqueArray< Real > m_vector_zero
Additional Inherited Members
Protected Member Functions inherited from Arcane::FemUtils::DoFLinearSystemImplBase
void _applyRowColumnEliminationToRHS (bool is_verbose)
OrderedRowColumnMap & _rowColumnEliminationMap ()
Detailed Description
Definition at line 50 of file AlephDoFLinearSystem.cc.
Member Typedef Documentation
RowColumn
using Arcane::FemUtils::AlephDoFLinearSystemImpl::RowColumn = RowColumnMap::RowColumn private
Definition at line 61 of file AlephDoFLinearSystem.cc.
RowColumnMap
using Arcane::FemUtils::AlephDoFLinearSystemImpl::RowColumnMap = OrderedRowColumnMap private
Map to store values by Row/Column.
This map has to be sorted if we want to reuse the internal structure because the matrix filled has to be in the same order when we reuse it.
Definition at line 60 of file AlephDoFLinearSystem.cc.
Constructor & Destructor Documentation
AlephDoFLinearSystemImpl()
Arcane::FemUtils::AlephDoFLinearSystemImpl::AlephDoFLinearSystemImpl (ISubDomain * sd, IItemFamily * dof_family, const String & solver_name) inline
Definition at line 66 of file AlephDoFLinearSystem.cc.
~AlephDoFLinearSystemImpl()
Arcane::FemUtils::AlephDoFLinearSystemImpl::~AlephDoFLinearSystemImpl () inline override
Definition at line 74 of file AlephDoFLinearSystem.cc.
References m_aleph_kernel, m_aleph_matrix, m_aleph_params, m_aleph_rhs_vector, m_aleph_solution_vector, and m_need_destroy_matrix_and_vector.
Member Function Documentation
_applyMatrixTransformationAndFillAlephMatrix()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix () private
Definition at line 287 of file AlephDoFLinearSystem.cc.
References _fillRowColumnEliminationInfos(), Arcane::FemUtils::DoFLinearSystemImplBase::_rowColumnEliminationMap(), _setMatrixValue(), Arcane::FemUtils::OrderedRowColumnMap::RowColumn::column_id, Arcane::FemUtils::OrderedRowColumnMap::contains(), Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::ELIMINATE_ROW, Arcane::FemUtils::ELIMINATE_ROW_COLUMN, Arcane::FemUtils::OrderedRowColumnMap::end(), Arcane::FemUtils::OrderedRowColumnMap::find(), Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue(), m_do_print_filling, m_forced_set_values_map, m_values_map, and Arcane::FemUtils::OrderedRowColumnMap::RowColumn::row_id.
Referenced by applyMatrixTransformation().
_applyRHSTransformation()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyRHSTransformation () private
Definition at line 347 of file AlephDoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::_applyRowColumnEliminationToRHS(), Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::ELIMINATE_ROW, Arcane::FemUtils::ELIMINATE_ROW_COLUMN, Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue(), m_do_print_filling, and Arcane::FemUtils::DoFLinearSystemImplBase::rhsVariable().
Referenced by applyRHSTransformation().
_computeMatrixInfo()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::_computeMatrixInfo () private
Definition at line 464 of file AlephDoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), m_aleph_kernel, m_do_print_filling, m_dof_matrix_indexes, m_need_destroy_matrix_and_vector, m_solver_backend, m_sub_domain, and Arcane::FemUtils::DoFLinearSystemImplBase::solutionVariable().
Referenced by build(), and clearValues().
_createAlephParam()
AlephParams * Arcane::FemUtils::AlephDoFLinearSystemImpl::_createAlephParam () const private
Definition at line 423 of file AlephDoFLinearSystem.cc.
Referenced by build().
_createRHSAndSolutionVector()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::_createRHSAndSolutionVector () private
Definition at line 382 of file AlephDoFLinearSystem.cc.
References m_aleph_kernel, m_aleph_rhs_vector, and m_aleph_solution_vector.
Referenced by solve().
_fillRHSVector()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRHSVector () private
Definition at line 397 of file AlephDoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), m_aleph_rhs_vector, m_do_print_filling, and Arcane::FemUtils::DoFLinearSystemImplBase::rhsVariable().
Referenced by solve().
_fillRowColumnEliminationInfos()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRowColumnEliminationInfos () private
Definition at line 262 of file AlephDoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystemImplBase::_rowColumnEliminationMap(), Arcane::FemUtils::OrderedRowColumnMap::clear(), Arcane::FemUtils::OrderedRowColumnMap::RowColumn::column_id, Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), Arcane::FemUtils::ELIMINATE_ROW_COLUMN, Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue(), m_values_map, and Arcane::FemUtils::OrderedRowColumnMap::RowColumn::row_id.
Referenced by _applyMatrixTransformationAndFillAlephMatrix().
_setMatrixValue()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::_setMatrixValue (DoF row, DoF column, Real value) inline private
Definition at line 206 of file AlephDoFLinearSystem.cc.
References m_aleph_matrix, m_do_print_filling, and Arcane::FemUtils::DoFLinearSystemImplBase::solutionVariable().
Referenced by _applyMatrixTransformationAndFillAlephMatrix().
applyMatrixTransformation()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::applyMatrixTransformation () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 508 of file AlephDoFLinearSystem.cc.
References _applyMatrixTransformationAndFillAlephMatrix(), m_aleph_kernel, and m_aleph_matrix.
Referenced by solve().
applyRHSTransformation()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::applyRHSTransformation () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 526 of file AlephDoFLinearSystem.cc.
References _applyRHSTransformation().
build()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::build () inline
Definition at line 89 of file AlephDoFLinearSystem.cc.
References _computeMatrixInfo(), _createAlephParam(), Arcane::FemUtils::DoFLinearSystemImplBase::clearValues(), and m_aleph_params.
clearValues()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::clearValues () inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 158 of file AlephDoFLinearSystem.cc.
References _computeMatrixInfo(), Arcane::FemUtils::OrderedRowColumnMap::clear(), Arcane::FemUtils::DoFLinearSystemImplBase::clearValues(), m_forced_set_values_map, and m_values_map.
eliminateRow()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::eliminateRow (DoFLocalId row, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 127 of file AlephDoFLinearSystem.cc.
References Arcane::FemUtils::ELIMINATE_ROW, Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), and Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue().
eliminateRowColumn()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::eliminateRowColumn (DoFLocalId row, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 136 of file AlephDoFLinearSystem.cc.
References Arcane::FemUtils::ELIMINATE_ROW_COLUMN, Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationInfo(), and Arcane::FemUtils::DoFLinearSystemImplBase::getEliminationValue().
getCSRValues()
CSRFormatView& Arcane::FemUtils::AlephDoFLinearSystemImpl::getCSRValues () inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 171 of file AlephDoFLinearSystem.cc.
hasSetCSRValues()
bool Arcane::FemUtils::AlephDoFLinearSystemImpl::hasSetCSRValues () const inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 175 of file AlephDoFLinearSystem.cc.
matrixAddValue()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 106 of file AlephDoFLinearSystem.cc.
References Arcane::FemUtils::OrderedRowColumnMap::addValue(), and m_values_map.
matrixSetValue()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 118 of file AlephDoFLinearSystem.cc.
References m_forced_set_values_map.
params()
AlephParams* Arcane::FemUtils::AlephDoFLinearSystemImpl::params () const inline
Definition at line 96 of file AlephDoFLinearSystem.cc.
References m_aleph_params.
setCSRValues()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::setCSRValues (const CSRFormatView & csr_view) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 167 of file AlephDoFLinearSystem.cc.
setSolverBackend()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::setSolverBackend (eSolverBackend v) inline
Definition at line 98 of file AlephDoFLinearSystem.cc.
References m_solver_backend.
setSolverCommandLineArguments()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::setSolverCommandLineArguments (const CommandLineArguments & args) inline override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 149 of file AlephDoFLinearSystem.cc.
References m_aleph_kernel.
solve()
void Arcane::FemUtils::AlephDoFLinearSystemImpl::solve () override virtual
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 536 of file AlephDoFLinearSystem.cc.
References _createRHSAndSolutionVector(), _fillRHSVector(), applyMatrixTransformation(), Arcane::FemUtils::DoFLinearSystemImplBase::dofFamily(), m_aleph_kernel, m_aleph_matrix, m_aleph_params, m_aleph_rhs_vector, m_aleph_solution_vector, m_solver_backend, m_vector_zero, and Arcane::FemUtils::DoFLinearSystemImplBase::solutionVariable().
Member Data Documentation
m_aleph_kernel
AlephKernel* Arcane::FemUtils::AlephDoFLinearSystemImpl::m_aleph_kernel = nullptr private
Definition at line 181 of file AlephDoFLinearSystem.cc.
Referenced by ~AlephDoFLinearSystemImpl(), _computeMatrixInfo(), _createRHSAndSolutionVector(), applyMatrixTransformation(), setSolverCommandLineArguments(), and solve().
m_aleph_matrix
AlephMatrix* Arcane::FemUtils::AlephDoFLinearSystemImpl::m_aleph_matrix = nullptr private
Definition at line 182 of file AlephDoFLinearSystem.cc.
Referenced by ~AlephDoFLinearSystemImpl(), _setMatrixValue(), applyMatrixTransformation(), and solve().
m_aleph_params
AlephParams* Arcane::FemUtils::AlephDoFLinearSystemImpl::m_aleph_params = nullptr private
Definition at line 185 of file AlephDoFLinearSystem.cc.
Referenced by ~AlephDoFLinearSystemImpl(), build(), params(), and solve().
m_aleph_rhs_vector
AlephVector* Arcane::FemUtils::AlephDoFLinearSystemImpl::m_aleph_rhs_vector = nullptr private
Definition at line 183 of file AlephDoFLinearSystem.cc.
Referenced by ~AlephDoFLinearSystemImpl(), _createRHSAndSolutionVector(), _fillRHSVector(), and solve().
m_aleph_solution_vector
AlephVector* Arcane::FemUtils::AlephDoFLinearSystemImpl::m_aleph_solution_vector = nullptr private
Definition at line 184 of file AlephDoFLinearSystem.cc.
Referenced by ~AlephDoFLinearSystemImpl(), _createRHSAndSolutionVector(), and solve().
m_do_print_filling
bool Arcane::FemUtils::AlephDoFLinearSystemImpl::m_do_print_filling = true private
True to print matrix values during filling.
Definition at line 193 of file AlephDoFLinearSystem.cc.
Referenced by _applyMatrixTransformationAndFillAlephMatrix(), _applyRHSTransformation(), _computeMatrixInfo(), _fillRHSVector(), and _setMatrixValue().
m_dof_matrix_indexes
VariableDoFInt32 Arcane::FemUtils::AlephDoFLinearSystemImpl::m_dof_matrix_indexes private
Definition at line 180 of file AlephDoFLinearSystem.cc.
Referenced by _computeMatrixInfo().
m_forced_set_values_map
RowColumnMap Arcane::FemUtils::AlephDoFLinearSystemImpl::m_forced_set_values_map private
List of (i,j) whose value is fixed. This will override added values in m_values_map.
Definition at line 190 of file AlephDoFLinearSystem.cc.
Referenced by _applyMatrixTransformationAndFillAlephMatrix(), clearValues(), and matrixSetValue().
m_need_destroy_matrix_and_vector
bool Arcane::FemUtils::AlephDoFLinearSystemImpl::m_need_destroy_matrix_and_vector = true private
True is we need to manually destroy the matrix/vector.
Definition at line 196 of file AlephDoFLinearSystem.cc.
Referenced by ~AlephDoFLinearSystemImpl(), and _computeMatrixInfo().
m_solver_backend
eSolverBackend Arcane::FemUtils::AlephDoFLinearSystemImpl::m_solver_backend = eSolverBackend::Hypre private
Definition at line 186 of file AlephDoFLinearSystem.cc.
Referenced by _computeMatrixInfo(), setSolverBackend(), and solve().
m_sub_domain
ISubDomain* Arcane::FemUtils::AlephDoFLinearSystemImpl::m_sub_domain = nullptr private
Definition at line 179 of file AlephDoFLinearSystem.cc.
Referenced by _computeMatrixInfo().
m_values_map
RowColumnMap Arcane::FemUtils::AlephDoFLinearSystemImpl::m_values_map private
List of (i,j) values added to the matrix.
Definition at line 188 of file AlephDoFLinearSystem.cc.
Referenced by _applyMatrixTransformationAndFillAlephMatrix(), _fillRowColumnEliminationInfos(), clearValues(), and matrixAddValue().
m_vector_zero
UniqueArray<Real> Arcane::FemUtils::AlephDoFLinearSystemImpl::m_vector_zero private
Definition at line 198 of file AlephDoFLinearSystem.cc.
Referenced by solve().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/AlephDoFLinearSystem.cc