ShArc: Arcane::FemUtils::AlienBSRFormat Class Reference
Arcane::FemUtils::AlienBSRFormat Class Reference
A class for assembling Block Sparse Row (BSR) matrices from mesh data.
#include <AlienBSRFormat.h>
Public Member Functions
AlienBSRFormat (ITraceMng *tm, RunQueue &queue, const FemDoFsOnNodes &dofs_on_nodes, bool use_accelerator)
template<class Function >
void assembleBilinear (Function compute_element_matrix)
template<class Function >
void assembleBilinearAtomic (Function compute_element_matrix)
Assembles the global BSR matrix for a bilinear operator, cell-wise.
template<class Function >
void assembleBilinearAtomicFree (Function compute_element_vectors)
Assembles the global BSR matrix for a bilinear operator, node-wise.
template<class Function >
void assembleBilinearOrderedPerBlock (Function compute_element_matrix)
template<class Function >
void assembleBilinearOrderedPerBlockAtomicFree (Function compute_element_vectors)
template<class Function >
void assembleBilinearOrderedPerRow (Function compute_element_matrix)
template<class Function >
void assembleBilinearOrderedPerRowAtomicFree (Function compute_element_vectors)
void computeColumns (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< uint64_t > &sorted_edges_ss)
void computeColumnsAtomicFree ()
void computeNeighbors (Int8 edges_per_element, Int64 nb_edge_total, NumArray< Int32, MDDim1 > &neighbors, SmallSpan< UInt64 > &sorted_edges_ss)
void computeNeighborsAtomicFree (SmallSpan< Int32 > &neighbors_ss)
void computeNzPerRowArray ()
template<typename ProfileT >
void computeProfile (const std::function< void(ProfileT &, ConstArrayView< Integer >)> &compute_matrix_profile)
void computeRowIndex (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > &sorted_edges_ss)
void computeRowIndexAtomicFree ()
void computeSortedEdges (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > &sorted_edges_ss)
void computeSparsityAtomic ()
void computeSparsityAtomicFree ()
void dumpMatrix (const String &filename)
void endSystemFillingStep ()
ConstArrayView< Arccore::Integer > getAllUIndex () const
Alien::Matrix & getMatrixA ()
Alien::ProfiledMatrixBuilder * getMatrixBuilder ()
Alien::Vector & getVectorB ()
Alien::Vector & getVectorX ()
void initialize (IMesh *mesh, Int8 nb_dof)
AlienBSRMatrix & matrix ()
RunQueue & queue ()
void resetMatrixValues ()
void startSystemFillingStep ()
void toLinearSystem (DoFLinearSystem &linear_system)
Static Public Member Functions
static ARCCORE_HOST_DEVICE UInt64 pack (Int32 n0, Int32 n1)
static ARCCORE_HOST_DEVICE void registerEdgeInColumns (Int32 src, Int32 dst, Accelerator::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > offsets, Accelerator::NumArrayView< DataViewGetter< Int32 >, MDDim1, DefaultLayout > row_index, Accelerator::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > columns)
static ARCCORE_HOST_DEVICE void unpack (UInt64 packed_edge, Int32 &n0, Int32 &n1)
Private Member Functions
Int64 computeNbEdge (IMesh *mesh)
Private Attributes
UniqueArray< Arccore::Integer > m_allUIndex
AlienBSRMatrix m_bsr_matrix
std::unique_ptr< Alien::ProfiledMatrixBuilder > m_builder
CsrFormat m_csr_matrix
const FemDoFsOnNodes & m_dofs_on_nodes
std::unique_ptr< Alien::ArcaneTools::BasicIndexManager > m_index_manager
Alien::Matrix m_matrixA
Alien::MatrixDistribution m_mdist
IMesh * m_mesh = nullptr
Int8 m_nb_dof = 1
RunQueue m_queue
Alien::ArcaneTools::Space m_space
bool m_use_accelerator = false
bool m_use_atomic_free = false
bool m_use_csr_in_linear_system = false
Alien::VectorDistribution m_vdist
Alien::Vector m_vectorB
Alien::Vector m_vectorX
Detailed Description
A class for assembling Block Sparse Row (BSR) matrices from mesh data.
The BSRFormat class is designed to construct and manage BSR matrices using mesh connectivity and degree-of-freedom (DoF) information.
In 2D, the sparsity is computed based on node-face connectivity, while in 3D, node-node connectivity is used.
Note
This class uses Arcane's accelerator api and will use GPU is possible. It uses a AlienBSRMatrix under the hood for representation and operations.
This class keep a reference on the instance of FemDoFOnNodes used in the constructor. So this instance of FemDoFOnNodes must live until the instance of this class is destroyed.
Definition at line 157 of file AlienBSRFormat.h.
Constructor & Destructor Documentation
AlienBSRFormat()
Arcane::FemUtils::AlienBSRFormat::AlienBSRFormat (ITraceMng * tm, RunQueue & queue, const FemDoFsOnNodes & dofs_on_nodes, bool use_accelerator)
Definition at line 256 of file AlienBSRFormat.cc.
Member Function Documentation
assembleBilinear()
template<class Function > void Arcane::FemUtils::AlienBSRFormat::assembleBilinear (Function compute_element_matrix) inline
Definition at line 618 of file AlienBSRFormat.h.
References assembleBilinearAtomic(), assembleBilinearAtomicFree(), and m_use_atomic_free.
assembleBilinearAtomic()
template<class Function > void Arcane::FemUtils::AlienBSRFormat::assembleBilinearAtomic (Function compute_element_matrix) inline
Assembles the global BSR matrix for a bilinear operator, cell-wise.
This function constructs the Block Sparse Row (BSR) matrix by iterating over mesh cells and accumulating contributions from element-level matrices. It uses a user-defined callback to compute the local matrix for each cell and updates the global matrix with atomic operations to ensure parallel safety.
Parameters:
compute_element_matrix: A callback function that computes the local matrix for a given cell. It must return a matrix compatible with the expected block size.
Key Details:
Uses cell-to-node connectivity from the mesh and DoF mappings for assembly.
Employs atomic operations to safely handle concurrent updates in parallel execution.
Handles block structure updates for blockSize x blockSize dimensions.
Definition at line 440 of file AlienBSRFormat.h.
References assembleBilinearOrderedPerBlock(), assembleBilinearOrderedPerRow(), m_bsr_matrix, and Arcane::FemUtils::AlienBSRMatrix::orderValuePerBlock().
Referenced by assembleBilinear().
assembleBilinearAtomicFree()
template<class Function > void Arcane::FemUtils::AlienBSRFormat::assembleBilinearAtomicFree (Function compute_element_vectors) inline
Assembles the global BSR matrix for a bilinear operator, node-wise.
This function constructs the Block Sparse Row (BSR) matrix by iterating over mesh nodes and accumulating contributions from element-level matrices. It uses a user-defined callback to compute the local vectors for each cell and updates the global matrix.
Parameters:
compute_element_vectors: A callback function that computes the local vectors for a given cell. It must return a vectors compatible with the expected block size.
Key Details:
Uses cell-to-node, node-to-cell connectivity from the mesh and DoF mappings for assembly.
Handles block structure updates for blockSize x blockSize dimensions.
Definition at line 604 of file AlienBSRFormat.h.
References assembleBilinearOrderedPerBlockAtomicFree(), assembleBilinearOrderedPerRowAtomicFree(), m_bsr_matrix, and Arcane::FemUtils::AlienBSRMatrix::orderValuePerBlock().
Referenced by assembleBilinear().
assembleBilinearOrderedPerBlock()
template<class Function > void Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlock (Function compute_element_matrix) inline
Definition at line 305 of file AlienBSRFormat.h.
References Arcane::FemUtils::AlienBSRMatrix::_columns(), Arcane::FemUtils::AlienBSRMatrix::_nbNonZeroPerRows(), Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), Arcane::FemUtils::AlienBSRMatrix::_values(), m_bsr_matrix, m_mesh, m_queue, Arcane::FemUtils::AlienBSRMatrix::nbBlock(), Arcane::FemUtils::AlienBSRMatrix::nbColumn(), and Arcane::FemUtils::AlienBSRMatrix::nbRow().
Referenced by assembleBilinearAtomic().
assembleBilinearOrderedPerBlockAtomicFree()
template<class Function > void Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerBlockAtomicFree (Function compute_element_vectors) inline
Definition at line 454 of file AlienBSRFormat.h.
References Arcane::FemUtils::AlienBSRMatrix::_columns(), Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), Arcane::FemUtils::AlienBSRMatrix::_values(), m_bsr_matrix, m_mesh, m_queue, Arcane::FemUtils::AlienBSRMatrix::nbBlock(), Arcane::FemUtils::AlienBSRMatrix::nbColumn(), Arcane::FemUtils::AlienBSRMatrix::nbNonZero(), and Arcane::FemUtils::AlienBSRMatrix::nbRow().
Referenced by assembleBilinearAtomicFree().
assembleBilinearOrderedPerRow()
template<class Function > void Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow (Function compute_element_matrix) inline
Definition at line 362 of file AlienBSRFormat.h.
References Arcane::FemUtils::AlienBSRMatrix::_columns(), Arcane::FemUtils::AlienBSRMatrix::_nbNonZeroPerRows(), Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), Arcane::FemUtils::AlienBSRMatrix::_values(), m_bsr_matrix, m_dofs_on_nodes, m_mesh, m_queue, Arcane::FemUtils::AlienBSRMatrix::nbBlock(), Arcane::FemUtils::AlienBSRMatrix::nbColumn(), Arcane::FemUtils::AlienBSRMatrix::nbNonZero(), Arcane::FemUtils::AlienBSRMatrix::nbRow(), and Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView().
Referenced by assembleBilinearAtomic().
assembleBilinearOrderedPerRowAtomicFree()
template<class Function > void Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRowAtomicFree (Function compute_element_vectors) inline
Definition at line 521 of file AlienBSRFormat.h.
References Arcane::FemUtils::AlienBSRMatrix::_columns(), Arcane::FemUtils::AlienBSRMatrix::_nbNonZeroPerRows(), Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), Arcane::FemUtils::AlienBSRMatrix::_values(), m_bsr_matrix, m_mesh, m_queue, Arcane::FemUtils::AlienBSRMatrix::nbBlock(), Arcane::FemUtils::AlienBSRMatrix::nbColumn(), Arcane::FemUtils::AlienBSRMatrix::nbNonZero(), and Arcane::FemUtils::AlienBSRMatrix::nbRow().
Referenced by assembleBilinearAtomicFree().
computeColumns()
void Arcane::FemUtils::AlienBSRFormat::computeColumns (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< uint64_t > & sorted_edges_ss)
Definition at line 611 of file AlienBSRFormat.cc.
References Arcane::FemUtils::AlienBSRMatrix::_columns(), Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), m_bsr_matrix, m_mesh, m_queue, registerEdgeInColumns(), and unpack().
computeColumnsAtomicFree()
void Arcane::FemUtils::AlienBSRFormat::computeColumnsAtomicFree ()
Definition at line 452 of file AlienBSRFormat.cc.
References Arcane::FemUtils::AlienBSRMatrix::_columns(), Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), m_bsr_matrix, m_mesh, and m_queue.
Referenced by computeSparsityAtomicFree().
computeNbEdge()
Int64 Arcane::FemUtils::AlienBSRFormat::computeNbEdge (IMesh * mesh) private
Definition at line 269 of file AlienBSRFormat.cc.
Referenced by initialize().
computeNeighbors()
void Arcane::FemUtils::AlienBSRFormat::computeNeighbors (Int8 edges_per_element, Int64 nb_edge_total, NumArray< Int32, MDDim1 > & neighbors, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 572 of file AlienBSRFormat.cc.
References m_queue, and unpack().
Referenced by computeRowIndex().
computeNeighborsAtomicFree()
void Arcane::FemUtils::AlienBSRFormat::computeNeighborsAtomicFree (SmallSpan< Int32 > & neighbors_ss)
Definition at line 409 of file AlienBSRFormat.cc.
References m_mesh, and m_queue.
Referenced by computeRowIndexAtomicFree().
computeNzPerRowArray()
void Arcane::FemUtils::AlienBSRFormat::computeNzPerRowArray ()
Definition at line 364 of file AlienBSRFormat.cc.
References Arcane::FemUtils::AlienBSRMatrix::_nbNonZeroPerRows(), Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), m_bsr_matrix, m_queue, Arcane::FemUtils::AlienBSRMatrix::nbColumn(), and Arcane::FemUtils::AlienBSRMatrix::nbRow().
Referenced by computeSparsityAtomic(), and computeSparsityAtomicFree().
computeProfile()
template<typename ProfileT > void Arcane::FemUtils::AlienBSRFormat::computeProfile (const std::function< void(ProfileT &, ConstArrayView< Integer >)> & compute_matrix_profile)
Definition at line 296 of file AlienBSRFormat.h.
References m_allUIndex, and m_matrixA.
Referenced by FemModuleElasticity::_doStationarySolve().
computeRowIndex()
void Arcane::FemUtils::AlienBSRFormat::computeRowIndex (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 594 of file AlienBSRFormat.cc.
References Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), computeNeighbors(), m_bsr_matrix, m_mesh, and m_queue.
Referenced by computeSparsityAtomic().
computeRowIndexAtomicFree()
void Arcane::FemUtils::AlienBSRFormat::computeRowIndexAtomicFree ()
Definition at line 436 of file AlienBSRFormat.cc.
References Arcane::FemUtils::AlienBSRMatrix::_rowsIndex(), computeNeighborsAtomicFree(), m_bsr_matrix, m_mesh, and m_queue.
Referenced by computeSparsityAtomicFree().
computeSortedEdges()
void Arcane::FemUtils::AlienBSRFormat::computeSortedEdges (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 517 of file AlienBSRFormat.cc.
References m_mesh, m_queue, and pack().
Referenced by computeSparsityAtomic().
computeSparsityAtomic()
void Arcane::FemUtils::AlienBSRFormat::computeSparsityAtomic ()
Definition at line 658 of file AlienBSRFormat.cc.
References computeNzPerRowArray(), computeRowIndex(), computeSortedEdges(), m_mesh, m_queue, and m_use_csr_in_linear_system.
computeSparsityAtomicFree()
void Arcane::FemUtils::AlienBSRFormat::computeSparsityAtomicFree ()
Definition at line 499 of file AlienBSRFormat.cc.
References computeColumnsAtomicFree(), computeNzPerRowArray(), computeRowIndexAtomicFree(), and m_use_csr_in_linear_system.
dumpMatrix()
void Arcane::FemUtils::AlienBSRFormat::dumpMatrix (const String & filename)
Definition at line 758 of file AlienBSRFormat.cc.
References Arcane::FemUtils::AlienBSRMatrix::dump(), and m_bsr_matrix.
endSystemFillingStep()
void Arcane::FemUtils::AlienBSRFormat::endSystemFillingStep ()
Definition at line 729 of file AlienBSRFormat.cc.
References m_builder, and m_use_accelerator.
getAllUIndex()
ConstArrayView<Arccore::Integer> Arcane::FemUtils::AlienBSRFormat::getAllUIndex () const inline
Definition at line 225 of file AlienBSRFormat.h.
References m_allUIndex.
Referenced by FemModuleElasticity::_assembleBilinearOperatorGpu().
getMatrixA()
Alien::Matrix& Arcane::FemUtils::AlienBSRFormat::getMatrixA () inline
Definition at line 237 of file AlienBSRFormat.h.
References m_matrixA.
Referenced by FemModuleElasticity::_assembleBilinearOperatorGpu().
getMatrixBuilder()
Alien::ProfiledMatrixBuilder* Arcane::FemUtils::AlienBSRFormat::getMatrixBuilder () inline
Definition at line 221 of file AlienBSRFormat.h.
References m_builder.
getVectorB()
Alien::Vector& Arcane::FemUtils::AlienBSRFormat::getVectorB () inline
Definition at line 229 of file AlienBSRFormat.h.
References m_vectorB.
getVectorX()
Alien::Vector& Arcane::FemUtils::AlienBSRFormat::getVectorX () inline
Definition at line 233 of file AlienBSRFormat.h.
References m_vectorX.
initialize()
void Arcane::FemUtils::AlienBSRFormat::initialize (IMesh * mesh, Int8 nb_dof)
Definition at line 290 of file AlienBSRFormat.cc.
References Arcane::FemUtils::a1, computeNbEdge(), Arcane::FemUtils::FemDoFsOnNodes::dofFamily(), m_allUIndex, m_dofs_on_nodes, m_index_manager, m_matrixA, m_mdist, m_mesh, m_nb_dof, m_space, m_vdist, m_vectorB, and m_vectorX.
Referenced by FemModuleElasticity::_initAlienBsr().
matrix()
AlienBSRMatrix & Arcane::FemUtils::AlienBSRFormat::matrix ()
Definition at line 740 of file AlienBSRFormat.cc.
References m_bsr_matrix.
pack()
static ARCCORE_HOST_DEVICE UInt64 Arcane::FemUtils::AlienBSRFormat::pack (Int32 n0, Int32 n1) inline static
Definition at line 185 of file AlienBSRFormat.h.
Referenced by computeSortedEdges().
queue()
RunQueue& Arcane::FemUtils::AlienBSRFormat::queue () inline
Definition at line 175 of file AlienBSRFormat.h.
References m_queue.
registerEdgeInColumns()
static ARCCORE_HOST_DEVICE void Arcane::FemUtils::AlienBSRFormat::registerEdgeInColumns (Int32 src, Int32 dst, Accelerator::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > offsets, Accelerator::NumArrayView< DataViewGetter< Int32 >, MDDim1, DefaultLayout > row_index, Accelerator::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > columns) inline static
Definition at line 203 of file AlienBSRFormat.h.
Referenced by computeColumns().
resetMatrixValues()
void Arcane::FemUtils::AlienBSRFormat::resetMatrixValues ()
Definition at line 749 of file AlienBSRFormat.cc.
References Arcane::FemUtils::AlienBSRMatrix::_values(), m_bsr_matrix, and m_queue.
startSystemFillingStep()
void Arcane::FemUtils::AlienBSRFormat::startSystemFillingStep ()
Definition at line 723 of file AlienBSRFormat.cc.
References m_builder, m_matrixA, and m_use_accelerator.
toLinearSystem()
void Arcane::FemUtils::AlienBSRFormat::toLinearSystem (DoFLinearSystem & linear_system)
Definition at line 349 of file AlienBSRFormat.cc.
unpack()
static ARCCORE_HOST_DEVICE void Arcane::FemUtils::AlienBSRFormat::unpack (UInt64 packed_edge, Int32 & n0, Int32 & n1) inline static
Definition at line 192 of file AlienBSRFormat.h.
Referenced by computeColumns(), and computeNeighbors().
Member Data Documentation
m_allUIndex
UniqueArray<Arccore::Integer> Arcane::FemUtils::AlienBSRFormat::m_allUIndex private
Definition at line 272 of file AlienBSRFormat.h.
Referenced by computeProfile(), getAllUIndex(), and initialize().
m_bsr_matrix
AlienBSRMatrix Arcane::FemUtils::AlienBSRFormat::m_bsr_matrix private
Definition at line 285 of file AlienBSRFormat.h.
Referenced by assembleBilinearAtomic(), assembleBilinearAtomicFree(), assembleBilinearOrderedPerBlock(), assembleBilinearOrderedPerBlockAtomicFree(), assembleBilinearOrderedPerRow(), assembleBilinearOrderedPerRowAtomicFree(), computeColumns(), computeColumnsAtomicFree(), computeNzPerRowArray(), computeRowIndex(), computeRowIndexAtomicFree(), dumpMatrix(), matrix(), and resetMatrixValues().
m_builder
std::unique_ptr<Alien::ProfiledMatrixBuilder> Arcane::FemUtils::AlienBSRFormat::m_builder private
Definition at line 282 of file AlienBSRFormat.h.
Referenced by endSystemFillingStep(), getMatrixBuilder(), and startSystemFillingStep().
m_csr_matrix
CsrFormat Arcane::FemUtils::AlienBSRFormat::m_csr_matrix private
Definition at line 286 of file AlienBSRFormat.h.
m_dofs_on_nodes
const FemDoFsOnNodes& Arcane::FemUtils::AlienBSRFormat::m_dofs_on_nodes private
Definition at line 290 of file AlienBSRFormat.h.
Referenced by assembleBilinearOrderedPerRow(), and initialize().
m_index_manager
std::unique_ptr<Alien::ArcaneTools::BasicIndexManager> Arcane::FemUtils::AlienBSRFormat::m_index_manager private
Definition at line 271 of file AlienBSRFormat.h.
Referenced by initialize().
m_matrixA
Alien::Matrix Arcane::FemUtils::AlienBSRFormat::m_matrixA private
Definition at line 280 of file AlienBSRFormat.h.
Referenced by computeProfile(), getMatrixA(), initialize(), and startSystemFillingStep().
m_mdist
Alien::MatrixDistribution Arcane::FemUtils::AlienBSRFormat::m_mdist private
Definition at line 275 of file AlienBSRFormat.h.
Referenced by initialize().
m_mesh
IMesh* Arcane::FemUtils::AlienBSRFormat::m_mesh = nullptr private
Definition at line 288 of file AlienBSRFormat.h.
Referenced by assembleBilinearOrderedPerBlock(), assembleBilinearOrderedPerBlockAtomicFree(), assembleBilinearOrderedPerRow(), assembleBilinearOrderedPerRowAtomicFree(), computeColumns(), computeColumnsAtomicFree(), computeNeighborsAtomicFree(), computeRowIndex(), computeRowIndexAtomicFree(), computeSortedEdges(), computeSparsityAtomic(), and initialize().
m_nb_dof
Int8 Arcane::FemUtils::AlienBSRFormat::m_nb_dof = 1 private
Definition at line 166 of file AlienBSRFormat.h.
Referenced by initialize().
m_queue
RunQueue Arcane::FemUtils::AlienBSRFormat::m_queue private
Definition at line 289 of file AlienBSRFormat.h.
Referenced by assembleBilinearOrderedPerBlock(), assembleBilinearOrderedPerBlockAtomicFree(), assembleBilinearOrderedPerRow(), assembleBilinearOrderedPerRowAtomicFree(), computeColumns(), computeColumnsAtomicFree(), computeNeighbors(), computeNeighborsAtomicFree(), computeNzPerRowArray(), computeRowIndex(), computeRowIndexAtomicFree(), computeSortedEdges(), computeSparsityAtomic(), queue(), and resetMatrixValues().
m_space
Alien::ArcaneTools::Space Arcane::FemUtils::AlienBSRFormat::m_space private
Definition at line 274 of file AlienBSRFormat.h.
Referenced by initialize().
m_use_accelerator
bool Arcane::FemUtils::AlienBSRFormat::m_use_accelerator = false private
Definition at line 270 of file AlienBSRFormat.h.
Referenced by endSystemFillingStep(), and startSystemFillingStep().
m_use_atomic_free
bool Arcane::FemUtils::AlienBSRFormat::m_use_atomic_free = false private
Definition at line 269 of file AlienBSRFormat.h.
Referenced by assembleBilinear().
m_use_csr_in_linear_system
bool Arcane::FemUtils::AlienBSRFormat::m_use_csr_in_linear_system = false private
Definition at line 268 of file AlienBSRFormat.h.
Referenced by computeSparsityAtomic(), and computeSparsityAtomicFree().
m_vdist
Alien::VectorDistribution Arcane::FemUtils::AlienBSRFormat::m_vdist private
Definition at line 276 of file AlienBSRFormat.h.
Referenced by initialize().
m_vectorB
Alien::Vector Arcane::FemUtils::AlienBSRFormat::m_vectorB private
Definition at line 278 of file AlienBSRFormat.h.
Referenced by getVectorB(), and initialize().
m_vectorX
Alien::Vector Arcane::FemUtils::AlienBSRFormat::m_vectorX private
Definition at line 279 of file AlienBSRFormat.h.
Referenced by getVectorX(), and initialize().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/AlienBSRFormat.h
src/CAWF/FEMUtils/AlienBSRFormat.cc
src/CAWF/FEMUtils/AlienBSRFormatSYCL.cc