ShArc: BC::INeumannBoundaryCondition Class Reference
BC::INeumannBoundaryCondition Class Reference abstract
#include <IArcaneFemBC.h>
Public Member Functions
virtual Arcane::FaceGroup getSurface ()=0
virtual StringConstArrayView getValue ()=0
Detailed Description
Definition at line 37 of file IArcaneFemBC.h.
Member Function Documentation
getSurface()
virtual Arcane::FaceGroup BC::INeumannBoundaryCondition::getSurface () pure virtual
Referenced by ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhsHexa8(), and ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhsQuad4().
getValue()
virtual StringConstArrayView BC::INeumannBoundaryCondition::getValue () pure virtual
Referenced by ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhsHexa8(), and ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhsQuad4().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/IArcaneFemBC.h