ShArc: Arcane::FemUtils::CsrFormatMatrixView Class Reference
Arcane::FemUtils::CsrFormatMatrixView Class Reference
View of a Matrix with CSR format.
#include <CsrFormatMatrixView.h>
Public Member Functions
CsrFormatMatrixView ()=default
constexpr ARCCORE_HOST_DEVICE Int32 column (CsrRowColumnIndex rc_index) const
Local index of the column for the given RowColumnIndex rc_index.
constexpr ARCCORE_HOST_DEVICE Span< const Int32 > columns () const
constexpr ARCCORE_HOST_DEVICE Int32 nbColumn () const
Number of the values in the matrix.
constexpr ARCCORE_HOST_DEVICE Int32 nbColumnForRow (Int32 row) const
Number of column for the row row.
constexpr ARCCORE_HOST_DEVICE Int32 nbRow () const
Number of the rows in the matrix.
constexpr ARCCORE_HOST_DEVICE Int32 nbValue () const
Number of the values in the matrix.
constexpr ARCCORE_HOST_DEVICE Int32 row (Int32 index) const
constexpr ARCCORE_HOST_DEVICE CsrRow rowRange (Int32 row) const
Range of CsrRowColumnIndex for the given row row.
constexpr ARCCORE_HOST_DEVICE Span< const Int32 > rows () const
constexpr ARCCORE_HOST_DEVICE CsrRowColumnIndex tryFindColumnInRow (Int32 row, Int32 column_id) const
Try to find a column in a row.
constexpr ARCCORE_HOST_DEVICE Real & value (CsrRowColumnIndex rc_index) const
Value of the matrix for the given RowColumnIndex rc_index.
constexpr ARCCORE_HOST_DEVICE Span< Real > values () const
Private Member Functions
CsrFormatMatrixView (SmallSpan< const Int32 > rows, SmallSpan< const Int32 > matrix_rows_nb_column, SmallSpan< const Int32 > columns, SmallSpan< Real > values)
Private Attributes
friend CsrFormat
SmallSpan< const Int32 > m_matrix_columns
SmallSpan< const Int32 > m_matrix_rows
SmallSpan< const Int32 > m_matrix_rows_nb_column
SmallSpan< Real > m_values
Detailed Description
View of a Matrix with CSR format.
This view is a temporary object and is invalided when the underlying matrix structure is modified.
Definition at line 135 of file CsrFormatMatrixView.h.
Constructor & Destructor Documentation
CsrFormatMatrixView() [1/2]
Arcane::FemUtils::CsrFormatMatrixView::CsrFormatMatrixView () default
CsrFormatMatrixView() [2/2]
Arcane::FemUtils::CsrFormatMatrixView::CsrFormatMatrixView (SmallSpan< const Int32 > rows, SmallSpan< const Int32 > matrix_rows_nb_column, SmallSpan< const Int32 > columns, SmallSpan< Real > values) inline private
Definition at line 145 of file CsrFormatMatrixView.h.
Member Function Documentation
column()
constexpr ARCCORE_HOST_DEVICE Int32 Arcane::FemUtils::CsrFormatMatrixView::column (CsrRowColumnIndex rc_index) const inline constexpr
Local index of the column for the given RowColumnIndex rc_index.
Definition at line 176 of file CsrFormatMatrixView.h.
References m_matrix_columns.
Referenced by tryFindColumnInRow().
columns()
constexpr ARCCORE_HOST_DEVICE Span<const Int32> Arcane::FemUtils::CsrFormatMatrixView::columns () const inline constexpr
Definition at line 158 of file CsrFormatMatrixView.h.
References m_matrix_columns.
Referenced by Arcane::FemUtils::PETScDoFLinearSystemImpl::_preallocateMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::indexValue(), and Arcane::FemUtils::HypreDoFLinearSystemImpl::solve().
nbColumn()
constexpr ARCCORE_HOST_DEVICE Int32 Arcane::FemUtils::CsrFormatMatrixView::nbColumn () const inline constexpr
Number of the values in the matrix.
Definition at line 164 of file CsrFormatMatrixView.h.
References m_matrix_columns.
Referenced by Arcane::FemUtils::CsrDoFLinearSystemImpl::indexValue(), and rowRange().
nbColumnForRow()
constexpr ARCCORE_HOST_DEVICE Int32 Arcane::FemUtils::CsrFormatMatrixView::nbColumnForRow (Int32 row) const inline constexpr
Number of column for the row row.
Definition at line 170 of file CsrFormatMatrixView.h.
References m_matrix_rows_nb_column, and row().
Referenced by Arcane::FemUtils::HypreDoFLinearSystemImpl::solve().
nbRow()
constexpr ARCCORE_HOST_DEVICE Int32 Arcane::FemUtils::CsrFormatMatrixView::nbRow () const inline constexpr
Number of the rows in the matrix.
Definition at line 162 of file CsrFormatMatrixView.h.
References m_matrix_rows.
Referenced by Arcane::FemUtils::CsrDoFLinearSystemImpl::indexValue(), rowRange(), and Arcane::FemUtils::HypreDoFLinearSystemImpl::solve().
nbValue()
constexpr ARCCORE_HOST_DEVICE Int32 Arcane::FemUtils::CsrFormatMatrixView::nbValue () const inline constexpr
Number of the values in the matrix.
Definition at line 166 of file CsrFormatMatrixView.h.
References m_values.
Referenced by Arcane::FemUtils::PETScDoFLinearSystemImpl::_preallocateMatrix(), and Arcane::FemUtils::HypreDoFLinearSystemImpl::solve().
row()
constexpr ARCCORE_HOST_DEVICE Int32 Arcane::FemUtils::CsrFormatMatrixView::row (Int32 index) const inline constexpr
Definition at line 168 of file CsrFormatMatrixView.h.
References m_matrix_rows.
Referenced by Arcane::FemUtils::CsrDoFLinearSystemImpl::indexValue(), nbColumnForRow(), rowRange(), and tryFindColumnInRow().
rowRange()
constexpr ARCCORE_HOST_DEVICE CsrRow Arcane::FemUtils::CsrFormatMatrixView::rowRange (Int32 row) const inline constexpr
Range of CsrRowColumnIndex for the given row row.
Definition at line 181 of file CsrFormatMatrixView.h.
References m_matrix_rows, nbColumn(), nbRow(), and row().
Referenced by tryFindColumnInRow().
rows()
constexpr ARCCORE_HOST_DEVICE Span<const Int32> Arcane::FemUtils::CsrFormatMatrixView::rows () const inline constexpr
Definition at line 157 of file CsrFormatMatrixView.h.
References m_matrix_rows.
Referenced by Arcane::FemUtils::PETScDoFLinearSystemImpl::_preallocateMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::indexValue(), and Arcane::FemUtils::HypreDoFLinearSystemImpl::solve().
tryFindColumnInRow()
constexpr ARCCORE_HOST_DEVICE CsrRowColumnIndex Arcane::FemUtils::CsrFormatMatrixView::tryFindColumnInRow (Int32 row, Int32 column_id) const inline constexpr
Try to find a column in a row.
Try to find the column column_id in the row row. If not found return a null index.
Definition at line 196 of file CsrFormatMatrixView.h.
References column(), row(), and rowRange().
value()
constexpr ARCCORE_HOST_DEVICE Real& Arcane::FemUtils::CsrFormatMatrixView::value (CsrRowColumnIndex rc_index) const inline constexpr
Value of the matrix for the given RowColumnIndex rc_index.
Definition at line 178 of file CsrFormatMatrixView.h.
References m_values.
values()
constexpr ARCCORE_HOST_DEVICE Span<Real> Arcane::FemUtils::CsrFormatMatrixView::values () const inline constexpr
Definition at line 159 of file CsrFormatMatrixView.h.
References m_values.
Referenced by Arcane::FemUtils::PETScDoFLinearSystemImpl::_initSolve(), Arcane::FemUtils::CsrDoFLinearSystemImpl::matrixAddValue(), Arcane::FemUtils::CsrDoFLinearSystemImpl::matrixSetValue(), Arcane::FemUtils::HypreDoFLinearSystemImpl::solve(), and Arcane::FemUtils::PETScDoFLinearSystemImpl::solve().
Member Data Documentation
CsrFormat
friend Arcane::FemUtils::CsrFormatMatrixView::CsrFormat private
Definition at line 137 of file CsrFormatMatrixView.h.
m_matrix_columns
SmallSpan<const Int32> Arcane::FemUtils::CsrFormatMatrixView::m_matrix_columns private
Definition at line 208 of file CsrFormatMatrixView.h.
Referenced by column(), columns(), and nbColumn().
m_matrix_rows
SmallSpan<const Int32> Arcane::FemUtils::CsrFormatMatrixView::m_matrix_rows private
Definition at line 206 of file CsrFormatMatrixView.h.
Referenced by nbRow(), row(), rowRange(), and rows().
m_matrix_rows_nb_column
SmallSpan<const Int32> Arcane::FemUtils::CsrFormatMatrixView::m_matrix_rows_nb_column private
Definition at line 207 of file CsrFormatMatrixView.h.
Referenced by nbColumnForRow().
m_values
SmallSpan<Real> Arcane::FemUtils::CsrFormatMatrixView::m_values private
Definition at line 209 of file CsrFormatMatrixView.h.
Referenced by nbValue(), value(), and values().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/CsrFormatMatrixView.h