ShArc: Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper Class Reference
Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper Class Reference
Helper class to handle RowColumn elimination.
#include <DoFLinearSystem.h>
Public Member Functions
~DoFLinearSystemRowColumnEliminationHelper ()
void addElimination (DoFLocalId row, Real value)
VariableDoFByte & getEliminationInfo ()
VariableDoFReal & getEliminationValue ()
Private Member Functions
DoFLinearSystemRowColumnEliminationHelper (DoFLinearSystem *dof_ls)
Private Attributes
friend DoFLinearSystem
DoFLinearSystem * m_dof_linear_system = nullptr
Detailed Description
Helper class to handle RowColumn elimination.
Instances of this class are temporary and are created via a call to DoFLinearSystem::rowColumnEliminationHelper().
There is two ways to use this class.
use the method addElimination() and specify the row and the value
get the variables handling elimination info (getEliminationInfo()) and elimination value (getEliminationValue()) and set the corresponding row with ELIMINATION_ROW_COLUMN and the value of the elimination.
Only the method 2 is available on accelerator.
Definition at line 102 of file DoFLinearSystem.h.
Constructor & Destructor Documentation
DoFLinearSystemRowColumnEliminationHelper()
Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::DoFLinearSystemRowColumnEliminationHelper (DoFLinearSystem * dof_ls) explicit private
Definition at line 745 of file DoFLinearSystem.cc.
~DoFLinearSystemRowColumnEliminationHelper()
Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::~DoFLinearSystemRowColumnEliminationHelper ()
Definition at line 754 of file DoFLinearSystem.cc.
Member Function Documentation
addElimination()
void Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::addElimination (DoFLocalId row, Real value)
Definition at line 761 of file DoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystem::_eliminateRowColumn(), and m_dof_linear_system.
Referenced by ArcaneFemFunctions::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowColumnElimination().
getEliminationInfo()
VariableDoFByte & Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::getEliminationInfo ()
Definition at line 770 of file DoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystem::_getEliminationInfo(), and m_dof_linear_system.
getEliminationValue()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::getEliminationValue ()
Definition at line 779 of file DoFLinearSystem.cc.
References Arcane::FemUtils::DoFLinearSystem::_getEliminationValue(), and m_dof_linear_system.
Member Data Documentation
DoFLinearSystem
friend Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::DoFLinearSystem private
Definition at line 104 of file DoFLinearSystem.h.
m_dof_linear_system
DoFLinearSystem* Arcane::FemUtils::DoFLinearSystemRowColumnEliminationHelper::m_dof_linear_system = nullptr private
Definition at line 137 of file DoFLinearSystem.h.
Referenced by addElimination(), getEliminationInfo(), and getEliminationValue().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/DoFLinearSystem.h
src/CAWF/FEMUtils/DoFLinearSystem.cc