ShArc: BC::ITractionBoundaryCondition Class Reference
BC::ITractionBoundaryCondition Class Reference abstract
AI generated: Interface for traction boundary conditions specifying surface forces.
#include <IArcaneFemBC.h>
Public Member Functions
virtual Arcane::FaceGroup getSurface ()=0
virtual String getTractionInputFile ()=0
virtual StringConstArrayView getValue ()=0
Detailed Description
AI generated: Interface for traction boundary conditions specifying surface forces.
Definition at line 49 of file IArcaneFemBC.h.
Member Function Documentation
getSurface()
virtual Arcane::FaceGroup BC::ITractionBoundaryCondition::getSurface () pure virtual
Referenced by ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsHexa8(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsTetra4(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsTria3(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsHexa8(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsTetra4(), and ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsTria3().
getTractionInputFile()
virtual String BC::ITractionBoundaryCondition::getTractionInputFile () pure virtual
Referenced by ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsHexa8(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsTetra4(), and ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsTria3().
getValue()
virtual StringConstArrayView BC::ITractionBoundaryCondition::getValue () pure virtual
Referenced by ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsHexa8(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsTetra4(), and ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsTria3().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/IArcaneFemBC.h