ShArc: Arcane::FemUtils::BSRFormat Class Reference
Arcane::FemUtils::BSRFormat Class Reference
A class for assembling Block Sparse Row (BSR) matrices from mesh data.
#include <BSRFormat.h>
Public Member Functions
BSRFormat (ITraceMng *tm, RunQueue &queue, const FemDoFsOnNodes &dofs_on_nodes)
template<class Function >
void assembleBilinear (Function compute_element_matrix)
template<class Function >
void assembleBilinearAtomic (Function compute_element_matrix)
Assembles the global BSR matrix for a bilinear operator, cell-wise.
template<class Function >
void assembleBilinearAtomicFree (Function compute_element_vectors)
Assembles the global BSR matrix for a bilinear operator, node-wise.
template<class Function >
void assembleBilinearOrderedPerBlock (Function compute_element_matrix)
template<class Function >
void assembleBilinearOrderedPerBlockAtomicFree (Function compute_element_vectors)
template<class Function >
void assembleBilinearOrderedPerRow (Function compute_element_matrix)
template<class Function >
void assembleBilinearOrderedPerRowAtomicFree (Function compute_element_vectors)
void computeColumns (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< uint64_t > &sorted_edges_ss)
void computeColumnsAtomicFree ()
void computeNeighbors (Int8 edges_per_element, Int64 nb_edge_total, NumArray< Int32, MDDim1 > &neighbors, SmallSpan< UInt64 > &sorted_edges_ss)
void computeNeighborsAtomicFree (SmallSpan< Int32 > &neighbors_ss)
void computeNzPerRowArray ()
void computeRowIndex (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > &sorted_edges_ss)
void computeRowIndexAtomicFree ()
void computeSortedEdges (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > &sorted_edges_ss)
void computeSparsity ()
void computeSparsityAtomic ()
void computeSparsityAtomicFree ()
void dumpMatrix (const String &filename)
void initialize (IMesh *mesh, Int8 nb_dof, bool does_linear_system_use_csr, bool use_atomic_free=false)
BSRMatrix & matrix ()
void resetMatrixValues ()
void toLinearSystem (DoFLinearSystem &linear_system)
Static Public Member Functions
static ARCCORE_HOST_DEVICE UInt64 pack (Int32 n0, Int32 n1)
static ARCCORE_HOST_DEVICE void registerEdgeInColumns (Int32 src, Int32 dst, Accelerator::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > offsets, Accelerator::NumArrayView< DataViewGetter< Int32 >, MDDim1, DefaultLayout > row_index, Accelerator::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > columns)
static ARCCORE_HOST_DEVICE void unpack (UInt64 packed_edge, Int32 &n0, Int32 &n1)
Private Member Functions
Int64 computeNbEdge (IMesh *mesh)
Private Attributes
BSRMatrix m_bsr_matrix
CsrFormat m_csr_matrix
const FemDoFsOnNodes & m_dofs_on_nodes
IMesh * m_mesh = nullptr
Int8 m_nb_dof = 1
RunQueue m_queue
bool m_use_atomic_free = false
bool m_use_csr_in_linear_system = false
Detailed Description
A class for assembling Block Sparse Row (BSR) matrices from mesh data.
The BSRFormat class is designed to construct and manage BSR matrices using mesh connectivity and degree-of-freedom (DoF) information.
In 2D, the sparsity is computed based on node-face connectivity, while in 3D, node-node connectivity is used.
Note
This class uses Arcane's accelerator api and will use GPU is possible. It uses a BSRMatrix under the hood for representation and operations.
This class keep a reference on the instance of FemDoFOnNodes used in the constructor. So this instance of FemDoFOnNodes must live until the instance of this class is destroyed.
Definition at line 156 of file BSRFormat.h.
Constructor & Destructor Documentation
BSRFormat()
Arcane::FemUtils::BSRFormat::BSRFormat (ITraceMng * tm, RunQueue & queue, const FemDoFsOnNodes & dofs_on_nodes)
Definition at line 233 of file BSRFormat.cc.
Member Function Documentation
assembleBilinear()
template<class Function > void Arcane::FemUtils::BSRFormat::assembleBilinear (Function compute_element_matrix) inline
Definition at line 569 of file BSRFormat.h.
References assembleBilinearAtomic(), assembleBilinearAtomicFree(), and m_use_atomic_free.
assembleBilinearAtomic()
template<class Function > void Arcane::FemUtils::BSRFormat::assembleBilinearAtomic (Function compute_element_matrix) inline
Assembles the global BSR matrix for a bilinear operator, cell-wise.
This function constructs the Block Sparse Row (BSR) matrix by iterating over mesh cells and accumulating contributions from element-level matrices. It uses a user-defined callback to compute the local matrix for each cell and updates the global matrix with atomic operations to ensure parallel safety.
Parameters:
compute_element_matrix: A callback function that computes the local matrix for a given cell. It must return a matrix compatible with the expected block size.
Key Details:
Uses cell-to-node connectivity from the mesh and DoF mappings for assembly.
Employs atomic operations to safely handle concurrent updates in parallel execution.
Handles block structure updates for blockSize x blockSize dimensions.
Definition at line 391 of file BSRFormat.h.
References assembleBilinearOrderedPerBlock(), assembleBilinearOrderedPerRow(), m_bsr_matrix, and Arcane::FemUtils::BSRMatrix::orderValuePerBlock().
Referenced by FemModuleElasticity::_assembleBilinearOperator(), FemModulePoisson::_assembleBilinearOperator(), and assembleBilinear().
assembleBilinearAtomicFree()
template<class Function > void Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree (Function compute_element_vectors) inline
Assembles the global BSR matrix for a bilinear operator, node-wise.
This function constructs the Block Sparse Row (BSR) matrix by iterating over mesh nodes and accumulating contributions from element-level matrices. It uses a user-defined callback to compute the local vectors for each cell and updates the global matrix.
Parameters:
compute_element_vectors: A callback function that computes the local vectors for a given cell. It must return a vectors compatible with the expected block size.
Key Details:
Uses cell-to-node, node-to-cell connectivity from the mesh and DoF mappings for assembly.
Handles block structure updates for blockSize x blockSize dimensions.
Definition at line 555 of file BSRFormat.h.
References assembleBilinearOrderedPerBlockAtomicFree(), assembleBilinearOrderedPerRowAtomicFree(), m_bsr_matrix, and Arcane::FemUtils::BSRMatrix::orderValuePerBlock().
Referenced by FemModuleElasticity::_assembleBilinearOperator(), FemModulePoisson::_assembleBilinearOperator(), and assembleBilinear().
assembleBilinearOrderedPerBlock()
template<class Function > void Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock (Function compute_element_matrix) inline
Definition at line 256 of file BSRFormat.h.
References Arcane::FemUtils::BSRMatrix::_columns(), Arcane::FemUtils::BSRMatrix::_nbNonZeroPerRows(), Arcane::FemUtils::BSRMatrix::_rowsIndex(), Arcane::FemUtils::BSRMatrix::_values(), m_bsr_matrix, m_dofs_on_nodes, m_mesh, m_queue, Arcane::FemUtils::BSRMatrix::nbBlock(), Arcane::FemUtils::BSRMatrix::nbColumn(), Arcane::FemUtils::BSRMatrix::nbNonZero(), Arcane::FemUtils::BSRMatrix::nbRow(), and Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView().
Referenced by assembleBilinearAtomic().
assembleBilinearOrderedPerBlockAtomicFree()
template<class Function > void Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlockAtomicFree (Function compute_element_vectors) inline
Definition at line 405 of file BSRFormat.h.
References Arcane::FemUtils::BSRMatrix::_columns(), Arcane::FemUtils::BSRMatrix::_rowsIndex(), Arcane::FemUtils::BSRMatrix::_values(), m_bsr_matrix, m_mesh, m_queue, Arcane::FemUtils::BSRMatrix::nbBlock(), Arcane::FemUtils::BSRMatrix::nbColumn(), Arcane::FemUtils::BSRMatrix::nbNonZero(), and Arcane::FemUtils::BSRMatrix::nbRow().
Referenced by assembleBilinearAtomicFree().
assembleBilinearOrderedPerRow()
template<class Function > void Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow (Function compute_element_matrix) inline
Definition at line 313 of file BSRFormat.h.
References Arcane::FemUtils::BSRMatrix::_columns(), Arcane::FemUtils::BSRMatrix::_nbNonZeroPerRows(), Arcane::FemUtils::BSRMatrix::_rowsIndex(), Arcane::FemUtils::BSRMatrix::_values(), m_bsr_matrix, m_dofs_on_nodes, m_mesh, m_queue, Arcane::FemUtils::BSRMatrix::nbBlock(), Arcane::FemUtils::BSRMatrix::nbColumn(), Arcane::FemUtils::BSRMatrix::nbNonZero(), Arcane::FemUtils::BSRMatrix::nbRow(), and Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView().
Referenced by assembleBilinearAtomic().
assembleBilinearOrderedPerRowAtomicFree()
template<class Function > void Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRowAtomicFree (Function compute_element_vectors) inline
Definition at line 472 of file BSRFormat.h.
References Arcane::FemUtils::BSRMatrix::_columns(), Arcane::FemUtils::BSRMatrix::_nbNonZeroPerRows(), Arcane::FemUtils::BSRMatrix::_rowsIndex(), Arcane::FemUtils::BSRMatrix::_values(), m_bsr_matrix, m_mesh, m_queue, Arcane::FemUtils::BSRMatrix::nbBlock(), Arcane::FemUtils::BSRMatrix::nbColumn(), Arcane::FemUtils::BSRMatrix::nbNonZero(), and Arcane::FemUtils::BSRMatrix::nbRow().
Referenced by assembleBilinearAtomicFree().
computeColumns()
void Arcane::FemUtils::BSRFormat::computeColumns (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< uint64_t > & sorted_edges_ss)
Definition at line 561 of file BSRFormat.cc.
References Arcane::FemUtils::BSRMatrix::_columns(), Arcane::FemUtils::BSRMatrix::_rowsIndex(), m_bsr_matrix, m_mesh, m_queue, registerEdgeInColumns(), and unpack().
Referenced by computeSparsityAtomic().
computeColumnsAtomicFree()
void Arcane::FemUtils::BSRFormat::computeColumnsAtomicFree ()
Definition at line 402 of file BSRFormat.cc.
References Arcane::FemUtils::BSRMatrix::_columns(), Arcane::FemUtils::BSRMatrix::_rowsIndex(), m_bsr_matrix, m_mesh, and m_queue.
Referenced by computeSparsityAtomicFree().
computeNbEdge()
Int64 Arcane::FemUtils::BSRFormat::computeNbEdge (IMesh * mesh) private
Definition at line 242 of file BSRFormat.cc.
Referenced by initialize().
computeNeighbors()
void Arcane::FemUtils::BSRFormat::computeNeighbors (Int8 edges_per_element, Int64 nb_edge_total, NumArray< Int32, MDDim1 > & neighbors, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 522 of file BSRFormat.cc.
References m_queue, and unpack().
Referenced by computeRowIndex().
computeNeighborsAtomicFree()
void Arcane::FemUtils::BSRFormat::computeNeighborsAtomicFree (SmallSpan< Int32 > & neighbors_ss)
Definition at line 359 of file BSRFormat.cc.
References m_mesh, and m_queue.
Referenced by computeRowIndexAtomicFree().
computeNzPerRowArray()
void Arcane::FemUtils::BSRFormat::computeNzPerRowArray ()
Definition at line 314 of file BSRFormat.cc.
References Arcane::FemUtils::BSRMatrix::_nbNonZeroPerRows(), Arcane::FemUtils::BSRMatrix::_rowsIndex(), m_bsr_matrix, m_queue, Arcane::FemUtils::BSRMatrix::nbColumn(), and Arcane::FemUtils::BSRMatrix::nbRow().
Referenced by computeSparsityAtomic(), and computeSparsityAtomicFree().
computeRowIndex()
void Arcane::FemUtils::BSRFormat::computeRowIndex (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 544 of file BSRFormat.cc.
References Arcane::FemUtils::BSRMatrix::_rowsIndex(), computeNeighbors(), m_bsr_matrix, m_mesh, and m_queue.
Referenced by computeSparsityAtomic().
computeRowIndexAtomicFree()
void Arcane::FemUtils::BSRFormat::computeRowIndexAtomicFree ()
Definition at line 386 of file BSRFormat.cc.
References Arcane::FemUtils::BSRMatrix::_rowsIndex(), computeNeighborsAtomicFree(), m_bsr_matrix, m_mesh, and m_queue.
Referenced by computeSparsityAtomicFree().
computeSortedEdges()
void Arcane::FemUtils::BSRFormat::computeSortedEdges (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 467 of file BSRFormat.cc.
References m_mesh, m_queue, and pack().
Referenced by computeSparsityAtomic().
computeSparsity()
void Arcane::FemUtils::BSRFormat::computeSparsity ()
Definition at line 635 of file BSRFormat.cc.
References computeSparsityAtomic(), computeSparsityAtomicFree(), and m_use_atomic_free.
Referenced by FemModuleElasticity::_assembleBilinearOperator(), and FemModulePoisson::compute().
computeSparsityAtomic()
void Arcane::FemUtils::BSRFormat::computeSparsityAtomic ()
Definition at line 608 of file BSRFormat.cc.
References computeColumns(), computeNzPerRowArray(), computeRowIndex(), computeSortedEdges(), m_mesh, m_queue, and m_use_csr_in_linear_system.
Referenced by computeSparsity().
computeSparsityAtomicFree()
void Arcane::FemUtils::BSRFormat::computeSparsityAtomicFree ()
Definition at line 449 of file BSRFormat.cc.
References computeColumnsAtomicFree(), computeNzPerRowArray(), computeRowIndexAtomicFree(), and m_use_csr_in_linear_system.
Referenced by computeSparsity().
dumpMatrix()
void Arcane::FemUtils::BSRFormat::dumpMatrix (const String & filename)
Definition at line 665 of file BSRFormat.cc.
References Arcane::FemUtils::BSRMatrix::dump(), and m_bsr_matrix.
initialize()
void Arcane::FemUtils::BSRFormat::initialize (IMesh * mesh, Int8 nb_dof, bool does_linear_system_use_csr, bool use_atomic_free = false)
Definition at line 263 of file BSRFormat.cc.
References computeNbEdge(), Arcane::FemUtils::BSRMatrix::initialize(), m_bsr_matrix, m_mesh, m_nb_dof, m_use_atomic_free, and m_use_csr_in_linear_system.
Referenced by FemModuleElasticity::_initBsr(), and FemModulePoisson::compute().
matrix()
BSRMatrix & Arcane::FemUtils::BSRFormat::matrix ()
Definition at line 647 of file BSRFormat.cc.
References m_bsr_matrix.
pack()
static ARCCORE_HOST_DEVICE UInt64 Arcane::FemUtils::BSRFormat::pack (Int32 n0, Int32 n1) inline static
Definition at line 179 of file BSRFormat.h.
Referenced by computeSortedEdges().
registerEdgeInColumns()
static ARCCORE_HOST_DEVICE void Arcane::FemUtils::BSRFormat::registerEdgeInColumns (Int32 src, Int32 dst, Accelerator::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > offsets, Accelerator::NumArrayView< DataViewGetter< Int32 >, MDDim1, DefaultLayout > row_index, Accelerator::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > columns) inline static
Definition at line 197 of file BSRFormat.h.
Referenced by computeColumns().
resetMatrixValues()
void Arcane::FemUtils::BSRFormat::resetMatrixValues ()
Definition at line 656 of file BSRFormat.cc.
References Arcane::FemUtils::BSRMatrix::_values(), m_bsr_matrix, and m_queue.
toLinearSystem()
void Arcane::FemUtils::BSRFormat::toLinearSystem (DoFLinearSystem & linear_system)
Definition at line 291 of file BSRFormat.cc.
References Arcane::FemUtils::DoFLinearSystem::hasSetCSRValues(), m_bsr_matrix, m_csr_matrix, m_use_csr_in_linear_system, Arcane::FemUtils::DoFLinearSystem::setCSRValues(), Arcane::FemUtils::BSRMatrix::toCsr(), Arcane::FemUtils::BSRMatrix::toLinearSystem(), and Arcane::FemUtils::CsrFormat::view().
Referenced by FemModuleElasticity::_assembleBilinearOperator(), and FemModulePoisson::_assembleBilinearOperator().
unpack()
static ARCCORE_HOST_DEVICE void Arcane::FemUtils::BSRFormat::unpack (UInt64 packed_edge, Int32 & n0, Int32 & n1) inline static
Definition at line 186 of file BSRFormat.h.
Referenced by computeColumns(), and computeNeighbors().
Member Data Documentation
m_bsr_matrix
BSRMatrix Arcane::FemUtils::BSRFormat::m_bsr_matrix private
Definition at line 242 of file BSRFormat.h.
Referenced by assembleBilinearAtomic(), assembleBilinearAtomicFree(), assembleBilinearOrderedPerBlock(), assembleBilinearOrderedPerBlockAtomicFree(), assembleBilinearOrderedPerRow(), assembleBilinearOrderedPerRowAtomicFree(), computeColumns(), computeColumnsAtomicFree(), computeNzPerRowArray(), computeRowIndex(), computeRowIndexAtomicFree(), dumpMatrix(), initialize(), matrix(), resetMatrixValues(), and toLinearSystem().
m_csr_matrix
CsrFormat Arcane::FemUtils::BSRFormat::m_csr_matrix private
Definition at line 243 of file BSRFormat.h.
Referenced by toLinearSystem().
m_dofs_on_nodes
const FemDoFsOnNodes& Arcane::FemUtils::BSRFormat::m_dofs_on_nodes private
Definition at line 247 of file BSRFormat.h.
Referenced by assembleBilinearOrderedPerBlock(), and assembleBilinearOrderedPerRow().
m_mesh
IMesh* Arcane::FemUtils::BSRFormat::m_mesh = nullptr private
Definition at line 245 of file BSRFormat.h.
Referenced by assembleBilinearOrderedPerBlock(), assembleBilinearOrderedPerBlockAtomicFree(), assembleBilinearOrderedPerRow(), assembleBilinearOrderedPerRowAtomicFree(), computeColumns(), computeColumnsAtomicFree(), computeNeighborsAtomicFree(), computeRowIndex(), computeRowIndexAtomicFree(), computeSortedEdges(), computeSparsityAtomic(), and initialize().
m_nb_dof
Int8 Arcane::FemUtils::BSRFormat::m_nb_dof = 1 private
Definition at line 165 of file BSRFormat.h.
Referenced by initialize().
m_queue
RunQueue Arcane::FemUtils::BSRFormat::m_queue private
Definition at line 246 of file BSRFormat.h.
Referenced by assembleBilinearOrderedPerBlock(), assembleBilinearOrderedPerBlockAtomicFree(), assembleBilinearOrderedPerRow(), assembleBilinearOrderedPerRowAtomicFree(), computeColumns(), computeColumnsAtomicFree(), computeNeighbors(), computeNeighborsAtomicFree(), computeNzPerRowArray(), computeRowIndex(), computeRowIndexAtomicFree(), computeSortedEdges(), computeSparsityAtomic(), and resetMatrixValues().
m_use_atomic_free
bool Arcane::FemUtils::BSRFormat::m_use_atomic_free = false private
Definition at line 240 of file BSRFormat.h.
Referenced by assembleBilinear(), computeSparsity(), and initialize().
m_use_csr_in_linear_system
bool Arcane::FemUtils::BSRFormat::m_use_csr_in_linear_system = false private
Definition at line 239 of file BSRFormat.h.
Referenced by computeSparsityAtomic(), computeSparsityAtomicFree(), initialize(), and toLinearSystem().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/BSRFormat.h
src/CAWF/FEMUtils/BSRFormat.cc