ShArc: ArcaneFemFunctions::MeshOperation Class Reference
ArcaneFemFunctions::MeshOperation Class Reference
Provides methods for various mesh-related operations.
#include <ArcaneFemFunctions.h>
Static Public Member Functions
static Real computeAreaQuad4 (ItemWithNodes item, const VariableNodeReal3 &node_coord)
Computes the area of a quadrilateral defined by four nodes.
static Real computeAreaTria3 (ItemWithNodes item, const VariableNodeReal3 &node_coord)
Computes the area of a triangle defined by three nodes.
static Real3 computeBaryCenterTetra4 (Cell cell, const VariableNodeReal3 &node_coord)
Computes the barycenter (centroid) of a tetrahedron.
static Real3 computeBaryCenterTria3 (Cell cell, const VariableNodeReal3 &node_coord)
Computes the barycenter (centroid) of a triangle.
static Real computeFacLengthOrArea (Face face, const VariableNodeReal3 &node_coord)
Computes the factor used for integration of 1D, 2D and 3D finite elements.
static Real computeLengthEdge2 (ItemWithNodes item, const VariableNodeReal3 &node_coord)
Computes the length of the edge defined by a given face.
static Real2 computeNormalEdge2 (Face face, const VariableNodeReal3 &node_coord)
Computes the normalized edge normal for a given face.
static Real3 computeNormalQuad (Face face, const VariableNodeReal3 &node_coord)
Computes the normalized quad normal for a given face.
static Real3 computeNormalTriangle (Face face, const VariableNodeReal3 &node_coord)
Computes the normalized triangle normal for a given face.
static Real computeVolumeHexa8 (ItemWithNodes item, const VariableNodeReal3 &node_coord)
Computes the volume of a hexahedron defined by eight nodes.
static Real computeVolumeTetra4 (ItemWithNodes item, const VariableNodeReal3 &node_coord)
Computes the volume of a tetrahedra defined by four nodes.
static void dirVectors (Face face, const VariableNodeReal3 &node_coord, Integer ndim, Real3 &e1, Real3 &e2, Real3 &e3)
Computes edge & Face normal & tangent vectors (normalized, direct oriented) This method is used for the FEM 2D & 3D needs (coming from PASSMO) for geometric transformations (rotations, projections, ...) In 2D, it assumes the edge lies in x-y plane (z coord = 0.)
static Int32 getGeomDimension (ItemWithNodes item)
Computes finite-element entity (Edge, Face or Cell) geometric dimension This method is used for the FEM 2D & 3D needs (coming from PASSMO) for Jacobian & elementary matrices computations.
static Real penta6Volume (ItemWithNodes item, const VariableNodeReal3 &node_coord)
Computes the volume of a pentahedron (wedge or triangular prism) defined by six nodes.
static Real pyramid5Volume (ItemWithNodes item, const VariableNodeReal3 &node_coord)
Computes the volume of a pyramid defined by five nodes.
Detailed Description
Provides methods for various mesh-related operations.
This class includes static methods for computing geometric properties of mesh elements, such as the area of triangles, the length of edges, and the normal vectors of edges.
Definition at line 111 of file ArcaneFemFunctions.h.
Member Function Documentation
computeAreaQuad4()
static Real ArcaneFemFunctions::MeshOperation::computeAreaQuad4 (ItemWithNodes item, const VariableNodeReal3 & node_coord) inline static
Computes the area of a quadrilateral defined by four nodes.
This method calculates the area of a quadrilateral by breaking it down into two triangles and using the determinant formula. The area is computed as half the value of the determinant of the matrix formed by the coordinates of the quadrilateral's vertices.
Definition at line 174 of file ArcaneFemFunctions.h.
computeAreaTria3()
static Real ArcaneFemFunctions::MeshOperation::computeAreaTria3 (ItemWithNodes item, const VariableNodeReal3 & node_coord) inline static
Computes the area of a triangle defined by three nodes.
This method calculates the area using the determinant formula for a triangle. The area is computed as half the value of the determinant of the matrix formed by the coordinates of the triangle's vertices.
Definition at line 152 of file ArcaneFemFunctions.h.
Referenced by FemModuleElasticity::_applyBodyForce(), FemModuleElasticity::_computeElementMatrixTria3(), FemModulePoisson::_computeElementMatrixTria3(), ArcaneFemFunctions::BoundaryConditions2D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyManufacturedSourceToRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsTetra4(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsTetra4(), and ArcaneFemFunctions::BoundaryConditions2D::integrateNodalFieldToRhsTria3().
computeBaryCenterTetra4()
static Real3 ArcaneFemFunctions::MeshOperation::computeBaryCenterTetra4 (Cell cell, const VariableNodeReal3 & node_coord) inline static
Computes the barycenter (centroid) of a tetrahedron.
This method calculates the barycenter of a tetrahedron defined by its nodes. The barycenter is computed as the average of the vertices' coordinates.
Definition at line 294 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::BoundaryConditions3D::applyManufacturedSourceToRhs().
computeBaryCenterTria3()
static Real3 ArcaneFemFunctions::MeshOperation::computeBaryCenterTria3 (Cell cell, const VariableNodeReal3 & node_coord) inline static
Computes the barycenter (centroid) of a triangle.
This method calculates the barycenter of a triangle defined by three nodes. The barycenter is computed as the average of the vertices' coordinates.
Definition at line 273 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::BoundaryConditions2D::applyManufacturedSourceToRhs().
computeFacLengthOrArea()
static Real ArcaneFemFunctions::MeshOperation::computeFacLengthOrArea (Face face, const VariableNodeReal3 & node_coord) inline static
Computes the factor used for integration of 1D, 2D and 3D finite elements.
This method calculates length or surface for a given finite-element (P1, P2, ...) and returns the associated factor for elementary integrals.
Definition at line 356 of file ArcaneFemFunctions.h.
References Arcane::FemUtils::Gpu::MeshOperation::computeAreaTria3().
computeLengthEdge2()
static Real ArcaneFemFunctions::MeshOperation::computeLengthEdge2 (ItemWithNodes item, const VariableNodeReal3 & node_coord) inline static
Computes the length of the edge defined by a given face.
This method calculates Euclidean distance between the two nodes of the face.
Definition at line 316 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsTria3(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsQuad4(), and ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsTria3().
computeNormalEdge2()
static Real2 ArcaneFemFunctions::MeshOperation::computeNormalEdge2 (Face face, const VariableNodeReal3 & node_coord) inline static
Computes the normalized edge normal for a given face.
This method calculates normal vector to the edge defined by nodes of the face, normalizes it, and ensures the correct orientation.
Definition at line 333 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhsQuad4(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsQuad4(), and ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsQuad4().
computeNormalQuad()
static Real3 ArcaneFemFunctions::MeshOperation::computeNormalQuad (Face face, const VariableNodeReal3 & node_coord) inline static
Computes the normalized quad normal for a given face.
This method calculates normal vector to the quad defined by nodes, of the face and normalizes it, and ensures the correct orientation. Newell's Method is used to compute the normal vector for the quadrilateral.
Definition at line 434 of file ArcaneFemFunctions.h.
computeNormalTriangle()
static Real3 ArcaneFemFunctions::MeshOperation::computeNormalTriangle (Face face, const VariableNodeReal3 & node_coord) inline static
Computes the normalized triangle normal for a given face.
This method calculates normal vector to the triangle defined by nodes, of the face and normalizes it, and ensures the correct orientation.
Definition at line 395 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs().
computeVolumeHexa8()
static Real ArcaneFemFunctions::MeshOperation::computeVolumeHexa8 (ItemWithNodes item, const VariableNodeReal3 & node_coord) inline static
Computes the volume of a hexahedron defined by eight nodes.
Definition at line 192 of file ArcaneFemFunctions.h.
computeVolumeTetra4()
static Real ArcaneFemFunctions::MeshOperation::computeVolumeTetra4 (ItemWithNodes item, const VariableNodeReal3 & node_coord) inline static
Computes the volume of a tetrahedra defined by four nodes.
This method calculates the volume using the scalar triple product formula. We do the following:
get the four nodes
ge the vector representing the edges of tetrahedron
compute volume using scalar triple product
Definition at line 128 of file ArcaneFemFunctions.h.
Referenced by FemModuleElasticity::_applyBodyForce(), FemModuleElasticity::_computeElementMatrixTetra4(), FemModulePoisson::_computeElementMatrixTetra4(), ArcaneFemFunctions::BoundaryConditions3D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyManufacturedSourceToRhs(), and ArcaneFemFunctions::BoundaryConditions3D::integrateNodalFieldToRhsTetra4().
dirVectors()
static void ArcaneFemFunctions::MeshOperation::dirVectors (Face face, const VariableNodeReal3 & node_coord, Integer ndim, Real3 & e1, Real3 & e2, Real3 & e3) inline static
Computes edge & Face normal & tangent vectors (normalized, direct oriented) This method is used for the FEM 2D & 3D needs (coming from PASSMO) for geometric transformations (rotations, projections, ...) In 2D, it assumes the edge lies in x-y plane (z coord = 0.)
Definition at line 474 of file ArcaneFemFunctions.h.
getGeomDimension()
static Int32 ArcaneFemFunctions::MeshOperation::getGeomDimension (ItemWithNodes item) inline static
Computes finite-element entity (Edge, Face or Cell) geometric dimension This method is used for the FEM 2D & 3D needs (coming from PASSMO) for Jacobian & elementary matrices computations.
Definition at line 461 of file ArcaneFemFunctions.h.
penta6Volume()
static Real ArcaneFemFunctions::MeshOperation::penta6Volume (ItemWithNodes item, const VariableNodeReal3 & node_coord) inline static
Computes the volume of a pentahedron (wedge or triangular prism) defined by six nodes.
Definition at line 216 of file ArcaneFemFunctions.h.
pyramid5Volume()
static Real ArcaneFemFunctions::MeshOperation::pyramid5Volume (ItemWithNodes item, const VariableNodeReal3 & node_coord) inline static
Computes the volume of a pyramid defined by five nodes.
Definition at line 240 of file ArcaneFemFunctions.h.
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/ArcaneFemFunctions.h