ShArc: Arcane::FemUtils::FemDoFsOnNodes Class Reference
Arcane::FemUtils::FemDoFsOnNodes Class Reference
Manage one or more DoFs on Nodes.
#include <FemDoFsOnNodes.h>
Classes
class Impl
Public Member Functions
FemDoFsOnNodes (Arcane::ITraceMng *tm)
FemDoFsOnNodes (const FemDoFsOnNodes &)=delete
FemDoFsOnNodes (FemDoFsOnNodes &&)=delete
~FemDoFsOnNodes ()
Arcane::IItemFamily * dofFamily () const
void initialize (Arcane::IMesh *mesh, Arcane::Int32 nb_dof_per_node)
Initialize the instance.
Arcane::IndexedNodeDoFConnectivityView nodeDoFConnectivityView () const
FemDoFsOnNodes & operator= (const FemDoFsOnNodes &)=delete
FemDoFsOnNodes & operator= (FemDoFsOnNodes &&)=delete
Private Attributes
Impl * m_p = nullptr
Detailed Description
Manage one or more DoFs on Nodes.
Before using an instance of this class you need to call method initialize().
After initialization, you can access DoFs like that:
FemDoFsOnNodes dofs_on_nodes = ...;
auto node_dof(m_dofs_on_nodes.nodeDoFConnectivityView());
Node node = ...
DoFLocalId dof0 = node_dof.dofId(node, 0); //< First DoF of the node
DoFLocalId dof1 = node_dof.dofId(node, 1); //< Second DoF of the node
Definition at line 45 of file FemDoFsOnNodes.h.
Constructor & Destructor Documentation
FemDoFsOnNodes() [1/3]
Arcane::FemUtils::FemDoFsOnNodes::FemDoFsOnNodes (Arcane::ITraceMng * tm)
~FemDoFsOnNodes()
Arcane::FemUtils::FemDoFsOnNodes::~FemDoFsOnNodes ()
Definition at line 62 of file FemDoFsOnNodes.cc.
References m_p.
FemDoFsOnNodes() [2/3]
Arcane::FemUtils::FemDoFsOnNodes::FemDoFsOnNodes (const FemDoFsOnNodes &) delete
FemDoFsOnNodes() [3/3]
Arcane::FemUtils::FemDoFsOnNodes::FemDoFsOnNodes (FemDoFsOnNodes &&) delete
Member Function Documentation
dofFamily()
IItemFamily * Arcane::FemUtils::FemDoFsOnNodes::dofFamily () const
Definition at line 154 of file FemDoFsOnNodes.cc.
References Arcane::FemUtils::FemDoFsOnNodes::Impl::m_dof_family, and m_p.
Referenced by FemModulePoisson::compute(), FemModuleElasticity::computeDivU(), Arcane::FemUtils::AlienBSRFormat::initialize(), and FemModulePoisson::startInit().
initialize()
void Arcane::FemUtils::FemDoFsOnNodes::initialize (Arcane::IMesh * mesh, Arcane::Int32 nb_dof_per_node)
Initialize the instance.
Definition at line 136 of file FemDoFsOnNodes.cc.
References Arcane::FemUtils::FemDoFsOnNodes::Impl::initialize(), and m_p.
Referenced by FemModuleElasticity::computeDivU(), and FemModulePoisson::startInit().
nodeDoFConnectivityView()
IndexedNodeDoFConnectivityView Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView () const
Definition at line 145 of file FemDoFsOnNodes.cc.
References Arcane::FemUtils::FemDoFsOnNodes::Impl::m_node_dof_connectivity, and m_p.
Referenced by FemModulePoisson::_assembleBilinear(), FemModuleElasticity::_assembleBilinearOperatorCpu(), FemModuleElasticity::_assembleBilinearOperatorGpu(), FemModuleElasticity::_assembleLinearOperator(), FemModulePoisson::_assembleLinearOperatorCpu(), FemModuleElasticity::_defineMatrixProfile(), FemModuleElasticity::_updateVariables(), FemModulePoisson::_updateVariables(), Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyConstantSourceToRhsBase(), Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupRhsOnly(), Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaPenalty(), Arcane::FemUtils::Gpu::BoundaryConditionsHelpers::applyDirichletToNodeGroupViaRowOrRowColumnElimination(), Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerBlock(), Arcane::FemUtils::AlienBSRFormat::assembleBilinearOrderedPerRow(), and Arcane::FemUtils::BSRFormat::assembleBilinearOrderedPerRow().
operator=() [1/2]
FemDoFsOnNodes& Arcane::FemUtils::FemDoFsOnNodes::operator= (const FemDoFsOnNodes &) delete
operator=() [2/2]
FemDoFsOnNodes& Arcane::FemUtils::FemDoFsOnNodes::operator= (FemDoFsOnNodes &&) delete
Member Data Documentation
m_p
Impl* Arcane::FemUtils::FemDoFsOnNodes::m_p = nullptr private
Definition at line 75 of file FemDoFsOnNodes.h.
Referenced by ~FemDoFsOnNodes(), dofFamily(), initialize(), and nodeDoFConnectivityView().
The documentation for this class was generated from the following files:
src/CAWF/FEMUtils/FemDoFsOnNodes.h
src/CAWF/FEMUtils/FemDoFsOnNodes.cc