ShArc: Arcane::FemUtils::PETScDoFLinearSystemImpl Class Reference
Arcane::FemUtils::PETScDoFLinearSystemImpl Class Reference
Public Member Functions
PETScDoFLinearSystemImpl (IItemFamily *dof_family, const String &solver_name)
~PETScDoFLinearSystemImpl () override
void build ()
void setAbsTolerance (Real v)
void setMaxIter (Int32 v)
void setPreconditioner (String v)
void setRelTolerance (Real v)
void setSolver (String v)
void setSolverCommandLineArguments (const CommandLineArguments &args) override
Set user parameters to PETSc.
void solve () override
Solve the linear system.
Public Member Functions inherited from Arcane::FemUtils::CsrDoFLinearSystemImpl
CsrDoFLinearSystemImpl (IItemFamily *dof_family, const String &solver_name)
void _applyForcedValuesToLhs ()
void _applyRowColumnEliminationOnMatrix ()
void _applyRowEliminationOnMatrix ()
void _applyRowOrRowColumnEliminationOnRHS ()
void _fillRowColumnEliminationInfos ()
void applyMatrixTransformation () override
void applyRHSTransformation () override
void clearValues () override
void eliminateRow (DoFLocalId row, Real value) override
void eliminateRowColumn (DoFLocalId row, Real value) override
CSRFormatView & getCSRValues () override
bool hasSetCSRValues () const override
Int32 indexValue (DoFLocalId row_lid, DoFLocalId column_lid)
void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) override
void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) override
void setCSRValues (const CSRFormatView &csr_view) override
Public Member Functions inherited from Arcane::FemUtils::DoFLinearSystemImplBase
DoFLinearSystemImplBase (IItemFamily *dof_family, const String &solver_name)
void clearValues () override
IItemFamily * dofFamily () const
VariableDoFByte & getEliminationInfo () final
VariableDoFReal & getEliminationValue () final
VariableDoFBool & getForcedInfo () final
VariableDoFReal & getForcedValue () final
bool isMatrixSparsityConstant () const final
bool isMatrixValuesConstant () const final
VariableDoFReal & rhsVariable () final
Runner runner () const override
void setConstantMatrixSparsity (const bool val) final
void setConstantMatrixValues (const bool val) final
void setRunner (const Runner &r) override
VariableDoFReal & solutionVariable () final
Public Member Functions inherited from Arcane::FemUtils::IDoFLinearSystemImpl
virtual ~IDoFLinearSystemImpl ()=default
Public Attributes
CaseOptionsPETScDoFLinearSystemFactory * options
Private Member Functions
void _computeMatrixNumeration ()
Compute global numeration of the matrix.
void _handleParameters (IParallelMng *pm)
Set default parameters to PETSc.
void _initSolve ()
Initialize the solving.
void _preallocateMatrix ()
Allocate matrix related PETSc objects.
Private Attributes
VariableDoFInt32 m_dof_matrix_numbering
Int32 m_first_row
bool m_is_initialized = false
Indicates if the solve function has already been called.
Real m_ksp_atol
Int32 m_ksp_max_it
Real m_ksp_rtol
std::string m_ksp_type
std::string m_mat_type
Int32 m_nb_own_row
Int32 m_nb_total_row
NumArray< Int32, MDDim1 > m_parallel_columns_index
NumArray< Int32, MDDim1 > m_parallel_rows_index
std::string m_pc_type
ISLocalToGlobalMapping m_petsc_map
Mat m_petsc_matrix
Vec m_petsc_rhs_vector
Vec m_petsc_solution_vector
KSP m_petsc_solver_context
NumArray< Real, MDDim1 > m_result_work_values
Work array to store values of solution vector in parallel.
NumArray< Real, MDDim1 > m_rhs_work_values
std::string m_vec_type
Additional Inherited Members
Protected Member Functions inherited from Arcane::FemUtils::CsrDoFLinearSystemImpl
void _applyRowOrRowColumnEliminationOnMatrix ()
Protected Member Functions inherited from Arcane::FemUtils::DoFLinearSystemImplBase
void _applyRowColumnEliminationToRHS (bool is_verbose)
OrderedRowColumnMap & _rowColumnEliminationMap ()
Detailed Description
Definition at line 50 of file PETScDoFLinearSystem.cc.
Constructor & Destructor Documentation
PETScDoFLinearSystemImpl()
Arcane::FemUtils::PETScDoFLinearSystemImpl::PETScDoFLinearSystemImpl (IItemFamily * dof_family, const String & solver_name) inline
Definition at line 55 of file PETScDoFLinearSystem.cc.
~PETScDoFLinearSystemImpl()
Arcane::FemUtils::PETScDoFLinearSystemImpl::~PETScDoFLinearSystemImpl () inline override
Definition at line 62 of file PETScDoFLinearSystem.cc.
Member Function Documentation
_computeMatrixNumeration()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::_computeMatrixNumeration () private
Compute global numeration of the matrix.
Each rank owns consecutive rows of the matrix in increasing order.
Definition at line 244 of file PETScDoFLinearSystem.cc.
_handleParameters()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::_handleParameters (IParallelMng * pm) private
Set default parameters to PETSc.
This function will call PetscInitialized() if it still does not had been called.
It will then deduct the default mat_type and vec_type.
Finally, the function will set default parameters to PETSc only if the user did not already set this parameter via the -A,petsc_flags option.
Definition at line 172 of file PETScDoFLinearSystem.cc.
References PETSC_OPTION, and PETSC_OPTION_STRING.
_initSolve()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::_initSolve () private
Initialize the solving.
The initialization does several things:
calls handleParameters()
calls computeMatrixNumeration()
handle PETSc objects preallocation
For allocation of PETSc objects:
If the matrix has a constant sparsity, it will preallocate the matrix in this function and free it at the destruction of this object. Otherwise, the matrix will be allocated and freed at each call to the solve() function. The same applies for the KSP object and the IS map.
If the matrix has constant values, it will set the values in the matrix in this function. Otherwise, the matrix values will be set at each call to the solve() function.
At the end of the function, we set the m_is_initialized attribute to true to indicate that we do not need to call this function again.
Definition at line 378 of file PETScDoFLinearSystem.cc.
References Arcane::FemUtils::CsrFormatMatrixView::values().
_preallocateMatrix()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::_preallocateMatrix () private
Allocate matrix related PETSc objects.
The function allocates the matrix in COO format, the KSP solver and the IS map.
Definition at line 297 of file PETScDoFLinearSystem.cc.
References Arcane::FemUtils::_translateCSRToCOO(), Arcane::FemUtils::CsrFormatMatrixView::columns(), Arcane::FemUtils::CsrFormatMatrixView::nbValue(), and Arcane::FemUtils::CsrFormatMatrixView::rows().
build()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::build () inline
Definition at line 80 of file PETScDoFLinearSystem.cc.
setAbsTolerance()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::setAbsTolerance (Real v) inline
Definition at line 109 of file PETScDoFLinearSystem.cc.
setMaxIter()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::setMaxIter (Int32 v) inline
Definition at line 107 of file PETScDoFLinearSystem.cc.
setPreconditioner()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::setPreconditioner (String v) inline
Definition at line 112 of file PETScDoFLinearSystem.cc.
setRelTolerance()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::setRelTolerance (Real v) inline
Definition at line 108 of file PETScDoFLinearSystem.cc.
setSolver()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::setSolver (String v) inline
Definition at line 111 of file PETScDoFLinearSystem.cc.
setSolverCommandLineArguments()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::setSolverCommandLineArguments (const CommandLineArguments & args) inline override virtual
Set user parameters to PETSc.
This function will call PetscInitialized() with the argc and argv of the -A,petsc_flags option. This will set the parameters passed by the user to PETSc.
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 96 of file PETScDoFLinearSystem.cc.
solve()
void Arcane::FemUtils::PETScDoFLinearSystemImpl::solve () override virtual
Solve the linear system.
The function call _initSolve function on its first time been called.
The function calls _preallocateMatrix if necessary, and allocates the vectors.
It then calls KSPSolve from the PETSc library to solve the linear system, and put the result in the m_petsc_solution_vector attribute of the class.
Before every allocation / deallocation, the function makes sure to check the constant sparsity and constant values to avoid a double free error or a use after free error.
Implements Arcane::FemUtils::IDoFLinearSystemImpl.
Definition at line 427 of file PETScDoFLinearSystem.cc.
References Arcane::FemUtils::a1, Arcane::FemUtils::a2, Arcane::FemUtils::b2, and Arcane::FemUtils::CsrFormatMatrixView::values().
Member Data Documentation
m_dof_matrix_numbering
VariableDoFInt32 Arcane::FemUtils::PETScDoFLinearSystemImpl::m_dof_matrix_numbering private
Definition at line 129 of file PETScDoFLinearSystem.cc.
m_first_row
Int32 Arcane::FemUtils::PETScDoFLinearSystemImpl::m_first_row private
Definition at line 139 of file PETScDoFLinearSystem.cc.
m_is_initialized
bool Arcane::FemUtils::PETScDoFLinearSystemImpl::m_is_initialized = false private
Indicates if the solve function has already been called.
Definition at line 125 of file PETScDoFLinearSystem.cc.
m_ksp_atol
Real Arcane::FemUtils::PETScDoFLinearSystemImpl::m_ksp_atol private
Definition at line 143 of file PETScDoFLinearSystem.cc.
m_ksp_max_it
Int32 Arcane::FemUtils::PETScDoFLinearSystemImpl::m_ksp_max_it private
Definition at line 140 of file PETScDoFLinearSystem.cc.
m_ksp_rtol
Real Arcane::FemUtils::PETScDoFLinearSystemImpl::m_ksp_rtol private
Definition at line 142 of file PETScDoFLinearSystem.cc.
m_ksp_type
std::string Arcane::FemUtils::PETScDoFLinearSystemImpl::m_ksp_type private
Definition at line 145 of file PETScDoFLinearSystem.cc.
m_mat_type
std::string Arcane::FemUtils::PETScDoFLinearSystemImpl::m_mat_type private
Definition at line 147 of file PETScDoFLinearSystem.cc.
m_nb_own_row
Int32 Arcane::FemUtils::PETScDoFLinearSystemImpl::m_nb_own_row private
Definition at line 138 of file PETScDoFLinearSystem.cc.
m_nb_total_row
Int32 Arcane::FemUtils::PETScDoFLinearSystemImpl::m_nb_total_row private
Definition at line 137 of file PETScDoFLinearSystem.cc.
m_parallel_columns_index
NumArray<Int32, MDDim1> Arcane::FemUtils::PETScDoFLinearSystemImpl::m_parallel_columns_index private
Definition at line 131 of file PETScDoFLinearSystem.cc.
m_parallel_rows_index
NumArray<Int32, MDDim1> Arcane::FemUtils::PETScDoFLinearSystemImpl::m_parallel_rows_index private
Definition at line 132 of file PETScDoFLinearSystem.cc.
m_pc_type
std::string Arcane::FemUtils::PETScDoFLinearSystemImpl::m_pc_type private
Definition at line 146 of file PETScDoFLinearSystem.cc.
m_petsc_map
ISLocalToGlobalMapping Arcane::FemUtils::PETScDoFLinearSystemImpl::m_petsc_map private
Definition at line 122 of file PETScDoFLinearSystem.cc.
m_petsc_matrix
Mat Arcane::FemUtils::PETScDoFLinearSystemImpl::m_petsc_matrix private
Definition at line 121 of file PETScDoFLinearSystem.cc.
m_petsc_rhs_vector
Vec Arcane::FemUtils::PETScDoFLinearSystemImpl::m_petsc_rhs_vector private
Definition at line 120 of file PETScDoFLinearSystem.cc.
m_petsc_solution_vector
Vec Arcane::FemUtils::PETScDoFLinearSystemImpl::m_petsc_solution_vector private
Definition at line 119 of file PETScDoFLinearSystem.cc.
m_petsc_solver_context
KSP Arcane::FemUtils::PETScDoFLinearSystemImpl::m_petsc_solver_context private
Definition at line 118 of file PETScDoFLinearSystem.cc.
m_result_work_values
NumArray<Real, MDDim1> Arcane::FemUtils::PETScDoFLinearSystemImpl::m_result_work_values private
Work array to store values of solution vector in parallel.
Definition at line 135 of file PETScDoFLinearSystem.cc.
m_rhs_work_values
NumArray<Real, MDDim1> Arcane::FemUtils::PETScDoFLinearSystemImpl::m_rhs_work_values private
Definition at line 133 of file PETScDoFLinearSystem.cc.
m_vec_type
std::string Arcane::FemUtils::PETScDoFLinearSystemImpl::m_vec_type private
Definition at line 148 of file PETScDoFLinearSystem.cc.
options
CaseOptionsPETScDoFLinearSystemFactory* Arcane::FemUtils::PETScDoFLinearSystemImpl::options
Definition at line 114 of file PETScDoFLinearSystem.cc.
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/PETScDoFLinearSystem.cc