ShArc: WellEnumerator Class Reference
WellEnumerator Class Reference
Two-Phase Flow
Enumerator for iterating over well conditions.
#include <WellEnumerator.h>
Public Member Functions
WellEnumerator (const Arcane::Array< Folder * > &folders, const Arcane::StringArray &names, const Arcane::Array< Arcane::PartialVariableCellReal * > &well_index, const Arcane::ByteArray &is_flow)
WellEnumerator (const WellEnumerator &e)
Folder & folder ()
const Folder & folder () const
bool isFlow () const
const Arcane::PartialVariableCellReal & wellIndex () const
Public Member Functions inherited from FolderEnumerator< Law::ContainerKind::PartialVariable, Law::ItemKind::Cell >
FolderEnumerator (const Arcane::Array< Folder * > &folders, const Arcane::StringArray &names)
FolderEnumerator (const FolderEnumerator &e)
Folder & folder ()
const Folder & folder () const
bool hasNext () const
Arcane::Integer index () const
Arcane::String name () const
void operator++ ()
Arcane::Integer size () const
Private Types
typedef FolderEnumerator< Law::ContainerKind::PartialVariable, Law::ItemKind::Cell > Base
Private Attributes
const Arcane::Array< Folder * > & m_folders
const Arcane::ByteArray & m_is_flow
const Arcane::Array< Arcane::PartialVariableCellReal * > & m_well_index
Additional Inherited Members
Public Types inherited from FolderEnumerator< Law::ContainerKind::PartialVariable, Law::ItemKind::Cell >
typedef Law::VariableFolder< CK, IK > Folder
Detailed Description
Enumerator for iterating over well conditions.
AI-Generated Documentation:
Extends FolderEnumerator for well-specific data, providing access to well indices and flow flags in addition to folder and name.
Definition at line 21 of file WellEnumerator.h.
Member Typedef Documentation
Base
typedef FolderEnumerator<Law::ContainerKind::PartialVariable, Law::ItemKind::Cell> WellEnumerator::Base private
AI-Generated Documentation: Base class type
Definition at line 29 of file WellEnumerator.h.
Constructor & Destructor Documentation
WellEnumerator() [1/2]
WellEnumerator::WellEnumerator (const Arcane::Array< Folder * > & folders, const Arcane::StringArray & names, const Arcane::Array< Arcane::PartialVariableCellReal * > & well_index, const Arcane::ByteArray & is_flow) inline
AI-Generated Documentation: Constructs the well enumerator
Definition at line 34 of file WellEnumerator.h.
WellEnumerator() [2/2]
WellEnumerator::WellEnumerator (const WellEnumerator & e) inline
AI-Generated Documentation: Copy constructor
Definition at line 44 of file WellEnumerator.h.
Member Function Documentation
folder() [1/2]
Folder& WellEnumerator::folder () inline
AI-Generated Documentation: Access to the current folder (mutable)
Definition at line 54 of file WellEnumerator.h.
References FolderEnumerator< Law::ContainerKind::PartialVariable, Law::ItemKind::Cell >::index(), and m_folders.
folder() [2/2]
const Folder& WellEnumerator::folder () const inline
AI-Generated Documentation: Access to the current folder (const)
Definition at line 51 of file WellEnumerator.h.
References FolderEnumerator< Law::ContainerKind::PartialVariable, Law::ItemKind::Cell >::index(), and m_folders.
isFlow()
bool WellEnumerator::isFlow () const inline
AI-Generated Documentation: Whether the current well is producing (flow)
Definition at line 63 of file WellEnumerator.h.
References FolderEnumerator< Law::ContainerKind::PartialVariable, Law::ItemKind::Cell >::index(), and m_is_flow.
wellIndex()
const Arcane::PartialVariableCellReal& WellEnumerator::wellIndex () const inline
AI-Generated Documentation: Returns the Peaceman well index for the current well
Definition at line 57 of file WellEnumerator.h.
References FolderEnumerator< Law::ContainerKind::PartialVariable, Law::ItemKind::Cell >::index(), and m_well_index.
Member Data Documentation
m_folders
const Arcane::Array<Folder*>& WellEnumerator::m_folders private
AI-Generated Documentation: List of folders for each well
Definition at line 71 of file WellEnumerator.h.
Referenced by folder().
m_is_flow
const Arcane::ByteArray& WellEnumerator::m_is_flow private
AI-Generated Documentation: Array of flow flags per well
Definition at line 77 of file WellEnumerator.h.
Referenced by isFlow().
m_well_index
const Arcane::Array<Arcane::PartialVariableCellReal*>& WellEnumerator::m_well_index private
AI-Generated Documentation: List of well index variables for each well
Definition at line 74 of file WellEnumerator.h.
Referenced by wellIndex().
The documentation for this class was generated from the following file:
src/TwoPhaseFlowSimulation/WellCondition/WellEnumerator.h