ShArc: RelativePermeabilityPowerLaw Class Reference
RelativePermeabilityPowerLaw Class Reference
Two-Phase Flow
Relative permeability power law (Corey-type).
#include <RelativePermeabilityPowerLaw.h>
Public Member Functions
RelativePermeabilityPowerLaw ()
void eval (const Real Sw, Real &krw, Real &dkrw_dSw) const
AI comment: Evaluates relative permeability krw = SwBar^alpha.
void setParameters (const Real Swi, const Real Sgc, const Real alpha)
AI comment: Sets relative permeability parameters: irreducible saturations, exponent.
Private Member Functions
Real computeSwBar (const Real Sw, Real &dSwBar_dSw) const
AI comment: Computes normalized saturation SwBar = (Sw - Swi) / (1 - Sgc - Swi)
void initParameters ()
AI comment: Initializes relative permeability parameters to default values.
Private Attributes
Real m_alpha
Real m_Sgc
Real m_Swi
Detailed Description
Relative permeability power law (Corey-type).
AI-Generated Documentation:
Computes wetting-phase relative permeability using the Corey power-law model: \(k_{rw}(S_w) \propto \bar{S}_w^\alpha\) where \(\bar{S}_w = (S_w - S_{wi}) / (1 - S_{wi} - S_{gc})\), with irreducible wetting saturation \(S_{wi}\), residual non-wetting saturation \(S_{gc}\), and exponent \(\alpha\).
Definition at line 29 of file RelativePermeabilityPowerLaw.h.
Constructor & Destructor Documentation
RelativePermeabilityPowerLaw()
RelativePermeabilityPowerLaw::RelativePermeabilityPowerLaw () inline
AI-Generated Documentation: Constructs the law with default parameters
Definition at line 34 of file RelativePermeabilityPowerLaw.h.
References initParameters().
Member Function Documentation
computeSwBar()
Real RelativePermeabilityPowerLaw::computeSwBar (const Real Sw, Real & dSwBar_dSw) const private
AI comment: Computes normalized saturation SwBar = (Sw - Swi) / (1 - Sgc - Swi)
AI-Generated Documentation: Computes normalized saturation #42
and its derivative
Definition at line 35 of file RelativePermeabilityPowerLaw.cc.
References m_Sgc, and m_Swi.
Referenced by eval().
eval()
void RelativePermeabilityPowerLaw::eval (const Real Sw, Real & krw, Real & dkrw_dSw) const
AI comment: Evaluates relative permeability krw = SwBar^alpha.
AI-Generated Documentation: Evaluates relative permeability and its derivative
Parameters
Sw Wetting-phase saturation
krw Relative permeability
dkrw_dSw Derivative of krw wrt Sw
Definition at line 23 of file RelativePermeabilityPowerLaw.cc.
References computeSwBar(), and m_alpha.
Referenced by RelativePermeabilityPowerLawConfigService::configure().
initParameters()
void RelativePermeabilityPowerLaw::initParameters () private
AI comment: Initializes relative permeability parameters to default values.
AI-Generated Documentation: Initializes parameters to default values
Definition at line 72 of file RelativePermeabilityPowerLaw.cc.
References setParameters().
Referenced by RelativePermeabilityPowerLaw().
setParameters()
void RelativePermeabilityPowerLaw::setParameters (const Real Swi, const Real Sgc, const Real alpha)
AI comment: Sets relative permeability parameters: irreducible saturations, exponent.
AI-Generated Documentation: Sets the law parameters
Parameters
Swi Irreducible wetting saturation
Sgc Residual non-wetting saturation
alpha Power-law exponent
Definition at line 61 of file RelativePermeabilityPowerLaw.cc.
References m_alpha, m_Sgc, and m_Swi.
Referenced by RelativePermeabilityPowerLawConfigService::configure(), and initParameters().
Member Data Documentation
m_alpha
Real RelativePermeabilityPowerLaw::m_alpha private
AI-Generated Documentation: Power-law exponent
Definition at line 67 of file RelativePermeabilityPowerLaw.h.
Referenced by eval(), and setParameters().
m_Sgc
Real RelativePermeabilityPowerLaw::m_Sgc private
AI-Generated Documentation: Residual non-wetting saturation
Definition at line 65 of file RelativePermeabilityPowerLaw.h.
Referenced by computeSwBar(), and setParameters().
m_Swi
Real RelativePermeabilityPowerLaw::m_Swi private
AI-Generated Documentation: Irreducible wetting saturation
Definition at line 63 of file RelativePermeabilityPowerLaw.h.
Referenced by computeSwBar(), and setParameters().
The documentation for this class was generated from the following files:
src/TwoPhaseFlowSimulation/PhysicalLaws/RelativePermeabilityPowerLaw/RelativePermeabilityPowerLaw.h
src/TwoPhaseFlowSimulation/PhysicalLaws/RelativePermeabilityPowerLaw/RelativePermeabilityPowerLaw.cc