ShArc: BC::IArcaneFemBC Class Reference
BC::IArcaneFemBC Class Reference abstract
AI generated: Main interface for accessing all types of FEM boundary conditions.
#include <IArcaneFemBC.h>
Public Member Functions
virtual ~IArcaneFemBC ()=default
virtual ConstArrayView< BC::IDirichletBoundaryCondition * > dirichletBoundaryConditions ()=0
virtual ConstArrayView< BC::IDirichletPointCondition * > dirichletPointConditions ()=0
virtual String getHandler ()=0
virtual ConstArrayView< BC::IManufacturedSolution * > manufacturedSolutions ()=0
virtual ConstArrayView< BC::INeumannBoundaryCondition * > neumannBoundaryConditions ()=0
virtual ConstArrayView< BC::ITractionBoundaryCondition * > tractionBoundaryConditions ()=0
Detailed Description
AI generated: Main interface for accessing all types of FEM boundary conditions.
Definition at line 72 of file IArcaneFemBC.h.
Constructor & Destructor Documentation
~IArcaneFemBC()
virtual BC::IArcaneFemBC::~IArcaneFemBC () virtual default
Member Function Documentation
dirichletBoundaryConditions()
virtual ConstArrayView<BC::IDirichletBoundaryCondition*> BC::IArcaneFemBC::dirichletBoundaryConditions () pure virtual
Referenced by FemModuleElasticity::_applyDirichlet(), FemModuleElasticity::_assembleDirichletsGpu(), FemModulePoisson::_assembleLinearOperatorCpu(), and FemModulePoisson::_assembleLinearOperatorGpu().
dirichletPointConditions()
virtual ConstArrayView<BC::IDirichletPointCondition*> BC::IArcaneFemBC::dirichletPointConditions () pure virtual
Referenced by FemModuleElasticity::_applyDirichlet(), FemModuleElasticity::_assembleDirichletsGpu(), FemModulePoisson::_assembleLinearOperatorCpu(), and FemModulePoisson::_assembleLinearOperatorGpu().
getHandler()
virtual String BC::IArcaneFemBC::getHandler () pure virtual
manufacturedSolutions()
virtual ConstArrayView<BC::IManufacturedSolution*> BC::IArcaneFemBC::manufacturedSolutions () pure virtual
neumannBoundaryConditions()
virtual ConstArrayView<BC::INeumannBoundaryCondition*> BC::IArcaneFemBC::neumannBoundaryConditions () pure virtual
Referenced by FemModulePoisson::_assembleLinearOperatorCpu(), and FemModulePoisson::_assembleLinearOperatorGpu().
tractionBoundaryConditions()
virtual ConstArrayView<BC::ITractionBoundaryCondition*> BC::IArcaneFemBC::tractionBoundaryConditions () pure virtual
Referenced by FemModuleElasticity::_applyTraction().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/IArcaneFemBC.h