ShArc: BC::IDirichletPointCondition Class Reference
BC::IDirichletPointCondition Class Reference abstract
#include <IArcaneFemBC.h>
Public Member Functions
virtual String getEnforceDirichletMethod ()=0
virtual Arcane::NodeGroup getNode ()=0
virtual Real getPenalty ()=0
virtual StringConstArrayView getValue ()=0
Detailed Description
Definition at line 19 of file IArcaneFemBC.h.
Member Function Documentation
getEnforceDirichletMethod()
virtual String BC::IDirichletPointCondition::getEnforceDirichletMethod () pure virtual
Referenced by Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToRhs().
getNode()
virtual Arcane::NodeGroup BC::IDirichletPointCondition::getNode () pure virtual
Referenced by Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToRhs().
getPenalty()
virtual Real BC::IDirichletPointCondition::getPenalty () pure virtual
Referenced by Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToRhs().
getValue()
virtual StringConstArrayView BC::IDirichletPointCondition::getValue () pure virtual
Referenced by Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToRhs().
The documentation for this class was generated from the following file:
src/CAWF/FEMUtils/IArcaneFemBC.h