ShArc: src/CAWF/Elasticity/ElementMatrixHexQuad.h File Reference
ElementMatrixHexQuad.h File Reference
Functions
ARCCORE_HOST_DEVICE RealMatrix< 24, 24 > computeElementMatrixHexa8Base (const RealVector< 8 > &dxu, const RealVector< 8 > &dyu, const RealVector< 8 > &dzu, Real integration_weight, Real lambda, Real mu)
Computes the element matrix for a quadrilateral element (HEXA8, ℙ1 FE).
ARCCORE_HOST_DEVICE RealMatrix< 24, 24 > computeElementMatrixHexa8Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord, const Accelerator::VariableCellRealInView &lambda, const Accelerator::VariableCellRealInView &mu)
AI comment: GPU-accelerated wrapper for hexahedron element matrix computation.
ARCCORE_HOST_DEVICE RealMatrix< 8, 8 > computeElementMatrixQuad4Base (const RealVector< 4 > &dxu, const RealVector< 4 > &dyu, Real integration_weight, Real lambda, Real mu)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
ARCCORE_HOST_DEVICE RealMatrix< 8, 8 > computeElementMatrixQuad4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord, const Accelerator::VariableCellRealInView &lambda, const Accelerator::VariableCellRealInView &mu)
AI comment: GPU-accelerated wrapper for quadrilateral element matrix computation.
Function Documentation
computeElementMatrixHexa8Base()
ARCCORE_HOST_DEVICE RealMatrix<24, 24> computeElementMatrixHexa8Base (const RealVector< 8 > & dxu, const RealVector< 8 > & dyu, const RealVector< 8 > & dzu, Real integration_weight, Real lambda, Real mu)
Computes the element matrix for a quadrilateral element (HEXA8, ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫∫ [σ(𝐮):ε(𝐯)dΩ with 𝐮 = (𝑢𝑥, 𝑢𝑦, 𝑢𝑧) and 𝐯 = (𝑣𝑥, 𝑣𝑦, 𝑣𝑧)
where:
σ(𝐮) is stress tensor with σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is strain tensor with εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
the bilinear integral expands to
a(𝐮,𝐯) = ∫∫∫ [σ_𝑥𝑥ε_𝑥𝑥 + σ_𝑦𝑦ε_𝑦𝑦 + σ_𝑧𝑧ε_𝑧𝑧 + 2σ_𝑥𝑦ε_𝑥𝑦 + 2σ_𝑦𝑧ε_𝑦𝑧 + 2σ_𝑧𝑥ε_𝑧𝑥]dΩ
this further expands to
a(𝐮,𝐯) = ∫∫∫ (λ+2μ)(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧)
∫∫∫ λ(∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑦/∂𝑦)
∫∫∫ μ(∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥) + μ(∂𝑢𝑧/∂𝑦 + ∂𝑢𝑦/∂𝑧)(∂𝑣𝑦/∂𝑧 + ∂𝑣𝑧/∂𝑦) + μ(∂𝑢𝑥/∂𝑧 + ∂𝑢𝑧/∂𝑥)(∂𝑣𝑧/∂𝑥 + ∂𝑣𝑥/∂𝑧)
The first term is "normal strain energy"
The second term is "compressibility effect"
The third term is "shear energy"
Definition at line 181 of file ElementMatrixHexQuad.h.
Referenced by FemModuleElasticity::_computeElementMatrixHexa8(), and computeElementMatrixHexa8Gpu().
computeElementMatrixHexa8Gpu()
ARCCORE_HOST_DEVICE RealMatrix<24, 24> computeElementMatrixHexa8Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord, const Accelerator::VariableCellRealInView & lambda, const Accelerator::VariableCellRealInView & mu)
AI comment: GPU-accelerated wrapper for hexahedron element matrix computation.
Definition at line 275 of file ElementMatrixHexQuad.h.
References computeElementMatrixHexa8Base(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientsAndJacobianHexa8(), and M_SQRT1_3.
computeElementMatrixQuad4Base()
ARCCORE_HOST_DEVICE RealMatrix<8, 8> computeElementMatrixQuad4Base (const RealVector< 4 > & dxu, const RealVector< 4 > & dyu, Real integration_weight, Real lambda, Real mu) inline
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫ σ(𝐮):ε(𝐯)dΩ with 𝐮 = (𝑢𝑥,𝑢𝑦) and 𝐯 = (𝑣𝑥,𝑣𝑦) σ(𝐮) is stress tensor with σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is strain tensor with εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
the bilinear integral expands to
a(𝐮,𝐯) = ∫∫ [σ_𝑥𝑥ε_𝑥𝑥 + σ_𝑦𝑦ε_𝑦𝑦 + 2σ_𝑥𝑦ε_𝑥𝑦]dΩ
this further expands to
a(𝐮,𝐯) = ∫∫ (λ+2μ)(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦)
∫∫ λ(∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦)
∫∫ μ(∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥)
The first term is "normal strain energy"
The second term is "compressibility effect"
The third term is "shear energy"
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 50 of file ElementMatrixHexQuad.h.
Referenced by FemModuleElasticity::_computeElementMatrixQuad4(), and computeElementMatrixQuad4Gpu().
computeElementMatrixQuad4Gpu()
ARCCORE_HOST_DEVICE RealMatrix<8, 8> computeElementMatrixQuad4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord, const Accelerator::VariableCellRealInView & lambda, const Accelerator::VariableCellRealInView & mu)
AI comment: GPU-accelerated wrapper for quadrilateral element matrix computation.
Definition at line 111 of file ElementMatrixHexQuad.h.
References computeElementMatrixQuad4Base(), Arcane::FemUtils::Gpu::FeOperation2D::computeGradientsAndJacobianQuad4(), and M_SQRT1_3.