ShArc: src/CAWF/Elasticity/ElementMatrix.h File Reference
ElementMatrix.h File Reference
Functions
ARCCORE_HOST_DEVICE RealMatrix< 12, 12 > computeElementMatrixTetra4Base (Real4 dxu, Real4 dyu, Real4 dzu, Real volume, Real lambda, Real mu)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
ARCCORE_HOST_DEVICE RealMatrix< 12, 12 > computeElementMatrixTetra4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord, const Accelerator::VariableCellRealInView &lambda, const Accelerator::VariableCellRealInView &mu)
AI comment: GPU-accelerated wrapper for tetrahedron element matrix computation.
ARCCORE_HOST_DEVICE RealMatrix< 6, 6 > computeElementMatrixTria3Base (Real3 dxu, Real3 dyu, Real area, Real lambda, Real mu)
Computes the element matrix for a triangular element (ℙ1 FE).
ARCCORE_HOST_DEVICE RealMatrix< 6, 6 > computeElementMatrixTria3Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord, const Accelerator::VariableCellRealInView &lambda, const Accelerator::VariableCellRealInView &mu)
AI comment: GPU-accelerated wrapper for triangular element matrix computation.
ARCCORE_HOST_DEVICE RealMatrix< 3, 12 > computeElementVectorTetra4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord, const Accelerator::VariableCellRealInView &lambda, const Accelerator::VariableCellRealInView &mu, Int32 node_lid)
AI comment: GPU-accelerated computation of a single row of the tetrahedron element matrix.
ARCCORE_HOST_DEVICE RealMatrix< 2, 6 > computeElementVectorTria3Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord, const Accelerator::VariableCellRealInView &lambda, const Accelerator::VariableCellRealInView &mu, Int32 node_lid)
Function Documentation
computeElementMatrixTetra4Base()
ARCCORE_HOST_DEVICE RealMatrix<12, 12> computeElementMatrixTetra4Base (Real4 dxu, Real4 dyu, Real4 dzu, Real volume, Real lambda, Real mu)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫∫ [σ(𝐮):ε(𝐯)dΩ with 𝐮 = (𝑢𝑥, 𝑢𝑦, 𝑢𝑧) and 𝐯 = (𝑣𝑥, 𝑣𝑦, 𝑣𝑧)
where:
σ(𝐮) is stress tensor with σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is strain tensor with εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
the bilinear integral expands to
a(𝐮,𝐯) = ∫∫∫ [σ_𝑥𝑥ε_𝑥𝑥 + σ_𝑦𝑦ε_𝑦𝑦 + σ_𝑧𝑧ε_𝑧𝑧 + 2σ_𝑥𝑦ε_𝑥𝑦 + 2σ_𝑦𝑧ε_𝑦𝑧 + 2σ_𝑧𝑥ε_𝑧𝑥]dΩ
this further expands to
a(𝐮,𝐯) = ∫∫∫ (λ+2μ)(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧)
∫∫∫ λ(∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑦/∂𝑦)
∫∫∫ μ(∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥) + μ(∂𝑢𝑧/∂𝑦 + ∂𝑢𝑦/∂𝑧)(∂𝑣𝑦/∂𝑧 + ∂𝑣𝑧/∂𝑦) + μ(∂𝑢𝑥/∂𝑧 + ∂𝑢𝑧/∂𝑥)(∂𝑣𝑧/∂𝑥 + ∂𝑣𝑥/∂𝑧)
The first term is "normal strain energy"
The second term is "compressibility effect"
The third term is "shear energy"
Definition at line 164 of file ElementMatrix.h.
Referenced by FemModuleElasticity::_computeElementMatrixTetra4(), and computeElementMatrixTetra4Gpu().
computeElementMatrixTetra4Gpu()
ARCCORE_HOST_DEVICE RealMatrix<12, 12> computeElementMatrixTetra4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord, const Accelerator::VariableCellRealInView & lambda, const Accelerator::VariableCellRealInView & mu)
AI comment: GPU-accelerated wrapper for tetrahedron element matrix computation.
Definition at line 218 of file ElementMatrix.h.
References computeElementMatrixTetra4Base(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientXTetra4(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientYTetra4(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientZTetra4(), and Arcane::FemUtils::Gpu::MeshOperation::computeVolumeTetra4().
Referenced by FemModuleElasticity::_assembleBilinearOperator().
computeElementMatrixTria3Base()
ARCCORE_HOST_DEVICE RealMatrix<6, 6> computeElementMatrixTria3Base (Real3 dxu, Real3 dyu, Real area, Real lambda, Real mu)
Computes the element matrix for a triangular element (ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫ σ(𝐮):ε(𝐯)dΩ with 𝐮 = (𝑢𝑥,𝑢𝑦) and 𝐯 = (𝑣𝑥,𝑣𝑦) σ(𝐮) is stress tensor with σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is strain tensor with εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
the bilinear integral expands to
a(𝐮,𝐯) = ∫∫ [σ_𝑥𝑥ε_𝑥𝑥 + σ_𝑦𝑦ε_𝑦𝑦 + 2σ_𝑥𝑦ε_𝑥𝑦]dΩ
this further expands to
a(𝐮,𝐯) = ∫∫ (λ+2μ)(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦)
∫∫ λ(∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦)
∫∫ μ(∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥)
The first term is "normal strain energy"
The second term is "compressibility effect"
The third term is "shear energy"
Definition at line 41 of file ElementMatrix.h.
Referenced by FemModuleElasticity::_computeElementMatrixTria3(), and computeElementMatrixTria3Gpu().
computeElementMatrixTria3Gpu()
ARCCORE_HOST_DEVICE RealMatrix<6, 6> computeElementMatrixTria3Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord, const Accelerator::VariableCellRealInView & lambda, const Accelerator::VariableCellRealInView & mu)
AI comment: GPU-accelerated wrapper for triangular element matrix computation.
Definition at line 65 of file ElementMatrix.h.
References Arcane::FemUtils::Gpu::MeshOperation::computeAreaTria3(), computeElementMatrixTria3Base(), Arcane::FemUtils::Gpu::FeOperation2D::computeGradientXTria3(), and Arcane::FemUtils::Gpu::FeOperation2D::computeGradientYTria3().
Referenced by FemModuleElasticity::_assembleBilinearOperator().
computeElementVectorTetra4Gpu()
ARCCORE_HOST_DEVICE RealMatrix<3, 12> computeElementVectorTetra4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord, const Accelerator::VariableCellRealInView & lambda, const Accelerator::VariableCellRealInView & mu, Int32 node_lid)
AI comment: GPU-accelerated computation of a single row of the tetrahedron element matrix.
Definition at line 238 of file ElementMatrix.h.
References Arcane::FemUtils::Gpu::FeOperation3D::computeGradientXTetra4(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientYTetra4(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientZTetra4(), and Arcane::FemUtils::Gpu::MeshOperation::computeVolumeTetra4().
Referenced by FemModuleElasticity::_assembleBilinearOperator().
computeElementVectorTria3Gpu()
ARCCORE_HOST_DEVICE RealMatrix<2, 6> computeElementVectorTria3Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord, const Accelerator::VariableCellRealInView & lambda, const Accelerator::VariableCellRealInView & mu, Int32 node_lid)
Definition at line 95 of file ElementMatrix.h.
References Arcane::FemUtils::Gpu::MeshOperation::computeAreaTria3(), Arcane::FemUtils::Gpu::FeOperation2D::computeGradientXTria3(), and Arcane::FemUtils::Gpu::FeOperation2D::computeGradientYTria3().
Referenced by FemModuleElasticity::_assembleBilinearOperator().