ShArc: Arcane::FemUtils Namespace Reference
Arcane::FemUtils Namespace Reference
Namespaces
Gpu
Classes
class AlephDoFLinearSystemFactoryService
class AlephDoFLinearSystemImpl
class AlienBSRFormat
A class for assembling Block Sparse Row (BSR) matrices from mesh data.
class AlienBSRMatrix
A class representing a Block Sparse Row (BSR) matrix.
class AlienDoFLinearSystemFactoryService
class AlienDoFLinearSystemImpl
AI generated: Implementation of DoFLinearSystem using Alien linear algebra.
class BSRFormat
A class for assembling Block Sparse Row (BSR) matrices from mesh data.
class BSRMatrix
A class representing a Block Sparse Row (BSR) matrix.
struct CaseTableInfo
Struct to associate a CaseTable with the right file.
class CooFormat
AI generated: Container for matrices in Coordinate (COO) format.
class CsrDoFLinearSystemImpl
class CsrFormat
AI generated: Container for matrices in Compressed Sparse Row (CSR) format.
class CsrFormatMatrixView
View of a Matrix with CSR format.
class CsrRow
Represents a row of a CSR Matrix.
class CsrRowColumnIndex
Index in the RowColumn list of a CSR Matrix.
class CsrRowColumnIterator
Represents an iterator over the indexes of the columns of a CsrRow.
class DefaultDoFLinearSystemFactory
Default factory for Linear System.
class DoFLinearSystem
Linear system Matrix A + Vector x + Vector b for Ax=b.
class DoFLinearSystemImplBase
class DoFLinearSystemRowColumnEliminationHelper
Helper class to handle RowColumn elimination.
class DoFLinearSystemRowEliminationHelper
Helper class to handle Row elimination.
class FemDoFsOnNodes
Manage one or more DoFs on Nodes.
class GaussDoFsOnCells
Manage one or more Gauss Points on Cells through the Arcane DoFs mechanism.
class HypreDoFLinearSystemFactoryService
class HypreDoFLinearSystemImpl
class IDoFLinearSystemFactory
AI generated: Interface for a factory that creates linear system implementations.
class IDoFLinearSystemImpl
class OrderedRowColumnMap
Ordered map to keep a set a values indexed by (row,column).
class PETScDoFLinearSystemFactoryService
class PETScDoFLinearSystemImpl
class RealMatrix
Matrix of size NxM.
class RealVector
Vector of size N.
class SequentialBasicDoFLinearSystemFactoryService
class SequentialDoFLinearSystemImpl
class Tensor2
AI generated: Represents a symmetric second-order tensor (Voigt notation, 6 components)
Typedefs
using CSRFormatView = CsrFormatMatrixView
AI generated: Legacy alias for CsrFormatMatrixView to maintain backward compatibility.
Enumerations
enum class eInternalSolverMethod { Auto , Direct , PCG }
enum class eSolverBackend { Hypre = 2 , Trilinos = 3 , PETSc = 5 }
enum class MatrixEliminationType : Byte { None = 0 , Row = 1 , RowColumn = 2 }
List of matrix elimination type.
enum class preconditioner { AMG , BJACOBI }
enum class solver { CG , GMRES , FGMRES , BICGSTAB }
Functions
void _convertNumArrayToCSRMatrix (Arcane::MatVec::Matrix &out_matrix, Arcane::MDSpan< const Arcane::Real, Arcane::MDDim2 > in_matrix)
Convert a dense matrix to an Arcane sequential CSR Matrix.
void _convertNumArrayToCSRMatrix (Matrix &out_matrix, MDSpan< const Real, MDDim2 > in_matrix)
void _translateCSRToCOO (Span< const Int32 > csr_rows, SmallSpan< Int32 > coo_rows, const RunQueue &queue)
Convert CSR format rows into COO format rows.
ARCANE_REGISTER_SERVICE_ALEPHDOFLINEARSYSTEMFACTORY (AlephLinearSystem, AlephDoFLinearSystemFactoryService)
ARCANE_REGISTER_SERVICE_ALIENDOFLINEARSYSTEMFACTORY (AlienLinearSystem, AlienDoFLinearSystemFactoryService)
ARCANE_REGISTER_SERVICE_HYPREDOFLINEARSYSTEMFACTORY (HypreLinearSystem, HypreDoFLinearSystemFactoryService)
ARCANE_REGISTER_SERVICE_PETSCDOFLINEARSYSTEMFACTORY (PETScLinearSystem, PETScDoFLinearSystemFactoryService)
ARCANE_REGISTER_SERVICE_SEQUENTIALBASICDOFLINEARSYSTEMFACTORY (SequentialBasicLinearSystem, SequentialBasicDoFLinearSystemFactoryService)
void checkNodeResultFile (ITraceMng *tm, const String &filename, const VariableNodeReal &node_values, double epsilon, double min_value=0.0)
Check the values of the variable against a reference file.
void checkNodeResultFile (ITraceMng *tm, const String &filename, const VariableNodeReal2 &node_values, double epsilon, double min_value=0.0)
Check the values of the variable against a reference file.
void checkNodeResultFile (ITraceMng *tm, const String &filename, const VariableNodeReal3 &node_values, double epsilon, double min_value=0.0)
Check the values of the variable against a reference file.
IDoFLinearSystemImpl * createAlephDoFLinearSystemImpl (ISubDomain *sd, IItemFamily *dof_family, const String &solver_name)
Real3 diagonalReal3x3 (const Real3x3 &mat)
Diagonal of a Real3x3 obtained as a new Real3x3 (useful for Passmo(nl) modules)
ARCCORE_HOST_DEVICE Int32 findIndexBinarySearch (Int32 row, Int32 col, const auto &in_row_coo, const auto &in_col_coo, Int32 row_length)
AI generated: Binary search for (row, col) index in a COO-formatted array.
template<int N>
RealMatrix< N, N > ARCCORE_HOST_DEVICE massMatrix (const RealMatrix< 1, N > &lhs, const RealMatrix< 1, N > &rhs)
AI generated: Computes the mass matrix (lhs^T * rhs) from row vector inputs.
template<int N>
RealMatrix< N, N > ARCCORE_HOST_DEVICE massMatrix (const RealVector< N > &lhs, const RealVector< N > &rhs)
AI generated: Computes the mass matrix as the outer product of two RealVector vectors.
template<int N, int M>
RealMatrix< N, N > ARCCORE_HOST_DEVICE matrixAddition (const RealMatrix< N, M > &a, const RealMatrix< M, N > &b)
AI generated: Element-wise addition of two matrices producing a square matrix.
template<int N, int M>
RealMatrix< N, N > ARCCORE_HOST_DEVICE matrixMultiplication (const RealMatrix< N, M > &a, const RealMatrix< M, N > &b)
AI generated: Matrix-matrix multiplication (a * b) producing a square matrix.
template<int N, int M>
RealMatrix< M, N > ARCCORE_HOST_DEVICE matrixTranspose (const RealMatrix< N, M > &a)
AI generated: Transpose of a matrix (swaps rows and columns)
template<int N>
RealVector< N > ARCCORE_HOST_DEVICE operator* (const RealVector< N > &lhs, const RealMatrix< N, N > &rhs)
AI generated: Matrix-vector product (lhs * rhs) for a RealVector and a RealMatrix.
ARCCORE_HOST_DEVICE RealMatrix< 3, 3 > operator^ (const Arcane::Real3 &lhs, const Arcane::Real3 &rhs)
AI generated: Outer product of two Real3 vectors producing a 3x3 matrix.
ARCCORE_HOST_DEVICE RealMatrix< 4, 4 > operator^ (const Real4 &lhs, const Real4 &rhs)
AI generated: Outer product of two Real4 vectors producing a 4x4 matrix.
template<int N>
RealMatrix< N, N > ARCCORE_HOST_DEVICE operator^ (const RealVector< N > &lhs, const RealVector< N > &rhs)
AI generated: Outer product of two RealVector vectors producing a square matrix.
Real3x3 outdiagonalReal3x3 (const Real3x3 &mat)
Diagonal of a Real3x3 obtained as a new Real3x3 (useful for Passmo(nl) modules)
CaseTable * readFileAsCaseTable (IParallelMng *pm, const String &filename, const Int32 &ndim)
Sample to read value from a file and create an associated CaseTable.
Real3 real3x3GetLowOutdiagonal (const Real3x3 &mat)
Return the out-diagonal terms of the lower part of a Real3x3 (useful for Passmo(nl) modules)
Real3 real3x3GetSupOutdiagonal (const Real3x3 &mat)
Return the out-diagonal terms of the upper part of a Real3x3 (useful for Passmo(nl) modules)
bool real3x3IsSym (const Arcane::Real3x3 &mat)
Checking whether a Real3x3 is symmetric (useful for Passmo(nl) modules)
bool real3x3IsSym (const Real3x3 &mat)
Real real3x3Trace (const Real3x3 &mat)
Compute the trace of a Real3x3 (useful for Passmo(nl) modules)
Variables
const Real a1 { 1. / 4. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 3.
const Real a2 { (5. - sqrt(5.)) / 20. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 2.
const Real ap1 { 0.5702963741068025 }
AI generated: Pyramid Gauss quadrature intermediate constant a_p1.
const Real apt1 { 1. / sqrt(3.) }
AI generated: Pentaedron Gauss quadrature intermediate constants.
const Real apt2 { 0.577350269189626 }
const Real b2 { (5. + 3. * sqrt(5.)) / 20. }
const Real b3 { 1. / 6. }
const Real b41 { (7. + sqrt(15.)) / 34. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 4 (group b)
const Real b42 { (7. - sqrt(15.)) / 34. }
const Real c3 { 1. / 2. }
const Real c41 { (13. - 3. * sqrt(15.)) / 34. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 4 (group c)
const Real c42 { (13. + 3. * sqrt(15.)) / 34. }
const Real d4 { (5. - sqrt(15.)) / 20. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 4 (group d/e)
const Real e4 { (5. + sqrt(15.)) / 20. }
static constexpr Byte ELIMINATE_NONE = static_cast<Byte>(MatrixEliminationType::None)
AI generated: Constant for matrix elimination type: none.
static constexpr Byte ELIMINATE_ROW = static_cast<Byte>(MatrixEliminationType::Row)
AI generated: Constant for matrix elimination type: row only.
static constexpr Byte ELIMINATE_ROW_COLUMN = static_cast<Byte>(MatrixEliminationType::RowColumn)
AI generated: Constant for matrix elimination type: row and column.
const Real hp21 { 0.1531754163448146 }
AI generated: Pyramid Gauss quadrature z-coordinate constants for order 2.
const Real hp22 { 0.6372983346207416 }
const Real hp31 { 1. / 6. }
AI generated: Pyramid Gauss quadrature z-coordinate constants for order 3.
const Real hp32 { 0.08063183038464675 }
const Real hp33 { 0.6098484849057127 }
const Integer maxnint = 9
AI generated: Maximum Gauss-Legendre quadrature order.
const Integer nptg [4] = { 1, 3, 4, 7 }
AI generated: Triangle Gauss quadrature number of integration points per order.
const Integer npwgpent3 [8] = { 0, 1, 1, 1, 0, 1, 1, 1 }
AI generated: Pentaedron weight-to-Gauss-point index mapping for order 3.
const Integer npwgpyr3 [6] = { 0, 0, 0, 0, 1, 2 }
AI generated: Pyramid weight-to-Gauss-point index mapping for order 3.
const Integer npwgtet3 [5] = { 0, 1, 1, 1 }
AI generated: Tetrahedron weight-to-Gauss-point index mapping for order 3.
const Integer npwgtet4 [15] = { 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3 }
AI generated: Tetrahedron weight-to-Gauss-point index mapping for order 4.
const Real wg [4][7]
AI generated: Triangle Gauss quadrature integration weights.
const Real wgauss1 = 2.
AI generated: Gauss-Legendre quadrature weight for order 1.
const Real wgauss2 [2] = { 1., 1. }
AI generated: Gauss-Legendre quadrature weight for order 2.
const Real wgauss3 [3] = { 5. / 9., 8. / 9., 5. / 9. }
AI generated: Gauss-Legendre quadrature weight for order 3.
const Real wgauss4 [4]
AI generated: Gauss-Legendre quadrature weight for order 4.
const Real wgauss5 [5]
AI generated: Gauss-Legendre quadrature weight for order 5.
const Real wgauss6 [6]
AI generated: Gauss-Legendre quadrature weight for order 6.
const Real wgauss7 [7]
AI generated: Gauss-Legendre quadrature weight for order 7.
const Real wgauss8 [8]
AI generated: Gauss-Legendre quadrature weight for order 8.
const Real wgauss9 [9]
AI generated: Gauss-Legendre quadrature weight for order 9.
const Real wgpent2 { 1. / 6. }
AI generated: Pentaedron Gauss quadrature weight for order 2.
const Real wgpent3 [2] { -27. / 96., 25. / 96. }
AI generated: Pentaedron Gauss quadrature weights for order 3.
const Real wgpyr2 { 2. / 15. }
AI generated: Pyramid Gauss quadrature weight for order 2.
const Real wgpyr3 [3] { 0.1024890634400000, 0.1100000000000000, 0.1467104129066667 }
AI generated: Pyramid Gauss quadrature weights for order 3.
const Real wgtet1 { 1. / 6. }
AI generated: Tetrahedron Gauss quadrature weight for order 1.
const Real wgtet2 { 1. / 24. }
AI generated: Tetrahedron Gauss quadrature weight for order 2.
const Real wgtet3 [2] = { -2. / 15., 3. / 40. }
AI generated: Tetrahedron Gauss quadrature weights for order 3.
const Real wgtet4 [4] = { 8. / 405., (2665 - 14. * sqrt(15)) / 226800., (2665 + 4. * sqrt(15)) / 226800., 5. / 567. }
AI generated: Tetrahedron Gauss quadrature weights for order 4.
const Real wgtetra = 1. / 24.
AI generated: Tetrahedron Gauss quadrature integration weight for order 2.
const Real xg1 [4][7]
AI generated: Triangle Gauss quadrature local x-coordinates on the first edge.
const Real xg2 [4][7]
AI generated: Triangle Gauss quadrature local x-coordinates on the second edge.
const Real xgauss1 = 0.
AI generated: Gauss-Legendre quadrature abscissa for order 1.
const Real xgauss2 [2] = { -1. / sqrt(3.), 1. / sqrt(3.) }
AI generated: Gauss-Legendre quadrature abscissa for order 2.
const Real xgauss3 [3] = { -sqrt(0.6), 0., sqrt(0.6) }
AI generated: Gauss-Legendre quadrature abscissa for order 3.
const Real xgauss4 [4]
AI generated: Gauss-Legendre quadrature abscissa for order 4.
const Real xgauss5 [5]
AI generated: Gauss-Legendre quadrature abscissa for order 5.
const Real xgauss6 [6]
AI generated: Gauss-Legendre quadrature abscissa for order 6.
const Real xgauss7 [7]
AI generated: Gauss-Legendre quadrature abscissa for order 7.
const Real xgauss8 [8]
AI generated: Gauss-Legendre quadrature abscissa for order 8.
const Real xgauss9 [9]
AI generated: Gauss-Legendre quadrature abscissa for order 9.
const Real xh { 0.5000000000000000 }
AI generated: Half-value constant (0.5) used in quadrature computations.
const Real xit [4] = { 0.58541020, 0.13819660, 0.13819660, 0.13819660 }
AI generated: Tetrahedron Gauss quadrature local x-coordinates.
const Real xpent [2][8]
AI generated: Pentaedron Gauss quadrature local x-coordinates for orders 2–3.
const Real xpyr [2][6]
AI generated: Pyramid Gauss quadrature local x-coordinates for orders 2–3.
const Real xtet [4][15]
AI generated: Tetrahedron Gauss quadrature local x-coordinates for orders 1–4.
const Real yit [4] = { 0.13819660, 0.58541020, 0.13819660, 0.13819660 }
AI generated: Tetrahedron Gauss quadrature local y-coordinates.
const Real ypent [2][8]
AI generated: Pentaedron Gauss quadrature local y-coordinates for orders 2–3.
const Real ypyr [2][6]
AI generated: Pyramid Gauss quadrature local y-coordinates for orders 2–3.
const Real ytet [4][15]
AI generated: Tetrahedron Gauss quadrature local y-coordinates for orders 1–4.
const Real zit [4] = { 0.13819660, 0.13819660, 0.58541020, 0.13819660 }
AI generated: Tetrahedron Gauss quadrature local z-coordinates.
const Real zpent [2][8]
AI generated: Pentaedron Gauss quadrature local z-coordinates for orders 2–3.
const Real zpyr [2][6]
AI generated: Pyramid Gauss quadrature local z-coordinates for orders 2–3.
const Real ztet [4][15]
AI generated: Tetrahedron Gauss quadrature local z-coordinates for orders 1–4.
Typedef Documentation
CSRFormatView
using Arcane::FemUtils::CSRFormatView = typedef CsrFormatMatrixView
AI generated: Legacy alias for CsrFormatMatrixView to maintain backward compatibility.
Definition at line 53 of file FemUtilsGlobal.h.
Enumeration Type Documentation
eInternalSolverMethod
enum Arcane::FemUtils::eInternalSolverMethod strong
Enumerator
Auto
Direct
PCG
Definition at line 36 of file DoFLinearSystem.cc.
eSolverBackend
enum Arcane::FemUtils::eSolverBackend strong
Enumerator
Hypre
Trilinos
PETSc
Definition at line 33 of file AlephDoFLinearSystem.cc.
MatrixEliminationType
enum Arcane::FemUtils::MatrixEliminationType : Byte strong
List of matrix elimination type.
Enumerator
None
No elimination.
Row
Row elimination.
RowColumn
RowColumn elimination.
Definition at line 60 of file FemUtilsGlobal.h.
preconditioner
enum Arcane::FemUtils::preconditioner strong
Enumerator
AMG
BJACOBI
Definition at line 53 of file HypreDoFLinearSystem.cc.
solver
enum Arcane::FemUtils::solver strong
Enumerator
CG
GMRES
FGMRES
BICGSTAB
Definition at line 45 of file HypreDoFLinearSystem.cc.
Function Documentation
_convertNumArrayToCSRMatrix() [1/2]
void Arcane::FemUtils::_convertNumArrayToCSRMatrix (Arcane::MatVec::Matrix & out_matrix, Arcane::MDSpan< const Arcane::Real, Arcane::MDDim2 > in_matrix)
Convert a dense matrix to an Arcane sequential CSR Matrix.
_convertNumArrayToCSRMatrix() [2/2]
void Arcane::FemUtils::_convertNumArrayToCSRMatrix (Matrix & out_matrix, MDSpan< const Real, MDDim2 > in_matrix)
Definition at line 36 of file FemUtils.cc.
Referenced by Arcane::FemUtils::SequentialDoFLinearSystemImpl::solve().
_translateCSRToCOO()
void Arcane::FemUtils::_translateCSRToCOO (Span< const Int32 > csr_rows, SmallSpan< Int32 > coo_rows, const RunQueue & queue)
Convert CSR format rows into COO format rows.
The computation will be done using RunQueue queue.
Definition at line 161 of file CsrFormatMatrix.cc.
Referenced by Arcane::FemUtils::PETScDoFLinearSystemImpl::_preallocateMatrix().
ARCANE_REGISTER_SERVICE_ALEPHDOFLINEARSYSTEMFACTORY()
Arcane::FemUtils::ARCANE_REGISTER_SERVICE_ALEPHDOFLINEARSYSTEMFACTORY (AlephLinearSystem , AlephDoFLinearSystemFactoryService)
ARCANE_REGISTER_SERVICE_ALIENDOFLINEARSYSTEMFACTORY()
Arcane::FemUtils::ARCANE_REGISTER_SERVICE_ALIENDOFLINEARSYSTEMFACTORY (AlienLinearSystem , AlienDoFLinearSystemFactoryService)
ARCANE_REGISTER_SERVICE_HYPREDOFLINEARSYSTEMFACTORY()
Arcane::FemUtils::ARCANE_REGISTER_SERVICE_HYPREDOFLINEARSYSTEMFACTORY (HypreLinearSystem , HypreDoFLinearSystemFactoryService)
ARCANE_REGISTER_SERVICE_PETSCDOFLINEARSYSTEMFACTORY()
Arcane::FemUtils::ARCANE_REGISTER_SERVICE_PETSCDOFLINEARSYSTEMFACTORY (PETScLinearSystem , PETScDoFLinearSystemFactoryService)
ARCANE_REGISTER_SERVICE_SEQUENTIALBASICDOFLINEARSYSTEMFACTORY()
Arcane::FemUtils::ARCANE_REGISTER_SERVICE_SEQUENTIALBASICDOFLINEARSYSTEMFACTORY (SequentialBasicLinearSystem , SequentialBasicDoFLinearSystemFactoryService)
checkNodeResultFile() [1/3]
void Arcane::FemUtils::checkNodeResultFile (ITraceMng * tm, const String & filename, const VariableNodeReal & node_values, double epsilon, double min_value = 0.0)
Check the values of the variable against a reference file.
The reference file filename is an ASCII file containing N values where N is the number of nodes in the mesh.
For each item the current value of node_values is compared to the reference value and if the relative difference is greater than epsilon this is an error.
Only values greater whose absolute value is greater than min_value are checked.
Definition at line 234 of file FemUtils.cc.
Referenced by FemModuleElasticity::_validateResults(), and FemModulePoisson::_validateResults().
checkNodeResultFile() [2/3]
void Arcane::FemUtils::checkNodeResultFile (ITraceMng * tm, const String & filename, const VariableNodeReal2 & node_values, double epsilon, double min_value = 0.0)
Check the values of the variable against a reference file.
The reference file filename is an ASCII file containing N Real2 values where N is the number of nodes in the mesh (so there will be N*2 real in the file). The file should have the following format: uid1 x1 y1 uid2 x2 y2 ... uidN xN yN.
For each item the current value of node_values is compared to the reference value and if the relative difference is greater than epsilon this is an error.
Only values greater whose absolute value is greater than min_value are checked.
Definition at line 244 of file FemUtils.cc.
checkNodeResultFile() [3/3]
void Arcane::FemUtils::checkNodeResultFile (ITraceMng * tm, const String & filename, const VariableNodeReal3 & node_values, double epsilon, double min_value = 0.0)
Check the values of the variable against a reference file.
The reference file filename is an ASCII file containing N Real3 values where N is the number of nodes in the mesh (so there will be N*3 real in the file). The file should have the following format: uid1 x1 y1 z1 uid2 x2 y2 z2 ... uidN xN yN zN.
For each item the current value of node_values is compared to the reference value and if the relative difference is greater than epsilon this is an error.
Only values greater whose absolute value is greater than min_value are checked.
Definition at line 254 of file FemUtils.cc.
createAlephDoFLinearSystemImpl()
IDoFLinearSystemImpl * Arcane::FemUtils::createAlephDoFLinearSystemImpl (ISubDomain * sd, IItemFamily * dof_family, const String & solver_name)
Definition at line 253 of file AlephDoFLinearSystem.cc.
Referenced by Arcane::FemUtils::DefaultDoFLinearSystemFactory::createInstance().
diagonalReal3x3()
Real3 Arcane::FemUtils::diagonalReal3x3 (const Real3x3 & mat)
Diagonal of a Real3x3 obtained as a new Real3x3 (useful for Passmo(nl) modules)
Definition at line 284 of file FemUtils.cc.
Referenced by outdiagonalReal3x3().
findIndexBinarySearch()
ARCCORE_HOST_DEVICE Int32 Arcane::FemUtils::findIndexBinarySearch (Int32 row, Int32 col, const auto & in_row_coo, const auto & in_col_coo, Int32 row_length)
AI generated: Binary search for (row, col) index in a COO-formatted array.
Definition at line 311 of file CooFormatMatrix.h.
massMatrix() [1/2]
template<int N> RealMatrix<N, N> ARCCORE_HOST_DEVICE Arcane::FemUtils::massMatrix (const RealMatrix< 1, N > & lhs, const RealMatrix< 1, N > & rhs) inline
AI generated: Computes the mass matrix (lhs^T * rhs) from row vector inputs.
Definition at line 330 of file FemUtils.h.
massMatrix() [2/2]
template<int N> RealMatrix<N, N> ARCCORE_HOST_DEVICE Arcane::FemUtils::massMatrix (const RealVector< N > & lhs, const RealVector< N > & rhs) inline
AI generated: Computes the mass matrix as the outer product of two RealVector vectors.
Definition at line 555 of file FemUtils.h.
matrixAddition()
template<int N, int M> RealMatrix<N, N> ARCCORE_HOST_DEVICE Arcane::FemUtils::matrixAddition (const RealMatrix< N, M > & a, const RealMatrix< M, N > & b) inline
AI generated: Element-wise addition of two matrices producing a square matrix.
Definition at line 281 of file FemUtils.h.
matrixMultiplication()
template<int N, int M> RealMatrix<N, N> ARCCORE_HOST_DEVICE Arcane::FemUtils::matrixMultiplication (const RealMatrix< N, M > & a, const RealMatrix< M, N > & b) inline
AI generated: Matrix-matrix multiplication (a * b) producing a square matrix.
Definition at line 296 of file FemUtils.h.
matrixTranspose()
template<int N, int M> RealMatrix<M, N> ARCCORE_HOST_DEVICE Arcane::FemUtils::matrixTranspose (const RealMatrix< N, M > & a) inline
AI generated: Transpose of a matrix (swaps rows and columns)
Definition at line 315 of file FemUtils.h.
operator*()
template<int N> RealVector<N> ARCCORE_HOST_DEVICE Arcane::FemUtils::operator* (const RealVector< N > & lhs, const RealMatrix< N, N > & rhs) inline
AI generated: Matrix-vector product (lhs * rhs) for a RealVector and a RealMatrix.
Definition at line 528 of file FemUtils.h.
operator^() [1/3]
ARCCORE_HOST_DEVICE RealMatrix<3, 3> Arcane::FemUtils::operator^ (const Arcane::Real3 & lhs, const Arcane::Real3 & rhs) inline
AI generated: Outer product of two Real3 vectors producing a 3x3 matrix.
Definition at line 256 of file FemUtils.h.
operator^() [2/3]
ARCCORE_HOST_DEVICE RealMatrix<4, 4> Arcane::FemUtils::operator^ (const Real4 & lhs, const Real4 & rhs) inline
AI generated: Outer product of two Real4 vectors producing a 4x4 matrix.
Definition at line 268 of file FemUtils.h.
operator^() [3/3]
template<int N> RealMatrix<N, N> ARCCORE_HOST_DEVICE Arcane::FemUtils::operator^ (const RealVector< N > & lhs, const RealVector< N > & rhs) inline
AI generated: Outer product of two RealVector vectors producing a square matrix.
Definition at line 542 of file FemUtils.h.
outdiagonalReal3x3()
Real3x3 Arcane::FemUtils::outdiagonalReal3x3 (const Real3x3 & mat)
Diagonal of a Real3x3 obtained as a new Real3x3 (useful for Passmo(nl) modules)
Definition at line 290 of file FemUtils.cc.
References diagonalReal3x3().
readFileAsCaseTable()
CaseTable * Arcane::FemUtils::readFileAsCaseTable (IParallelMng * pm, const String & filename, const Int32 & ndim)
Sample to read value from a file and create an associated CaseTable.
The file should contains 3 values for each time step (so the number of values should be a multiple of 4).
Definition at line 182 of file FemUtils.cc.
real3x3GetLowOutdiagonal()
Real3 Arcane::FemUtils::real3x3GetLowOutdiagonal (const Real3x3 & mat)
Return the out-diagonal terms of the lower part of a Real3x3 (useful for Passmo(nl) modules)
Definition at line 278 of file FemUtils.cc.
Referenced by real3x3IsSym().
real3x3GetSupOutdiagonal()
Real3 Arcane::FemUtils::real3x3GetSupOutdiagonal (const Real3x3 & mat)
Return the out-diagonal terms of the upper part of a Real3x3 (useful for Passmo(nl) modules)
Definition at line 271 of file FemUtils.cc.
Referenced by real3x3IsSym().
real3x3IsSym() [1/2]
bool Arcane::FemUtils::real3x3IsSym (const Arcane::Real3x3 & mat)
Checking whether a Real3x3 is symmetric (useful for Passmo(nl) modules)
real3x3IsSym() [2/2]
bool Arcane::FemUtils::real3x3IsSym (const Real3x3 & mat)
Definition at line 302 of file FemUtils.cc.
References real3x3GetLowOutdiagonal(), and real3x3GetSupOutdiagonal().
Referenced by Arcane::FemUtils::Tensor2::Tensor2(), and Arcane::FemUtils::Tensor2::operator=().
real3x3Trace()
Real Arcane::FemUtils::real3x3Trace (const Real3x3 & mat)
Compute the trace of a Real3x3 (useful for Passmo(nl) modules)
Definition at line 264 of file FemUtils.cc.
Variable Documentation
a1
const Real Arcane::FemUtils::a1 { 1. / 4. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 3.
Definition at line 232 of file GaussQuadrature.h.
Referenced by Arcane::FemUtils::AlienBSRFormat::initialize(), Arcane::FemUtils::AlienDoFLinearSystemImpl::solve(), Arcane::FemUtils::HypreDoFLinearSystemImpl::solve(), and Arcane::FemUtils::PETScDoFLinearSystemImpl::solve().
a2
const Real Arcane::FemUtils::a2 { (5. - sqrt(5.)) / 20. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 2.
Definition at line 230 of file GaussQuadrature.h.
Referenced by Arcane::FemUtils::AlienDoFLinearSystemImpl::solve(), Arcane::FemUtils::HypreDoFLinearSystemImpl::solve(), and Arcane::FemUtils::PETScDoFLinearSystemImpl::solve().
ap1
const Real Arcane::FemUtils::ap1 { 0.5702963741068025 }
AI generated: Pyramid Gauss quadrature intermediate constant a_p1.
Definition at line 302 of file GaussQuadrature.h.
apt1
const Real Arcane::FemUtils::apt1 { 1. / sqrt(3.) }
AI generated: Pentaedron Gauss quadrature intermediate constants.
Definition at line 347 of file GaussQuadrature.h.
apt2
const Real Arcane::FemUtils::apt2 { 0.577350269189626 }
Definition at line 347 of file GaussQuadrature.h.
b2
const Real Arcane::FemUtils::b2 { (5. + 3. * sqrt(5.)) / 20. }
Definition at line 230 of file GaussQuadrature.h.
Referenced by Arcane::FemUtils::PETScDoFLinearSystemImpl::solve().
b3
const Real Arcane::FemUtils::b3 { 1. / 6. }
Definition at line 232 of file GaussQuadrature.h.
b41
const Real Arcane::FemUtils::b41 { (7. + sqrt(15.)) / 34. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 4 (group b)
Definition at line 234 of file GaussQuadrature.h.
b42
const Real Arcane::FemUtils::b42 { (7. - sqrt(15.)) / 34. }
Definition at line 234 of file GaussQuadrature.h.
c3
const Real Arcane::FemUtils::c3 { 1. / 2. }
Definition at line 232 of file GaussQuadrature.h.
c41
const Real Arcane::FemUtils::c41 { (13. - 3. * sqrt(15.)) / 34. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 4 (group c)
Definition at line 236 of file GaussQuadrature.h.
c42
const Real Arcane::FemUtils::c42 { (13. + 3. * sqrt(15.)) / 34. }
Definition at line 236 of file GaussQuadrature.h.
d4
const Real Arcane::FemUtils::d4 { (5. - sqrt(15.)) / 20. }
AI generated: Tetrahedron Gauss quadrature intermediate constants for order 4 (group d/e)
Definition at line 238 of file GaussQuadrature.h.
e4
const Real Arcane::FemUtils::e4 { (5. + sqrt(15.)) / 20. }
Definition at line 238 of file GaussQuadrature.h.
ELIMINATE_NONE
constexpr Byte Arcane::FemUtils::ELIMINATE_NONE = static_cast<Byte>(MatrixEliminationType::None) static constexpr
AI generated: Constant for matrix elimination type: none.
Definition at line 70 of file FemUtilsGlobal.h.
Referenced by Arcane::FemUtils::DoFLinearSystemImplBase::clearValues().
ELIMINATE_ROW
constexpr Byte Arcane::FemUtils::ELIMINATE_ROW = static_cast<Byte>(MatrixEliminationType::Row) static constexpr
AI generated: Constant for matrix elimination type: row only.
Definition at line 72 of file FemUtilsGlobal.h.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyRHSTransformation(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowColumnEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowEliminationOnMatrix(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnRHS(), Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs(), and Arcane::FemUtils::AlephDoFLinearSystemImpl::eliminateRow().
ELIMINATE_ROW_COLUMN
constexpr Byte Arcane::FemUtils::ELIMINATE_ROW_COLUMN = static_cast<Byte>(MatrixEliminationType::RowColumn) static constexpr
AI generated: Constant for matrix elimination type: row and column.
Definition at line 74 of file FemUtilsGlobal.h.
Referenced by Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyMatrixTransformationAndFillAlephMatrix(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_applyRHSTransformation(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowColumnEliminationOnMatrix(), Arcane::FemUtils::DoFLinearSystemImplBase::_applyRowColumnEliminationToRHS(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_applyRowOrRowColumnEliminationOnRHS(), Arcane::FemUtils::AlephDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::CsrDoFLinearSystemImpl::_fillRowColumnEliminationInfos(), Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs(), and Arcane::FemUtils::AlephDoFLinearSystemImpl::eliminateRowColumn().
hp21
const Real Arcane::FemUtils::hp21 { 0.1531754163448146 }
AI generated: Pyramid Gauss quadrature z-coordinate constants for order 2.
Definition at line 304 of file GaussQuadrature.h.
hp22
const Real Arcane::FemUtils::hp22 { 0.6372983346207416 }
Definition at line 304 of file GaussQuadrature.h.
hp31
const Real Arcane::FemUtils::hp31 { 1. / 6. }
AI generated: Pyramid Gauss quadrature z-coordinate constants for order 3.
Definition at line 306 of file GaussQuadrature.h.
hp32
const Real Arcane::FemUtils::hp32 { 0.08063183038464675 }
Definition at line 306 of file GaussQuadrature.h.
hp33
const Real Arcane::FemUtils::hp33 { 0.6098484849057127 }
Definition at line 306 of file GaussQuadrature.h.
maxnint
const Integer Arcane::FemUtils::maxnint = 9
AI generated: Maximum Gauss-Legendre quadrature order.
Definition at line 379 of file GaussQuadrature.h.
nptg
const Integer Arcane::FemUtils::nptg[4] = { 1, 3, 4, 7 }
AI generated: Triangle Gauss quadrature number of integration points per order.
Definition at line 202 of file GaussQuadrature.h.
npwgpent3
const Integer Arcane::FemUtils::npwgpent3[8] = { 0, 1, 1, 1, 0, 1, 1, 1 }
AI generated: Pentaedron weight-to-Gauss-point index mapping for order 3.
Definition at line 376 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
npwgpyr3
const Integer Arcane::FemUtils::npwgpyr3[6] = { 0, 0, 0, 0, 1, 2 }
AI generated: Pyramid weight-to-Gauss-point index mapping for order 3.
Definition at line 335 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
npwgtet3
const Integer Arcane::FemUtils::npwgtet3[5] = { 0, 1, 1, 1 }
AI generated: Tetrahedron weight-to-Gauss-point index mapping for order 3.
Definition at line 286 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
npwgtet4
const Integer Arcane::FemUtils::npwgtet4[15] = { 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3 }
AI generated: Tetrahedron weight-to-Gauss-point index mapping for order 4.
Definition at line 290 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wg
const Real Arcane::FemUtils::wg[4][7]
Initial value:
= {
  { xh, 0., 0., 0., 0., 0., 0. },
  { 1. / 6., 1. / 6., 1. / 6., 0., 0., 0., 0. },
  { -27. / 96., 25. / 96., 25. / 96., 25. / 96., 0., 0., 0. },
  { 0.112500000000000, (155. + sqrt(15.)) / 2400., (155. + sqrt(15.)) / 2400., (155. + sqrt(15.)) / 2400.,
    (155. - sqrt(15.)) / 2400., (155. - sqrt(15.)) / 2400., (155. - sqrt(15.)) / 2400. }
}
AI generated: Triangle Gauss quadrature integration weights.
Definition at line 192 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight(), and ArcaneFemFunctions::FemGaussQuadrature::triWeight().
wgauss1
const Real Arcane::FemUtils::wgauss1 = 2.
AI generated: Gauss-Legendre quadrature weight for order 1.
Definition at line 48 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgauss2
const Real Arcane::FemUtils::wgauss2[2] = { 1., 1. }
AI generated: Gauss-Legendre quadrature weight for order 2.
Definition at line 54 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgauss3
const Real Arcane::FemUtils::wgauss3[3] = { 5. / 9., 8. / 9., 5. / 9. }
AI generated: Gauss-Legendre quadrature weight for order 3.
Definition at line 60 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgauss4
const Real Arcane::FemUtils::wgauss4[4]
Initial value:
= {
  xh - sqrt(5. / 6.) / 6., xh + sqrt(5. / 6.) / 6.,
  xh + sqrt(5. / 6.) / 6., xh - sqrt(5. / 6.) / 6.
}
AI generated: Gauss-Legendre quadrature weight for order 4.
Definition at line 70 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgauss5
const Real Arcane::FemUtils::wgauss5[5]
Initial value:
= {
  (322. - 13 * sqrt(70.)) / 900., (322. + 13 * sqrt(70.)) / 900., 128. / 225.,
  (322. + 13 * sqrt(70.)) / 900., (322. - 13 * sqrt(70.)) / 900.
}
AI generated: Gauss-Legendre quadrature weight for order 5.
Definition at line 83 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgauss6
const Real Arcane::FemUtils::wgauss6[6]
Initial value:
= {
  0.171324492379170, 0.360761573048139,
  0.467913934572691, 0.467913934572691,
  0.360761573048139, 0.171324492379170
}
AI generated: Gauss-Legendre quadrature weight for order 6.
Definition at line 97 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgauss7
const Real Arcane::FemUtils::wgauss7[7]
Initial value:
= {
  0.129484966168870, 0.279705391489277,
  0.381830050505119, 0.417959183673469, 0.381830050505119,
  0.279705391489277, 0.129484966168870
}
AI generated: Gauss-Legendre quadrature weight for order 7.
Definition at line 112 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgauss8
const Real Arcane::FemUtils::wgauss8[8]
Initial value:
= {
  0.101228536290376, 0.222381034453374,
  0.313706645877887, 0.362683783378362,
  0.362683783378362, 0.313706645877887,
  0.222381034453374, 0.101228536290376
}
AI generated: Gauss-Legendre quadrature weight for order 8.
Definition at line 128 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgauss9
const Real Arcane::FemUtils::wgauss9[9]
Initial value:
= {
  0.081274388361574, 0.180648160694857,
  0.260610696402935, 0.312347077040003, 0.330239355001260,
  0.312347077040003, 0.260610696402935,
  0.180648160694857, 0.081274388361574
}
AI generated: Gauss-Legendre quadrature weight for order 9.
Definition at line 145 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getWeight().
wgpent2
const Real Arcane::FemUtils::wgpent2 { 1. / 6. }
AI generated: Pentaedron Gauss quadrature weight for order 2.
Definition at line 370 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wgpent3
const Real Arcane::FemUtils::wgpent3[2] { -27. / 96., 25. / 96. }
AI generated: Pentaedron Gauss quadrature weights for order 3.
Definition at line 372 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wgpyr2
const Real Arcane::FemUtils::wgpyr2 { 2. / 15. }
AI generated: Pyramid Gauss quadrature weight for order 2.
Definition at line 329 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wgpyr3
const Real Arcane::FemUtils::wgpyr3[3] { 0.1024890634400000, 0.1100000000000000, 0.1467104129066667 }
AI generated: Pyramid Gauss quadrature weights for order 3.
Definition at line 331 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wgtet1
const Real Arcane::FemUtils::wgtet1 { 1. / 6. }
AI generated: Tetrahedron Gauss quadrature weight for order 1.
Definition at line 276 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wgtet2
const Real Arcane::FemUtils::wgtet2 { 1. / 24. }
AI generated: Tetrahedron Gauss quadrature weight for order 2.
Definition at line 278 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wgtet3
const Real Arcane::FemUtils::wgtet3[2] = { -2. / 15., 3. / 40. }
AI generated: Tetrahedron Gauss quadrature weights for order 3.
Definition at line 280 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wgtet4
const Real Arcane::FemUtils::wgtet4[4] = { 8. / 405., (2665 - 14. * sqrt(15)) / 226800., (2665 + 4. * sqrt(15)) / 226800., 5. / 567. }
AI generated: Tetrahedron Gauss quadrature weights for order 4.
Definition at line 282 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight().
wgtetra
const Real Arcane::FemUtils::wgtetra = 1. / 24.
AI generated: Tetrahedron Gauss quadrature integration weight for order 2.
Definition at line 227 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::tetraWeight().
xg1
const Real Arcane::FemUtils::xg1[4][7]
Initial value:
= {
  { 1. / 3., 0., 0., 0., 0., 0., 0. },
  { xh, 0., xh, 0., 0., 0., 0. },
  { 1. / 3., 3. / 5., 1. / 5., 1. / 5., 0., 0., 0. },
  { 1. / 3., (9. - 2. * sqrt(15.)) / 21., (6. + sqrt(15.)) / 21., (6. + sqrt(15.)) / 21.,
    (9. + 2. * sqrt(15.)) / 21., (6. - sqrt(15.)) / 21., (6. - sqrt(15.)) / 21. }
}
AI generated: Triangle Gauss quadrature local x-coordinates on the first edge.
Definition at line 161 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition(), and ArcaneFemFunctions::FemGaussQuadrature::triRefPosition().
xg2
const Real Arcane::FemUtils::xg2[4][7]
Initial value:
= {
  { 1. / 3., 0., 0., 0., 0., 0., 0. },
  { xh, xh, 0., 0., 0., 0., 0. },
  { 1. / 3., 1. / 5., 3. / 5., 1. / 5., 0., 0., 0. },
  { 1. / 3., (6. + sqrt(15.)) / 21., (9. - 2. * sqrt(15.)) / 21., (6. + sqrt(15.)) / 21., (6. - sqrt(15.)) / 21.,
    (9. + 2. * sqrt(15.)) / 21., (6. - sqrt(15.)) / 21. }
}
AI generated: Triangle Gauss quadrature local x-coordinates on the second edge.
Definition at line 171 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition(), and ArcaneFemFunctions::FemGaussQuadrature::triRefPosition().
xgauss1
const Real Arcane::FemUtils::xgauss1 = 0.
AI generated: Gauss-Legendre quadrature abscissa for order 1.
Definition at line 46 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xgauss2
const Real Arcane::FemUtils::xgauss2[2] = { -1. / sqrt(3.), 1. / sqrt(3.) }
AI generated: Gauss-Legendre quadrature abscissa for order 2.
Definition at line 52 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xgauss3
const Real Arcane::FemUtils::xgauss3[3] = { -sqrt(0.6), 0., sqrt(0.6) }
AI generated: Gauss-Legendre quadrature abscissa for order 3.
Definition at line 58 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xgauss4
const Real Arcane::FemUtils::xgauss4[4]
Initial value:
= {
  -sqrt((3. + 2. * sqrt(1.2)) / 7.), -sqrt((3. - 2. * sqrt(1.2)) / 7.),
  sqrt((3. - 2. * sqrt(1.2)) / 7.), sqrt((3. + 2. * sqrt(1.2)) / 7.)
}
AI generated: Gauss-Legendre quadrature abscissa for order 4.
Definition at line 64 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xgauss5
const Real Arcane::FemUtils::xgauss5[5]
Initial value:
= {
  -sqrt(245. + 14. * sqrt(70.)) / 21., -sqrt(245. - 14. * sqrt(70.)) / 21., 0.,
  sqrt(245. - 14. * sqrt(70.)) / 21., sqrt(245. + 14. * sqrt(70.)) / 21.
}
AI generated: Gauss-Legendre quadrature abscissa for order 5.
Definition at line 77 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xgauss6
const Real Arcane::FemUtils::xgauss6[6]
Initial value:
= {
  -0.932469514203152, -0.661209386466265,
  -0.238619186083197, 0.238619186083197,
  0.661209386466265, 0.932469514203152
}
AI generated: Gauss-Legendre quadrature abscissa for order 6.
Definition at line 90 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xgauss7
const Real Arcane::FemUtils::xgauss7[7]
Initial value:
= {
  -0.949107912342759, -0.741531185599394,
  -0.405845151377397, 0., 0.405845151377397,
  0.741531185599394, 0.949107912342759
}
AI generated: Gauss-Legendre quadrature abscissa for order 7.
Definition at line 105 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xgauss8
const Real Arcane::FemUtils::xgauss8[8]
Initial value:
= {
  -0.960289856497536, -0.796666477413627,
  -0.525532409916329, -0.183434642495650,
  0.183434642495650, 0.525532409916329,
  0.796666477413627, 0.960289856497536
}
AI generated: Gauss-Legendre quadrature abscissa for order 8.
Definition at line 120 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xgauss9
const Real Arcane::FemUtils::xgauss9[9]
Initial value:
= {
  -0.968160239507626, -0.836031107326636,
  -0.613371432700590, -0.324253423403809, 0.,
  0.324253423403809, 0.613371432700590,
  0.836031107326636, 0.968160239507626
}
AI generated: Gauss-Legendre quadrature abscissa for order 9.
Definition at line 137 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getRefPosition().
xh
const Real Arcane::FemUtils::xh { 0.5000000000000000 }
AI generated: Half-value constant (0.5) used in quadrature computations.
Definition at line 42 of file GaussQuadrature.h.
xit
const Real Arcane::FemUtils::xit[4] = { 0.58541020, 0.13819660, 0.13819660, 0.13819660 }
AI generated: Tetrahedron Gauss quadrature local x-coordinates.
Definition at line 215 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::tetraRefPosition().
xpent
const Real Arcane::FemUtils::xpent[2][8]
Initial value:
= {
  { -apt1, -apt1, -apt1, apt1, apt1, apt1, 0., 0. },
  { -apt2, -apt2, -apt2, -apt2, apt2, apt2, apt2, apt2 }
}
AI generated: Pentaedron Gauss quadrature local x-coordinates for orders 2–3.
Definition at line 349 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().
xpyr
const Real Arcane::FemUtils::xpyr[2][6]
Initial value:
= {
  { xh, 0., -xh, 0., 0., 0. },
  { ap1, 0., -ap1, 0., 0., 0. }
}
AI generated: Pyramid Gauss quadrature local x-coordinates for orders 2–3.
Definition at line 308 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().
xtet
const Real Arcane::FemUtils::xtet[4][15]
Initial value:
= {
  { a1, 0., 0., 0.,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a2, a2, a2, b2,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a1, b3, b3, b3, c3,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a1, b41, b41, b41, c41, b42, b42, b42, c42, d4, d4, e4, d4, e4, e4 }
}
AI generated: Tetrahedron Gauss quadrature local x-coordinates for orders 1–4.
Definition at line 242 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().
yit
const Real Arcane::FemUtils::yit[4] = { 0.13819660, 0.58541020, 0.13819660, 0.13819660 }
AI generated: Tetrahedron Gauss quadrature local y-coordinates.
Definition at line 219 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::tetraRefPosition().
ypent
const Real Arcane::FemUtils::ypent[2][8]
Initial value:
= {
  { xh, 0., xh, xh, 0., xh, 0., 0. },
  { 1. / 3., 3. / 5., 1. / 5., 1. / 5., 1. / 3., 3. / 5., 1. / 5., 1. / 5. }
}
AI generated: Pentaedron Gauss quadrature local y-coordinates for orders 2–3.
Definition at line 356 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().
ypyr
const Real Arcane::FemUtils::ypyr[2][6]
Initial value:
= {
  { 0., xh, 0., -xh, 0., 0. },
  { 0., ap1, 0., -ap1, 0., 0. }
}
AI generated: Pyramid Gauss quadrature local y-coordinates for orders 2–3.
Definition at line 315 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().
ytet
const Real Arcane::FemUtils::ytet[4][15]
Initial value:
= {
  { a1, 0., 0., 0.,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a2, a2, b2, a2,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a1, b3, b3, c3, b3,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a1, b41, b41, c41, b41, b42, b42, c42, b42, d4, e4, d4, e4, d4, e4 }
}
AI generated: Tetrahedron Gauss quadrature local y-coordinates for orders 1–4.
Definition at line 254 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().
zit
const Real Arcane::FemUtils::zit[4] = { 0.13819660, 0.13819660, 0.58541020, 0.13819660 }
AI generated: Tetrahedron Gauss quadrature local z-coordinates.
Definition at line 223 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::tetraRefPosition().
zpent
const Real Arcane::FemUtils::zpent[2][8]
Initial value:
= {
  { xh, xh, 0., xh, xh, 0., 0., 0. },
  { 1. / 3., 1. / 5., 3. / 5., 1. / 5., 1. / 3., 1. / 5., 3. / 5., 1. / 5. }
}
AI generated: Pentaedron Gauss quadrature local z-coordinates for orders 2–3.
Definition at line 363 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().
zpyr
const Real Arcane::FemUtils::zpyr[2][6]
Initial value:
= {
  { hp21, hp21, hp21, hp21, hp22, 0. },
  { hp31, hp31, hp31, hp31, hp32, hp33 }
}
AI generated: Pyramid Gauss quadrature local z-coordinates for orders 2–3.
Definition at line 322 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().
ztet
const Real Arcane::FemUtils::ztet[4][15]
Initial value:
= {
  { a1, 0., 0., 0.,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a2, b2, a2, a2,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a1, b3, c3, b3, b3,
    0., 0., 0., 0., 0., 0., 0., 0., 0., 0. },
  { a1, b41, c41, b41, b41, b42, c42, b42, b42, e4, d4, d4, e4, e4, d4 }
}
AI generated: Tetrahedron Gauss quadrature local z-coordinates for orders 1–4.
Definition at line 266 of file GaussQuadrature.h.
Referenced by ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition().