ShArc: Arcane::FemUtils::Gpu::MeshOperation Namespace Reference
Arcane::FemUtils::Gpu::MeshOperation Namespace Reference
Functions
ARCCORE_HOST_DEVICE Real computeAreaTria (FaceLocalId face_lid, const IndexedFaceNodeConnectivityView &fn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
AI generated: Computes the area of a triangular face from face-to-node connectivity.
ARCCORE_HOST_DEVICE Real computeAreaTria3 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
computes the area of a triangle defined by three nodes.
ARCCORE_HOST_DEVICE Real computeLengthFace (FaceLocalId face_lid, IndexedFaceNodeConnectivityView fn_cv, Accelerator::VariableNodeReal3InView in_node_coord)
Computes the length of the edge defined by a given face.
ARCCORE_HOST_DEVICE Real2 computeNormalFace (FaceLocalId face_lid, IndexedFaceNodeConnectivityView fn_cv, Accelerator::VariableNodeReal3InView in_node_coord, FaceInfoListView faces_infos)
Computes the normalized edge normal for a given face.
ARCCORE_HOST_DEVICE Real3 computeNormalTriangle (FaceLocalId face_lid, IndexedFaceNodeConnectivityView fn_cv, Accelerator::VariableNodeReal3InView in_node_coord, FaceInfoListView faces_infos)
Computes the normalized triangle normal for a given face.
static ARCCORE_HOST_DEVICE Real computeVolumeHexa8 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
AI generated: Computes the volume of a hexahedron as the sum of three tetrahedral decompositions.
ARCCORE_HOST_DEVICE Real computeVolumeTetra4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
Computes the volume of a tetrahedra defined by four nodes.
Function Documentation
computeAreaTria()
ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Gpu::MeshOperation::computeAreaTria (FaceLocalId face_lid, const IndexedFaceNodeConnectivityView & fn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline
AI generated: Computes the area of a triangular face from face-to-node connectivity.
Definition at line 93 of file ArcaneFemFunctionsGpu.h.
computeAreaTria3()
ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Gpu::MeshOperation::computeAreaTria3 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline
computes the area of a triangle defined by three nodes.
The area is determined as half the magnitude of the cross-product of two edge vectors originating from the first node.
Definition at line 77 of file ArcaneFemFunctionsGpu.h.
Referenced by _computeElementMatrixTria3Gpu(), _computeElementVectorTria3Gpu(), computeElementMatrixTria3Gpu(), computeElementMatrixTria3SYCL(), computeElementVectorTria3Gpu(), computeElementVectorTria3SYCL(), and ArcaneFemFunctions::MeshOperation::computeFacLengthOrArea().
computeLengthFace()
ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Gpu::MeshOperation::computeLengthFace (FaceLocalId face_lid, IndexedFaceNodeConnectivityView fn_cv, Accelerator::VariableNodeReal3InView in_node_coord) inline
Computes the length of the edge defined by a given face.
This method calculates Euclidean distance between the two nodes of the face.
Definition at line 140 of file ArcaneFemFunctionsGpu.h.
computeNormalFace()
ARCCORE_HOST_DEVICE Real2 Arcane::FemUtils::Gpu::MeshOperation::computeNormalFace (FaceLocalId face_lid, IndexedFaceNodeConnectivityView fn_cv, Accelerator::VariableNodeReal3InView in_node_coord, FaceInfoListView faces_infos) inline
Computes the normalized edge normal for a given face.
This method calculates normal vector to the edge defined by nodes of the face, normalizes it, and ensures the correct orientation.
Definition at line 160 of file ArcaneFemFunctionsGpu.h.
computeNormalTriangle()
ARCCORE_HOST_DEVICE Real3 Arcane::FemUtils::Gpu::MeshOperation::computeNormalTriangle (FaceLocalId face_lid, IndexedFaceNodeConnectivityView fn_cv, Accelerator::VariableNodeReal3InView in_node_coord, FaceInfoListView faces_infos) inline
Computes the normalized triangle normal for a given face.
This method calculates normal vector to the triangle defined by nodes, of the face and normalizes it, and ensures the correct orientation.
Definition at line 191 of file ArcaneFemFunctionsGpu.h.
computeVolumeHexa8()
static ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Gpu::MeshOperation::computeVolumeHexa8 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline static
AI generated: Computes the volume of a hexahedron as the sum of three tetrahedral decompositions.
Definition at line 219 of file ArcaneFemFunctionsGpu.h.
computeVolumeTetra4()
ARCCORE_HOST_DEVICE Real Arcane::FemUtils::Gpu::MeshOperation::computeVolumeTetra4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline
Computes the volume of a tetrahedra defined by four nodes.
The volume is given by one-sixth of the absolute value of the determinant formed by three edge vectors originating from the first node.
Definition at line 115 of file ArcaneFemFunctionsGpu.h.
Referenced by _computeElementMatrixTetra4Gpu(), _computeElementVectorTetra4Gpu(), computeElementMatrixTetra4Gpu(), computeElementMatrixTetra4SYCL(), computeElementVectorTetra4Gpu(), and computeElementVectorTetra4SYCL().