ShArc: Arcane::FemUtils::Gpu::FeOperation2D Namespace Reference
Arcane::FemUtils::Gpu::FeOperation2D Namespace Reference
Classes
struct Quad4GaussPointInfo
AI generated: Stores shape function gradients (dN/dx, dN/dy) and Jacobian determinant at a quadrature point for a Quad4 element.
Functions
static ARCCORE_HOST_DEVICE Quad4GaussPointInfo computeGradientsAndJacobianQuad4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord, Real xi, Real eta)
AI generated: Computes shape function gradients and Jacobian determinant for a Quad4 element at a given (xi, eta) Gauss point.
ARCCORE_HOST_DEVICE Real3 computeGradientXTria3 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
Computes the 𝑥 gradients of basis functions 𝐍 for ℙ1 triangles.
ARCCORE_HOST_DEVICE Real3 computeGradientYTria3 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
Computes the 𝑦 gradients of basis functions 𝐍 for ℙ1 triangles.
Function Documentation
computeGradientsAndJacobianQuad4()
static ARCCORE_HOST_DEVICE Quad4GaussPointInfo Arcane::FemUtils::Gpu::FeOperation2D::computeGradientsAndJacobianQuad4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord, Real xi, Real eta) inline static
AI generated: Computes shape function gradients and Jacobian determinant for a Quad4 element at a given (xi, eta) Gauss point.
Definition at line 315 of file ArcaneFemFunctionsGpu.h.
Referenced by computeElementMatrixQuad4Gpu(), and ArcaneFemFunctions::FeOperation2D::computeGradientQuad4().
computeGradientXTria3()
ARCCORE_HOST_DEVICE Real3 Arcane::FemUtils::Gpu::FeOperation2D::computeGradientXTria3 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline
Computes the 𝑥 gradients of basis functions 𝐍 for ℙ1 triangles.
This method calculates gradient operator ∂/∂𝑥 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,3 for the three shape function 𝑁ᵢ hence output is a vector of size 3
    ∂𝐍/∂𝑥 = [ ∂𝑁₁/∂𝑥  ∂𝑁₂/∂𝑥  ∂𝑁₃/∂𝑥 ]
    ∂𝐍/∂𝑥 = 1/(2𝐴) [ y2-y3  y3−y1  y1−y2 ]
Definition at line 264 of file ArcaneFemFunctionsGpu.h.
Referenced by _computeElementMatrixTria3Gpu(), _computeElementVectorTria3Gpu(), computeElementMatrixTria3Gpu(), computeElementMatrixTria3SYCL(), computeElementVectorTria3Gpu(), and computeElementVectorTria3SYCL().
computeGradientYTria3()
ARCCORE_HOST_DEVICE Real3 Arcane::FemUtils::Gpu::FeOperation2D::computeGradientYTria3 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline
Computes the 𝑦 gradients of basis functions 𝐍 for ℙ1 triangles.
This method calculates gradient operator ∂/∂𝑦 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,3 for the three shape function 𝑁ᵢ hence output is a vector of size 3
    ∂𝐍/∂𝑥 = [ ∂𝑁₁/∂𝑦  ∂𝑁₂/∂𝑦  ∂𝑁₃/∂𝑦 ]
    ∂𝐍/∂𝑥 = 1/(2𝐴) [ 𝑥₃−𝑥₂  𝑥₁−𝑥₃  𝑥₂−𝑥₁ ]
Definition at line 292 of file ArcaneFemFunctionsGpu.h.
Referenced by _computeElementMatrixTria3Gpu(), _computeElementVectorTria3Gpu(), computeElementMatrixTria3Gpu(), computeElementMatrixTria3SYCL(), computeElementVectorTria3Gpu(), and computeElementVectorTria3SYCL().