ShArc: Arcane::FemUtils::Gpu::FeOperation3D Namespace Reference
Arcane::FemUtils::Gpu::FeOperation3D Namespace Reference
Classes
struct Hexa8GaussPointInfo
AI generated: Stores shape function gradients (dN/dx, dN/dy, dN/dz) and Jacobian determinant at a quadrature point for a Hexa8 element.
Functions
ARCCORE_HOST_DEVICE Hexa8GaussPointInfo computeGradientsAndJacobianHexa8 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord, Real xi, Real eta, Real zeta)
AI generated: Computes shape function gradients and Jacobian determinant for a Hexa8 element at a given (xi, eta, zeta) Gauss point.
ARCCORE_HOST_DEVICE Real4 computeGradientXTetra4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
Computes the X gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
ARCCORE_HOST_DEVICE Real4 computeGradientYTetra4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
Computes the Y gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
ARCCORE_HOST_DEVICE Real4 computeGradientZTetra4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const Accelerator::VariableNodeReal3InView &in_node_coord)
Computes the 𝑧 gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
Function Documentation
computeGradientsAndJacobianHexa8()
ARCCORE_HOST_DEVICE Hexa8GaussPointInfo Arcane::FemUtils::Gpu::FeOperation3D::computeGradientsAndJacobianHexa8 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord, Real xi, Real eta, Real zeta) inline
AI generated: Computes shape function gradients and Jacobian determinant for a Hexa8 element at a given (xi, eta, zeta) Gauss point.
Definition at line 542 of file ArcaneFemFunctionsGpu.h.
Referenced by computeElementMatrixHexa8Gpu(), and ArcaneFemFunctions::FeOperation3D::computeGradientHexa8().
computeGradientXTetra4()
ARCCORE_HOST_DEVICE Real4 Arcane::FemUtils::Gpu::FeOperation3D::computeGradientXTetra4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline
Computes the X gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
This method calculates gradient operator ∂/∂𝑥 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,4 for the four shape function 𝑁ᵢ hence output is a vector of size 4
    ∂𝐍/∂𝑥 = [ ∂𝑁₁/∂𝑥  ∂𝑁₂/∂𝑥  ∂𝑁₃/∂𝑥  ∂𝑁₄/∂𝑥 ]
    ∂𝐍/∂𝑥 = 1/(6𝑉) [ b0  b1  b2  b3 ]
where: b0 = (n1.y * (n3.z - n2.z) + n2.y * (n1.z - n3.z) + n3.y * (n2.z - n1.z)), b1 = (n0.y * (n2.z - n3.z) + n2.y * (n3.z - n0.z) + n3.y * (n0.z - n2.z)), b2 = (n0.y * (n3.z - n1.z) + n1.y * (n0.z - n3.z) + n3.y * (n1.z - n0.z)), b3 = (n0.y * (n1.z - n2.z) + n1.y * (n2.z - n0.z) + n2.y * (n0.z - n1.z)).
Definition at line 409 of file ArcaneFemFunctionsGpu.h.
Referenced by _computeElementMatrixTetra4Gpu(), _computeElementVectorTetra4Gpu(), computeElementMatrixTetra4Gpu(), computeElementMatrixTetra4SYCL(), computeElementVectorTetra4Gpu(), and computeElementVectorTetra4SYCL().
computeGradientYTetra4()
ARCCORE_HOST_DEVICE Real4 Arcane::FemUtils::Gpu::FeOperation3D::computeGradientYTetra4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline
Computes the Y gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
This method calculates gradient operator ∂/∂𝑦 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,4 for the four shape functions 𝑁ᵢ, hence the output is a vector of size 4.
    ∂𝐍/∂𝑦 = [ ∂𝑁₁/∂𝑦  ∂𝑁₂/∂𝑦  ∂𝑁₃/∂𝑦  ∂𝑁₄/∂𝑦 ]
    ∂𝐍/∂𝑦 = 1/(6𝑉) [ c0  c1  c2  c3 ]
where: c0 = (n1.z * (n3.x - n2.x) + n2.z * (n1.x - n3.x) + n3.z * (n2.x - n1.x)), c1 = (n0.z * (n2.x - n3.x) + n2.z * (n3.x - n0.x) + n3.z * (n0.x - n2.x)), c2 = (n0.z * (n3.x - n1.x) + n1.z * (n0.x - n3.x) + n3.z * (n1.x - n0.x)), c3 = (n0.z * (n1.x - n2.x) + n1.z * (n2.x - n0.x) + n2.z * (n0.x - n1.x)).
Definition at line 457 of file ArcaneFemFunctionsGpu.h.
Referenced by _computeElementMatrixTetra4Gpu(), _computeElementVectorTetra4Gpu(), computeElementMatrixTetra4Gpu(), computeElementMatrixTetra4SYCL(), computeElementVectorTetra4Gpu(), and computeElementVectorTetra4SYCL().
computeGradientZTetra4()
ARCCORE_HOST_DEVICE Real4 Arcane::FemUtils::Gpu::FeOperation3D::computeGradientZTetra4 (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const Accelerator::VariableNodeReal3InView & in_node_coord) inline
Computes the 𝑧 gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
This method calculates gradient operator ∂/∂𝑧 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,4 for the four shape functions 𝑁ᵢ, hence the output is a vector of size 4.
    ∂𝐍/∂𝑧 = [ ∂𝑁₁/∂𝑧  ∂𝑁₂/∂𝑧  ∂𝑁₃/∂𝑧  ∂𝑁₄/∂𝑧 ]
    ∂𝐍/∂𝑧 = 1/(6𝑉) [ d0  d1  d2  d3 ]
where: d0 = (n1.x * (n3.y - n2.y) + n2.x * (n1.y - n3.y) + n3.x * (n2.y - n1.y)), d1 = (n0.x * (n2.y - n3.y) + n2.x * (n3.y - n0.y) + n3.x * (n0.y - n2.y)), d2 = (n0.x * (n3.y - n1.y) + n1.x * (n0.y - n3.y) + n3.x * (n1.y - n0.y)), d3 = (n0.x * (n1.y - n2.y) + n1.x * (n2.y - n0.y) + n2.x * (n0.y - n1.y)).
Definition at line 505 of file ArcaneFemFunctionsGpu.h.
Referenced by _computeElementMatrixTetra4Gpu(), _computeElementVectorTetra4Gpu(), computeElementMatrixTetra4Gpu(), computeElementMatrixTetra4SYCL(), computeElementVectorTetra4Gpu(), and computeElementVectorTetra4SYCL().