ShArc: src/CAWF/Poisson/ElementMatrix.h File Reference
ElementMatrix.h File Reference
Functions
ARCCORE_HOST_DEVICE RealMatrix< 4, 4 > _computeElementMatrixTetra4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const ax::VariableNodeReal3InView &in_node_coord)
ARCCORE_HOST_DEVICE RealMatrix< 3, 3 > _computeElementMatrixTria3Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const ax::VariableNodeReal3InView &in_node_coord)
ARCCORE_HOST_DEVICE RealMatrix< 1, 4 > _computeElementVectorTetra4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const ax::VariableNodeReal3InView &in_node_coord, Int32 node_lid)
ARCCORE_HOST_DEVICE RealMatrix< 1, 3 > _computeElementVectorTria3Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView &cn_cv, const ax::VariableNodeReal3InView &in_node_coord, Int32 node_lid)
Function Documentation
_computeElementMatrixTetra4Gpu()
ARCCORE_HOST_DEVICE RealMatrix<4, 4> _computeElementMatrixTetra4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const ax::VariableNodeReal3InView & in_node_coord)
Definition at line 93 of file ElementMatrix.h.
References Arcane::FemUtils::Gpu::FeOperation3D::computeGradientXTetra4(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientYTetra4(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientZTetra4(), and Arcane::FemUtils::Gpu::MeshOperation::computeVolumeTetra4().
Referenced by FemModulePoisson::_assembleBilinearOperator().
_computeElementMatrixTria3Gpu()
ARCCORE_HOST_DEVICE RealMatrix<3, 3> _computeElementMatrixTria3Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const ax::VariableNodeReal3InView & in_node_coord)
Definition at line 41 of file ElementMatrix.h.
References Arcane::FemUtils::Gpu::MeshOperation::computeAreaTria3(), Arcane::FemUtils::Gpu::FeOperation2D::computeGradientXTria3(), and Arcane::FemUtils::Gpu::FeOperation2D::computeGradientYTria3().
Referenced by FemModulePoisson::_assembleBilinearOperator().
_computeElementVectorTetra4Gpu()
ARCCORE_HOST_DEVICE RealMatrix<1, 4> _computeElementVectorTetra4Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const ax::VariableNodeReal3InView & in_node_coord, Int32 node_lid)
Definition at line 107 of file ElementMatrix.h.
References Arcane::FemUtils::Gpu::FeOperation3D::computeGradientXTetra4(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientYTetra4(), Arcane::FemUtils::Gpu::FeOperation3D::computeGradientZTetra4(), and Arcane::FemUtils::Gpu::MeshOperation::computeVolumeTetra4().
Referenced by FemModulePoisson::_assembleBilinearOperator().
_computeElementVectorTria3Gpu()
ARCCORE_HOST_DEVICE RealMatrix<1, 3> _computeElementVectorTria3Gpu (CellLocalId cell_lid, const IndexedCellNodeConnectivityView & cn_cv, const ax::VariableNodeReal3InView & in_node_coord, Int32 node_lid)
Definition at line 54 of file ElementMatrix.h.
References Arcane::FemUtils::Gpu::MeshOperation::computeAreaTria3(), Arcane::FemUtils::Gpu::FeOperation2D::computeGradientXTria3(), and Arcane::FemUtils::Gpu::FeOperation2D::computeGradientYTria3().
Referenced by FemModulePoisson::_assembleBilinearOperator().