// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
#ifndef NUMERICS_CONDITION_FOLDERENUMERATOR_H
#define NUMERICS_CONDITION_FOLDERENUMERATOR_H
/* Author : desrozis at Fri Apr 24 15:13:48 2015
 * Generated by createNew
 */

#include "ArcGeoSim/Physics/Law2/Contribution/VariableFolder.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/**
 * \ingroup TwoPhaseFlow
 * \aigenerated
 * \brief Template class for enumerating over boundary/well condition folders.
 *
 * Provides iteration over named variable folders (e.g., boundary patches
 * or well regions), each associated with a slice of variables and properties.
 */
template<Law::ContainerKind::eType CK, Law::ItemKind::eType IK>
class FolderEnumerator
{
public:
  
  /** \aigenerated The variable folder type for this enumeration */
  typedef Law::VariableFolder<CK,IK> Folder;
  
public:

  /** \aigenerated Constructs the enumerator from folder and name arrays */
  FolderEnumerator(const Arcane::Array<Folder*>& folders,
 		  	  	       const Arcane::StringArray& names)
    : m_folders(folders)
	  , m_names(names)
    , m_index(0)
  {
    ARCANE_ASSERT((folders.size() == names.size()),("folder and names size different"));
  }

  /** \aigenerated Copy constructor */
  FolderEnumerator(const FolderEnumerator& e)
    : m_folders(e.m_folders)
  	, m_names(e.m_names)
    , m_index(0) {}

  /** \aigenerated True if enumeration is not finished (increment first) */
  bool hasNext() const { return m_index != size(); }

  /** \aigenerated Increments to the next element */
  void operator++() { m_index ++; }

  /** \aigenerated Access to the current folder (const) */
  const Folder& folder() const { return *(m_folders[m_index]); }

  /** \aigenerated Access to the current folder (mutable) */
  Folder& folder() { return *(m_folders[m_index]); }

  /** \aigenerated Returns the name of the current folder */
  Arcane::String name() const { return m_names[m_index]; }

  /** \aigenerated Returns the number of elements to enumerate */
  Arcane::Integer size() const { return m_folders.size(); }

  /** \aigenerated Returns the current index */
  Arcane::Integer index() const { return m_index; }

private:

  /** \aigenerated List of folder pointers to enumerate */
  const Arcane::Array<Folder*>& m_folders;

  /** \aigenerated List of folder names */
  const Arcane::StringArray& m_names;

  /** \aigenerated Current index in the enumeration */
  Arcane::Integer m_index;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* NUMERICS_CONDITION_FOLDERENUMERATOR_H */
