// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef BOUNDARYCONDITION_IBOUNDARYMANAGER_H
#define BOUNDARYCONDITION_IBOUNDARYMANAGER_H
/* Author : desrozis at Thu Aug 23 15:27:31 2012
 * Generated by createNew
 */

#include "FolderEnumerator.h"

#include "ArcRes/Entities/System.h"
#include "ArcGeoSim/Physics/Gump/Property.h"


/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/**
 * \ingroup TwoPhaseFlow
 * \aigenerated
 * \brief Interface for boundary condition management.
 *
 * Manages the registration, creation, and update of boundary conditions
 * for the two-phase flow simulation. Supports enumeration over active
 * boundary folders.
 */
class IBoundaryManager
{
public:
  
  /** \aigenerated Enumerator type for iterating over boundary folders */
  typedef FolderEnumerator<Law::ContainerKind::PartialVariable,
                           Law::ItemKind::Face> BoundaryEnumerator;

  /** \aigenerated Virtual destructor */
  virtual ~IBoundaryManager() {}
  
public:

  /** \aigenerated Initializes boundary conditions: registers properties,
   *  creates variables, and populates at current time */
  virtual void init(ArcRes::System& system) = 0;

  /** \aigenerated Updates boundary conditions at the current time */
  virtual void update(ArcRes::System& system) = 0;

  /** \aigenerated Checks whether boundary conditions exist */
  virtual bool exists() const = 0;

  /** \aigenerated Returns an enumerator over the active boundaries */
  virtual BoundaryEnumerator boundaryEnumerator() const = 0;

};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#define ENUMERATE_BOUNDARY(e, c) \
  for(IBoundaryManager::BoundaryEnumerator e = c; e.hasNext(); ++e)

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* BOUNDARYCONDITION_IBOUNDARYMANAGER_H */
