// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
/* Author : desrozis at Fri Mar 21 12:10:47 2014
 * Generated by createNew
 */

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
//#define SPARSE_AUDI
// generated by gump
#include "ArcRes/Entities/System.h"
#include "ArcRes/Properties.h"

#include "BoundaryCondition/IBoundaryManager.h"
#include "InitialCondition/IInitialCondition.h"
#include "WellCondition/IWellManager.h"

#include "PhysicalSystem/IPhysicalSystem.h"
#include "PhysicalSystem/IVariableManager.h"

#include "PhysicalLaws/ILawConfigurator.h"

#include "ArcGeoSim/Numerics/DiscreteOperator/IDivKGradDiscreteOperator.h"

#include "ArcGeoSim/Physics/Law2/VariableManager.h"
#include "ArcGeoSim/Physics/Law2/FunctionManager.h"
#include "ArcGeoSim/Physics/Law2/FunctionEvaluator.h"
#include "ArcGeoSim/Physics/Law2/EvaluationResults.h"
#include "ArcGeoSim/Physics/Law2/Contribution/Contribution.h"
#include "ArcGeoSim/Physics/Law2/Contribution/ContributionAccessor.h"
#include "ArcGeoSim/Physics/Law2/Contribution/VariableFolderAccessor.h"


#include "ArcGeoSim/Numerics/NumericalScheme/TwoPointsScheme/TwoPointsTransmissivity.h"
#include "ArcGeoSim/Numerics/NumericalScheme/TwoPointsStencil.h"
#include "ArcGeoSim/Numerics/ArcNumTools/LinearAlgebra/Vector.h"
#include "ArcGeoSim/Numerics/ArcNumTools/LinearAlgebra/Matrix.h"
#include "ArcGeoSim/Numerics/ArcNumTools/Solver/INewtonSolver.h"

#include "ArcGeoSim/Appli/AppService.h"
#include "ArcGeoSim/Appli/ITimeLoopSnapshotManager.h"
#include "ArcGeoSim/Time/Activity/ReplayTimeStep.h"

#include "ArcGeoSim/Mesh/Geometry/IGeometryMng.h"
#include "ArcGeoSim/Mesh/Geometry/ManualUpdateGeometryPolicy.h"

#include "ArcGeoSim/Numerics/GroupCreator/IGroupCreator.h"

#include "TwoPhaseFlowSimulation_axl.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/**
 * \ingroup TwoPhaseFlow
 * \aigenerated
 * Main module for two-phase flow simulation in porous media.
 *
 * TwoPhaseFlowSimulationModule implements the coupled system of equations
 * for two-phase (water/oil or water/gas) flow, including accumulation,
 * internal flux, and boundary flux computations. It uses the Newton method
 * for solving the non-linear system and supports various physical laws
 * (capillary pressure, relative permeability, fluid density, etc.).
 */
class TwoPhaseFlowSimulationModule
        : public ArcaneTwoPhaseFlowSimulationObject
                , public ArcNum::INonLinearSystem
{
public:

    /** \aigenerated Constructs the module */
    TwoPhaseFlowSimulationModule(const Arcane::ModuleBuildInfo & sbi)
            : ArcaneTwoPhaseFlowSimulationObject(sbi)
    {}

    /** \aigenerated Destructor */
    ~TwoPhaseFlowSimulationModule() {}

public:

    /** \aigenerated Initializes the simulation */
    void init();

    /** \aigenerated Executes one computation step */
    void compute();

    /** \aigenerated Returns the number of equations in the system */
    Integer nbEquations() const { return m_unknown_manager.size() ; }

    /** \aigenerated Returns the system domain */
    Domain const& systemDomain() const {  return m_domain ; }

    /** \aigenerated Initializes the linear system profile (matrix sparsity) */
    void initLinearSystemProfile(Arcane::CellGroup cells,
                               Alien::MatrixProfiler& blockProfiler,
                               Arcane::ConstArray2View<Arcane::Integer> indexes,
                               Arcane::Integer block_size) ;

    /** \aigenerated Sets the solution variable pointers */
    void setSolutionVariables(Arcane::SharedArray<Arcane::VariableCellReal*>& solutions) ;

    /** \aigenerated Returns the equation system (unknowns manager) */
    const Law::PropertyVector& equationSystem() const { return m_unknown_manager; }

    /** \aigenerated Builds the residual and Jacobian matrix */
    void build(ArcNum::Vector& residual, ArcNum::Matrix& jacobian);

    /** \aigenerated Applies constraints on the solution (e.g. clipping) */
    void applyConstraintOnSolution(bool &NonPhysicalSolution);

    /** \aigenerated Returns the variable cell folder */
    const Law::VariableCellFolder& folder() const { return m_folder->domain(); }

private:

    /** \aigenerated Returns the Gump system */
    ArcRes::System& system() { return m_system; }

    /** \aigenerated Returns the unknown properties manager */
    const Law::PropertyVector& unknownsManager() const { return m_unknown_manager; }

    /** \aigenerated Returns the law function manager */
    Law::FunctionManager& functionMng() { return m_funcs; }

    /** \aigenerated Returns the domain for contributions */
    Law::VariableCellFolder& domain() { return m_folder->domain(); }

    /** \aigenerated Returns the domain at time T0 */
    Law::VariableCellFolder& domainT0() { return m_folder->domainT0(); }

    /** \aigenerated Returns the domain at time Tn */
    Law::VariableCellFolder& domainTn() { return m_folder->domainTn(); }

    /** \aigenerated Adds a time-varying variable for snapshot management */
    void _addTimeVariable(const Gump::ScalarRealProperty& property);

    /** \aigenerated Initializes the physical system */
    void _initPhysicalSystem();

    /** \aigenerated Initializes mesh geometry */
    void _initGeometry();

    /** \aigenerated Initializes mesh groups */
    void _initGroup() ;

    /** \aigenerated Initializes domain variable manager */
    void _initDomainVariableMng();

    /** \aigenerated Initializes boundary variable manager */
    void _initBoundaryVariableMng();

    /** \aigenerated Initializes well variable manager */
    void _initWellVariableMng();

    /** \aigenerated Initializes time variable manager (restart snapshots) */
    void _initTimeVariableMng();

    /** \aigenerated Initializes transmissivity operators */
    void _initTransmissivity();

    /** \aigenerated Initializes the equation system (unknowns) */
    void _initEquationSystem();

    /** \aigenerated Initializes the restore/snapshot system */
    void _initRestore();

    /** \aigenerated Configures and initializes physical laws */
    void _initLaws();

    /** \aigenerated Initializes the Newton solver */
    void _initNewton();

    /** \aigenerated Updates mesh geometry at each time step */
    void _updateGeometry();

    /** \aigenerated Evaluates physical laws on a given folder */
    template<typename Folder>
    void _evaluateLaws(Folder& folder, Law::EvaluationMode derivability);

    /** \aigenerated Builds the accumulation term (mass matrix) */
    void _buildAccumulation(ArcNum::Vector& residual, ArcNum::Matrix& jacobian);

    /** \aigenerated Builds the closure equations */
    void _buildClosure(ArcNum::Vector& residual, ArcNum::Matrix& jacobian);

    /** \aigenerated Builds the internal flux term */
    void _buildFluxInternal(ArcNum::Vector& residual, ArcNum::Matrix& jacobian);

    /** \aigenerated Builds the boundary flux term */
    void _buildFluxBoundary(ArcNum::Vector& residual, ArcNum::Matrix& jacobian);

    /** \aigenerated Builds the well flux term */
    void _buildFluxWell(ArcNum::Vector& residual, ArcNum::Matrix& jacobian);

    void _twoPointsProfiler(Arcane::CellGroup cells,
                          Alien::MatrixProfiler& blockProfiler,
                          Arcane::ConstArray2View<Arcane::Integer> indexes,
                          Arcane::Integer block_size) const
    {
      Arcane::CellGroup group = cells;
      info() << "Define profil on group '" << group.name() << "' size = " << group.size();

      ENUMERATE_CELL(icell, group.own()) {
        const Arcane::Integer lid = icell->localId();
        blockProfiler.addMatrixEntry(indexes[lid][0]/block_size, indexes[lid][0]/block_size);
      }

      ENUMERATE_FACE(iface, group.innerActiveFaceGroup()) {
        const Arcane::Cell back_cell = iface->backCell();
        const Arcane::Integer back_lid = back_cell.localId();
        const Arcane::Cell front_cell = iface->frontCell();
        const Arcane::Integer front_lid = front_cell.localId();
        if(back_cell->isOwn())
          blockProfiler.addMatrixEntry(indexes[back_lid][0]/block_size, indexes[front_lid][0]/block_size);
        if(front_cell->isOwn())
          blockProfiler.addMatrixEntry(indexes[front_lid][0]/block_size, indexes[back_lid][0]/block_size);
        }

      info() << "OK Define profil";
    }

    void _multiPointsProfiler(Arcane::CellGroup cells,
                            Alien::MatrixProfiler& blockProfiler,
                            Arcane::ConstArray2View<Arcane::Integer> indexes,
                            Arcane::Integer block_size) const {
      Arcane::CellGroup group = cells;

      info() << "Define profil on group '" << group.name() << "' size = " << group.size();

      ENUMERATE_CELL(icell, group.own()) {
        const Arcane::Integer lid = icell->localId();
        //profiler(indexes[lid], indexes[lid]);
        blockProfiler.addMatrixEntry(indexes[lid][0]/block_size,indexes[lid][0]/block_size);
      }

      ENUMERATE_FACE(iface, group.innerActiveFaceGroup()) {
        m_schemeStencil -> init(iface) ;

        const Arcane::Cell backCell(iface->backCell()) ;

        if(backCell.isOwn()) {
          const Arcane::Integer backLid(backCell.localId()) ;
          for(m_schemeStencil -> begin() ; ! m_schemeStencil -> end() ; m_schemeStencil -> next()) {
            const auto& lawCell(m_schemeStencil->cell()) ;
            const auto cellLId(lawCell.localId()) ;
            //profiler(indexes[backLid], indexes[cellLId]);
            blockProfiler.addMatrixEntry(indexes[backLid][0]/block_size, indexes[cellLId][0]/block_size);
          }
        }

        const Arcane::Cell frontCell(iface->frontCell()) ;

        if(frontCell.isOwn()) {
          const Arcane::Integer frontLid(frontCell.localId()) ;
          for(m_schemeStencil -> begin() ; ! m_schemeStencil -> end() ; m_schemeStencil -> next()) {
            const auto& lawCell(m_schemeStencil->cell()) ;
            const auto cellLId(lawCell.localId()) ;
            //profiler(indexes[frontLid], indexes[cellLId]);
            blockProfiler.addMatrixEntry(indexes[frontLid][0]/block_size, indexes[cellLId][0]/block_size);
          }
        }
      }

      ENUMERATE_FACE(iface, group.outerActiveFaceGroup()) {
        m_schemeStencil -> init(iface) ;

        const Arcane::Cell boundaryCell(iface->boundaryCell()) ;

        if(boundaryCell.isOwn()) {
          const Arcane::Integer boundLid(boundaryCell.localId()) ;
          for(m_schemeStencil -> begin() ; ! m_schemeStencil -> end() ; m_schemeStencil -> next()) {
            const auto& lawCell(m_schemeStencil->cell()) ;
            const auto cellLId(lawCell.localId()) ;
            //profiler(indexes[boundLid], indexes[cellLId]);
            blockProfiler.addMatrixEntry(indexes[boundLid][0]/block_size, indexes[cellLId][0]/block_size);
          }
        }
      }

      //TODO : Create the group of contacts from the connections and complete the profiling of the matrix

      info() << "Multi-points profile defined";
    }

private:

    /** \aigenerated Two-point transmissivity operator */
    ArcNum::TwoPointsTransmissivity m_transmissivities;

    /** \aigenerated Multi-point stencil for flux computation (optional) */
    std::shared_ptr<ArcNum::MultiPointsStencil> m_schemeStencil ;

    /** \note Original: unknowns as Law::PropertyVector!
     *  \aigenerated Manager for unknown properties */
    Law::PropertyVector m_unknown_manager;

    /** \note Original: system instance based on gump
     *  \aigenerated Gump-based system instance */
    ArcRes::System m_system;

    /** \note Original: evolutive variable management restart newton
     *  \aigenerated Snapshot manager for restart on Newton failure */
    ArcGeoSim::AppService<ArcGeoSim::ITimeLoopSnapshotManager> m_snapshots;

    /** \note Original: law function manager and evaluator
     *  \aigenerated Function manager for physical law evaluation */
    Law::FunctionManager m_funcs;

    /** \aigenerated Properties to evaluate in law functions */
    Arcane::SharedArray<Gump::ScalarRealProperty> m_properties_to_evaluate;

    /** \note Original: acces domain for contributions
     *  \aigenerated Domain accessor for contribution assembly */
    ArcGeoSim::AppService<IVariableManager> m_folder;

    /** \aigenerated Non-linear system domain */
    ArcNum::INonLinearSystem::Domain        m_domain ;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/** AI comment: Registers a scalar property for time-varying snapshot management */
void
TwoPhaseFlowSimulationModule::
_addTimeVariable(const Gump::ScalarRealProperty& property)
{
    domainTn().addVariable(property);
    auto v   = Law::values(domain(), property);
    auto vTn = Law::values(domainTn(), property);
    m_snapshots->snap(v, vTn);
}

/** AI comment: Loads the Gump physical system from the service manager */
void
TwoPhaseFlowSimulationModule::
_initPhysicalSystem()
{
    if(m_system == NULL) {
        ArcGeoSim::AppService<IPhysicalSystem> physical_system;
        m_system = physical_system->system();
    }
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/** AI comment: Full initialization sequence: system, geometry, groups, variables, laws, Newton */
void
TwoPhaseFlowSimulationModule::
init()
{

    info() << "create physical solver";
    _initPhysicalSystem();

    info() << "create function manager";
    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    if(fluid.phases().size() != 2)
        fatal() << "fluid-system should have exactly two phases";

    if(system().solidSubSystem().phases().size() != 0)
        fatal() << "solid-system should not be filled";

    _initGeometry();
    _initGroup() ;
    _initDomainVariableMng();
    if(options()->hasBoundaryCondition())
        _initBoundaryVariableMng();
    _initTransmissivity();
    if(options()->hasWellCondition())
        _initWellVariableMng();
    _initTimeVariableMng();
    _initLaws();
    _initRestore();
    _initEquationSystem();
    _initNewton();
}

/** AI comment: Initializes matrix profile using two-point or multi-point stencil */
void
TwoPhaseFlowSimulationModule::
initLinearSystemProfile(Arcane::CellGroup cells,
                        Alien::MatrixProfiler& blockProfiler,
                        Arcane::ConstArray2View<Arcane::Integer> indexes,
                        Integer block_size)
{

  if(m_schemeStencil == nullptr)
    _twoPointsProfiler(cells, blockProfiler, indexes, block_size);
  else
    _multiPointsProfiler(cells, blockProfiler, indexes, block_size) ;
}

/** AI comment: Sets pointers to solution variables for the Newton solver */
void TwoPhaseFlowSimulationModule::
setSolutionVariables(Arcane::SharedArray<Arcane::VariableCellReal*>& solutions)
{
  auto accessor = folder().lawVariableAccessor();
  for(Integer i =0; i< m_unknown_manager.size(); ++i)
  {
    const Law::ScalarRealProperty& property = m_unknown_manager[i];
    solutions.add(new Arcane::VariableCellReal(accessor.values(property)));
  }
}
/*---------------------------------------------------------------------------*/

/** AI comment: Solves the non-linear system via Newton method at each time step */
void
TwoPhaseFlowSimulationModule::
compute()
{
    info() << "solve non linear problem at iteration " << m_global_iteration();
    bool r = options()->numerics().newton()->solve();
    if(not r) {
        // snapped evolutive variables go back to initial time step value
        throw ArcGeoSim::TimeStep::ReplayException("Error in computation - go backward!");
    }
}

/*---------------------------------------------------------------------------*/

/** AI comment: Builds the residual vector and Jacobian matrix for the non-linear system */
void
TwoPhaseFlowSimulationModule::
build(ArcNum::Vector& residual, ArcNum::Matrix& jacobian)
{
    residual = 0.;

    _evaluateLaws(domain(), Law::eWithDerivative);

    _buildAccumulation(residual, jacobian);
    _buildFluxInternal(residual, jacobian);
    if(options()->hasBoundaryCondition())
        _buildFluxBoundary(residual, jacobian);
    if(options()->hasWellCondition())
        _buildFluxWell(residual, jacobian);
    _buildClosure(residual, jacobian);
}

/*---------------------------------------------------------------------------*/

/** AI comment: Clips saturation to [0,1] and renormalizes to enforce saturation sum constraint */
void
TwoPhaseFlowSimulationModule::
applyConstraintOnSolution(bool &NonPhysicalSolution)
{
    auto pressure = Law::values<ArcRes::Pressure>(domain(),system());

    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();
    auto S = Law::values<ArcRes::Saturation>(domain(),fluid.phases());

    ENUMERATE_CELL(icell, allCells()) {
        Arcane::Real totalS = 0;

        ENUMERATE_PHASE(iphase, fluid.phases()) {
            if (S[iphase][icell] < 0 ) {  S[iphase][icell] = 0; }
            if (S[iphase][icell] > 1 ) {  S[iphase][icell] = 1; }
            totalS += S[iphase][icell];
        }

        ENUMERATE_PHASE(iphase, fluid.phases()) {
            S[iphase][icell] = S[iphase][icell] / totalS;
        }
    }
}


/*---------------------------------------------------------------------------*/

/** AI comment: Registers and computes geometric properties (volume, center, face normal) */
void
TwoPhaseFlowSimulationModule::
_initGeometry()
{
    info() << "register geometric properties";

    IAppServiceMng* app_service_mng = IAppServiceMng::instance(subDomain()->serviceMng());
    IGeometryMng* geometry_mng = app_service_mng->find<IGeometryMng>(true);
    geometry_mng->setPolicyTolerance(true);

    geometry_mng->addItemGroupProperty(allCells(),
                                       IGeometryProperty::PMeasure,
                                       IGeometryProperty::PVariable);

    geometry_mng->addItemGroupProperty(allCells(),
                                       IGeometryProperty::PCenter,
                                       IGeometryProperty::PVariable);

    geometry_mng->addItemGroupProperty(allFaces(),
                                       IGeometryProperty::PMeasure,
                                       IGeometryProperty::PVariable);

    geometry_mng->addItemGroupProperty(allFaces(),
                                       IGeometryProperty::PCenter,
                                       IGeometryProperty::PVariable);

    geometry_mng->addItemGroupProperty(allFaces(),
                                       IGeometryProperty::PNormal,
                                       IGeometryProperty::PVariable);

    info() << "force update of geometric properties";

    _updateGeometry();

}

/*---------------------------------------------------------------------------*/

/** AI comment: Forces an update of all geometric properties via the geometry manager */
void
TwoPhaseFlowSimulationModule::
_updateGeometry(){
    IGeometryPolicy* geometry_policy = new ManualUpdateGeometryPolicy;
    IAppServiceMng* app_service_mng = IAppServiceMng::instance(subDomain()->serviceMng());
    IGeometryMng* geometry_mng = app_service_mng->find<IGeometryMng>(true);
    geometry_mng->update(mesh(), geometry_policy);
    delete geometry_policy;
}
/*---------------------------------------------------------------------------*/

/** AI comment: Creates mesh groups via the group creator service */
void
TwoPhaseFlowSimulationModule::
_initGroup()
{
    auto groupCreator(options() -> groupCreator()) ;
    groupCreator -> init() ;
    groupCreator -> prepare() ;
    // Group creation add new Geometry properties: need to update GeometryMng
    _updateGeometry();
    groupCreator -> apply() ;
}

/*---------------------------------------------------------------------------*/

/** AI comment: Registers domain variable containers for all fluid properties and applies IC */
void
TwoPhaseFlowSimulationModule::
_initDomainVariableMng()
{
    info() << "define domain containers for properties";

    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    domain().addVariable(ArcRes::Pressure(system()));
    domain().addVariable(ArcRes::Permeability(fluid));
    domain().addVariable(ArcRes::XPermeability(fluid));
    domain().addVariable(ArcRes::YPermeability(fluid));
    domain().addVariable(ArcRes::ZPermeability(fluid));
    domain().addVariable(ArcRes::VolumeFraction(fluid));

    ENUMERATE_PHASE(iphase, fluid.phases()) {
        domain().addVariable(ArcRes::Density(iphase), Law::WithDerivative);
        domain().addVariable(ArcRes::Viscosity(iphase), Law::WithDerivative);
        domain().addVariable(ArcRes::RelativePermeability(iphase), Law::WithDerivative);
        domain().addVariable(ArcRes::Saturation(iphase));
        domain().addVariable(ArcRes::CapillaryPressure(iphase), Law::WithDerivative);

    }

    info() << "initialize domain properties";
    m_domain.init(domain().key(),domain().support()) ;

    for(Arcane::Integer i = 0; i < options()->initialCondition.size(); ++i) {
        options()->initialCondition[i]->init(system(),domain());
    }
}

/*---------------------------------------------------------------------------*/

/** AI comment: Initializes boundary condition variables and containers for each boundary */
void
TwoPhaseFlowSimulationModule::
_initBoundaryVariableMng()
{
    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    info() << "initialize boundary properties";
    options()->boundaryCondition()->init(system());

    info() << "define boundary containers for others properties";
    ENUMERATE_BOUNDARY(bound,options()->boundaryCondition()->boundaryEnumerator()) {

        Law::PartialVariableFaceFolder& bound_vars = bound.folder();

        ENUMERATE_PHASE(iphase,fluid.phases()) {
            bound_vars.addVariable(ArcRes::Density(iphase));
            bound_vars.addVariable(ArcRes::Viscosity(iphase));
            bound_vars.addVariable(ArcRes::RelativePermeability(iphase));
            bound_vars.addVariable(ArcRes::CapillaryPressure(iphase));
        }
    }

}

/*---------------------------------------------------------------------------*/

/** AI comment: Initializes well condition variables and containers for each well */
void
TwoPhaseFlowSimulationModule::
_initWellVariableMng()
{
    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    options()->wellCondition()->init(system(), domain());
    info() << "define well containers for others properties";
    ENUMERATE_WELL(well,options()->wellCondition()->enumerator()) {
        Law::PartialVariableCellFolder& well_vars = well.folder();
        ENUMERATE_PHASE(iphase,fluid.phases()) {
            well_vars.addVariable(ArcRes::Density(iphase));
            well_vars.addVariable(ArcRes::Viscosity(iphase));
            well_vars.addVariable(ArcRes::RelativePermeability(iphase));
            well_vars.addVariable(ArcRes::CapillaryPressure(iphase));
        }
    }

}

/*---------------------------------------------------------------------------*/

/** AI comment: Registers time-varying variables for Newton failure rollback */
void
TwoPhaseFlowSimulationModule::
_initTimeVariableMng()
{
    info() << "register containers of property to restore if failure";
    _addTimeVariable(ArcRes::Pressure(system()));

    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();
    ENUMERATE_PHASE(iphase, fluid.phases()) {
        _addTimeVariable(ArcRes::Saturation(iphase));
        _addTimeVariable(ArcRes::Density(iphase));
        _addTimeVariable(ArcRes::CapillaryPressure(iphase));
    }
}

/*---------------------------------------------------------------------------*/

/** AI comment: Configures physical laws and evaluates them on domain, boundary, and wells */
void
TwoPhaseFlowSimulationModule::
_initLaws()
{
    info() << "prepare laws for evaluations";

    for (Arcane::Integer i = 0; i < options()->law.size(); ++i) {
        options()->law[i]->configure(m_funcs, system());
    }

    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();
    ENUMERATE_PHASE(iphase, fluid.phases()) {
        m_properties_to_evaluate.add(ArcRes::Density(iphase));
        m_properties_to_evaluate.add(ArcRes::Viscosity(iphase));
        m_properties_to_evaluate.add(ArcRes::RelativePermeability(iphase));
        m_properties_to_evaluate.add(ArcRes::CapillaryPressure(iphase));
    }

    if(options()->hasBoundaryCondition()){
        info() << "evaluate laws on boundary";
        ENUMERATE_BOUNDARY(bound,options()->boundaryCondition()->boundaryEnumerator())
        {
            _evaluateLaws(bound.folder(), Law::eWithoutDerivative);
        }
    }

    if(options()->hasWellCondition()){
        info() << "evaluate laws on well";
        ENUMERATE_WELL(well,options()->wellCondition()->enumerator())
        {
            _evaluateLaws(well.folder(), Law::eWithoutDerivative);
        }
    }

    info() << "evaluate laws in domain";
    _evaluateLaws(domain(), Law::eWithoutDerivative);
}

/*---------------------------------------------------------------------------*/

/** AI comment: Initializes Tn containers by copying initial law evaluation results */
void
TwoPhaseFlowSimulationModule::
_initRestore()
{
    info() << "compute law containers a first time step ";

    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    auto Pc = Law::values<ArcRes::CapillaryPressure>(domain(),fluid.phases());
    auto Pc_tn = Law::values<ArcRes::CapillaryPressure>(domainTn(),fluid.phases());

    auto rho = Law::values<ArcRes::Density>(domain(),fluid.phases());
    auto rho_tn = Law::values<ArcRes::Density>(domainTn(),fluid.phases());

    auto S = Law::values<ArcRes::Saturation>(domain(),fluid.phases());
    auto S_tn = Law::values<ArcRes::Saturation>(domainTn(),fluid.phases());

    ENUMERATE_PHASE(iphase, system().phases()) {
        rho_tn[iphase].copy(rho[iphase]);
        S_tn[iphase].copy(S[iphase]);
        Pc_tn[iphase].copy(Pc[iphase]);
    }
}

/*---------------------------------------------------------------------------*/

/** AI comment: Computes transmissivity operator using scalar or tensor permeability */
void
TwoPhaseFlowSimulationModule::
_initTransmissivity()
{
    info() << "compute transmissivities ";
    m_transmissivities.addOperator("T", options()->numerics().twoPointsScheme());

    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    auto scalarPerm = options() -> scalarPerm();

    if(scalarPerm){
        auto T = Law::values<ArcRes::Permeability>(domain(),fluid);
        m_transmissivities.computeOperator( "T", T);
    }else{
        auto Kx = Law::values<ArcRes::XPermeability>(domain(),fluid);
        auto Ky = Law::values<ArcRes::YPermeability>(domain(),fluid);
        auto Kz = Law::values<ArcRes::ZPermeability>(domain(),fluid);
        Arcane::VariableCellReal permXInFile(Arcane::VariableBuildInfo(mesh(), options() -> permxVarName())) ;
        Arcane::VariableCellReal permYInFile(Arcane::VariableBuildInfo(mesh(), options() -> permyVarName())) ;
        Arcane::VariableCellReal permZInFile(Arcane::VariableBuildInfo(mesh(), options() -> permzVarName())) ;
        Arcane::VariableCellReal3 K((Arcane::VariableBuildInfo(mesh(), "PermXYZ")));
        ENUMERATE_CELL(icell, allCells()) {
            K[icell][0] = permXInFile[icell]* 1e-14;
            Kx[icell] = permXInFile[icell]* 1e-14;

            K[icell][1] = permYInFile[icell]* 1e-14;
            Ky[icell] = permYInFile[icell]* 1e-14;

            K[icell][2] = permZInFile[icell]* 1e-14;
            Kz[icell] = permZInFile[icell]* 1e-14;
        }
        m_transmissivities.computeOperator( "T", K);
    }
}

/*---------------------------------------------------------------------------*/

/** AI comment: Sets up equation/unknown system: pressure for phase 0, saturation for others */
void
TwoPhaseFlowSimulationModule::
_initEquationSystem()
{
    info() << "create equations / unknowns system";

    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();
    ENUMERATE_PHASE(iphase, fluid.phases()) {
        if(iphase.index() == 0)
            m_unknown_manager << ArcRes::Pressure(system());
        else
            m_unknown_manager << ArcRes::Saturation(iphase);
    }
    m_unknown_manager << ArcRes::Saturation(system().phase(0));
}

/*---------------------------------------------------------------------------*/

/** AI comment: Initializes the Newton solver with this module as the non-linear system */
void
TwoPhaseFlowSimulationModule::
_initNewton()
{
    info() << "initialize newton solver";
    auto problem = ArcGeoSim::makeDelegatedSharedPtr<INonLinearSystem>(this);
    options()->numerics().newton()->init(problem);
}

/*---------------------------------------------------------------------------*/

template<typename Folder>
void
TwoPhaseFlowSimulationModule::
_evaluateLaws(Folder& folder, Law::EvaluationMode derivability)
{
    Arcane::IntegerUniqueArray ids(m_properties_to_evaluate.size());
    std::transform(m_properties_to_evaluate.begin(), m_properties_to_evaluate.end(),
                   ids.begin(), [](const Gump::Property& p) { return p.id(); });
    Law::FunctionEvaluator evaluator(m_funcs,ids);
    evaluator.evaluate(folder.lawVariableAccessor(),
                       folder.support(), derivability);
}

/*---------------------------------------------------------------------------*/

/** AI comment: Builds the accumulation term (mass * saturation * density / delta-t) */
void TwoPhaseFlowSimulationModule::
_buildAccumulation(ArcNum::Vector& residual, ArcNum::Matrix& jacobian)
{
    info() << "build accumulation";
    // Get Geoxim Entities

    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    // Get Geometry Variables
    ArcGeoSim::AppService<IGeometryMng> geometry_mng;

    const IGeometryMng::RealVariable& volume =
            geometry_mng->getRealVariableProperty(allCells(), IGeometryProperty::PMeasure);

    // Get Geoxim Domain Explicit Variables

    auto phi = Law::values<ArcRes::VolumeFraction>(domain(),fluid);

    // Get Geoxim Domain Implicit Variables at Time Tn

    auto rho_tn = Law::values<ArcRes::Density>(domainTn(),fluid.phases());
    auto S_tn = Law::values<ArcRes::Saturation>(domainTn(),fluid.phases());

    // Get Geoxim Domain Implicit Variables

    const auto& um = unknownsManager();
    auto rho = Law::contribution<ArcRes::Density>(domain(),functionMng(),um,fluid.phases());
    auto S = Law::contribution<ArcRes::Saturation>(domain(),functionMng(),um,fluid.phases());

    const Arcane::Real deltat = m_global_deltat();

    // Build Term

    ENUMERATE_CELL(icell, ownCells()) {

        const Arcane::Real pore_volume = phi[icell] * volume[icell] ;
        const Arcane::Real cell_factor = pore_volume / deltat;

        ArcNum::initContribution();

        ENUMERATE_PHASE(iphase, system().phases()) {

            const Arcane::Integer iequation = iphase.index();

            const auto C =
                    cell_factor  * (  rho   [iphase][icell] * S   [iphase][icell]
                                      - rho_tn[iphase][icell] * S_tn[iphase][icell] ) ;

            residual[iequation][icell]        += C;
            jacobian[iequation][icell][icell] += C;
        }
    }
}

/*---------------------------------------------------------------------------*/

/** AI comment: Builds the internal flux term between cells using two-point flux approximation */
void TwoPhaseFlowSimulationModule::
_buildFluxInternal(ArcNum::Vector& residual, ArcNum::Matrix& jacobian)
{
    info() << "build internal flux";

    // Get Geoxim Entities
    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    // Get Discrete Operator Transmissibility
    const Arcane::VariableFaceReal& T = m_transmissivities["T"][ArcNum::Classical];

    const auto& um = unknownsManager();

    // Get Geoxim Domain Implicit Variables
    auto P = Law::contribution<ArcRes::Pressure>(domain(),functionMng(),2,um,system());
    auto Pc = Law::contribution<ArcRes::CapillaryPressure>(domain(),functionMng(),2,um,fluid.phases());
    auto kr = Law::contribution<ArcRes::RelativePermeability>(domain(),functionMng(),2,um,fluid.phases());
    auto mu = Law::contribution<ArcRes::Viscosity>(domain(),functionMng(),2,um,fluid.phases());
    auto rho = Law::contribution<ArcRes::Density>(domain(),functionMng(),2,um,fluid.phases());

    // Build Term

    Arcane::FaceGroup inner_faces = mesh()->allCells().innerFaceGroup();

    ENUMERATE_FACE(iface,inner_faces) {

	ArcNum::initContribution();
	
        ArcNum::TwoPointsStencil stencil(iface);

        auto const& cell_k = stencil.back();
        auto const& cell_l = stencil.front();

        ENUMERATE_PHASE(iphase, fluid.phases()) {

            const auto grad_kl = T[iface] * (P[cell_k] + Pc[iphase][cell_k]  - P[cell_l] - Pc[iphase][cell_l] );

            const auto mobility_k =
                    rho[iphase][cell_k] * kr[iphase][cell_k] / mu[iphase][cell_k];

            const auto mobility_l =
                    rho[iphase][cell_l] * kr[iphase][cell_l] / mu[iphase][cell_l];

#ifdef SPARSE_AUDI
            const auto flux_kl = (audi::value(grad_kl)>=0) ?
    		        mobility_k*grad_kl :
			mobility_l*grad_kl ;
#else
            const Law::Contribution flux_kl =
                    (   audi::one(grad_kl >= 0) * mobility_k
                        + audi::one(grad_kl <  0) * mobility_l ) * grad_kl;
#endif

            const Arcane::Integer iequation = iphase.index();

            if (cell_k.isOwn()) {
                residual[iequation][cell_k]          += flux_kl;
                jacobian[iequation][cell_k][stencil] += flux_kl;
            }

            if (cell_l.isOwn()) {
                residual[iequation][cell_l]          -= flux_kl;
                jacobian[iequation][cell_l][stencil] -= flux_kl;
            }
        }
    }
}

/*---------------------------------------------------------------------------*/

/** AI comment: Builds the boundary flux term using Dirichlet boundary condition values */
void TwoPhaseFlowSimulationModule::
_buildFluxBoundary(ArcNum::Vector& residual, ArcNum::Matrix& jacobian)
{
    info() << "build boundary flux";

    // Get Geoxim Entities
    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    // Get Discrete Operator Transmissibility
    const Arcane::VariableFaceReal& T = m_transmissivities["T"][ArcNum::Classical];

    const auto& um = unknownsManager();

    // Get Geoxim Domain Implicit Variables
    auto P = Law::contribution<ArcRes::Pressure>(domain(),functionMng(),um,system());
    auto Pc = Law::contribution<ArcRes::CapillaryPressure>(domain(),functionMng(),um,fluid.phases());
    auto kr = Law::contribution<ArcRes::RelativePermeability>(domain(),functionMng(),um,fluid.phases());
    auto mu = Law::contribution<ArcRes::Viscosity>(domain(),functionMng(),um,fluid.phases());
    auto rho = Law::contribution<ArcRes::Density>(domain(),functionMng(),um,fluid.phases());

    ENUMERATE_BOUNDARY(bound,options()->boundaryCondition()->boundaryEnumerator()) {

        Law::PartialVariableFaceFolder& bound_folder = bound.folder();

        // Get Geoxim Boundary Variables
        auto b_P = Law::values<ArcRes::Pressure>(bound_folder,system());
        auto b_Pc = Law::values<ArcRes::CapillaryPressure>(bound_folder,fluid.phases());
        auto b_kr = Law::values<ArcRes::RelativePermeability>(bound_folder,fluid.phases());
        auto b_mu = Law::values<ArcRes::Viscosity>(bound_folder,fluid.phases());
        auto b_rho = Law::values<ArcRes::Density>(bound_folder,fluid.phases());

        // Build Term

        Arcane::FaceGroup boundary_faces = bound_folder.support();

        ENUMERATE_FACE(iFace, boundary_faces) {

            ArcNum::initContribution();

            const Arcane::Cell& cell_k = iFace->boundaryCell();

            ENUMERATE_PHASE(iphase, fluid.phases()) {

                const auto grad_kb = T[iFace] * (P[cell_k] + Pc[iphase][cell_k] - b_P[iFace] - b_Pc[iphase][iFace]);

                const auto mobility_k =
                        rho[iphase][cell_k] * kr[iphase][cell_k] / mu[iphase][cell_k];

                const Arcane::Real mobility_b =
                        b_rho[iphase][iFace] * b_kr[iphase][iFace] / b_mu[iphase][iFace];

#ifdef SPARSE_AUDI
                const auto flux_kb = (audi::value(grad_kb)>=0) ?
    		        mobility_k*grad_kb :
			mobility_b*grad_kb ;
#else
                const Law::Contribution flux_kb =
                        (   audi::one(grad_kb >= 0) * mobility_k
                            + audi::one(grad_kb <  0) * mobility_b ) * grad_kb;
#endif

                const Arcane::Integer iequation = iphase.index();

                if(cell_k.isOwn()) {
                    residual[iequation][cell_k]         += flux_kb;
                    jacobian[iequation][cell_k][cell_k] += flux_kb;
                }
            }
        }
    }
}

/*---------------------------------------------------------------------------*/

/** AI comment: Builds the well flux term using well index and bottom-hole pressure */
void TwoPhaseFlowSimulationModule::
_buildFluxWell(ArcNum::Vector& residual, ArcNum::Matrix& jacobian)
{

    info() << "build well flux";

    // Get Entities
    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    // Get Domain Implicit Variables
    const auto& um = unknownsManager();

    auto P = Law::contribution<ArcRes::Pressure>(domain(),functionMng(),um,system());
    auto Pc = Law::contribution<ArcRes::CapillaryPressure>(domain(),functionMng(),um,fluid.phases());
    auto kr = Law::contribution<ArcRes::RelativePermeability>(domain(),functionMng(),um,fluid.phases());
    auto mu = Law::contribution<ArcRes::Viscosity>(domain(),functionMng(),um,fluid.phases());
    auto rho = Law::contribution<ArcRes::Density>(domain(),functionMng(),um,fluid.phases());

    ENUMERATE_WELL(well,options()->wellCondition()->enumerator()) {

        Law::PartialVariableCellFolder& well_folder = well.folder();

        // Get well Variables
        Arcane::PartialVariableCellReal b_IP(well.wellIndex());

        auto b_P = Law::values<ArcRes::Pressure>(well_folder,system());
        auto b_Pc = Law::values<ArcRes::CapillaryPressure>(well_folder,fluid.phases());
        auto b_kr = Law::values<ArcRes::RelativePermeability>(well_folder,fluid.phases());
        auto b_mu = Law::values<ArcRes::Viscosity>(well_folder,fluid.phases());
        auto b_rho = Law::values<ArcRes::Density>(well_folder,fluid.phases());

        // Build Term

        auto cells = well_folder.support();

        ENUMERATE_CELL(icell, cells) {

            ArcNum::initContribution();

            ENUMERATE_PHASE(iphase, fluid.phases()) {

                const auto grad_kw = b_IP[icell] * (P[icell] + Pc[iphase][icell]  - b_P[icell] + b_Pc[iphase][icell] );

                auto mobility_k =
                        rho[iphase][icell] * kr[iphase][icell] / mu[iphase][icell];

                auto mobility_w =
                        b_rho[iphase][icell] * b_kr[iphase][icell] / b_mu[iphase][icell];

#ifdef SPARSE_AUDI
                const auto flux_kw = (audi::value(grad_kw)>=0) ?
    		        mobility_k*grad_kw :
			mobility_w*grad_kw ;
#else
                const Law::Contribution flux_kw =
                        (   audi::one(grad_kw >= 0) * mobility_k
                            + audi::one(grad_kw <  0) * mobility_w ) * grad_kw;
#endif

                auto iequation = iphase.index();

                residual[iequation][icell]        += flux_kw;
                jacobian[iequation][icell][icell] += flux_kw;
            }
        }
    }
}


/*---------------------------------------------------------------------------*/

/** AI comment: Builds the saturation closure equation (sum of saturations = 1) */
void TwoPhaseFlowSimulationModule::
_buildClosure(ArcNum::Vector& residual, ArcNum::Matrix& jacobian)
{
    // Get Geoxim Entities
    ArcRes::FluidSubSystem fluid = system().fluidSubSystem();

    const auto& um = unknownsManager();

    // Get Geoxim Domain Implicit Variables
    auto S = Law::contribution<ArcRes::Saturation>(domain(),functionMng(),um,fluid.phases());

    // Build Term

    const Arcane::Integer iequation = fluid.phases().size();

    ENUMERATE_CELL(icell, ownCells()) {

        ArcNum::initContribution();

        ENUMERATE_PHASE(iphase, system().phases()) {

            const auto C = S[iphase][icell];

            residual[iequation][icell]        += C;
            jacobian[iequation][icell][icell] += C;
        }

        residual[iequation][icell] -= 1.;
    }
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

using namespace Arcane;
ARCANE_REGISTER_MODULE_TWOPHASEFLOWSIMULATION(TwoPhaseFlowSimulationModule);
